### ISSUE TITLE
Cycle through warning/error blocks

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1004]
It would be useful if one could cycle through the blocks that are marked with warnings or errors by clicking on the icons in the warning indicator. Currently searching the workspace for warnings/errors is time consuming, especially in large projects, and the icons are not easily discernible at very small zoom scales.

**Comment by ewpatton** [comment]
Some TODOs for this issue:
- [ ] Refactor the [code to focus](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/blocklyeditor/src/blocks/procedures.js#L848) on a procedure definition block into a function on the workspace to focus on any block.
- [ ] Cache the list of blocks with warnings/errors on either the warning handler or warning indicator so that it doesn't have to be recomputed every time the user clicks the icon.
- [ ] Add click/touch handlers to the warning/error icons to step through the cached list of warnings/errors.

**Comment by ewpatton** [comment]
@SusanRatiLane Another good candidate for you to investigate.

**Comment by ewpatton** [comment]
@SusanRatiLane Also take a look at my comment on #1084, which solves step 1 for us.

**Comment by SusanRatiLane** [comment]
I was researching how to do this exact thing an hour ago. Great.

**Comment by SusanRatiLane** [comment]
This issue and #1084 are being addressed in [branch](SusanRatiLane/appinventor-sources/tree/1004-Cycle-through-warning-error-blocks)
