### ISSUE TITLE
GitBuildId Error caused by git describe's unexpected output

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1005]
![image](https://user-images.githubusercontent.com/22613139/32849820-4097bd00-ca6b-11e7-839b-cbd41ca69025.png)
![image](https://user-images.githubusercontent.com/22613139/32849895-775224c0-ca6b-11e7-9def-7cd028f0c65f.png)

![image](https://user-images.githubusercontent.com/22613139/32850108-3a533c66-ca6c-11e7-8112-e28016c70003.png)

how this can be fixed?

**Comment by ewpatton** [comment]
@ColinTree Which version of git are you using?

**Comment by ewpatton** [comment]
Easiest fix would be to make a new branch from head. You should be able to this by `git checkout new-branch-name`.

**Comment by ColinTree** [comment]
it just a new branch checkout from upstream(mit-cml/appinv) directly.
i m not sure if i need to clone the whole repo again?

**Comment by ewpatton** [comment]
Given that git is handing back a SHA1, it is likely not a branch. You are probably in detached head state, so you need to make a branch out of it using the checkout command I described above.

**Comment by ColinTree** [comment]
would the depth of cloning affect this? i cloned the repo with only depth 5 to save my storage space...

**Comment by ColinTree** [comment]
Solved, i should not checkout from a remote branch.
sorry
