### ISSUE TITLE
Oversize block comment display error

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1008]
![image](https://user-images.githubusercontent.com/22613139/32977216-e6e80792-cc63-11e7-9b39-429cf1bffee0.png)![image](https://user-images.githubusercontent.com/22613139/32977220-f0fabe8c-cc63-11e7-9a2d-e09f1b1602cb.png)

i think this canbe fixed through css styling

(only happens in Chrome)

**Comment by ewpatton** [comment]
Caused by google/blockly#1382
