### ISSUE TITLE
Upcoming MIT App Inventor for iOS is affected by Apple App Store review guidelines. [OFF-TOPIC]

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1012]
Hello,
I would like to inform that, upcoming MIT App Inventor for iOS is affected by Apple App Store review guidelines. Due to Apple's review guidelines update 4.2.6, users won't be allowed to upload apps that are made with an "app generation service" or from "commercialized template". For more info, please check following site:
https://developer.apple.com/app-store/review/guidelines/
Regards, Ben (@moliata at GitHub)

**Comment by moliata** [comment]
Hmm, but how will you guys make Yail work for iOS. I mean Yail is a Kawa scheme language with Simple component model. Isn't Kawa just Java scheme language. This only means you will either have to rewrite whole Yail just for iOS version right? In this case, I think guys, that you will have to rewrite at least buildserver, blocklyeditor (yail generator part) and components (to be for ios).
Regards, Ben.
P.S: please take a look here, https://groups.google.com/forum/m/#!category-topic/mitappinventortest/M8sn2G1e8Qc

**Comment by moliata** [comment]
Also, I would like to ask whether you will use Swift or Objective C

**Comment by ewpatton** [comment]
We have a prototype of YAIL working on iOS. Not all of the blocks are supported yet, but that will come in time. The components library is written primarily in Swift with Objective-C for certain things.

**Comment by moliata** [comment]
Great, if possible can you send me a link to GitHub repo over an email (benas.molis@gmail.com), I will try to contribute on some stuff, as I am pretty good at Swift 😄 , also, what type of prototype of Yail do you have? I mean, did you find an alternative scheme language to Kawa and alternative component model to Simple for iOS? Regards, Ben.

**Comment by moliata** [comment]
This is no longer an issue.
