### ISSUE TITLE
Implement a StopListening method for SpeechRecognizer

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1013]
[From the forum](https://groups.google.com/d/msg/app-inventor-open-source-dev/V00TNRaAmcE/s_8Poym_AQAJ): It would be nice to have a mechanism to stop the speech recognizer based on user interaction, e.g. releasing a button.

**Comment by choichifai2005** [comment]
Yes, if the user can control when to stop the listening, the user experience will be much better

**Comment by choichifai2005** [comment]
Will the method realize? it will be a new block in the the original function or make it as an extension? how can I help for make it a bit faster?

**Comment by ewpatton** [comment]
@choichifai2005 If you would like to implement this, you should take a look at the [SpeechRecognizer.java](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/SpeechRecognizer.java) file under components/src/com/google/appinventor/components/runtime and reimplement to use the [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer.html) service. The tricker here is that this class was added in API level 8, so we would need to add something to the FroyoUtil class to implement the new functionality while keeping the old functionality for phones running API level < 8.

**Comment by ankritisachan** [comment]
Hi ! Is this issue open to work ? I would like to work on it.

**Comment by ankritisachan** [comment]
@ewpatton Can I work on this issue?

**Comment by choichifai2005** [comment]
@ankritisachan Thank you for your interest! I have wait for someone to implement this for more than one year! now just wait MIT to reply you.

**Comment by ewpatton** [comment]
@ankritisachan Yes, it's available if you want to work on it. It will require some significant work though because the current implementation uses Intents to launch a speech recognizer activity outside App Inventor. The component will need to be rewritten to use the [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer) interface. Also, the SpeechRecognizer interface is only available starting at SDK 8, and we will want to continue to support the older approach for backward compatibility with existing apps with a migration path for developers who prefer the newer API. Therefore, you may want to structure it thusly:

1. Create a SpeechRecognizerController interface with the appropriate methods (start, stop, etc.)
2. Make two concrete classes, e.g., IntentBasedSpeechRecognizer and ServiceBasedSpeechRecognizer, that implement this.
3. Add a new DesignerProperty called UseLegacyRecognizer with default value True
4. Add an Initialize() method to SpeechRecognizer that creates the appropriate type based on whether UseLegacyRecognizer is true. If the Build.Version.SDK_INT is < 8, you will always want to instantiate the IntentBased version since the newer one isn't supported.
5. Update the other methods to call the instantiated SpeechRecognizerController to get the behavior specified for the user.
6. Add the new pause/stop methods. I would also recommend looking into whether we can report partial results via an event.
7. Once you're done, bump SPEECHRECOGNIZER_COMPONENT_VERSION in YaVersion.java and add code paths in YoungAndroidFormUpgrader.java and versioning.js to handle upgrading older projects (these are no-op upgrades the way I've structured it above).

**Comment by ankritisachan** [comment]
@ewpatton I have been trying to understand android speech recognizer. I found that the intent based method creates an external dialog for speech recognition. Another method uses RecognitionListener interface implemented in the main class. I understood their basic implementation and use in an android app. 
I need your help in clarification of a few things with your above comment. 
SpeechRecognizerController interface will contain simple methods named start, stop, etc. 
1) ServiceBasedSpeechRecognizer will implement both SpeechRecognitionController interface and RecognitionListener interface and use SpeechRecognizer class overriding all their methods.
2) IntentBasedSpeechRecognizer will implement only SpeechRecognitionController interface and use the same method which is currently used in AI while overriding start and stop methods.
Is this initial understanding correct?

**Comment by ewpatton** [comment]
@ankritisachan That's pretty close. The only thing is that I don't think we can stop the IntentBasedSpeechRecognizer once it starts (which is why we need to consider this approach to begin with). If you think it can be done, it would be a good experiment to try before refactoring to use the interface approach. Otherwise, it sounds like you understand what to do.

**Comment by ankritisachan** [comment]
@ewpatton I also tried to find some solution to stop IntentBasedSpeechRecognizer, but couldn't find any. So, considering the current state, I was thinking if we really need a SpeechRecognitionController interface for both the implementation of SpeechRecognizer. Intent-based do not have any start or stop method as such. Only service-based SpeechRecognizer will be able to justify start and stop methods. So, wouldn't it be better if we do not create the SpeechReccognitionController interface and only implement RecognitionListener interface to ServiceBasedSpeechRecognizer? And then finally use SpeechRecognizer to instantiate the appropriate class as you suggested.

**Comment by ankritisachan** [comment]
@ewpatton Please let me know your opinion.

**Comment by ewpatton** [comment]
@ankritisachan We might consider other options in the future, such as embedding our own neural network or integrating with a service such as Amazon Alexa (on Kindle Fire tablets). I think we should just be consistent and have every option implement the interface. In some cases, like the intent based version, it will be a no-op, but that's okay because that's already what we have today w.r.t. stop functionality.

**Comment by ankritisachan** [comment]
@ewpatton I have been trying to implement IntentBasedSpeechRecognizer initially just make sure that current method is up and running. But currently, I am unable to retrieve results from IntentBasedSpeechRecognizer.java to  SpeechRecognizer.java. I am also not sure if the result is being stored appropriately in the result variable of IntentBasedSpeechRecognizer(line 11 of https://pastebin.com/jdekywFe). The corresponding files are [SpeechRecognizerController](https://pastebin.com/LtUPLGvE), [IntentBasedSpeechRecognizer](https://pastebin.com/jdekywFe) and [SpeechRecognizer](https://pastebin.com/gBtTbgtf). 
To be more precise, I am not clear with how and when resultReturned() method of  ActivityResultListener.java is being called and used. I also tried implementing ActivityResultListener in an inner class in IntentBasedSpeechRecognizer.java but I don't think that will make any difference until I understand how resultReturned() method works.
Please have a look at the code files and help me with this.

**Comment by ewpatton** [comment]
@ankritisachan `SpeechController` will need to provide a way so that `SpeechRecognizer` can register to get the result. In both of the approaches (i.e., Intent and Service), the detection is happening in a non-blocking way. When you launch the intent, Android starts a new activity on top of the App Inventor activity where speech recognition occurs and our code keeps going (it doesn't block). Therefore, on lines 67-69 of the `SpeechRecognizer` file you linked, the result isn't ready because the new activity likely won't have finished even launching yet.

The overall flow is:

- [x] SpeechRecognizer creates an instance of one of the SpeechController instances
- [ ] SpeechRecognizer registers a listener (to be defined) with the SpeechController. This listener will be called with the results and should set the result and call AfterGettingText.
- [x] Register for the activity result in the start method.
- [x] Start the activity for the result.
- [x] The speech recognition activity will return a result to the Form, which calls the resultReturned method.
- [ ] In resultReturned, call the listener that is registered by the SpeechRecognizer with the result.
- [ ] Maintenance: Implement the Deletable interface, which adds an onDelete method, in order to set the SpeechController reference to null to break the reference cycle for garbage collection.

What would probably make the sense would be to create an AbstractSpeechController class that manages the listeners since this logic will be the same for both approaches, and then have IntentBasedSpeechController and ServiceBasedSpeechController inherit from that class.

At a minimum, I think we will want the listener interface to look like the following:

```java
public interface SpeechListener {
  // For the service approach in which we can report partial results to the blocks
  void onPartialResult(String text);
  // For the final result, used by both approaches
  void onResult(String text);
  // In case we need to report any errors, such as the activity or service dying for an unexpected reason.
  void onError(String message, Throwable error);
}
```

The most straightforward approach may be for the SpeechRecognizer to implement the interface and register itself with the SpeechController. The other approach would be to instantiate an anonymous SpeechListener within SpeechRecognizer and have it call the appropriate methods in SpeechRecognizer.

**Comment by ankritisachan** [comment]
@ewpatton Thanks a lot! I implemented the listener and both the Recognizer Methods are working now.
 
Going for this now,
> 3. Add a new DesignerProperty called UseLegacyRecognizer with default value True
What is this property about? I didn't understand the meaning of Legacy here. How will this property work?

> 4. Add an Initialize() method to SpeechRecognizer that creates the appropriate type based on whether UseLegacyRecognizer is true.
What does this line mean above?

**Comment by ewpatton** [comment]
@ankritisachan We try not to change behavior in a way that is unexpected for people developing apps with App Inventor, so we need to support swapping in the new speech recognizer in a way that doesn't disrupt existing projects. For example, the flow of an existing app might be based around the current Intent-based approach, and the app creator may need to change the flow to use the new approach. We don't want to force everyone over to the new model right away because of this.

The addition of the `UseLegacyRecognizer` (which we may want to simplify to `UseLegacy`) property serves the following purposes:

1. Existing apps can keep the behavior they already have; some work may need to be done to update them to use the new approach
2. Existing companions without the new feature will still have exhibit the old behavior consistent with the property being enabled-by-default.
3. Apps with the new companion will have the existing behavior but can be switched to the new behavior, i.e., upgrading the companion doesn't unexpectedly change the flow of the program.

**Comment by ankritisachan** [comment]
@ewpatton Please have a look at following files.
I was doubtful about the implementation of 'UseLegacy' property, please verify that. Also, one thing i.e. checking for partial results implementation is left to be done. Rest all is mostly done. I took the help of a few internet sources too.
Following are the files - 
 [SpeechRecognizerController](https://pastebin.com/ig94g60f), [SpeechRecognizer](https://pastebin.com/GgeGbg3c), [SpeechListener](https://pastebin.com/fDcgBstA), [IntentBasedSpeechRecognizer](https://pastebin.com/tYub6mJf), [ServiceBasedSpeechRecognizer](https://pastebin.com/JupurnvB).

Finally regarding displaying stopListening() function for the IntentBased approach doesn't make any sense. Is there a way where we can hide stopListening() function if IntentBased approach is used else if ServiceBased approach is used, we display it. Is something similar possible? How do we handle that?

Also, please let me know if any other points you need me to look into.

**Comment by choichifai2005** [comment]
@ankritisachan In my opinion, the stopListening() function is very useful, it should be an individual block can call manually. 
the existing problem now is: "the system waiting for finish listening". if the speech recognizer is use in a silent place, this is great, however, if in a place with noisy background, the system don't know where is the end of listening, so we need to implement a stopListening() to tell the system "stop listening and recognize what you get up to now!
