### ISSUE TITLE
Update Texting documentation regarding Google Voice

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1015]
The texting component can send with GV, but can no longer receive due to breaking changes introduced by Google. We need to make a note in the documentation to inform developers of this situation.

**Comment by suvamjain** [comment]
Hi @ewpatton , 
I'm looking to fix this issue. Can I get some more information like where to find this in the code base?

**Comment by ewpatton** [comment]
All of the reference documentation is in the docs/reference/ directory. You’ll want to update the social.html file.

**Comment by suvamjain** [comment]
<img width="1002" alt="GV doc changes" src="https://user-images.githubusercontent.com/29479040/54883743-f688e500-4e8e-11e9-9aaa-7aba37b559c1.png">

Please verify the last paragraph in the above mentioned screenshot.

**Comment by ewpatton** [comment]
@suvamjain I don't believe the text about Marshmallow is correct. GoogleVoice uses different permissions than the built-in texting permissions. The issue was that Google changed the Google Voice UI which we parsed for sending/receiving texts. I implemented a fix for sending texts but never updated receiving texts. I think the text should say that one can send texts with GV but not receive them.

**Comment by suvamjain** [comment]
![image](https://user-images.githubusercontent.com/29479040/54974484-37c9e380-4fba-11e9-8b2f-0ef9406fa01e.png)
What about this one?

**Comment by ewpatton** [comment]
@suvamjain Adding the GoogleVoiceEnabled blocks shouldn't add the dangerous permissions prevented by Google Play's newest policies. Google Voice defines its own similarly named (but not the same) permissions for sending/receiving Google Voice messages. I think the text in bold is unnecessary. The important thing that we need to be highlighting is that receiving no longer works. The component has regressed to be sending only (and even getting that back was some work).

**Comment by suvamjain** [comment]
Hi @ewpatton, Please review the PR I just submitted.

**Comment by ewpatton** [comment]
Resolved via 1e04a9f03db639ef6a52604fcaa2081d31796f3f
