### ISSUE TITLE
Edit from device

### ISSUE THREAD

**Issue by mrrm92** [mit-cml/appinventor-sources#1020]
Pleasu, enable on device programming by either:
*Make the editor’s webpage responsive
*Create a fronted for the editor 
*Bundle everything in a native app

**Comment by moliata** [comment]
I think the only thing, we should do is make drag & dropping available to mobile devices too, by implementing touch listeners.

**Comment by ewpatton** [comment]
I have a prototype of this functionality based on some student work. I will do what I can to resurrect it and bring it current with master.

**Comment by mrrm92** [comment]
This would be enough anyway


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: moliata <notifications@github.com> 
Data: 26/11/17  14:03  (GMT+01:00) 
A: mit-cml/appinventor-sources <appinventor-sources@noreply.github.com> 
Cc: mrrm92 <chicochetal@gmail.com>, Author <author@noreply.github.com> 
Oggetto: Re: [mit-cml/appinventor-sources] Edit from device (#1020) 

I think the only thing, we should do is make drag & dropping available to mobile devices too, by implementing touch listeners.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mit-cml/appinventor-sources","title":"mit-cml/appinventor-sources","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mit-cml/appinventor-sources"}},"updates":{"snippets":[{"icon":"PERSON","message":"@moliata in #1020: I think the only thing, we should do is make drag \u0026 dropping available to mobile devices too, by implementing touch listeners."}],"action":{"name":"View Issue","url":"https://github.com/mit-cml/appinventor-sources/issues/1020#issuecomment-347007248"}}}
