### ISSUE TITLE
Make Responsive the default Sizing

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1024]
Given the breadth of form factors available on the market, we should think about making Responsive the default Sizing rather than Fixed. We would need an upgrader for old projects that assume the current default of Fixed to be explicitly set to Fixed. If Sizing is Responsive, we need to think about whether we remove the explicit setting so that the user gets the default (which would be Responsive). One concern is that this could break projects being imported into App Inventor clones that don't take up this change.

**Comment by halatmit** [comment]
I agree that we should make responsive the default.   I didn't do this initially, since I thought it would be easier for kids deigning for a single device to use fixed.   But as Evan says, the multiplicity of devices changes this.   
But as Evan says, we need to be careful about breaking projects.

**Comment by ColinTree** [comment]
+1 about this.
At least everytime when Im making a app that uses Canvas, i need to switch it to responsive, and it provides a higher quality of displaying

**Comment by ewpatton** [comment]
Recently we added a `alwaysSend` field to `@DesignerProperty` to cope with different defaults in earlier versions of the companion. If someone tackles this, that field should be set to `true` for this property until such time as all allowed companion versions have responsive as the default.

**Comment by lightingft** [comment]
@ewpatton I can look into this. So, if I understand correctly, the upgrader should handle setting the default value to responsive too, is that correct?

**Comment by ewpatton** [comment]
@lightingft Yes, it is conceptually very similar to the other change you worked on with the BarcodeScanner component.

**Comment by ewpatton** [comment]
Fixed by #1644 and is pending a component release
