### ISSUE TITLE
Focus on ok after GWT dialogs is shown

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1037]
I got used to press Enter after click delete button of a component. 
Due to the upgrade of the dialog, this may not be available anymore.
I think this should be easy to fix. But, should i (we)?

**Comment by ColinTree** [comment]
Also, escape key is not available to close the dialog anymore

**Comment by ewpatton** [comment]
@ColinTree Yes; it would be great for you to implement this.
