### ISSUE TITLE
Update if block documentation

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1049]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/zI4r_Q7jJEg/wCdZh-7gCQAJ): The documentation for the `if` block with mutator references a "do" statement, but the statement is called "then" in the block. This can be misleading and should be corrected to match the block.

**Comment by ewpatton** [comment]
@farxinu Would you mind taking a look at this? It should be a quick fix.

**Comment by farxinu** [comment]
Would this be on the explore site or within the code repository?

**Comment by ewpatton** [comment]
This is on explore.

**Comment by farxinu** [comment]
I can't publish the page, but http://explore.appinventor.mit.edu/ai2/support/blocks/control is updated.

**Comment by ewpatton** [comment]
@farxinu Thanks. I've pushed the change to the production site.
