### ISSUE TITLE
Migrate to Java 8

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1053]
Today I've received an email from Google Cloud saying this:
```
Dear App Engine developer, 
We're writing to let you know that the Java 7 runtime is deprecated as of December 13, 2017 in favor of the generally available Java 8 runtime. In accordance with the Google Cloud Platform deprecation policy, you will be able to migrate your projects off the Java 7 runtime over the next 12 months prior to the shutdown date of January 16, 2019. For more information, see the Java 7 runtime deprecation page. 
Please note the following incompatibilities between the Java 7 and Java 8 runtimes: 
•	Cloud Endpoints v1 is incompatible with the Java 8 runtime and scheduled to shut down on August 2, 2018. Please migrate to Cloud Endpoints v2 before migrating to the Java 8 runtime.
•	Appstats will not report Appstats data in the Java 8 runtime. If you would like to maintain Appstats functionality, please migrate from Appstats to Stackdriver Trace before migrating to the Java 8 runtime. 
•	If you have a free-tier project that uses the java.net.HttpURLConnection class or includes a Google client library that uses that class, please enable billing on your app or set the url-stream-handler parameter to "urlfetch" in your appengine-web.xml file before January 16, 2019.
For a full list of Java 7 and Java 8 incompatibilities, please see this guide. 
The Java 8 runtime has a number of benefits compared to earlier versions of Java on App Engine Standard, such as the removal of the Class Whitelist, availability of all public JDK APIs, and ability to use java.io.File, threads, and any Java libraries. 
For complete migration instructions and a list of key differences between App Engine Java 7 and Java 8 runtimes, which are based on the OpenJDK 7 and OpenJDK 8 runtimes respectively, please see our Java 8 migration page. 
Your projects listed below have been identified as using the Java 7 runtime: 
•	Makeroid Builder (makeroid-builder) 
If you have any questions or require assistance, please do not hesitate to contact Google Cloud Support. 
```

It sais that we have to migrate to Java 8

**Probably this will be the same regarding AI2**

**Comment by ewpatton** [comment]
Thanks @barreeeiroo.

**Comment by moliata** [comment]
This will also cause a lot of issues, because users won't be able to deploy AI on a free tier. Besides components and buildserver, AI uses LoginServlet and YoungAndroidProjectService which need java.net.HttpUrlConnection. regards.

**Comment by ewpatton** [comment]
@moliata Do you have a citation about the free tier claim? As far as I know, the Java 8 GAE environment supports the full JDK8 whereas the Java 7 version limits which JDK classes can be used ([ref](https://cloud.google.com/appengine/docs/standard/#java8)).

**Comment by moliata** [comment]
@ewpatton A quote from a notice:
"If you have a free-tier project that uses the java.net.HttpURLConnection class or includes a Google client library that uses that class, please enable billing on your app or set the url-stream-handler parameter to "urlfetch" in your appengine-web.xml file before January 16, 2019."

**Comment by moliata** [comment]
@ewpatton sorry, didn't see a part about "urlfetch", no problem.

**Comment by barreeeiroo** [comment]
@ewpatton This has to be fixed ASAP
Google no longer deploys apps with Java7 as runtime. In the logs it appears as warning, but it gets rejected by the server

![screenshot_2018-04-15-00-43-10-364_com android chrome](https://user-images.githubusercontent.com/19251112/38773133-67c28ddc-4046-11e8-9a7f-38e23a6a3c1f.png)

**Comment by jisqyv** [comment]
@barreeeiroo Are you sure that is why the rejection is happening. Everything I have read from Google indicates that we have time. Doing the update is on my queue, but it isn't the highest priority thing there. Btw. most of the work involves testing, lots of testing. Not so much coding.

**Comment by Amerkashi** [comment]
On AppyBuilder, I just performed a test-deployment using Java 7.  It deployed and runs with no issues

**Comment by halatmit** [comment]
Java 7 is supported until January 2019.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
It's good to confirm that it is still working as intended. Thanks @Amerkashi.

@jisqyv I think that we should deploy this to ai2-test soon so that we can aim to update ai2 over the summer when school is out.

**Comment by barreeeiroo** [comment]
Yeah, sorry @jisqyv @ewpatton 😅 
I touched something at the code and it was failing, and as it didn't report anything else except that warning I thought it was caused due to Java7
