### ISSUE TITLE
Fixed mode scaling broken on ai2-test

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1055]
As noted by @halatmit and @jsheldonmit, the scaling factor for fixed mode is not being correctly applied on ai2-test. This results in some applications, such as games that rely on fixed mode to position components consistently, breaking. Current thoughts are that this was either introduced by the min SDK change or due to how I handled simulating the old titlebar after we switched to allowing the ActionBar.

**Comment by ewpatton** [comment]
Increasing the min SDK on master did not trigger the issue. Both companions report the scaling factor as 1.2857143. This is also the value reported by the broken companion.

**Comment by halatmit** [comment]
Thanks for the update.   Good hunting.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
The source of the issue is that in onGlobalLayout we compute the difference in height between the scale layout and the root view and compare it to the content view top. This is reporting 88 and 0, resp., which makes the form assume the keyboard is shown and switches the scaling behavior to match responsive's behavior. The height differential is due to the status bar. Turning ShowStatusBar to false will yield the correct behavior.

**Comment by halatmit** [comment]
Super.   I am so glad you found this.

Can you put up an instance for us to test?    There's a lot of confusion
with claims about about the Lenovo tablet and backwards accelerometer
sensors
and we need to see if any of that is real.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by marksherman** [comment]
Is this the bug that causes the screen to sometimes be "zoomed" oddly?

**Comment by ewpatton** [comment]
@marksherman AFAIK, yes? This is the bug reported by Josh where the scaling is incorrect on ai2-test. I don't think accounts for the odd behavior Farzeen and you showed me where the Android chrome itself seemed to not understand the orientation.

**Comment by marksherman** [comment]
I'm caught up now, don't mind me. Thanks

**Comment by jisqyv** [comment]
Fix on ucr
