### ISSUE TITLE
WidthPercent and HeightPercent lack documentation

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1058]
The `WidthPercent` and `HeightPercent` blocks do not have any tooltip documentation to explain their purpose.

**Comment by lightingft** [comment]
@ewpatton I would like to handle this issue.

Also, this seems to be the case for the Width & Height blocks. Should documentation be added for these also?

**Comment by ewpatton** [comment]
@lightingft It's yours.

**Comment by ewpatton** [comment]
Resolved by 7c0d6677e51a4a4457eb66d04f1ed1d1cedcce28
