### ISSUE TITLE
BLE SupportedServices issue

### ISSUE THREAD

**Issue by chegewara** [mit-cml/appinventor-sources#1065]
According to description BluetothLe.SupportedServices should have return list of services, but if we check output from this component with component "is a list?" it will never return value tru. Its the output from example:
`The operation is in list? cannot accept the arguments: , [00001812-0000-1000-8000-00805f9b34fb], [00001801-0000-1000-8000-00805f9b34fb Unknown Service,00001800-0000-1000-8000-00805f9b34fb Unknown Service,0000180a-0000-1000-8000-00805f9b34fb Unknown Service,00001812-0000-1000-8000-00805f9b34fb Unknown Service,]`

As we can see im trying to check if on services list is service with `UUID 00001812-0000-1000-8000-00805f9b34fb` and such service exists in list, but cant be found because service UUID is appended with 'Unknown Service' string.

**Comment by ewpatton** [comment]
The `SupportedServices` operation actually returns a string, not a list (ref: [Javadoc](https://github.com/mit-cml/appinventor-extensions/blob/b1dc03b9094b35a8abd873237255bcaf41cafd78/appinventor/components/src/edu/mit/appinventor/ble/BluetoothLE.java#L1505)). If you would prefer to lookup a UUID, you could use the `DeviceServices` property instead, which returns a list of lists that can be used with the lookup in pairs block.

**Comment by chegewara** [comment]
Thanks.
