### ISSUE TITLE
Deprecated Apache Http Client API

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#1066]
Since Apache Http Client API is deprecated in Android and Google insists us to use `java.net.*` APIs, we should also make that move.

I have found these files to be affected when using Android Oreo (API 26):

* util\IClientLoginHelper.java
* util\ClientLoginHelper.java
* util\WebServiceUtil.java
* util\SmsBroadcastReceiver.java
* FusiontablesControl.java
* MediaStore.java

**Comment by pavi2410** [comment]
These packages didn't exist when using Android Oreo SDK (API 26):

org.apache.http.client
org.apache.http.client.entity
org.apache.http.client.methods
org.apache.http.conn.params
org.apache.http.impl.client
org.apache.http.impl.conn.tsccm

**Comment by pavi2410** [comment]
Here is the link to where Google states its deprecation: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

**Comment by kevinc123** [comment]
@pavi2410 In the android sdk folder there is a legacy apache http lib that provides old methods.

You can find it in folder "optional", file "org.apache.http.legacy.jar", add it to buildserver's build.xml and problem solved until the affected files are being fixed

**Comment by ewpatton** [comment]
Fixed in 3b3f7d0
