### ISSUE TITLE
Update with target SDK 26

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1067]
According to the [Android Developers Blog](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html), we will need to start targeting Android SDK 26 before August 2018 as any new apps published in the Play Store will be required to do so. Existing apps, such as the companion, have until November 2018 to support the new SDK. We can also expect to be required to do this yearly starting from next year.

Further, the support libraries for SDK 26 set the min SDK to 14 whereas we currently support back to 7. We will need significant testing to ensure that this will minimize the impact on users of old devices.

See also #1066

**Comment by NmdOfficial** [comment]
Any new about this when you think AI can release it? @ewpatton

**Comment by moliata** [comment]
@ewpatton this should be technical debt.

**Comment by ewpatton** [comment]
@NmdOfficial I'll be sending email to the open source list later today with more details.

**Comment by NmdOfficial** [comment]
Hello @ewpatton ,
I had wrote you yesterday a email.
I had not received any information about the upgrade details per email.

Can you send me all details per mail? 
best regards,
Mika

**Comment by kkashi01** [comment]
@ewpatton chachanging target sdk to 26 we'll also affect look and feel of apps. Isn't that correct?

**Comment by ewpatton** [comment]
Fixed in 3b3f7d0
