### ISSUE TITLE
Using keyboard to copy and paste blocks no longer works

### ISSUE THREAD

**Issue by conorshipp** [mit-cml/appinventor-sources#1068]
This was originally reported on the Makeroid forum [here](https://community.makeroid.io/t/can-not-copy-and-paste-blocks/1571?u=conor).

Copying and pasting blocks using the CTRL+C and CTRL+V keyboard combinations no longer works on Makeroid. I have tested on ai2.appinventor.mit.edu and it works, however, it doesn't work on ai2-test.appinventor.mit.edu, it shows the  typeblock bar instead.

After doing some tests, I found out that reverting commit ba120fc solves the issue.

**Comment by moliata** [comment]
@conorshipp please take a look at #1069
