### ISSUE TITLE
Visible is not found in HorizontalArrangement (through extension)

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1073]
![image](https://user-images.githubusercontent.com/22613139/34403827-98010a1a-ebe5-11e7-8332-c1b6a0a54791.png)
Error message:
`java.lang.NoSuchMethodError: No virtual method Visible(Ljava/lang/Boolean;)V in class Lcom/google/appinventor/components/runtime/HorizontalArrangement; or its super classes (declaration of 'com.google.appinventor.components.runtime.HorizontalArrangement' appears in /data/app/edu.mit.appinventor.aicompanion3-2/base.apk)`

i did try to refresh my browser and upgrade my companion, but this still shows up when i try to toggle visibility of a HorizontalArrangement using a extensoin. 

Related code chain: 
* ![image](https://user-images.githubusercontent.com/22613139/34404408-5ccea8d2-ebe8-11e7-80d9-d5455afaef41.png)
* ![image](https://user-images.githubusercontent.com/22613139/34404402-458e1806-ebe8-11e7-9019-b570d99cf6c5.png)
* ![image](https://user-images.githubusercontent.com/22613139/34404319-e4d1cd78-ebe7-11e7-8a98-a19519b4d104.png)
  ![image](https://user-images.githubusercontent.com/22613139/34404441-86104f34-ebe8-11e7-9c7f-9d943f7bb4e9.png)
* ![image](https://user-images.githubusercontent.com/22613139/34404296-c7503fc8-ebe7-11e7-93c6-cc5e98122e5f.png)
* ![image](https://user-images.githubusercontent.com/22613139/34404302-d18c94e6-ebe7-11e7-8d4a-234e67595e3f.png)

**Comment by ColinTree** [comment]
Problem even exist as i built an apk

**Comment by ColinTree** [comment]
This property works well if using block.
i think it maybe caused by the renderer of Android View

**Comment by ColinTree** [comment]
I found that i can't even catch this exception though i add this at the very top of the chain (the start of AddElement). I was originally trying to print the full StackTrace to a string so that i can find out where the problem is actually from.

**Comment by ewpatton** [comment]
@ColinTree Have you tried recompiling the extension since the release? Does that fix the issue? The Visible(Z) property is defined in AndroidViewComponent, which is a superclass of HorizontalArrangement, so it is unclear why it's not linking correctly.

FYI, this is an error, not an exception, so you either have to catch `NoSuchMethodError` or `Throwable` (which will catch everything). However, this would only mask the problem and doesn't help solve your issue.

**Comment by ColinTree** [comment]
i update all the local codes and rebuild the extension, then the Error disappeared.

**Comment by ColinTree** [comment]
It is weird that i found that the new version of extension start to make error in the old version platforms like thunkable.

**Comment by ColinTree** [comment]
Finally found that what happened to this:
Due to the changes merged from ucr, Visible(Boolean) has been changed to Visible(boolean)

**Comment by ColinTree** [comment]
This works for me.

![image](https://user-images.githubusercontent.com/22613139/34444405-f4527960-ed08-11e7-9e21-407c68813755.png)

**Comment by ColinTree** [comment]
Closing. It is correcting the variable type from Boolean to boolean, and it is not the responsibility of appinventor team to make extensions adapted.
