### ISSUE TITLE
FeatureCollection should be modified

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1074]
Hello there,
as of Ewan's Maps commit, FeatureCollections component is not using a default file picker, instead a custom one. That is problematic, because we a) don't follow standards b) it's not designed well (From URL option opens a dialog in position: 0, 0 not in the center like Upload File does & when there is no file added to that component, it displays empty state as "..." not like in default picker "None...". Also, because this component is invisible, we need to make it look like a MockNonvisibleComponent while it's being dragged. So we would able to see an icon and a component's name while we dragging and after dropping it on the map, it should just become gone.
Best regards, Ben (@moliata on GitHub)

**Comment by ewpatton** [comment]
Because the FeatureCollection is primarily intended to work with remote sources of map data, the URL option was added to make it more useful. However, I agree that there are a few ways it can be improved so I'll work on addressing those concerns.

**Comment by moliata** [comment]
@ewpatton we could then look into fixing following things:
a) Position "From URL" dialog in the middle of the page
b) Change empty state label from "..." to "None..."
c) On FeatureCollections component drag make it look like a MockNonvisibleComponent
