### ISSUE TITLE
iOS Crowdfunding page should have PayPal option (off-topic)

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1075]
Hello,
I would like to note, that iOS platform's crowdfunding page should have a PayPal payment option. I know a lot of people, who actually wanted to donate and get a 250$ perk, but weren't been able. This also applies to me, as my CC is not yet activated and trying to donate with a PayPal for me is not possible.
Best regards, Ben.

**Comment by conorshipp** [comment]
It does already have a PayPal option...
![screenshot_20171228-103438](https://user-images.githubusercontent.com/25845449/34408317-168cec80-ebbb-11e7-9cd0-3f8769b030e7.png)

https://crowdfund.mit.edu/project/8152

**Comment by moliata** [comment]
Ok, thank you for letting me know, didn't see that.
