### ISSUE TITLE
Question about Taskes (Services)

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1079]
I remember that there was a special version of appinventor, that include a implement of controlling services (but not activities), and this was named Task(s). And Tasks was at the same level of Screens. (Can be created in the same way of Screen, and started in a similar way)

Is this still in the task list of appinventor? or it had been dropped for some reason?

**Comment by moliata** [comment]
It it still being developed by @thequixotic, but it takes time. Thanks for your patience.

**Comment by ColinTree** [comment]
Got that, thanks.
