### ISSUE TITLE
Highlight procedure does not account for zoom level

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1084]
[From the forum](https://groups.google.com/d/msg/app-inventor-open-source-dev/BOe09LA82_s/C9EGCOeKDwAJ): If the blocks editor has a zoom != 1, then the mechanism that moves the blocks workspace viewport doesn't end up pointed at the right spot.

**Comment by ewpatton** [comment]
Rachel implemented the ability to focus on an arbitrary block that also takes into account the workspace zoom level. See [`WorkspaceSvg.centerOnBlock` in Blockly master](https://github.com/google/blockly/blob/1d9fad068ecca184f74bdc419590e24e7f943a1b/core/workspace_svg.js#L1647). Since we don't have the bandwidth to handle another merge at this point, we may want to copy it wholesale into blocklyeditor/src/workspace_svg.js and update our code in procedures.js. One useful thing about our approach is that one can undo the workspace move to go back to the viewport prior to the focus shift. We should think about backporting that to Blockly.

**Comment by SusanRatiLane** [comment]
This is addressed as part of #1004
