### ISSUE TITLE
Disable/Enable  All Blocks on the right click menu of the Block editor

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#1091]
Companion on big projects is pretty slow when it is needed to update the device running app.
Some projects do something every time they update from web site to companion on the device, every time the app developer modifies a minimal property of the UI they update the device.
Result: a lot of time spent waiting for UI to appear and finish rendering and the app that does what it has to do on every Companion update.

Disabling all blocks will improve performances on project that you need to tune up the UI because they aren't executed every time the project is update on the device, this will accelerate the developing process and the user experience.

**Comment by ewpatton** [comment]
[Original post for reference](https://groups.google.com/d/msg/app-inventor-open-source-dev/KUFjWeBZh7A/GPWDPmPzDwAJ)
