### ISSUE TITLE
Filter bar appears black on black for newer Android versions

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1092]
[From the forum](https://groups.google.com/d/msg/aipowerusers/M9rrA-3RjHI/f9eRoqhkDgAJ): The filter bar text is black on black background. We may not be setting the appropriate style ID for newer versions of Android.

**Comment by moliata** [comment]
There is a lot of issues with themes as I see, we need to take a huge look into this.
P.S: I think these all themes and android resources related issues should have it's own label: themes caused problem

**Comment by ewpatton** [comment]
@moliata The release was one of the largest component releases to date. There were bound to be issues once you spread the change across hundreds of different hardware/software combinations. We'll work quickly to fix them and get another release out a few days.

**Comment by moliata** [comment]
@ewpatton sure, hope that will happen.

**Comment by ewpatton** [comment]
Closed via ec77db5
