### ISSUE TITLE
Icon display error when using base64 (at any component) (for extensions)

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1107]
![image](https://user-images.githubusercontent.com/22613139/34566655-35f40a24-f19a-11e7-9304-aef7e683271b.png)

Missing quotes between url and brackets: 
![image](https://user-images.githubusercontent.com/22613139/34566727-9f4ee96c-f19a-11e7-88a2-6b0716f9f528.png)

I prefer make this like the icon above:
![image](https://user-images.githubusercontent.com/22613139/34566819-f989d842-f19a-11e7-9fa6-61e5573e4acd.png)

**Comment by moliata** [comment]
By the way, it's better to use data:image instead of data:img

**Comment by ewpatton** [comment]
Certainly the datatype is wrong--it should be image/jpg not img/jpg. If you correct that issue, does the icon appear?

**Comment by ColinTree** [comment]
@ewapatton if i make it `url("data:img/jpg.....")` then i would works. it is because of the quote but not `img`.

**Comment by ewpatton** [comment]
Are the quotes there if you load one of our IOT extensions? It seems weird that the behavior is correct in that instance but not this one.

**Comment by ColinTree** [comment]
Ok I will try those later.
Everything works well with the base64 url besides here (any components), because it is using css styling to show the image, but the other places are using src argument of `<img>` tag.

**Comment by ColinTree** [comment]
IOT extensions are using online url for icon loading, it works here.
![image](https://user-images.githubusercontent.com/22613139/34577588-9a651a1c-f1bc-11e7-983f-82ea2dfbd551.png)
![image](https://user-images.githubusercontent.com/22613139/34577582-954dc0b0-f1bc-11e7-9b91-389089e081c1.png)

**Comment by moliata** [comment]
There is not difference between img and image, but it is recommended to use image.

**Comment by ewpatton** [comment]
@ColinTree That's what I thought. You can embed an image in the extension for the icon by creating a package aiwebres inside of the extension package. Set the iconName in `@DesignerComponent` to `aiwebres/<your-icon-file>` ([example](https://github.com/mit-cml/appinventor-extensions/blob/extension/arduino-101/appinventor/components/src/edu/mit/appinventor/iot/arduino101/Arduino101Button.java#L34)). That would be preferable to using a data URI in my opinion.
