### ISSUE TITLE
My opinion about renaming projects

### ISSUE THREAD

**Issue by p4ssw0rd** [mit-cml/appinventor-sources#1112]
I think renaming a project by copy and delete is a bad idea. But we have to do that, because the project name is a part of filename in ProjectFileData,and used as objectid in GCS. So, we should use appname as project name show in the list, and use projectId in filenames. When user create a new project,we create a project without any file first.and then use the projectid to naming the default files.

**Comment by moliata** [comment]
Hey, thank you for your comment, but next time please post this on original topic.

**Comment by ewpatton** [comment]
Agreed with @moliata. Please post this as a comment on #905.

**Comment by p4ssw0rd** [comment]
Okey.
