### ISSUE TITLE
Description in ode file and not in the component file itself?

### ISSUE THREAD

**Issue by NmdOfficial** [mit-cml/appinventor-sources#1122]
https://github.com/mit-cml/appinventor-sources/blob/8a363032ae686b816d2eecac0ec93a1f8871935d/appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java#L6588

Hello I have just a simple question.
Why are in the odemessages.java file some maps descriptions?
Should as example a property description not be wrote in the current component java file?
The most descriptions are in the odemessages.java file empty. 
And this is correct.

But why are now some of the descriptions direct added in the odemessages.java file?
best regards

**Comment by ewpatton** [comment]
The descriptions in OdeMessages are included when one exports the the OdeMessages.properties file. They are useful for people translating as they provide some context as to the term's meaning in the broader App Inventor context. For example, "map" could mean a geographical map, or it could be "map" in the functional programming sense. In other languages, this might be translated to completely different words. The description should help disambiguate the English meanings.

**Comment by ewpatton** [comment]
I should add that the descriptions in the OdeMessages are not the descriptions that are used in the blocks. They are solely for translation purposes.

**Comment by NmdOfficial** [comment]
Another question:
Why are now in the ode messages file some descriptions not empty?

The most (99%) of the descriptions are done in the given component itself.

Why are now only some descriptions direct added in the odemessages file?!
It does not make sense to me.. because the most descriptions of a property were always added in the component (-> SimpleProperty(description="blablabla")... itself

**Comment by ewpatton** [comment]
The descriptions in OdeMessages file are not user-facing. You still need to add the description to the appropriate `@SimpleProperty` annotation. The descriptions that are in OdeMessages are only intended to be shown to people translating the component strings into another language.

**Comment by NmdOfficial** [comment]
Thank you very much for explain it.
