### ISSUE TITLE
Add helpString to Designer Properties

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1128]
I think it can be like this: 
![image](https://user-images.githubusercontent.com/22613139/34977140-5a0602b2-fad4-11e7-8028-e3a6824644bd.png)
Similar to: 
![image](https://user-images.githubusercontent.com/22613139/34977108-46565dde-fad4-11e7-9836-5d2f57517d02.png)

**Comment by ewpatton** [comment]
I actually implemented a version of this many years ago prior to the internationalization of App Inventor. I don't think it would be that difficult to bring it current. The problem is that we do not have translations of the simple property descriptions into other languages--they are hard-coded in the `@SimpleProperty` annotation rather than being described in OdeMessages.java.

**Comment by tasos12** [comment]
Hello Evan
I would like to apply for GSoC 2019 with MIT App Inventor and help resolving this issue as part of the community introduction phase.

**Comment by suvamjain** [comment]
Hi @ewpatton ,
looking to fix this issue. Can I get some more information like where to find this in the code base?

**Comment by ewpatton** [comment]
This requires a few changes. Here’s a rough sketch:

1. Add the new field to DesignerProperty.java (in components...annotations)
2. Update ComponentDescriptionGenerator to include the new field in the json description of the property (in components...scripts)

Somewhere I have a branch that includes the property helpstrings in the UI that will use this. I will send you a pointer once I put it up. In the meantime you can work on implementing 1 and 2.

**Comment by suvamjain** [comment]
I have implemented steps 1 and 2 @ewpatton, @ColinTree. Now can you please guide me further, how to add a helpstring icon near designer properties and how do they show the property description on clicking it. **Changes referring to step 1 and 2 in the respective files are highlighted in the screenshots attached below** - 

### Step 1 --> changes in ../components/annotations/DesignerProperty.java 

![image](https://user-images.githubusercontent.com/29479040/54885631-66ee3100-4ea4-11e9-9b32-55f6ce0b7b38.png)

### Step 2 --> changes in ../components/scripts/ComponentDescriptorGenerator.java 

![image](https://user-images.githubusercontent.com/29479040/54885633-6fdf0280-4ea4-11e9-9868-62f9b2917808.png)

**Comment by suvamjain** [comment]
Also @ewpatton, can you please assign this issue to me

**Comment by ewpatton** [comment]
@suvamjain It seems reasonable to me. I'll try to find the branch I have for properties and get it up as a PR. Do you want to submit this?

**Comment by suvamjain** [comment]
Yes, I want to submit this. If I'm right I just have to commit the code on my forked repo and then a pull request should be sent, correct?

**Comment by ewpatton** [comment]
@suvamjain Yes, that's correct. For this change, you can submit the PR against master.

**Comment by ewpatton** [comment]
Note that the recommended best practice is to create a feature branch and commit your work there. This way your copy of master stays in step with ours. Submit the PR for the feature branch to master.

**Comment by suvamjain** [comment]
Just for confirmation, PR stands for Project Repository right?

**Comment by josmas** [comment]
@suvamjain  PR stands for [Pull Request](https://help.github.com/en/articles/about-pull-requests).

**Comment by suvamjain** [comment]
Oh!! thanks @josmas 😅

**Comment by suvamjain** [comment]
Hi @ewpatton, Please review the PR I just submitted.
