### ISSUE TITLE
Question - name on non visible components

### ISSUE THREAD

**Issue by NmdOfficial** [mit-cml/appinventor-sources#1131]
Hello.
This is not a issue, this is a question. 

I want to know which file we have to modify to show or hide the name of a component in the non-visible components table.
After we added a non visible component we see below the phone preview the components logo and name. 
How can we enable or disable there the name of the current non visible component?

**Comment by ewpatton** [comment]
@NmdOfficial You should look at `MockNonvisibleComponent` in `appengine/src/com/google/appinventor/client/editor/simple/components`. The `iconWidget` field has a `setCaption` property. My guess is that if you set it to null/the empty string it should hide the title.

**Comment by NmdOfficial** [comment]
Thank you very much for the help. @ewpatton
