### ISSUE TITLE
Question - App loading background color

### ISSUE THREAD

**Issue by NmdOfficial** [mit-cml/appinventor-sources#1134]
Hello. Today I have another but simple question again.
When we start a app made with app inventor or any other distrubution we will see a black screen until all things are finished loading. As example if we have many blocks inside the app we will see the black screen until it is finished loading. 

How can we change the default black background color to any other color on app start?
Is it the frame layout where we have to add a color in the on create section?
I hope my question is clear.
Best regards.

**Comment by ewpatton** [comment]
There is not an official way to do this in App Inventor, but it is possible. You will need to modify Compiler.java to include a color entry for the background color you want to use, and in the set the windowBackground item in AppTheme, e.g.:

```xml
<item name="android:windowBackground">@color/windowBackgroundColor</item>
```

**Comment by jcruze057** [comment]
how do i do that in app inventor? can we include that as official function in ai2?
