### ISSUE TITLE
Buildserver build-from-zip receive 403 Forbidden

### ISSUE THREAD

**Issue by 4383** [mit-cml/appinventor-sources#1135]
Hi!

I try to setup the local build server according the instructions defined [here](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/README) the build server seems to be started properly:
```
     [java] Jan 17, 2018 10:01:42 PM com.google.appinventor.buildserver.BuildServer main
     [java] INFO: App Inventor Build Server - Git Fingerprint: 8a687c241217cf6c122c1cd938e23aa09f03bbf0
     [java] Jan 17, 2018 10:01:42 PM com.google.appinventor.buildserver.BuildServer main
     [java] INFO: Running at: http://172.17.0.2:9990/buildserver
     [java] Jan 17, 2018 10:01:42 PM com.google.appinventor.buildserver.BuildServer main
     [java] INFO: Maximum simultanous builds = unlimited!
     [java] Jan 17, 2018 10:01:42 PM com.google.appinventor.buildserver.BuildServer main
     [java] INFO: Visit: http://172.17.0.2:9990/buildserver/health for server health
     [java] Jan 17, 2018 10:01:42 PM com.google.appinventor.buildserver.BuildServer main
     [java] INFO: Visit: http://172.17.0.2:9990/buildserver/vars for server values
     [java] Jan 17, 2018 10:01:42 PM com.google.appinventor.buildserver.BuildServer main
     [java] INFO: Server running
```

But when I try to build something by using curl I always receive a `403 Forbidden`, why? I've followed the readme step by step.

Curl command used:
```sh
$ curl --data-binary @/mypath/foo.zip \
   --output  /mypath/foo.apk \
   --dump-header /mypath/output.log \
   http://172.17.0.2:9990/buildserver/build-from-zip
```

Also I try with uname paramter:
```sh
$ curl --data-binary @/mypath/foo.zip \
   --output  /mypath/foo.apk \
   --dump-header /mypath/output.log \
   http://172.17.0.2:9990/buildserver/build-from-zip?uname=test
```

But I don't really understand what correspond to uname, can you explain this to me?

Second, I want to build an `foo.aia` but the server seems to only handle zipfile (according to the http routing name function => `build-from-zip`), `aia` file is a zipfile with extension renamed, so, buildserver can deal directly with an `aia` file?

Thanks for your help!

**Comment by 4383** [comment]
Also when I try to use this command I receive the following error:
```sh
ant RunMain -Dzip.file= /mypath/foo.zip -Duser.name=test -Doutput.dir=/mypath
...
     [java] INFO: extracting /tmp/1516228594427_0.7372726608315997-0/youngandroidproject/project.properties from input zip
     [java] Jan 17, 2018 10:36:34 PM com.google.appinventor.buildserver.ProjectBuilder build
     [java] SEVERE: Unknown exception signalled by genYailFilesIf Necessary
     [java] java.lang.NullPointerException
     [java]     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
     [java]     at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:77)
     [java]     at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:72)
     [java]     at com.google.common.io.Resources.asByteSource(Resources.java:66)
     [java]     at com.google.common.io.Resources.newInputStreamSupplier(Resources.java:57)
     [java]     at com.google.appinventor.buildserver.Compiler.getResource(Compiler.java:1699)
     [java]     at com.google.appinventor.buildserver.ProjectBuilder.generateYail(ProjectBuilder.java:489)
     [java]     at com.google.appinventor.buildserver.ProjectBuilder.genYailFilesIfNecessary(ProjectBuilder.java:230)
     [java]     at com.google.appinventor.buildserver.ProjectBuilder.build(ProjectBuilder.java:137)
     [java]     at com.google.appinventor.buildserver.Main.main(Main.java:82)

BUILD FAILED
/appinventor-sources/appinventor/buildserver/build.xml:263: Java returned: 1
```

And when I inspect sended request from the official online version I can observe that I language description was sended via an ajax post:
![capture du 2018-01-17 23-51-13](https://user-images.githubusercontent.com/1541489/35071779-454583b6-fbe2-11e7-9638-13654c314b92.png)

So I think that a temporary step is need for generate Yail file before build, can you confirm?

**Comment by ewpatton** [comment]
In App Inventor Classic, YAIL files were generated by the build server. For the current version of App Inventor, YAIL files are now generated in the web interface by the blocks editor, and can only be generated/downloaded/exported if you are an administrator. If you are running a local instance of App Inventor, you can opt to be an administrator when you choose the "log in with google account" link on the login page.

**Comment by 4383** [comment]
@ewpatton thanks for response.
It's possible to directly build an `aia` file by passing it in command parameter? like this:
```sh
$ ant RunMain -Dzip.file= /mypath/foo.zip -Duser.name=test -Doutput.dir=/mypath
```

**Comment by 4383** [comment]
I don't want use the web interface for building my apk files, by example I want to export an `aia` file from the web interface and in second time in local I want to build this project with the command line like CLI.

**Comment by ewpatton** [comment]
Yes, I know that you can build apps from the command line. My point is that when you export the project from the website the YAIL code is not included, unless you are an administrator.

**Comment by josmas** [comment]
To reiterate @ewpatton's comment, simply log in as Admin in your local server, that way the YAIL will be included when you export the app, and you will be able to use the command line to build it.

Closing this for now. Re-open if needed.
