### ISSUE TITLE
Content from textblock is displayed in projects page if selected. 

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#1140]
If you select the text in a textblock and click on my projects the text from the textblock is copied to the projectpage and you can edit it. 

It works with Chrome and Opera, so it will be a blockly issue. I made a gif file to show the issue in AppyBuilder but i saw it in Thunkable, Makeroid and App Inventor.

![peek 2018-01-20 09-54](https://user-images.githubusercontent.com/32273650/35181786-b15bad18-fdc8-11e7-8ddf-8381a124b937.gif)

**Comment by ewpatton** [comment]
I think what we need to do here is call `Blockly.hideChaff()` when we transition to another display other than the blocks editor.
