### ISSUE TITLE
black screen appears before first screen appears

### ISSUE THREAD

**Issue by jcruze057** [mit-cml/appinventor-sources#1149]
hi, i am having this issue, how do i temove the blank black screen?

**Comment by jcruze057** [comment]
here is the youtube video https://youtu.be/grpl8z3WsF8

**Comment by jcruze057** [comment]
and also how to remove the blinking of the whole screen when keyboard appears?

**Comment by jcruze057** [comment]
here is the video https://youtu.be/NAzLchFRKww

**Comment by jcruze057** [comment]
it seems this could be rhe fix but this is in android studio, ho do i apply this in app inventor?
https://stackoverflow.com/questions/20546703/how-to-fix-white-screen-on-app-start-up

**Comment by ColinTree** [comment]
That is because the work for Initialling Event is too heavy. Please reduce the blocks in Screen.Initialize.
A way to do that is moving blocks into a Clock.Timer which run only once(implement this with variable), and runs only few millisec after Initiallize.

**Comment by ColinTree** [comment]
Also, only one problem should be discussed in a single thread(issue) please.

**Comment by jcruze057** [comment]
cool, I only put 1 block in the screen initialize, just to enable the clock but now I removed it and the black screen is gone, now I only got one problem left and thats the blinking of the whole screen when the keyboard appears and resizes all controls. how do we solve this?

**Comment by ColinTree** [comment]
That would be weird. Would you please share the blocks? Or what about try another phone?

**Comment by jcruze057** [comment]
here is the block https://scontent.fmnl4-4.fna.fbcdn.net/v/t1.0-9/27067368_10156249155508679_8024048032535232544_n.jpg?oh=9a81a5be14e87241f4dbf86c2a2b7b86&oe=5B21C83A

**Comment by ColinTree** [comment]
I think i got a zone lock on this website here, you can upload image to github directly here.

**Comment by jcruze057** [comment]
![capture](https://user-images.githubusercontent.com/12553445/35548006-af618d42-05b7-11e8-810d-c535eca03f33.PNG)

**Comment by ColinTree** [comment]
Well, is this all of your blocks? Are you using some extensions?

**Comment by jcruze057** [comment]
I am not using any extension but I am planning to add BluetoothLE1

**Comment by ColinTree** [comment]
Does it behave the same with a new project?

**Comment by jcruze057** [comment]
yes all of my projects

**Comment by ColinTree** [comment]
That may not the problem of appinventor cuz i dont got this problem here.
Please try on another device.

**Comment by NmdOfficial** [comment]
He is talking about this:
https://github.com/mit-cml/appinventor-sources/issues/1134

**Comment by jcruze057** [comment]
yes, so is there a way to get rid of the black screen?

**Comment by ewpatton** [comment]
There is not a supported way of addressing this in App Inventor. You may be able to use AppToMarket or similar to modify the compiled AndroidManifest to specify a windowBackgroundColor. In the future, this is a discussion that is better asked on [the MIT App Inventor forum](https://groups.google.com/forum/#!forum/mitappinventortest).

**Comment by NmdOfficial** [comment]
There is a easy way to do that @ewpatton 
If you want to know how. Let me know it.
best regards

**Comment by jcruze057** [comment]
@nmdofficial, is it posdible to mske it an official feature of app inventor? it wpuld be cool and also should be able to choose what type of animation. byt since it is not officially a bug,va could already explain it to my peers
