### ISSUE TITLE
Duplicated line

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#1157]
https://github.com/mit-cml/appinventor-sources/blob/34b388fb4270200009afa3d2bac5dd80b90b5f3f/appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml#L26

https://github.com/mit-cml/appinventor-sources/blob/34b388fb4270200009afa3d2bac5dd80b90b5f3f/appinventor/appengine/src/com/google/appinventor/YaClient.gwt.xml#L34

**Comment by ColinTree** [comment]
Why not just submit a PR to fix this, dont even needs to do it in local machine
