### ISSUE TITLE
Confirm dialog for deleting blocks is not replaced by GWT dialog

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1173]
This is what it shows by pressing delete on keyboard
![image](https://user-images.githubusercontent.com/22613139/37167633-6a781590-233d-11e8-821a-a2871140e6d1.png)

This is what it shows when dragged into the bin
![image](https://user-images.githubusercontent.com/22613139/37167665-849c9ce8-233d-11e8-974a-ec1db2145919.png)

Also, the bin dialog is not listening to escape key & enter key on keyboard.

**Comment by ewpatton** [comment]
@ZhengCornell Here's a small issue you could take a look at if you have time. It will require changing Blockly core though so let me know when you start to work on it.

**Comment by ewpatton** [comment]
Closed via #1668
