### ISSUE TITLE
Dialog does not block top tool bar drop downs

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1177]
Gif file: (size 1.3m)
![animation](https://user-images.githubusercontent.com/22613139/37210117-88793c18-23e2-11e8-81d0-096bc9219fdb.gif)

It should be like:
![image](https://user-images.githubusercontent.com/22613139/37210162-b1256740-23e2-11e8-829c-a2264fa3b287.png)

**Comment by ewpatton** [comment]
As pointed out by @hsun1316, this doesn't seem to be happening in production. @ColinTree if you can give us more information to reproduce this we can reopen it.
