### ISSUE TITLE
Help Needed Building Source

### ISSUE THREAD

**Issue by TurboProgramming** [mit-cml/appinventor-sources#1178]
Hello,

I'm trying to build the App Inventor Source to Cloud Console (App Engine) but Cloud Console doesn't have ant supported by default and I need help.

How can I proceed?

**Comment by TurboProgramming** [comment]
I'm at the `ant clean` part

**Comment by josmas** [comment]
Could you please ask this question in the Open Source group? here's the link: https://groups.google.com/forum/#!forum/app-inventor-open-source-dev

Closing this issue for now as it is not a source issue.
