### ISSUE TITLE
Error 1103: unable to post or put the text "xxxxx" with the specified URL : http://rendezvous.appinventor.mit.edu/rendezvous

### ISSUE THREAD

**Issue by hongtaozhang** [mit-cml/appinventor-sources#1185]
i am a chinese user,  when i use  mit companion  to scan qr code and click the connect with code , i found it post data to this url : rendezvous.appinventor.mit.edu,  in china , we can not access this url, how can i fix this issue ?

**Comment by ewpatton** [comment]
@hongtaozhang Which App Inventor service are you using? If you are using the server hosted in Guangzhou, I believe they have a different version of the companion that you must use.

**Comment by hongtaozhang** [comment]
> @hongtaozhang Which App Inventor service are you using? If you are using the server hosted in Guangzhou, I believe they have a different version of the companion that you must use.

how can i fix this issue?  change the url "rendezvous.appinventor.mit.edu" to another?  which host in guangzhou ?

**Comment by ewpatton** [comment]
I'm closing this for now. If you are still having issues with the rendezvous server (which has been updated), please consider asking for help on the [MIT App Inventor Forum](https://groups.google.com/forum/#!forum/mitappinventortest).
