### ISSUE TITLE
Duplicate methods

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#1186]
https://github.com/mit-cml/appinventor-sources/blob/25444cceb00411df0e663ab501ee55acdaed0ef9/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java#L1825-L1838

https://github.com/mit-cml/appinventor-sources/blob/25444cceb00411df0e663ab501ee55acdaed0ef9/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java#L1840-L1853

Both are clearly similar methods.

**Comment by josmas** [comment]
They are indeed! Can you track usage of both methods? an IDE should be helpful to track usage and do some refactoring if you are up for it.

**Comment by pavi2410** [comment]
Yes, sure
