### ISSUE TITLE
AAR vector resources incomplete

### ISSUE THREAD

**Issue by kevinc123** [mit-cml/appinventor-sources#1190]
After decompiling an apk I found that the vector resources are incomplete.

I think that this can be caused by the resource merger or when packaging the apk

This is the actual output of abc_ic_ab_back_material.xml for example in the compiled apk made by buildserver:
`<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:tint="?attr/colorControlNormal" android:height="24dp" android:width="24dp">
    <path />
</vector>`

And this is the original file found on temp folder made by buildserver build\exploded-aars\android.support.v7.appcompat\res\drawable (I removed copyrigth message):

`<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0"
        android:autoMirrored="true"
        android:tint="?attr/colorControlNormal">
    <path
            android:pathData="M20,11L7.8,11l5.6,-5.6L12,4l-8,8l8,8l1.4,-1.4L7.8,13L20,13L20,11z"
            android:fillColor="@android:color/white"/>
</vector>`

**Comment by kevinc123** [comment]
Solved, seems that in newer versions of AAPT and appcompat/support libs we need to add another argument to appt

This did the trick in runAaptPackage method:
`aaptPackageCommandLineArgs.add("--no-version-vectors"); `

![image](https://user-images.githubusercontent.com/13980708/37628942-37540528-2bdc-11e8-840c-9565acc659e8.png)
![image](https://user-images.githubusercontent.com/13980708/37629046-bd6888aa-2bdc-11e8-95a6-1c1c2885ffdc.png)

**Comment by ewpatton** [comment]
Fixed in 3b3f7d0
