### ISSUE TITLE
Internal Error with NxtColorSensor

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1195]
**Try to drag the NxtColorSensor to the designer and see what happens**

On AI2-Test:

- `faultData = com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot set property 'yb' of null`
- `faultData = com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'Fb' of null`

On Makeroid:

- `faultData = com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot set property 'leftPosition' of null`
- `faultData = com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'widget' of null`

You get completly random errors

**Comment by josmas** [comment]
Hey @barreeeiroo thanks for the report; If you could try #1196 in Makeroid, that would be great.
