### ISSUE TITLE
FirebaseDB property isn't properly generated

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1199]
First of all congrats for the 500 ⭐️ 
![image](https://user-images.githubusercontent.com/19251112/38178450-8fbb005e-3613-11e8-8a40-dfec5535dc8b.png)

---

And here's the issue:
![image](https://user-images.githubusercontent.com/19251112/38178456-ca6c81f0-3613-11e8-9b0a-3f7fc9e48698.png)

The _**Use Default**_ property isn't generated in the same way as the other boolean properties (such is _Persists_)
It's because it's generated from MockFirebaseDB.java instead from FirebaseDB.java, but couldn't this be fixed?

**Comment by josmas** [comment]
hey @barreeeiroo is there an actual problem with the property? Or is your question `why` is the property different?

**Comment by NmdOfficial** [comment]
I think the question is why the "Persist" property is not created in the component itself?

**Comment by josmas** [comment]
My guess is that the property is only used to build the app, same as a number of properties in `Screen` such as `VersionName` and so forth. It is not visible in blocks, as it should not be set programmatically; the same design is used in CloudDB.

**Comment by barreeeiroo** [comment]
But it breaks a little bit the design, no?
All properties have the checkbox above the label, while there no

**Comment by ewpatton** [comment]
The Use Default checkbox here is not a separate property editor, but is part of the FirebaseURL property editor (specifically [YoungAndroidDefaultURLPropertyEditor.java](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/properties/YoungAndroidDefaultURLPropertyEditor.java)).

An alternative design might be to have a radio option with "DEFAULT" and "CUSTOM" where CUSTOM also includes a textbox, similar to how a survey might have multiple options with an "other:" entry.

**Comment by jisqyv** [comment]
Not a bug to fix
