### ISSUE TITLE
Blocks still in Backpack cannot be seen in new project if they correspond to extension from original project

### ISSUE THREAD

**Issue by jsheldonmit** [mit-cml/appinventor-sources#1200]
From Chris Ward, AppInv Power User:
Copied 3 blocks to the empty Backpack
Opened another existing project
Opened the Backpack - no blocks can be seen
Right mouse click menu shows 3 blocks in Backpack
Select Paste All Blocks from Backpack - one block can be seen in Viewer, others cannot but they do (correctly) trigger warnings

He discovered that the blocks do correctly render at all in the backpack if they reference an extension that's not in the project being pasted to.

**Comment by ewpatton** [comment]
I guess this isn't terribly surprising that this would happen. I think it should be a straightforward fix.
