### ISSUE TITLE
ClearTag in CloudDB results in error

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1208]
[From the forum](https://groups.google.com/forum/#!topic/mitappinventortest/wn7-t8QhTwQ): Using the CloudDB ClearTag block in the companion app results in a CloudDB error with the message `byte[] cannot be cast to java.lang.Long`.

**Comment by farxinu** [comment]
I've confirmed this issue exists.

**Comment by jisqyv** [comment]
@ewpatton @farxinu This should be fixed. The fix was in the security filter in front of redis, so no release is/was needed. Fixed code is deployed.

-Jeff
