### ISSUE TITLE
Blocks do not return to original position if trashing is canceled

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1210]
In testing #1198, I noticed that when I cancel the dialog, the blocks do not move back to the original position from which they were dragged. In most cases, if people are intending to delete the blocks this is fine because they will be destroyed, but if the user decides against deleting then the blocks are out of place.

**Comment by hsun1316** [comment]
@ewpatton @josmas I would like to work on this issue, is there anywhere I can look to get started with this?

**Comment by josmas** [comment]
hey @hsun1316 it seems like the deletion is done [here](https://github.com/mit-cml/blockly/blob/65b130840f56961767320904929d0abf4794a218/core/blockly.js#L231). That might give you some idea on where to look at next.

**Comment by ewpatton** [comment]
Closed via #1551
