### ISSUE TITLE
Width is not shown in alphabetical order in designer page

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1212]
Low priority but looks weird, since it always shown after property Height
e.g.
![image](https://user-images.githubusercontent.com/22613139/38778673-d2c6803a-40ef-11e8-99a5-29e53009b489.png)

**Comment by ewpatton** [comment]
@ColinTree This logic predates my involvement with App Inventor, but I believe the logic for grouping them is that if one is modifying height, they are also likely modifying width, and so they are placed in visual proximity. By treating "Width" as "Heightz", it ensures that the two are lexographically sorted close together with Width coming after Height.
