### ISSUE TITLE
Validation problems prevent project loading

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1213]
Two problems in the validation of the blocks editor that can result in invalid workspaces on load:

Normally, a text block with numbers will be accepted as numeric thanks to type coercion. This is done by using `parseFloat`, which will parse as many valid characters as possible. This doesn't guarantee that the value is a valid number, however, for example:

![image](https://user-images.githubusercontent.com/1331253/38835977-a56ad658-419a-11e8-8b26-3c3ef593d79e.png)

In addition to doing this, once the block is connected you can remove the number and the addition block accepts the string:

![image](https://user-images.githubusercontent.com/1331253/38836021-cabb6ec2-419a-11e8-8b12-0895b3deacc9.png)

When loading a project with blocks like this, the error "The blocks area did not load properly..." error appears and the project is no longer editable.

**Comment by SusanRatiLane** [comment]
I'm not clear why we want the the behavior of accepting a text input to a numeric operation?

From testing indicates that validation is being run before an action rather than after. If a string passes validation and has already been linked to an operation at the beginning of a change, altered text does not appear to be recognized as failing validation until it is edited a second time.

**Comment by ewpatton** [comment]
I think we want to check that the validator behavior has the following two constraints:

1. The value validator is checked at every key stroke to ensure that "0" is allowed but "0i" is not (for a number-ish block). We also need to make sure the validator is more robust to the fact that `parseInt` and `parseFloat` will parse the first portion of the text that is a number even if not all of the text is.
2. The connection validator is run when a change to the block is committed. This way, if there is no longer a number in the text field, we can bump out the block.

Per our discussion in the office, it is also a good idea to appropriate catch the thrown exception in this case and mark the block bad rather than make the project quasi-read-only as is currently the case.
