### ISSUE TITLE
Project crashing after adding some components

### ISSUE THREAD

**Issue by aperpen** [mit-cml/appinventor-sources#1216]
My project is crashing both in MIT Companion or in the compiled apk.
The problem started after adding this component: 
![image](https://user-images.githubusercontent.com/24506783/39000033-5401c37a-43f3-11e8-9ac6-ddfc3a8593e6.png)

I don't get any error message, it's just crashing. If you remove that component, it will work properly again.
This is the working aia (renamed to .ZIP because github doesn't support .AIA): [working.zip](https://github.com/mit-cml/appinventor-sources/files/1928648/working.zip)
And this is the failing aia: [failing.zip](https://github.com/mit-cml/appinventor-sources/files/1928644/failing.zip)

The component causing troubles is in screen "App", in "Pantalla" > "Menu".

**Comment by ewpatton** [comment]
I think you are running out of memory on your device. I just tested this on our latest emulator package for Mac and it worked fine. Consider reducing the size of your images and see if you continue to experience crashes. In the future, questions like this should be asked in the [MIT App Inventor Forum](groups.google.com/forum/#!forum/mitappinventortest).

**Comment by aperpen** [comment]
Ok. Just posted it here because I thought it was a bug. Thank you for your help.
