### ISSUE TITLE
Doubt about GAE Instances

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1220]
I guess AppInventor runs under Google AppEngine Standard Environment
If so, why not switching to Flexible Environment?

**Comment by ewpatton** [comment]
@barreeeiroo 
Two reasons:
1. Historically, the standard environment was the only offering when App Inventor was open sourced, so it is partly the devil you know.
2. App Inventor resource needs are very dependent on the time of day around the world (it peaks daily around 3pm ET when most schools in the US are in session), so we use anywhere from 4 to upwards of 30 instances. By letting Google scale the number of instances automatically, it helps us reduce some of our costs by not requiring 30 instances running all of the time.

**Comment by halatmit** [comment]
Currently we're seeing about 90K users day -- 680K unique users, since April 1 and about 1.5M sessions.
