### ISSUE TITLE
Request generic component event feature

### ISSUE THREAD

**Issue by wxbit** [mit-cml/appinventor-sources#1223]
Well, I have finished a working version. [https://dev.wxbit.com](https://dev.wxbit.com)
The version is asking for test. Maybe I should submit later?
Also, I have added dynamic creation capability to component container, all the visible ui component can be created in blocky code.

![canvas](https://user-images.githubusercontent.com/3827464/39626097-34d85620-4f66-11e8-961f-fcd5d285bdfe.gif)

**Comment by kkashi01** [comment]
That looks very nice. Does it allow you to dynamically set the component properties too?

**Comment by p4ssw0rd** [comment]
@kkashi01 Sure,absolutely.

**Comment by kkashi01** [comment]
@p4ssw0rd. Can you provide the .aia for this?
https://user-images.githubusercontent.com/3827464/39626097-34d85620-4f66-11e8-961f-fcd5d285bdfe.gif

**Comment by p4ssw0rd** [comment]
Ok, it can be imported to my dev server only. With generic component event, it's very simple.
It can be simpler without timer, which I use to wait for keyboard to hide.

[CanvasEn.aia.zip](https://github.com/mit-cml/appinventor-sources/files/1974758/CanvasEn.aia.zip)

![canvasen-designer](https://user-images.githubusercontent.com/3827464/39633403-82fdfe92-4f7d-11e8-873a-d80ab80067aa.png)

![canvasen](https://user-images.githubusercontent.com/3827464/39633211-f5332b78-4f7c-11e8-9dfe-bc96f642ad37.png)

**Comment by ewpatton** [comment]
@p4ssw0rd Do you have a design doc for this? How does a concrete event handler for a specific ball relate to the generic version?

**Comment by p4ssw0rd** [comment]
Generic event handler has a "component" parameter, identify which instance is handling event.

**Comment by ewpatton** [comment]
I think we will want to have this as two separate submissions if you decide to submit it, one for the generic event handlers and another for dynamic objects. Take a look also at comments on #313, #347, and #450, which attempted to solve the generic event handler problem.

When I implemented similar functionality for Maps, I chose to bubble events from most specific to least specific event handler. For example, if you had a polygon inside of a feature collection inside a map, the polygon's event handler would be evaluated first, followed by the feature collection's handler, followed by the map's handler. Please verify that your implementation has similar semantics.

**Comment by ewpatton** [comment]
Resolved via 4ddd02dbb020dbcbf99483c1edeeb784e0d4f895
