### ISSUE TITLE
Close bug

### ISSUE THREAD

**Issue by SynapseUser** [mit-cml/appinventor-sources#1226]
I see that this issue has been reported in the past [Here](https://github.com/mit-cml/appinventor-sources/issues/284) But the issue was closed  ?

However I think there are still issues with how screens are closed. I have produced a small test app that demonstrates this issue. You can download it here 
[Here](http://www.synapsesoftware.co.uk/backup/closetest.aia)

Here is an overview of the problem 
[Here](http://www.synapsesoftware.co.uk/backup/CloseBug.pdf)

Please advise.

Thanks.

**Comment by ewpatton** [comment]
Short answer: App Inventor assumes that Screen1 is the lowest item in the activity stack. When you open a second copy of Screen1, as you do in your example, this assumption is broken.

Long answer: The close application logic closes all of the screens in the Android activity stack until it hits Screen1, and then calls `System.exit(0);` to quit the VM. However, Android sees this as more of a crash than an exit, so it attempts to restore the activity stack to what it was just prior to the exit call. In this case, the topmost Screen1 has been finished, so now the topmost activity is now Screen2 (with the original Screen1 still below it in the stack). This is the underlying basis for the behavior you observe.

**Comment by SynapseUser** [comment]
Hi -
Sorry, not sure what you mean when you say `When you open a second copy of Screen1, as you do in your example, this assumption is broken.`  I was not aware that I was opening a "copy" of anything - the app has 3 screens and I am using the only command I know to open an instance of a new screen ?

Also, I think its worth mentioning that this phenomenon really only manifests itself when you try deploy the app to your phone (without using the AI companion.)

If I am not using the commands correctly or if there is a "better" way to call additional screens without triggering this circular behaviour, then I would appreciate some advice.

Many Thanks.

**Comment by SynapseUser** [comment]
I am guessing that this is still an issue, so thought I would suggest a work-around for anyone experiencing the same issue. Please remember - afaik - this is just an issue if you try deploy your app to your phone as an apk.

To force-close the app, I store a variable in TinyDB called "quit_check" when the "quit" button is pressed, I write "YES" to this field. All other screens that can be called from the main screen check / read this value (during the screen initialize method) and if its "YES" they call "Close Application" command again. This seems to work.

Hope this helps someone..

**Comment by ewpatton** [comment]
Activities are managed as a stack in Android, and therefore in App Inventor. When you use the "open another screen" it always creates a new activity that gets put on the stack. The sample project you shared with us does this:

```
                  Screen1
         Screen2  Screen2  Screen2
Screen1  Screen1  Screen1  Screen1
----------------------------------
   t0       t1       t2       t3
```

When you get to state `t2` and call close application, App Inventor pops all of the activities from the topmost activity until it gets to an activity called Screen1. The problem is that because you are opening another Screen1, it immediately finds that second Screen1 and attempts to exit. Android, confused as to why the app has exited, will recover the activity stack minus the activity that exited, which gives you state `t3`.

Instead of opening another Screen1, you should call "close screen" to return to Screen1 from Screen2. This ensures that a single Screen1 exists so that the semantics of the close application block are maintained.

**Comment by p4ssw0rd** [comment]
We should not be allowed to open another Screen1.Or should force close another screen to return.

**Comment by SynapseUser** [comment]
Ok, thanks for clearing that up for me. I come from a windows development background (Delphi) and so am used to having more flexibility with regards program flow and asset management.

Is the approach you outline a property of Java or App inventor ? It just seems to enforce a very restrictive / linear navigation model. Quite often in an application, one screen can call a second which in turn may need to call a third. In the system you outline, the user would have to go something like this ->

Screen1 -> Screen2->Screen3
Then to get back to the main screen would have to re-trace their steps, so,.,
Screen3 ->Screen2 -> Screen1

Whereas , quite often its useful to allow the user to simply go from screen3 directly back to screen1 (and so bypass Screen2).

Just seems odd to me coming from a typical Windows development system.

Anyway, thanks for your feedback.

**Comment by SynapseUser** [comment]
Fair point and I will close this issue now.
Cheers..

**Comment by p4ssw0rd** [comment]
@ewpatton When NFC component is used, Screen1 activity is set as  singleTask in Compiler.java. Can we always set Screen1 as singleTadk to fix? Open screens without close will crashed the app.
