### ISSUE TITLE
componentDb.getPropertyForType(...) is null

### ISSUE THREAD

**Issue by 10MINT** [mit-cml/appinventor-sources#1229]
I've seen this error now a few times. The uploading assets dialog finishes, but the phone does nothing. Reloading does not help, so I'm not able to test my apps anymore. Maybe this is coincidence, but I've encountered the "disappearing blocks problem" in the same apps.

> notes = Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 
> foundIn = nb167el3 
> faultData = com.google.gwt.core.client.JavaScriptException: (TypeError) : g.getPropertyForType(...) is null 
> projectId = 4725547334369280

**Comment by josmas** [comment]
That method seems to be used on twice (
https://github.com/mit-cml/appinventor-sources/search?utf8=%E2%9C%93&q=.getPropertyForType&type=).
You could place a breakpoint in the javascript to debug and see the values
that make it go null... that might give you some ideas of what's going on.


cheers,
José

**Comment by 10MINT** [comment]
The console says
> TypeError: g.getPropertyForType(...) is null
mjh/</nb.Yail.getPropertySetterString http://ai2.appinventor.mit.edu/:27:22407
mjh/</nb.Yail.getPropertySettersLines http://ai2.appinventor.mit.edu/:27:22150
mjh/</nb.Yail.getComponentPropertiesLines http://ai2.appinventor.mit.edu/:27:21691
mjh/</nb.Yail.getComponentLines http://ai2.appinventor.mit.edu/:27:21135
mjh/</nb.Yail.getComponentLines http://ai2.appinventor.mit.edu/:27:21358
mjh/</nb.ReplMgr.buildYail http://ai2.appinventor.mit.edu/:28:1912
mjh/</nb.ReplMgr.pollYail http://ai2.appinventor.mit.edu/:28:3300
mjh/</nb.ReplMgr.sendFormData/this.polltimer< http://ai2.appinventor.mit.edu/:28:3144

**Comment by josmas** [comment]
sure, it is `null`, we know that, but if you place a breakpoint you should be able to inspect associated values such as `componentType, propertyName` and maybe (maybe not) figure out why it is `null` in that case. Is it asking for a `componentType` that does not exist? or is `propertyName` also `null` making the returned value `null` overall?... it may be possible to answer those questions with a breakpoint.

Is this with the unmodified sources or does it happen in a custom build?

**Comment by 10MINT** [comment]
MIT server at http://ai2.appinventor.mit.edu/

**Comment by ewpatton** [comment]
@10MINT Please send us an export of the broken project so that we can take a look.

**Comment by 10MINT** [comment]
Sure, where should I send it?

**Comment by ewpatton** [comment]
You can send it to my GitHub username at mit.edu

**Comment by 10MINT** [comment]
@ewpatton I tried to send it to you, but Google does not allow sending .aia files, so I'm posting it here. (Rename it to .aia)
[i18n.zip](https://github.com/mit-cml/appinventor-sources/files/1981164/i18n.zip)

**Comment by ewpatton** [comment]
I am able to reproduce the error with your project. I think the issue is that you have an extension property (`FileFromAsset`) annotated with `@DesignerProperty` but not `@SimpleProperty`. The easiest way to fix the problem would be to annotate that with `@SimpleProperty(userVisible = false)`.

Longer term, we should think about either having the external component generator either generate a block property entry even if the `@SimpleProperty` annotation is missing, or if we detect this scenario we can have the generator error out and request that the author address the problem.

**Comment by 10MINT** [comment]
Thanks for taking a look at it. I'll take a look at my other extensions, too. Might be a good idea to catch these errors server-side.

**Comment by ewpatton** [comment]
A bit more detail on what's going on:

The thrown error is occurring [here](https://github.com/mit-cml/appinventor-sources/blob/0a27dc33ccad782db3516c3d3f255404eb6564d4/appinventor/blocklyeditor/src/generators/yail.js#L409) as part of the screen codegen. This error will occur whenever there is a designer property with a non-default value and without a corresponding block property. The type information is part of the block property definition, and so we attempt to get the type from null when the block property definition doesn't exist.

**Comment by 10MINT** [comment]
I can now confirm that this fixed my broken apps!
