### ISSUE TITLE
aiStarter 3.0 does not work on Mac OS X < 10.12

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1232]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/Bs4rsWg3uCw/pzOJVWoEAwAJ): Running the new aiStarter build on a Mac OS X distribution older than 10.12 yields an error from Python about being compiled for a newer version of the OS.

```
 ./aiStarter 

[5805] Error loading Python lib '/var/folders/54/s4935tzs36vb_k9sphct89m80000gn/T/_MEIq2ysiz/.Python': dlopen: dlopen(/var/folders/54/s4935tzs36vb_k9sphct89m80000gn/T/_MEIq2ysiz/.Python, 10): Symbol not found: _getentropy
  Referenced from: /var/folders/54/s4935tzs36vb_k9sphct89m80000gn/T/_MEIq2ysiz/.Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/54/s4935tzs36vb_k9sphct89m80000gn/T/_MEIq2ysiz/.Python
```

**Comment by ewpatton** [comment]
I have sent a version 3.0.1rc1 to those reporting issues with macOS 10.10 and 10.11. If they report success with this new version, then I will update the site.

**Comment by jac2969** [comment]
could you please send me aiStarter version 3.0.1rc1? Thanks,

**Comment by ewpatton** [comment]
@jac2969 You can find it [here](https://www.dropbox.com/s/s4g8wwuz2mb92jc/MIT_App_Inventor_Setup_3.0.1rc1.dmg?dl=0). Please let us know whether or not it works for you.

**Comment by sharif582** [comment]
Is aiStarter 3.0 available for windows?

**Comment by guckuck** [comment]
Still not work with 3.0rc3.

**Comment by ewpatton** [comment]
aiStarter 3.0 was rebuilt on 10.10 with an older version of Python to fix this issue. The next release based on the latest updates to the build script may target a newer version of macOS.
