### ISSUE TITLE
Add PageLoaded event for WebViewer

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1235]
A suggestion from the power users was to add an event to report when the WebViewer finishes loading a page. The typical approach is to use a clock to check for some state. Android provides the WebViewClient class, with an onPageFinished callback, that should support adding this behavior to App Inventor. A rough sketch for completion is:

- [ ] Add PageLoaded event to WebViewer
- [ ] Extend `WebViewer.WebViewerClient` implementation to handle this callback and fire the associated event.
- [ ] Increment WEBVIEWER_COMPONENT_VERSION in YaVersion
- [ ] Add noUpgrader for new version in versioning.js
- [ ] Update YoungAndroidFormUpgraded to update the version number

**Comment by ledeni56** [comment]
I will start working on this issue.

**Comment by ewpatton** [comment]
@ledeni56 Thanks for taking a look. I think I've already spelled out most of the steps you'll need to take to finish this task, but let me know if you have any questions.

**Comment by ledeni56** [comment]
@ewpatton Can you please check out my commit:
https://github.com/ledeni56/appinventor-sources/commit/a00b63f5d1508bb04a11b1b124464b39e0672070
I'm still trying to understand the code and how it all works. 
What else do I need to add to have the event appear on the Web application as a block in WebViewer?

**Comment by lightingft** [comment]
@ledeni56 The code you have written is sufficient for the block to appear in the AppInventor. Simply run the ant build again on your local machine, then run the server and open the AppInventor application via your localhost, and test to see if it works!

**Comment by ewpatton** [comment]
@ledeni56 Functionally it looks good, but one change I would recommend is including the URL of the page loaded as a parameter in the event. As @lightingft mentions, run the build again to update the blocks list for the web viewer. Don't forget per the other points on my checklist to update the version number in YaVersion.java and add upgrade paths in YoungAndroidFormUpgrader.java and versioning.js so that existing WebViewers are upgraded cleanly (in both cases, the operation is a no-op, but it's good practice).
