### ISSUE TITLE
Add option to enable hardware acceleration

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1237]
The Look extension needs hardware acceleration (WebGL) support in the WebView. The simple fix would be to add one line to Compiler.java to add the appropriate flag to the manifest. A more complicated fix would be adding a Screen1 property to control whether hardware acceleration is enabled. 

Note, "true" is the default starting with min/target SDK of 14 or higher.

**Comment by jisqyv** [comment]
@ewpatton How far back (SDK wise) would this work?

**Comment by ewpatton** [comment]
Looking at [1], we may be able to enable it programmatically in the extension. Let's test that first.

[1] https://stackoverflow.com/questions/10339277/turn-on-hardware-acceleration-if-available-such-android-3-with-android-apk-2?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by ewpatton** [comment]
Hardware acceleration is on-by-default if target SDK is greater than or equal to 14 and the app is running on SDK greater than or equal to 14.

Closed via 3b3f7d0
