### ISSUE TITLE
BarcodeScanner causes companion to disconnect on Android Oreo.

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1242]
Whenever we use BarcodeScanner for connecting companion or just testing an app, after scanning QR code, app just exits. It also rotates screen to landscape and then back to portrait. Behaviour is occurring on Google Pixel 2, Android Oreo 8.1

**Comment by ewpatton** [comment]
@moliata I have tested this with a Google Pixel C (tablet) running 8.1 and it scans the barcode just fine and proceeds to connect. Do you see anything in the adb logs that might indicate a potential problem?

**Comment by moliata** [comment]
I will take a look later sometime again.
