### ISSUE TITLE
Doubt about CPU specs

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1253]
Is AppInventor compatible with ARMv7 cores?

It would be running in a dedicated bare-metal server with 4 ARMv7Cores and 2GB of RAM
Also, are those specs enough for a buildserver?

**Comment by ewpatton** [comment]
No. All of our build servers are virtualized on x86-64 hardware. The copies of aapt, etc. that we bundle under lib are the x86 versions of those binaries. Assuming that there are ARM compatible binaries floating around, you could swap them in for the x86 equivalents before building your build server, but it is not something we officially support.

**Comment by barreeeiroo** [comment]
So, AppInventor won't work on ARM, right?

**Comment by barreeeiroo** [comment]
So, AppInventor (or any fork) won't run on ARM, right?

**Comment by josmas** [comment]
as @ewpatton mentions, if you find ARM versions of all the platform specific tools under lib, it **_could_** work. No guarantees though. You might also want to monitor your current build server and check how many concurrent builds you could allow with 2GB or RAM; that could give you a baseline.

**Comment by barreeeiroo** [comment]
Then we'll go for the x86-64 version 👍
We just were looking for ARM because they were much cheaper

**Comment by ewpatton** [comment]
The App Inventor build servers will not work on ARM without additional modification. The website and the apps work on ARM.

**Comment by barreeeiroo** [comment]
And a bare-metal server with 4 dedicated cores x86-64 and 8GB of RAM will be enough for a buildserver?
