### ISSUE TITLE
Question about /rebind

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1258]
What is `ExtendedServiceProxyGenerator.java` file specifically used for? ...and what does it do?

**Comment by ewpatton** [comment]
ExtendedServiceProxyGenerator is sort of a syntactic sugar. For each RemoteService defined in the server hierarchy of appengine, it generates code to report the start, completion, and error statuses of an RPC without having to write the code by hand for every single call. These ExtendedServiceProxy instances are bound to the RpcStatusPopup in Ode.initializeUi(). The RpcStatusPopup is the little message box that appears at the top of the screen during various RPCs. Its usage is specified in YaClient.gwt.xml.
