### ISSUE TITLE
Time and Date pickers don't seem to work on certain devices

### ISSUE THREAD

**Issue by josmas** [mit-cml/appinventor-sources#126]
Certain Samsung phones seem to be not working properly. More information in the thread here: ​https://groups.google.com/forum/#!topic/mitappinventortest/gQZ-1MOO-Ic

Same code works in a different phone, but not in an samsung S3. This needs to be reproduced with the specified phone (or find other models/brands that behave like the one listed).

**Comment by halatmit** [comment]
@josmas Is it OK to close this issue?

**Comment by josmas** [comment]
@halatmit yeah, will close for now. It can always be reopened if issues arise again.

**Comment by halatmit** [comment]
Thanks.

We've got too many open issues, so I want to be careful about leaving
things hanging aournd.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty
