### ISSUE TITLE
Audit help URLs for blocks

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1272]
When testing the fix for #1269, I noticed that a number of components do not have the "Help" menu option enabled. This comes from having a helpUrl associated with the block. We should audit all of the components and fix any that lack the appropriate URL so that every block ends up with a valid help link.

**Comment by ZhengCornell** [comment]
I can take a look at this issue.

**Comment by ewpatton** [comment]
Ok @ZhengCornell. I think that @SusanRatiLane has already done this but a second look just to confirm everything is worthwhile. If everything checks out, please let me know and we can close this issue.

**Comment by ZhengCornell** [comment]
I think it works well on my side.

**Comment by ewpatton** [comment]
@ZhengCornell Sounds good. I will consider this issue closed.
