### ISSUE TITLE
Finger size for canvas touching detect

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1276]
https://github.com/mit-cml/appinventor-sources/blob/408f3ed1bb54c332d5e5e08598fbc58c81bd16e8/appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java#L183

https://github.com/mit-cml/appinventor-sources/blob/408f3ed1bb54c332d5e5e08598fbc58c81bd16e8/appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java#L191

https://github.com/mit-cml/appinventor-sources/blob/408f3ed1bb54c332d5e5e08598fbc58c81bd16e8/appinventor/components/src/com/google/appinventor/components/runtime/Canvas.java#L199

This should be allowed to be customized (maybe by properties) if someone need a different value

**Comment by bartmathijssen** [comment]
@ColinTree What would be the benefit of having this feature in App Inventor?

**Comment by ewpatton** [comment]
This will be a user-configurable property in the next release.
