### ISSUE TITLE
Order of loading property is different in apk & companion

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1279]
With the same project & same blocks, the property value from another component when initializing a component's property is different.
[Full extension codes](https://github.com/OpenSourceAIX/CanvasAddons/tree/775718dabade979dbb1203713dac4c23880e0ce3)

![image](https://user-images.githubusercontent.com/22613139/41605053-33f99a4e-7413-11e8-8db8-301886ccd5dc.png)

![image](https://user-images.githubusercontent.com/22613139/41604932-ed437318-7412-11e8-8898-3b433b851a6e.png)

It seems like the companion (ReplForm) would create the components first and then set up properties. But in compiled applications (Form) would initialize the components with the property

**Comment by ewpatton** [comment]
@ColinTree Can you send me the AIA for this project?

**Comment by ColinTree** [comment]
@ewpatton please try 
[CanvasAddonsTest_checkpoint1.zip](https://github.com/mit-cml/appinventor-sources/files/2118884/CanvasAddonsTest_checkpoint1.zip)

**Comment by ColinTree** [comment]
@ewpatton Getting any progress on this?
