### ISSUE TITLE
Bad behavior on user sign out

### ISSUE THREAD

**Issue by josmas** [mit-cml/appinventor-sources#128]
This is an old issue that turns up now and again (intermittent).

**From bug report**
Hi all, I found a bad piece of user experience in the newest build of AI2, but not sure if this counts as a bug. I tried with numerous different accounts and encountered the same thing:
After I clicked "sign out" at the top right corner, the page refresh and I got redirected to a blank AI2 page, nothing was loaded besides the gray-textured background. Checked the Chrome JavaScript? console and saw this line of error:

    Refused to execute script from '​http://ai2-test.appinventor.mit.edu/ode/ode.nocache.js' because its 
    MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

It may be worth discussing that what should users see after they clicked "sign out." Maybe the AI homepage http://appinventor.mit.edu/? This page doesn't require user to log in to see.

**Comment by halatmit** [comment]
I tried clicking "sign out"  and was sent (correctly) to the Google login page.   I'm going to close this issue.
