### ISSUE TITLE
Any blocks after while-break will cause the build to fail.

### ISSUE THREAD

**Issue by p4ssw0rd** [mit-cml/appinventor-sources#1282]
#1230  https://github.com/mit-cml/appinventor-sources/commit/70421e9b375f7ad9fbe9f579e3a621dfcf19dc5b

![failed](https://user-images.githubusercontent.com/3827464/41695512-e3f8e45c-7541-11e8-8602-ad218c18eee4.png)

**Comment by jisqyv** [comment]
@p4ssw0rd Where did you test this. I just tested this and it builds properly. Keep in mind, we closed the issue (#1230) when we merged the fix into the ucr branch. This code has not yet been deployed to ai2-test. That will likely happen sometime tomorrow when I am more awake (11:12PM local time here).

**Comment by jisqyv** [comment]
@p4ssw0rd Never mind, I was just able to duplicate the build failures with the latest code. Back to the coding board :-)

**Comment by p4ssw0rd** [comment]
@jisqyv I have marge the latest code and test local

**Comment by jisqyv** [comment]
@p4ssw0rd So this bug is deep in the Kawa compiler code... We fixed #1230 by modifying our code to avoid triggering a buggy optimization. I'm not sure if we will have as easy a fix for this one, but I'll look more when I am more awake...

**Comment by p4ssw0rd** [comment]
@jisqyv Thank you, good night. I'm not familiar with Kawa. Can't help.

**Comment by jisqyv** [comment]
#1285 includes a modified kawa jar file (binary) that fixes this issue (and hopefully all the others!).

**Comment by jisqyv** [comment]
@p4ssw0rd I think I got it...

**Comment by ewpatton** [comment]
Resolved by #1295 and #1297 .
