### ISSUE TITLE
Multiple questions (off-topic)

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1286]
Hello there,
I have a few questions to ask about the platform.

1. What's the progress with iOS (just warming up or doing last mini adjustments)?
2. Is Quixotic still working on services or they are on hold? It seems that last commit was made 3 seasons ago.
3. Are there any considerations of working on Java Bridge built-in the App Inventor? It seems that it is a pretty neat system.

Best regards,
Ben.

**Comment by ewpatton** [comment]
1. We are making steady progress on iOS. For a coverage report of our iOS companion, see http://doesappinventorrunonios.com.
2. I am not sure. @thequixotic will have to speak on that.
3. @wolberd and I discussed this a while back but no concrete plan emerged. It would be nice to have the ability to go from App Inventor to Android Studio/Xcode in the future, but is not a high priority at the moment.

**Comment by moliata** [comment]
1. What are those Column and Row properties? Android doesn't have them.
2. Current work is already amazing it just needs to have fully implemented Repeating Tasks and unsupported components by tasks should be hidden.

**Comment by ewpatton** [comment]
The Column and Row properties are on AndroidViewComponent and are only used when the component is placed in a TableArrangement. A developer implicitly sets them in the designer and they cannot be modified at runtime.

**Comment by moliata** [comment]
@ewpatton thanks again!

**Comment by moliata** [comment]
@ewpatton why Nxt components are not supported by iOS? I don't really see what kind of restrictions can cause that.
