### ISSUE TITLE
Project that signals error when trying to delete it

### ISSUE THREAD

**Issue by josmas** [mit-cml/appinventor-sources#129]
See thread for the project source:
​https://groups.google.com/forum/#!category-topic/mitappinventortest/MzUuDPUDpD8

Load this project. Then go to the projects page, mark it, and press delete. This produces an error (FF or Chrome). I don't see anything shown in the JS console. If you then press delete a second time, the project is deleted. 

**Notes**
*Dec 1*
I tried to delete a project by ticking the box before the project and clicking on the delete project button.
When i clicked the delete project button, the page gives an error message. The second time i tried i didn't get the error message.

*July 1*
This error still exists in chrome (didn't try FF). Pressing Delete generates the error:

    notes = Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit?/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36
    foundIn = nb134b
    faultData = com.google.gwt.event.shared.UmbrellaException?: Exception caught: (TypeError?) : Cannot read property 'ReplMgr?' of undefined
    projectId = -1

**Comment by weihuali0509** [comment]
@halatmit @josmas I don't see an option to close this issue, I guess I don't have the admin right. Please close it for me.

**Comment by halatmit** [comment]
closed
