### ISSUE TITLE
Twitter authorization failing

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1293]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/bWiLnEGxNjQ/RGrH8ypkBwAJ): Twitter component is reporting HTTP 403 errors when attempting to authorize. The error message from Twitter is:

> Twitter error: 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following). Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings.

**Comment by farxinu** [comment]
This is user error, not a bug.

**Comment by puravidaapps** [comment]
I tested this using my twitter tutorial here https://puravidaapps.com/twitter.php using my old credentials from 2014... you might want to elaborate, why you think, this is a user error
Taifun
PS: another user contacted me by email and he got the same issue in App Inventor while it's working for him on C#...

**Comment by josmas** [comment]
I have tested with existing and new twitter credentials and get the same result, so no user error here, I am afraid.

**Comment by quitte74** [comment]
Any update here? I'm facing the exact same issue.

**Comment by SusanRatiLane** [comment]
We don't have a resolution at this time. Updates to the Twitter API have broken authorization on our Twitter component, but we don't have an alternate means to authorize right now.

**Comment by patryk84a** [comment]
Maybe it would be necessary to remove the broken component so as not to mislead users unnecessarily?

**Comment by ewpatton** [comment]
We deprecated the Twitter component and marked it as internal.
