### ISSUE TITLE
Error in rendering in two blocks

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#1298]
Not a big problem but there are two blocks where the rendering is not 100%. See image. 

![selectie_999 370](https://user-images.githubusercontent.com/32273650/42074004-240b6366-7b6a-11e8-8ddc-3f9872e18c45.png)

**Comment by halatmit** [comment]
I can confirm that I see this with the procedure block, but not with the
initialize local block.
== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
I am aware of this. I think Chris Ward reported it via the power users forum a while back. The issue appears with the Blockly update and only affects blocks with indented value inputs. The math to drow the highlight path is off, which results in the visual glitch. The visual glitch only appears when the block is not selected.

**Comment by ewpatton** [comment]
I left off my previous investigation with the hypothesis that the code in this [if block](https://github.com/mit-cml/blockly/blob/4ac45d5cd608e7c25c6ab9fb2549096cbb870e98/core/block_render_svg.js#L764) is the source of the issue.
