### ISSUE TITLE
How to upgrade Android SDK?

### ISSUE THREAD

**Issue by wxbit** [mit-cml/appinventor-sources#1308]
I want to upgrade the Android SDK to 26, is there any introductions ?

**Comment by josmas** [comment]
You can have a look at the [steps to upgrade to 5.1.1](https://github.com/mit-cml/appinventor-sources/pull/734) but note (you will also see in the comments) that changes from API 23+ will affect your builds, and they are not trivial changes.

There is an ongoing upgrade project happening at the moment, so if you can wait for a while, may be easier than trying to do all the work yourself.

**Comment by p4ssw0rd** [comment]
@josmas  Thanks, I found @ewpatton have a branch. https://github.com/ewpatton/appinventor-sources/tree/wip-target-sdk-26

**Comment by jisqyv** [comment]
@p4ssw0rd @josmas https://github.com/jisqyv/appinventor-sources/tree/wip-target-sdk-26-jis is the current branch we are working against. It is used for ai2-test (and I expect to update ai2-test this weekend) as well as the second buildserver we use for "Build for Google Play"

**Comment by ewpatton** [comment]
Closed via 3b3f7d0
