### ISSUE TITLE
About the CloudDB Component

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1311]
I've been playing for a while locally with CloudDB, and I was able to get it work
But I don't know what are the following parameters:
```
    <property name="clouddb.uuid.secret" value="changeme!"/>
    <property name="clouddb.secret" value="changeme too!" />
```
I mean, how can those parameters be altered on the server, and what's the proper configuration to put them live?
Because I was able to run it using a custom token/password, but I would like to know how to run it in production

**Comment by barreeeiroo** [comment]
I suppose the `clouddb.secret` might be the `requirepass` value in `redis.conf`, but whay about the `clouddb.uuid.secret`?
How do we have to configure those params?

**Comment by jisqyv** [comment]
@barreeeiroo Sorry for the slow response. These properties are used by the Security/Sharing Shim that we put in front of Redis that permits us to use one Redis server shared between multiple people. The clouddb.secret is used to "sign" the CloudDB Tokens issued by the CloudDB component. It is shared between the MIT App Inventor server and the security shim.

The clouddb.uid.secret is used to perform a keyed hash of a person's internal usersid to derive the ID that is used to separate out their CloudDB keys from other users. The hash adds some additional privacy.
