### ISSUE TITLE
Blocks overlaying each other

### ISSUE THREAD

**Issue by Amerkashi** [mit-cml/appinventor-sources#1313]
Hello,

I was just loading a project and noticed that all blocks were stacked / overlayed on top of each other (see Image1). Then I exported .aia so that it could be inspected. Then from my projects, I selected same project again. This time all blocks were stacked on top-left of blocks editor (see Image2). I was not able to attache file here. [HERE](http://www.appybuilder.com/temp/Foo.aia) is a link where you can get the .aia . THANKS

Image1:
![image](https://user-images.githubusercontent.com/36113589/42741586-a8312116-8881-11e8-870e-e005daa44408.png)

Image2:
![image](https://user-images.githubusercontent.com/36113589/42741593-b9d926c0-8881-11e8-862e-25c0725d62d4.png)

**Comment by ewpatton** [comment]
I believe that this has been fixed by #1115. If you continue to see a problem with new projects created after this commit, please reopen this issue.
