### ISSUE TITLE
MIT App Inventor Error

### ISSUE THREAD

**Issue by kaalamannacool** [mit-cml/appinventor-sources#1314]
Someone can help out there? I don't know what to do, I'm stacked in and I need to fix this badly.
[MASS.zip](https://github.com/mit-cml/appinventor-sources/files/2200317/MASS.zip)

**Comment by ColinTree** [comment]
Please provide some proper detail of the bug.
If this is not a bug report, please move to developer support forum.
e.g. https://groups.google.com/forum/m/#!forum/mitappinventortest
