### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by desuto** [mit-cml/appinventor-sources#1317]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by moliata** [comment]
App Inventor actually has a logo.

**Comment by ewpatton** [comment]
@desuto @moliata is correct. Please see [codi_long.png](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/appengine/war/images/codi_long.png) and [AI2Companion-Icon.png](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/aiplayapp/assets/AI2Companion-Icon.png) as examples.
