### ISSUE TITLE
Buttons no longer take "None" as a color on Android < 5.0

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1318]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/Lv0cVfKjoao/BHqKRbO_CwAJ): Buttons with background color "None" show default button look.

The commit 769fe75 changed the color filter used to apply the background color. This works on Material UI, but prevents being able to have a clear button background on older versions of Android. We should have a check for older Android versions to make sure they get the correct old behavior.

**Comment by ewpatton** [comment]
[Another forum report](https://groups.google.com/d/msg/mitappinventortest/Hjg5POIerLQ/V8Ck7iS0CwAJ) shows that this also affects switching back to the default background from a color change.

**Comment by weihuali0509** [comment]
@ColinTree I believe your recent fix to Thunkable Classic source code should also fix this as well. Can you submit a PR to the MIT App Inventor repo?

**Comment by SusanRatiLane** [comment]
My testing showed this problem in Oreo. It looks like it's a bigger regression than just old versions of Android.

**Comment by SusanRatiLane** [comment]
In my testing, the change from TextViewUtil.setBackGroundColor to view.getBackground().setColorFilter in commit 769fe75 didn't restore the ripple effect to buttons in newer Android versions. It did cause the problem with the None button color. Both operations appear to affect the drawable.

Restoring the ripple effect looks like it will take some design work. Research indicates that it could be done by setting the Tint of the button or by setting the background color, followed by a RippleDrawable object. Neither option comes in neatly packaged methods.

**Comment by SusanRatiLane** [comment]
Additionally, current buttons in that theme with background color set to None have no visible indication of click at all.

**Comment by NmdOfficial** [comment]
Simple solution we use in makeroid:

![blocks](https://user-images.githubusercontent.com/29900947/45874991-a8d3d880-bd96-11e8-8b76-7c6bbf77003b.png)

**Comment by SusanRatiLane** [comment]
@NmdOfficial I'll give this a try.

Is there anything noteworthy you're doing in setShape when the shape is not default?

**Comment by NmdOfficial** [comment]
On set shape I add there again margin for the button (other shapes as default have no margin)
and too I add there a rippledrawable.
We in makeroid use much more things as default app inventor.

**Comment by SusanRatiLane** [comment]
Whoops, sorry. The above was my error.

When I use the code above, the no color background appears as it should. However, it switches back to default when I click it. I imagine there's more code to restore the Alpha after click? 

Once the button is restored to default, the ripple effect works fine of course.

Note: I got the correct background behavior using getBackground().setColorFilter(backgroundColor, PorterDuff.Mode.CLEAR);

instead of 

getBackground().setAlpha(0)

This works fine for background color, and it keeps its color after clicking. There's just no click effect.

**Comment by ewpatton** [comment]
We should also check to see that these changes work when the background color is manipulated from the blocks.

**Comment by NmdOfficial** [comment]
The problem in AI button code is on Touch event.
There is the alpha value set on every touch down and up

**Comment by SusanRatiLane** [comment]
@NmdOfficial OK, fair. I will experiment.

Can you confirm that this approach preserves the ripple effect? Issue #1324, which I see you submitted, reports that changing the Alpha destroys the ripple effect. We are trying to reengineer this whole approach to deal with newer Android better.

**Comment by NmdOfficial** [comment]
This code:
TextViewUtil.setBackgroundColor(view, backgroundColor);

was removing the ripple effect from the buttons.

On newer android versions we have by default a touch down and up animation on buttons.
setAlpha in the touch event was surely created to make such a effect on older devices.
But as you can see it breakes some new things.. You wrote

> When I use the code above, the no color background appears as it should. However, it switches back to default when I click it. I imagine there's more code to restore the Alpha after click?
