### ISSUE TITLE
Spinner AfterPicking invoked even when no item selected

### ISSUE THREAD

**Issue by kkashi01** [mit-cml/appinventor-sources#132]
Spinner AfterPicking immediately invoked even if it has not been opened.

Steps:
Drop Spinner component onto designer
For its ElementsFromString, enter csv values such as a,b,c,d,e
Add in a label; e.g. Label1
From BlocksEditor, Select, Spinner1.AfterPicking handler
In there, set Label1.Text to Spinner1.Selection.

Connect the companion and you'll notice that immediately Label1.Text will be set to a

**Comment by halatmit** [comment]
@jisqyv 
should this issue be closed now?

**Comment by EnisM** [comment]
Jeff said he tested and merged PR 134, but I'm not sure if this is fixed. I asked him but haven't heard back yet... It's a pain though... I've been working a lot with spinners lately and this AfterPicking, and when it's triggered is really annoying.

**Comment by halatmit** [comment]
@jisqyv 
Jeff, Did you fix this as part of working on PR 134?

**Comment by jisqyv** [comment]
@EnisM Yes, this is fixed. Keep in mind that it isn't in the release yet, just in the master branch.

**Comment by EnisM** [comment]
Great... Yes, I know merged and released... I'm still content it's merged
as it means we'll see it fairly soon... Thanks Jeff...  Another one off the
list... congrats!

On Sat, Jan 24, 2015 at 10:06 PM, Jeffrey Schiller <notifications@github.com

**Comment by halatmit** [comment]
Thanks!  I thought that might be the case.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Sat, Jan 24, 2015 at 10:06 PM, Jeffrey Schiller <notifications@github.com
