### ISSUE TITLE
When receiving sms message longer then 160 characters it is truncated

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#1321]
When you receive an sms which has a length > 160 it is truncated to 25 characters.  

Expected behaviour would be to be able to receive bigger sms or at least the first 160 characters.

**Comment by ewpatton** [comment]
@PeterMathijssen Is this tied to the SDK 26 update or do you observe it in a legacy build application as well?

**Comment by PeterMathijssen** [comment]
It happens in both versions. It also happens in AppyBuilder, Makeroid and Thunkable.

**Comment by ewpatton** [comment]
@PeterMathijssen I sent you a link to a test companion with a possible fix. It seems to work in the emulator but if you can confirm with a real device that would be helpful.

**Comment by PeterMathijssen** [comment]
I tested your companion apk and it is working. The complete sms is visible inside the app.
