### ISSUE TITLE
Orientation change interface

### ISSUE THREAD

**Issue by Mika-89** [mit-cml/appinventor-sources#1322]
Please read following problem:
https://groups.google.com/forum/m/#!searchin/app-inventor-open-source-dev/Orientation/app-inventor-open-source-dev/QHBlzClp-u8

Now you know what Iam talking about.
Is there any way to create a custom interface which we then can use in any component to detect the orientation change was done?
I ask because I want to handle that case without that users needs any block for some changes. 
I want to let it do it the component with a interface byitself. 

I added as example a interface which is invoked at the same time when the screen orientation change fires. 

Does anyone have a solution for that?

**Comment by ewpatton** [comment]
Not as an extension, but you could introduce an OnOrientationChange interface and in Form.java add the boilerplate to register and notify components implementing that interface (cf. OnResumeListener et al.). Your component can then implement this interface and register with the Form to be notified when the orientation changes.

**Comment by NmdOfficial** [comment]
I'm not talking about a extension.
I want such thing in the source system.

I tried to run the interface in the config change event from android.
But the only way which works (with blocks) was the screen orientation change event.

I have read that this a event is a special case and just fired after the orientation was done.

My example listener above is fired before the change was done.
But I need a solution for a interface after the orientation was done.

**Comment by ewpatton** [comment]
Fixed by #2124
