### ISSUE TITLE
Button - setAlpha destroys material ripple effect

### ISSUE THREAD

**Issue by NmdOfficial** [mit-cml/appinventor-sources#1324]
Since a long time it looks like nobody have noticed that this line:
https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/ButtonBase.java#L154

and this line:

https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/ButtonBase.java#L162

destroys on devices with android 5+ the default ripple touch effect.

I don't know why you use this. This makes all buttons looks really ugly and by now every builder (not makeroid) have not fixed this "bug".

I know you want to create a touch effect with "setAlpha" but you dont need this on devices android 5+.

Maybe a solution will be to remove this lines for android 5+.
Btw: The show feedback option is too useless and not needed if you will follow the google guidelines for material design.

Current the code (setAlpha) is only executed if "Show Feedback" is enabled.
But do users really need this option?
Is it not better that a user can see the touch?

**Comment by ewpatton** [comment]
@NmdOfficial Given that themes are relatively new to App Inventor, and that most people stick to using the Classic theme, I'm not all that surprised that this has gone unnoticed. We may need to rethink how this works in light of #1318 to make sure we can support devices sufficiently far back, as there are still older devices using the Holo theme.

**Comment by ewpatton** [comment]
Closed via 9ebfb0d.
