### ISSUE TITLE
Upgrade BackPressed codes

### ISSUE THREAD

**Issue by michael-winkler** [mit-cml/appinventor-sources#1330]
We have following commit on https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/Form.java#L480
  /*
   * Here we override the hardware back button, just to make sure
   * that the closing screen animation is applied. (In API level
   * 5, we can simply override the onBackPressed method rather
   * than bothering with onKeyDown)
   */
  @Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_BACK) {
      if (!BackPressed()) {
        boolean handled = super.onKeyDown(keyCode, event);
        AnimationUtil.ApplyCloseScreenAnimation(this, closeAnimType);
        return handled;
      } else {
        return true;
      }
    }
    return super.onKeyDown(keyCode, event);
  }

<hr>

Is there a way to update this old code ?
I mean app inventor min api is above 5.
So it should be no problem to use a better code.

**Comment by ewpatton** [comment]
@NmdOfficial Correct, now that we have dropped support for SDK levels 4-6, we should be able to switch to overriding onBackPressed.

**Comment by ewpatton** [comment]
The important thing is that we need to test any change on a range of devices and OS levels. We should also make sure to test with a phone with a physical keyboard.
