### ISSUE TITLE
Videoplayer - Bug report

### ISSUE THREAD

**Issue by michael-winkler** [mit-cml/appinventor-sources#1335]
We in makeroid receive many issues from following component:
VideoPlayer.java in line

https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/VideoPlayer.java#L640

and in line
https://github.com/mit-cml/appinventor-sources/blob/308f1f33e82a313ebd8ec0c5afaa10de30fb1678/appinventor/components/src/com/google/appinventor/components/runtime/VideoPlayer.java#L593

- OS Version: 7.1.1
- Device: SM-C710F
- RAM Free: 27.6%
- Disk Free: 10.4%

`Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.getVideoWidth(MediaPlayer.java)`

<hr>

It looks to me that the videoplayer was null, else I have no idea why we get the IllegalStateException.

**Comment by moliata** [comment]
Can you first of all replicate the following issues yourself on the App Inventor platform. It's not really a good practice to post issues from a separate platform without replicating it.

**Comment by moliata** [comment]
If you can't replicate the issue, even though it's the same file, it's no way to ensure that the same is caused on the App Inventor. Giving crash reports from a different platform even with a lot of similarities won't help. It's better not to post all the issues from your platform. Better give something that we could look into and try to fix. For example, project files.
