### ISSUE TITLE
Cannot compile project with reserved keyword for name

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1336]
Projects with reserved Java keywords will not compile correctly, e.g., `final`. We should have a check in the project naming dialog that disallows these names. I expect that this also affects screens.

**Comment by ewpatton** [comment]
[Another possible project where the name is `new`](https://groups.google.com/d/msg/mitappinventortest/G-J-HjXRzDM/-GA8TIteEQAJ)

**Comment by NmdOfficial** [comment]
"switch" & "case" should too not work

Iam not sure what happens with:
"void" "String" "boolean" bool" or "public" and "private".

What about "static" or "abstract" or "class" ?
