### ISSUE TITLE
Round Operator Issue

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1339]
As seen here: https://community.makeroid.io/t/the-round-operation-bug/9144/8?u=barreeeiroo

If you input `2.5` to the _round_ block in _Math_ category, it outputs `2`, while the correct output should be `3`

**Comment by BeksOmega** [comment]
I think I've got something for this mostly working, so I'd like to lay claim :D

**Comment by halatmit** [comment]
Please keep this simple.   App Inventor's target users are kids.  Introducing blocks or properties that control rounding options seems like a very advanced idea.   I'd advocate following R6RS and IEE 754.

**Comment by ewpatton** [comment]
@BeksOmega We may just want to update the documentation for the block, both in the Markdown and in the tooltip, to explain the type of rounding that's done rather than overwhelm people with different options.

**Comment by BeksOmega** [comment]
Sounds good to me! o7

**Comment by BeksOmega** [comment]
@ewpatton Just checked, [the docs](http://ai2.appinventor.mit.edu/reference/blocks/math.html#round) are already up-to-date. And the tooltip currently reads "Round a number up or down." which I think is ok when compared to the tooltips for ceil and floor: "Rounds the input to the smallest number not less then the input" and "Rounds the input to the largest number not greater then the input" respectively.

Given that, would you still like me to update the tooltip?

**Comment by ewpatton** [comment]
@BeksOmega Yes, we should amend the tooltip to include a note about rounding numbers ending in .5 to the nearest even integer.
