### ISSUE TITLE
Heading behavior and documentation mismatch

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1340]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/cq7TaW-BGbw/PesPuCJlEAAJ): The documentation for `Flung` for Canvas and Sprites claims that `heading` will be in the range [0, 360). However, values reported by a test app show that values are in the range [-180,180).

So there are three things we should consider:

1. Update the documentation so that the range is [180, 180) and be done with it.
2. Fix the math so that it normalizes the value to [0, 360).
3. Slightly more challenging: I always think of heading as relative to north (+Y on 2D screen). Right now the 0 value is +X (east). We could rotate the heading value so that 0 is +Y and 90 is +X.

In the case of 2 or 3, we should provide an option on the Canvas to retain the Legacy behavior with upgrader for projects so that existing projects relying on the old semantics do not break.

**Comment by dhruvpatidar359** [comment]
Hello @ewpatton sir , 
some clarifications i want to know about :
1 > In the first point you said , update the docs by [180,180) , is it [-180,180) or the previous one ?
2 > In the second point , if we are saying the range is [-180,180) then why we are normalizing the result in [0,360)
3 > In the third point , i think we should make it standard , like we see in a coordinate system ( as in maths) 
The 90 => +Y
0 => +X

Many Thanks

**Comment by ewpatton** [comment]
Re. item 1, yes the lower bound should be -180.

In the case of items 2 and 3, this would bring the Heading property in alignment with a compass heading where north is measured from 0 going clockwise. Today the angle is positive clockwise from 0 to 180 starting from +X then going counterclockwise to -X and the angle is negative when going clockwise.

**Comment by dhruvpatidar359** [comment]
@ewpatton  Sir , in the second point i have some doubts , why we want to nomalize to [0,360) as it is  already in the [-180,180) and we also want like this ?

**Comment by dhruvpatidar359** [comment]
@ewpatton Sir , i think if you want to implement the third point of yours , then we can change the code as,
in the file Canvas.java at line no . 1737 
```
float heading = (float) -Math.toDegrees(Math.atan2(vx, vy)) + 90f;
if (heading < 0) {
  heading += 360f;
}
```
want to know your point of view.

Many Thanks
