### ISSUE TITLE
Fill Parent does not work in  Scrollable on Android 7+ with target SDK 26

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1344]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/awf1V2cNItk/HmCuMkxRBAAJ): With SDK 26, using Height = FillParent in a Scrollable Form no longer, the view ends up with 0 height instead of fitting the intrinsic content size (Android < 6 behavior).

**Comment by NmdOfficial** [comment]
What about that?

if (scrollable) {
            frameLayout = new ScrollView(this);
            ((ScrollView) frameLayout).setFillViewport(true);
        } else {
            frameLayout = new FrameLayout(this);
        }

**Comment by ewpatton** [comment]
Fixed by 3b3f7d0
