### ISSUE TITLE
Add Stop method to VideoPlayer

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1345]
Power user Chris Ward suggests implementing a Stop method for the VideoPlayer. While technically one could call `Pause()` and then `SeekTo(0)` to implement `Stop()` semantics in blocks, it is more intuitive to just have a `Stop()` method.

**Comment by halatmit** [comment]
Sounds good.

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by kuan9611** [comment]
@ewpatton Thinking of picking up this one next. I'm guessing `videoView.stopPlayback()` is the method to call? The [VideoView documentation](https://developer.android.com/reference/android/widget/VideoView) doesn't really have anything on it. 
There's also already a `FULLSCREEN_VIDEO_ACTION_STOP` constant in [FullScreenVideoUtil.java](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/util/FullScreenVideoUtil.java).

**Comment by ewpatton** [comment]
@kuan9611 That sounds reasonable to me. While you are in there, we should simplify the logic at [line 106](https://github.com/mit-cml/appinventor-sources/blob/4bfa0e3546e82e7aa429f069e35c627fe3b73454/appinventor/components/src/com/google/appinventor/components/runtime/util/FullScreenVideoUtil.java#L106), as we target Eclair and higher.

**Comment by kuan9611** [comment]
@ewpatton Actually I've probably been over complicating things. According to [this post](https://stackoverflow.com/questions/22744692/how-resume-playback-after-stopplayback-android), `stopPlayback()` will release the current media player instance, which doesn't seem like what we want. If the intended behavior is simply to rewind video to beginning, maybe it's best to simply call `Pause()` and `SeekTo(0)` inside the method?

**Comment by ewpatton** [comment]
Resolved by b2d4a63c3db4a652c173a381ab52191eaa88f5d3
