### ISSUE TITLE
Splitting text does not trim empty item in the front

### ISSUE THREAD

**Issue by danielkwan0516** [mit-cml/appinventor-sources#1351]
*For example:*

    split text "10010"      at ""  => (*empty-string* 1 0 0 1 0)
    split text "Hello"      at ""  => (*empty-string* H e l l o)
    split text "10010"      at "1" => (*empty-string* 00 0)
    split text "1110010111" at "1" => (*empty-string* *empty-string* *empty-string* 00 0)
    split text ",,,,,,"     at "," => ()
    split text ",,,Huh?,,," at "," => (*empty-string* *empty-string* *empty-string* Huh?)
    split text "Huh?,,,,,," at "," => (Huh?)

**Huh?**

**Comment by josmas** [comment]
Are your first two examples correct? how are you generating the YAIL?

For the other results, Kawa is [calling the java function directly](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/src/com/google/appinventor/buildserver/resources/runtime.scm#L2332), and this seems to be a **_feature_** of Java as explained in the [split docs](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#split(java.lang.String)): _Trailing empty strings are not included in the results_.

It is inconsistent with most other languages like JavaScript, and even Kotlin, but this is what should happen using the Android SDK too (unless Kotlin is used!).

**Comment by ewpatton** [comment]
I don't think we want to change the semantics of the block because existing applications may already rely on this behavior. As @josmas mentions, it is just passing through to Java's string splitting function, and so it aligns with the existing semantics in the underlying framework.
