### ISSUE TITLE
Suggestions on buttons in "Blocks"

### ISSUE THREAD

**Issue by danielkwan0516** [mit-cml/appinventor-sources#1352]
I think a pointer cursor (`cursor: pointer`) should be shown when users move the cursor to the following 4 buttons.
![image](https://user-images.githubusercontent.com/29452642/45256295-3e4e9000-b3c7-11e8-8c8f-50104c86566a.png)
Also, it's hard to see the buttons since they are only in gray color (grey colour). And the rubbish bin becomes under the blocks.
![image](https://user-images.githubusercontent.com/29452642/45256376-26c3d700-b3c8-11e8-8e7d-1ed743bda4e9.png)
Besides, I suggest adding a slider to indicate and change the size. Otherwise, I would have to click the + or - buttons for maybe 20 times to zoom in/out.

**Comment by ramiAbdou** [comment]
@ewpatton looking to fix this right now. Can I get some direction to where in the code base this is?

**Comment by josmas** [comment]
Hey @ramiAbdou there seem to be two different issues here. The second part, the controls, are inherited from [Blockly](https://developers.google.com/blockly/). You can have a look and see if there is a way to customise the look and feel when they are loaded in the page.

The other part, regarding the pointer cursor, the files to look at are most likely those that start with _backpack_ in the _blocklyeditor_  project. Maybe [here](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/blocklyeditor/src/backpack.js) but not 100% certain. You probably want to look where the image is added (probably an svg or png image, and take it from there.

**Comment by ewpatton** [comment]
Resolved by #1552
