### ISSUE TITLE
Migrate built-in blocks documentation to GitHub

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1355]
The built-in blocks are documented in the Drupal site, but components and other documentation are versioned in this repo. We should move the blocks documentation here so that it can follow the language versioning.

**Comment by ewpatton** [comment]
@SusanRatiLane I think we should put this onto `ucr` and then once it is merged we can rebase #1354 and update the documentation there so that it is versioned.

**Comment by SusanRatiLane** [comment]
This makes sense to me.

**Comment by SusanRatiLane** [comment]
Closed by #1358
