### ISSUE TITLE
Error Compile Ucr-26 if add simpleCompTypesString.contains?

### ISSUE THREAD

**Issue by kangris-sket** [mit-cml/appinventor-sources#1359]
Im try add component on New Bracnh Ucr-26..
I add code  compiler.java 

> 

      if (simpleCompTypesString.contains("AdMob")  && isForCompanion) {
        System.out.println("Android Manifest: including AdMob tag");
        out.write("<activity android:name=\"com.google.android.gms.ads.AdActivity\" android:configChanges=\"keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize\"/>");
        out.write("<meta-data android:name=\"com.google.android.gms.version\" android:value=\"10084000\"/>");
      }
in line 799

But ant builder get massege error ..

> Compiler.java:799: error: cannot find symbol
    [javac]       if (simpleCompTypesString.contains("AdMob") 
    [javac]                                                      ^
    [javac]   symbol:   variable simpleCompTypesString
    [javac]   location: class Compiler
    [javac] 1 errors
    [javac] 1 warning

> 
Please how to fix ..Thanks you very much

**Comment by ewpatton** [comment]
You should test whether the FQCN of the component is in `simpleCompTypes`. There is no field `simpleCompTypesString`, which is why you receive the error. For an example, search for `NearField` in Compiler.java.

**Comment by kangris-sket** [comment]
Thanks sir :smiley: 

> You should test whether the FQCN of the component is in `simpleCompTypes`. There is no field `simpleCompTypesString`, which is why you receive the error. For an example, search for `NearField` in Compiler.java.

Thanks sir 😄  
I will try use "simpleCompTypes.contains"

**Comment by ewpatton** [comment]
In the future, please keep these types of questions on the [open source development forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).
