### ISSUE TITLE
Its not easy find warnings on big projects

### ISSUE THREAD

**Issue by GOTFire** [mit-cml/appinventor-sources#1361]
Hello
When removing component,procedure ... its makes warning on block side its normal.There is problem with finding this warnings on blocks.If user have huge projects like me its not easy find this warnings location.

Solution
Is it posible add warning icon to colapsed blocks.So ı can use colapse all blocks and sort all block for find warning easy. 

Another solution
When clicked warning icon its show us where is the warning block.Like hightlight procedure option.

**Comment by p4ssw0rd** [comment]
The second option is better, https://app.wxbit.com has implemented, clicking the icon will loop to show an error or warning.

**Comment by ewpatton** [comment]
See also #1004, which is the cycling option.
