### ISSUE TITLE
"Help" for do-return control block opens do-return procedure block help

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1365]
During testing of #1358 I noticed that right-clicking on the Do-Return control block and selecting Help would open the help for the do-return procedure block. The problem is in the Block definition [here](https://github.com/mit-cml/appinventor-sources/blob/860cd7652ecd97b8cf15e71b256d11112b8899f5/appinventor/blocklyeditor/src/blocks/control.js#L481). It is a quick fix to update to the correct HELPURL reference.

**Comment by SusanRatiLane** [comment]
This was a quickie, so I just knocked out.
