### ISSUE TITLE
TitleVisible affects Scrollable in Designer

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1381]
If Scrollable is checked in the designer, you are able to scroll the screen, but if you change (check or uncheck) TitleVisible or StatusBarVisible properties, even though Scrollable property is checked, you are no longer able to scroll in the Designer, to be able to scroll again, you have to uncheck and check again Scrollable property.

**Comment by SpencerHowell** [comment]
I have tested this issue in both Chrome and Edge, and it appears that this problem has been fixed. The user is still able to scroll after pressing any combination of the two check boxes.

I believe this issue can be closed.

**Comment by ewpatton** [comment]
@SpencerHowell I'm also seeing that this isn't a problem. @moliata Can you verify that this still affects you and what browser you're using if that's the case?

**Comment by moliata** [comment]
No longer a problem, closing the issue.
