### ISSUE TITLE
Help,Build error YAIL compiler - DX execution failed?

### ISSUE THREAD

**Issue by kangris-sket** [mit-cml/appinventor-sources#1385]
Help,Build error YAIL compiler - DX execution failed?

I have add some component,and get this error!
What is error?How to fix?

`
[java]
     [java] UNEXPECTED TOP-LEVEL EXCEPTION:
     [java] com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
     [java]     at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:484)
     [java]     at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
     [java]     at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:473)
     [java]     at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
     [java]     at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
     [java]     at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
     [java]     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
     [java]     at com.android.dx.command.dexer.Main.run(Main.java:277)
     [java]     at com.android.dx.command.dexer.Main.main(Main.java:245)
     [java]     at com.android.dx.command.Main.main(Main.java:106)
     [java]
     [java] Oct 03, 2018 10:41:58 PM com.google.appinventor.buildserver.Compiler setProgress
     [java] INFO: The current progress is 75%
     [java] Oct 03, 2018 10:41:58 PM com.google.appinventor.buildserver.Compiler runDx
     [java] WARNING: YAIL compiler - DX execution failed.

BUILD FAILED
D:\AI\appinventor-sources\appinventorPlus\build.xml:21: The following error occurred while executing this line:
D:\AI\appinventor-sources\appinventorPlus\buildserver\build.xml:236: Java returned: 1

`

Thanks you

**Comment by moliata** [comment]
This is a problem with your project and not the App Inventor. DX Execution mostly fails because of a) external extensions b) incorrectly placed blocks c) messed up things in project's configuration files.

**Comment by kangris-sket** [comment]
> This is a problem with your project and not the App Inventor. DX Execution mostly fails because of a) external extensions b) incorrectly placed blocks c) messed up things in project's configuration files.

thanks sir for replay 👍 

i try correctly again my external extension

**Comment by moliata** [comment]
You may want to close the topic until then.

**Comment by josmas** [comment]
closing this one for now. For this type of request, please use the [Open Source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).
