### ISSUE TITLE
Request - Hiden folder "AppInventor" on storage?

### ISSUE THREAD

**Issue by kangris-sket** [mit-cml/appinventor-sources#1388]
Request - Hiden folder "AppInventor" on storage?

for default ,after install app inventor create folder "AppInventor/asset" n "data" .
cant it hiden ?

thanks.

**Comment by ewpatton** [comment]
The App Inventor companion uses this folder for storing project related asses. Starting with the SDK 30 release it is stored in the app specific directory, which is not accessible to other applications. This should no longer be an issue.
