### ISSUE TITLE
Implement Switch

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1392]
[Relevant forum post](https://groups.google.com/d/msg/app-inventor-open-source-dev/XqrJYN5rnZQ/ySXFq5ohBAAJ): For Android starting with 4.0, and for iOS, Switch is the preferred UI element for boolean inputs. We should implement a Switch component so that apps can better fit the look and feel of newer OS versions.

**Comment by SusanRatiLane** [comment]
Development is on this branch: https://github.com/SusanRatiLane/appinventor-sources/tree/Toggle-control

**Comment by ewpatton** [comment]
Resolved by c0cabd21e3b57d8a8b946f628994b89300b98b4a
