### ISSUE TITLE
How to add any extension as components

### ISSUE THREAD

**Issue by kunalkool** [mit-cml/appinventor-sources#1393]
I want to add extensions i made for app inventor in my builder as a components .
How i can do that please explain in very method .

**Comment by kunalkool** [comment]
no for example if i am using any body else extension with permission then i
am saying

**Comment by josmas** [comment]
Oh, I see, so it is not your extension. That makes more sense.
You might get some help in the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev), please try asking there instead of opening an issue. Thanks and good luck.
