### ISSUE TITLE
aiStarter doesn't work in Raspberry Pi

### ISSUE THREAD

**Issue by gabrielcbe** [mit-cml/appinventor-sources#1410]
After following the instructions on how to install aiStarter in Linux/Debian, still couldn't make it work, getting errors like.  "Error in the Exec format" - and when trying to run as a Sudo "Syntax error: work unexpected (Expecting ")"); 

We're using OS Raspbian (based in Linux/Debian) and the processor has an ARMHF architecture.
I'm not sure, but I think the some of the problems might be due to the architecture of the processor when installing in the .deb file.
Installed in ubuntu and Mint to te
st it and it worked fine, but I can't change the Raspberry to either of these OS. 

I need to make the USB connection with the rapsberry pi and the mobile phone, Any idea what might be happening?

**Comment by ewpatton** [comment]
Your intuition is correct. The .deb file bundles only x86 binaries, it does not include arm binaries. A rough sketch of how you might be able to work around it:

1. `sudo apt-get install adb` to get adb installed
2. Download the aiStarter.py and bottle.py files from appinventor/misc/emulator-support
3. Create a directory to house your "aiStarter" installation (INSTALLDIR), and create a directory `commands-for-Appinventor` (COMMANDDIR)
4. Create a symlink to `which adb` in $COMMANDDIR
5. Modify aiStarter.py by changing `PLATDIR` from `/usr/google/appinventor/` to INSTALLDIR
6. Run `python aiStarter.py`

This will run an interpreted version of aiStarter that makes use of the arm version of adb. You may need to do additional configuration in your system to make sure adb can talk to your Android device over USB. You should be able to test that is working by running `adb shell` to open a shell on your device.

**Comment by gabrielcbe** [comment]
Hey man, thanks for the help. 
I tried doing what you said, it seem that i can connect my phone in the adb and run the aiStarter separately, but as soon as I connect my phone and try to Connect>USB in the website I'm getting some error like this (image below).

![2018-11-08_17-04-35](https://user-images.githubusercontent.com/43211813/48221170-7ac34b80-e378-11e8-88c1-0db20b1522be.png)

I might have screwed something thing up, any idea what this errors mean (my fault or still needs something to run properly)?

I didn't create the symlink but i did put the files in the the folder.
I'll try installing in a different Raspberry Pi to see if I get a different result.

Thanks

**Comment by ewpatton** [comment]
The problem is that you need the adb command to be the version that is compiled for arm. If you haven't replaced /usr/google/appinventor/adb, then you are still using the x86 version bundled in the deb. Remove the copy of adb there and replace it with a symlink to the one in /usr/bin (if installed using apt-get) and it should no longer give you the exec format error. Well, assuming that apt-get installs the arm version, that is.

**Comment by gabrielcbe** [comment]
Worked like a charm!
thanks a lot @ewpatton!
