### ISSUE TITLE
Default button color changes

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1412]
I was not able to reproduce this in 2.46 but it happens in production in the 2.47 companion. I have an app with a button and a set of buttons that control the former's background color. Upon picking a color using the set of buttons, I change the background color of the first button in the designer. When the screen refreshes, the set of buttons to choose color take on the last background color of the first button (see screenshot). I started by pressing Red to turn the button red, and then change its background color to blue. The result is that the button is blue but the others all turn red. Because we capture and modify the default button background, it's possible this might be shared across all buttons resulting in this behavior.

![screenshot_1541793443](https://user-images.githubusercontent.com/1331253/48285306-2d0a1a00-e430-11e8-93ec-825b9ccffd35.png)

**Comment by SusanRatiLane** [comment]
Cannot reproduce on current master or production. It's possible this was fixed as a side effect of #1377

**Comment by ewpatton** [comment]
I was able to repro this on master (project attached).

1. Load test project
2. Connect companion
3. Click "Red" button
4. In the designer, change the background color of the big button from Blue to something else
5. The buttons at the bottom will change background color to Red

Note that Button5.BackgroundColor ("Red" button) reports 0 (default) even though it visually is different, so it seems to be something cached at the UI layer with the background drawable for the buttons.

[Bug1412.aia.zip](https://github.com/mit-cml/appinventor-sources/files/3137833/Bug1412.aia.zip)

**Comment by ewpatton** [comment]
Fixed by #1932
