### ISSUE TITLE
About File location

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#1413]
Why is [OnInitializeListener](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/util/OnInitializeListener.java) not in the parent directory like other listeners?

**Comment by josmas** [comment]
I'm pretty sure I recall that being an oversight during review. No actual design decision or anything, more of a mistake than anything else.
