### ISSUE TITLE
Phone and SMS permissions security update.

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1416]
https://android-developers.googleblog.com/2018/10/providing-safe-and-secure-experience.html

**Comment by ewpatton** [comment]
@moliata We are aware of this issue. It may end up that we take these permissions out of the companion depending on Google's determination.

**Comment by barreeeiroo** [comment]
Hi @ewpatton 
I have submitted a request to Google's Team to whitelist our companion
I'll let you know if we are allowed to keep those permissions

**Comment by fm9610** [comment]
Deadline for update your app or submit a Permissions Declaration Form is January 9, 2019.

**Comment by fm9610** [comment]
Is there any response from Google? Must I submit a Permission Declaration Form before the January 9, 2019 deadline? Thanks!

**Comment by barreeeiroo** [comment]
_Bumping Issue_

Any update on this?
There are only 4 days left to reach the 9th January

**Comment by ewpatton** [comment]
Resolved by #1506
