### ISSUE TITLE
Add more screen size options for designer

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1428]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/vaeiv_JLoYQ/fxU5CTkLAQAJ): Given the many variants of resolutions/screen available today, it would be nice to have more options for preview size the designer beyond phone/tablet. It would also be useful for those who have larger monitors to use the Viewer box rather than having it mostly taken up by whitespace.

**Comment by ewpatton** [comment]
One thought is that the developer could add entries with the width/height for different devices, and this could be stored as a UserFileData so that it is available across projects.

**Comment by ZhengCornell** [comment]
@ewpatton @josmas thinking of solving this one.

**Comment by josmas** [comment]
hey @ZhengCornell [here's](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/appengine/src/com/google/appinventor/client/editor/simple/SimpleVisibleComponentsPanel.java#L86) when the current setting can be changed. I would recommend reading this [document](https://docs.google.com/document/d/1rOsvtd6ZjmRYqBdL9OWRhtwf735lJydDQjvkjCYVJ6E/pub) although it was written for app inventor 1, but will still give you an idea of how things are organised (when you are reading it, think that a lot of things have changed).
