### ISSUE TITLE
Add password textbox option to Notifier

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1431]
[From the power users](https://groups.google.com/d/msg/aipowerusers/rNrKQhdWrSU/wEK_i5CZAQAJ): Notifier could benefit from having an option to prompt for a password. Currently, one can only prompt for plaintext.

**Comment by kuan9611** [comment]
@ewpatton @josmas thinking of tackling this one. Is [this](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/Notifier.java) the file I should look at?

**Comment by josmas** [comment]
Hey @kuan9611 that seems to be the right place.

**Comment by ewpatton** [comment]
@kuan9611 This post may also be relevant [via StackOverflow](https://stackoverflow.com/questions/7453925/password-field-in-alertdialog).

**Comment by kuan9611** [comment]
@ewpatton @josmas PR [here](https://github.com/mit-cml/appinventor-sources/pull/1550)
