### ISSUE TITLE
Investigate adaptive (round) icons on Android Pie (SDK 28) and higher

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1436]
Starting on Android Pie, the launcher expects apps to use an adaptive icon. Legacy icons (like the ones we have today) are shrunk down and displayed inside a white circle for "compatibility." We should investigate how we can convert existing icons into adaptive icons so that developer-specified icons work on Android Pie and higher. This also affects the companion's icon starting on Pie.

**Comment by ewpatton** [comment]
Updating to reflect that this seems to be affecting Pie, not Oreo. Below is a screenshot of what the icon looks like:

<img width="104" alt="screen shot 2018-11-21 at 11 57 09 am" src="https://user-images.githubusercontent.com/1331253/48856611-d7653400-ed84-11e8-9c83-850bf4b964c4.png">

**Comment by ewpatton** [comment]
So I took a look at this to better understand what we could do w.r.t. App Inventor. The ideal thing would be to represent our icon as a Android vector file and use that to generate the icon. However, that would make supplying icons from the users really hard since most would probably prefer to use a raster icon. Another approach is that we can provide an upsized icon and then generate mipmaps, which is what Android Studio does. We could repackage the generator code in the buildserver (it is ASL 2.0 licensed), and generate all of the necessary icons from the provided icon file on Screen1. In my tests, I used the 1024px square icon for iOS and it worked reasonably well.

This won't be resolved for the next release, so I'm going to remove it from the milestone.

**Comment by ewpatton** [comment]
Using the aforementioned solution would also resolve #902

**Comment by ewpatton** [comment]
Note to self: tools/adt/idea/android/src/com/android/tools/idea/npw/assetstudio/LauncherIconGenerator.java

**Comment by SusanRatiLane** [comment]
I was going down the Android Studio solution, but in my tests it didn't work properly. I'd like to review with you. It's likely I missed a part of the build process.

**Comment by ewpatton** [comment]
Since this hasn't seemed to critical, it might be a good project for someone in @mit-cml/cornell-cs-5152-students-fall-2019 to look at

**Comment by ewpatton** [comment]
Fixed by #1888
