### ISSUE TITLE
German translation for AI

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1439]
Create properties file for german translation using existing completed project on Pootle (http://www.google.com/url?q=http%3A%2F%2Fpootle.appinventor.mit.edu%2F&sa=D&sntz=1&usg=AFQjCNGq4eLVh7Wh8j3wISC7fnvAq3cbxQ). That's an outdated project, so we'll have to see how well it matches existing strings.

**Comment by ewpatton** [comment]
Resolved by e11af9db4f71a4cb9a512e1ea9610da08e31e7d7
