### ISSUE TITLE
Update Maps Component Marker documentation

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1451]
It is not obvious how to make use of Any Component blocks for Map Markers. 

Suggestion from Steve Gradijan:

[MapsComponentMarker.docx](https://github.com/mit-cml/appinventor-sources/files/2640590/MapsComponentMarker.docx)

**Comment by ewpatton** [comment]
Another option we might want to consider is making it so that if there is a Map present, you get the Any Marker blocks in addition to Any Map.

**Comment by kdclang** [comment]
I agree with Evan's suggestion - if you have a Map component, add the Any Marker blocks too. Then there is no need for an invisible Marker if you don't already have Marker components in your project.

**Comment by ewpatton** [comment]
@SusanRatiLane I'm thinking that given we have merged and released #1500 that we might be able to close this one. Let's propose it to Steve and see what he thinks.

**Comment by SusanRatiLane** [comment]
Ah, that makes sense. Yes.
