### ISSUE TITLE
Update Procedure Blocks documentation

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1452]
Update proposed by Steve Gradijan:
[ProcedureBlocks.docx](https://github.com/mit-cml/appinventor-sources/files/2640610/ProcedureBlocks.docx)

**Comment by J0hnL0cke** [comment]
"App Inventor will not let you define two procedures in the same app with the same name". Shouldn't that be "App Inventor will not let you define two procedures in the same **screen** with the same name"?

**Comment by SusanRatiLane** [comment]
Great. Thanks.
