### ISSUE TITLE
Create built-in repo for YR Media templates

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1455]
Right now, if one wants to start with the YR Media tutorials, they must launch them from the [App Inventor homepage](http://appinventor.mit.edu). We should also make a built-in repo in App Inventor so that one can open them from right inside App Inventor, similar to how we can open Hello Purr.

**Comment by 27vinayvyas** [comment]
Hello @ewpatton 
I was trying for this issue but could not understand what exactly we are supposed to do?
From where can we access "Hello Puff" inside app inventor??

**Comment by ewpatton** [comment]
If you go to Projects > Import aia from repository, you can see that Hello Purr is provided as a sample app. I'd like it if we can import all of the tutorials listed [here](http://appinventor.mit.edu/explore/app-building-guides.html) as projects as well.

In the sources, the Hello Purr template is located at `appengine/war/templates/`. You should be able to use the directory there as a prototype for the other projects, substituting the appropriate descriptive text and project file.

**Comment by bartmathijssen** [comment]
Can the templates get generated via http://templates.appinventor.mit.edu/trincoll/builder/index.html? That would make it much easier. I should I upload at the thumbnail field? The YR Media logo?

**Comment by ewpatton** [comment]
Closed via a59ac22
