### ISSUE TITLE
URI is not absolute error

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1457]
When calling File.ReadFrom with a file name starting with `//`, we do not construct a complete file URI. This then gets passed to FileUtil, which throws an exception.

**Comment by linchenyu1988** [comment]
Still having the issue by using File.ReadFrom with //. Keep getting "URI is not absolute" error. Any suggestion about how to read a csv file?

**Comment by ewpatton** [comment]
@linchenyu1988 The fix is PR #1462 and is under review.

**Comment by linchenyu1988** [comment]
Does the fix be applied yet? The "URI is not absolute" error is still there. Thanks
