### ISSUE TITLE
StockQuotes tutorial is no longer valid

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1460]
Yahoo Finance is no longer free. It is probably not possible to make this tutorial work. 

There are other APIs that could be used to make a tutorial, perhaps Wikipedia's API.

Thread for reference: https://groups.google.com/forum/#!category-topic/mitappinventortest/2N_j1exzQi4

**Comment by ewpatton** [comment]
We decided to pull the tutorial down from the website. We will write a replacement tutorial using a different web API.
