### ISSUE TITLE
Read from File Path Error

### ISSUE THREAD

**Issue by zmd94** [mit-cml/appinventor-sources#1470]
Hi. Today, I try to read myCall.csv file from AI2 asset folder using path `//myCall.csv`. I already upload the file in AI2 server. Yet, I get error with URI is not absolute. Just see below image:

![image 2](https://user-images.githubusercontent.com/8069305/49658388-e6363100-fa7c-11e8-8522-fe6604e990d9.jpg)

So, I try to read the myCall.csv file from SD card, by change the path to `/myCall.csv`. Before that, I just move the myCall.csv file from AI2 asset folder to SD card. Luckily there is no problem. 

Do, AI2 has change the method to read file from assset folder?

Thank you.

**Comment by ewpatton** [comment]
This is a regression and is being tracked by #1457. The fix is being tested in #1462.

**Comment by zmd94** [comment]
Will wait for the fix being merged into master branch. Many thanks for fast response.
