### ISSUE TITLE
Fusion Tables is turning down

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#1473]
Google Fusion Tables is shutting down and their API will be turned off on December 3, 2019.

**Comment by ewpatton** [comment]
@moliata We also got the notice. Our immediate plan is to add a notice when someone imports a FusiontablesControl that Google is discontinuing support in December of 2019, but we don't yet have a long term plan for a replacement (if any).

**Comment by moliata** [comment]
@ewpatton great idea, we can add the Firebase's experimental warning and just add it to the FusiontablesControl component, not a huge hassle. I can take a look on the weekend.

**Comment by ewpatton** [comment]
#1916 removed the FusiontablesControl from general use and will go into the next release. I'm considering this "done".
