### ISSUE TITLE
Lacking lifecycle common library

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1496]
It should be between this line, 
https://github.com/mit-cml/appinventor-sources/blob/49013feb17620b813dcd8d02500061777e0ca414/appinventor/components/build.xml#L122
and this line
https://github.com/mit-cml/appinventor-sources/blob/49013feb17620b813dcd8d02500061777e0ca414/appinventor/components/build.xml#L123

![image](https://user-images.githubusercontent.com/22613139/50573603-677dab00-0e12-11e9-8f2f-1c577c7ac544.png)

**Comment by ewpatton** [comment]
I'm not sure that we actually need the lifecycle library in App Inventor. At least, I haven't seen any bugs that we could ascribe to the fact that we don't compile against it. Are you tripping on something that is caused by us missing this when compiling the components module?

**Comment by ColinTree** [comment]
Yes, in original App inventor sources, there are no problem without this, but it is some times required by some functionalities.
As we have already stored this lib in the repo, why dont we add it to classpath just like the other support libs?
