### ISSUE TITLE
aiStarter is broken with WebRTC

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#1499]
I've been testing the new WebRTC feature, and I noticed that the script aiStarter with WebRTC is not working properly (or hasn't worked for me)
It crashes after attemping to load Form on Companion

ADB Logcat displays this:
```
01-02 20:29:59.188 14902 14967 D WebRTC: response = 
01-02 20:29:59.189 14902 14967 E WebRTC: Caught JSONException: org.json.JSONException: End of input at character 0 of 
01-02 20:29:59.189 14902 14967 E WebRTC: org.json.JSONException: End of input at character 0 of 
01-02 20:29:59.189 14902 14967 E WebRTC: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at org.json.JSONArray.<init>(JSONArray.java:92)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at org.json.JSONArray.<init>(JSONArray.java:108)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at com.google.appinventor.components.runtime.util.WebRTCNativeMgr$4.run(SourceFile:252)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-02 20:29:59.189 14902 14967 E WebRTC: 	at java.lang.Thread.run(Thread.java:764)
```

I then realized that the error comes from this line: https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/util/WebRTCNativeMgr.java#L253
I assume the response to Rendezvous is empty, so the error raises (as any code is passed to the URL, technically)

I would like to confirm if this error is from a miss-configuration from my side, or this error is also part of appinventor-sources

**Comment by ewpatton** [comment]
@barreeeiroo I haven't had any issues when using the companion in the emulator. Under what circumstances are you triggering this error? Are you using the latest rendezvous code under misc?

**Comment by barreeeiroo** [comment]
I have copied all files from WebRTC commit, and updated rendezvous.js
Companion through WiFi works as intended, but USB Connection doesn't

**Comment by ewpatton** [comment]
I'm not able to replicate this. I tested with Companion 2.49 running on an Amazon Kindle Fire tablet and was able to successfully connect using the USB option.

**Comment by barreeeiroo** [comment]
Humm, I will debug it more in depth. I should have made something wrong in the process
Thanks for your help, I'll update the issue when I get any news

**Comment by jisqyv** [comment]
WebRTCMgr has been refactored since this issue was opened and we believe this is no longer a problem.
