### ISSUE TITLE
Default behavior for Maps LoadFromURL

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1502]
Currently, the Map.LoadFromURL method takes a string containing a GeoJSON URL as input but fails silently if the GotFeatures event is not defined to process the features from the file. This isn't necessarily intuitive behavior.

Default behavior should be to loop through features defined in the file and create those features using the FeatureFromDescription method. 

Default behavior can be overridden by defining the GotFeatures event.

**Comment by ewpatton** [comment]
Closed via #1538
