### ISSUE TITLE
Loading Maps features from URL loading only one feature

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1503]
This test application is designed to load the New England states from the States Quiz tutorial when the "Load Map" button is clicked.

The GotFeatures event appears to receive a list that is 6 elements long, but only the state of Rhode Island is loaded onto the map. 

(Remove the spurious extra .zip I added. The upload rejected the aia extension.)

[MapNewEngland.aia.zip](https://github.com/mit-cml/appinventor-sources/files/2727701/MapNewEngland.aia.zip)

**Comment by SusanRatiLane** [comment]
Addendum: Polygon type will not display from this file, but MultiPolygon will. Converting state definitions to MultiPolygons containing only one Polygon (i.e. adding another set of [] around the coordinates) causes the state shape to display on the map when the code is executed.

**Comment by ewpatton** [comment]
So #1654 broke this functionality completely. I should have a fix shortly.

**Comment by ewpatton** [comment]
Closed via #1700
