### ISSUE TITLE
JsonComponentDescription Error with new Library?javac: invalid flag: -?

### ISSUE THREAD

**Issue by kangris-sket** [mit-cml/appinventor-sources#1513]
JsonComponentDescription Error with new Library?

Im use new commit and try add component admob with library.
and get error :(

> javac: invalid flag: -

`JsonComponentDescription:
    [mkdir] Created dir: E:\appinventor-sources\appinventor\components\build\classes\JsonComponentDescription
    [javac] Compiling 236 source files to E:\appinventor-sources\appinventor\components\build\classes\JsonComponentDescription
    [javac] javac: invalid flag: -
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
`

How to fix?Please...
And try another library get same error :(

**Comment by kangris-sket** [comment]
I think tis get error from merger to ucr...?
because commit compinion 2.49 is fine... but after 2.50 get error :(

**Comment by ewpatton** [comment]
I would recommend that you ask this in the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev), as this is not an issue with the App Inventor sources but your modifications.
