### ISSUE TITLE
When the selected language is not English, the page where the password is incorrectly returned http://127.0.0.1:8888/login is blank

### ISSUE THREAD

**Issue by fsyzty** [mit-cml/appinventor-sources#1518]
When the selected language is not English, the page where the password is incorrectly returned http://127.0.0.1:8888/login is blank instead of http://127.0.0.1:8888/login/?error=Invalid%20Password

appengine\src\com\google\appinventor\client\explorer\youngandroid\GalleryList.java
// Add panels to main tabPanel
    appTabs.add(appRecent, "Recent");
    appTabs.add(appTutorial,"Tutorials");
    appTabs.add(appFeatured, "Featured");
    appTabs.add(appPopular, "Popular");
    appTabs.add(appSearch, "Search");
    appTabs.selectTab(0);
    appTabs.addStyleName("gallery-app-tabs");
    galleryGUI.add(appTabs);

Did not consider other languages

**Comment by ewpatton** [comment]
I think there are two separate issues here. One is the login issue and the other is the internationalization of the gallery.

For the former, I'm willing to accept that it is a bug, but given that we don't use the login page for production I'm not particularly concerned about dedicating our core team to fixing it (if anyone wants to submit a patch, we will gladly accept the help).

For the issue about the gallery, we will not address the internationalization issue for this version. We have an alternate gallery implementation we are working on that will be internationalized. It is not worth duplicate effort on this front.

**Comment by fsyzty** [comment]
appinventor\appengine\src\com\google\appinventor\server\LoginServlet.java

  private void fail(HttpServletRequest req, HttpServletResponse resp, String error) throws IOException {
    resp.sendRedirect("/login/?error=" + sanitizer.sanitize(error));
    return;
  }
-----------------------------------------------------------------
  private void fail(HttpServletRequest req, HttpServletResponse resp,String locale, String error) throws IOException {
    resp.sendRedirect("/login/?locale="+ locale +"&error=" + URLEncoder.encode(sanitizer.sanitize(error)));
    return;
  }

----------------------------------------------------------------------
fail(req, resp,*******************************）

---------------------------------------------------------------------
fail(req, resp,locale,***********************）

**Comment by fsyzty** [comment]
appinventor-sources\appinventor\appengine\war\login.jsp
----------------------------------------------------------------------------------------------
`<center><p><a href="/login/sendlink"  style="text-decoration:none;">${passwordclickhereLabel}</a></p></center>`
----------------------------------------------------------------------------------------------
`<center><p><a href="/login/sendlink?locale=<%= locale %>"  style="text-decoration:none;">${passwordclickhereLabel}</a></p></center>`

**Comment by ewpatton** [comment]
Fixed by #2434
