### ISSUE TITLE
Move ComponentListGenerator constants into common

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1522]
Currently, ComponentListGenerator (components) defines constants used as keys in the descriptions of components that are consumed by Compiler (buildserver). However, rather than referencing the constants, we duplicate the definitions in Compiler.java. The appropriate thing to do here would be to refactor the constants into the common module and then reference the single definition from both the ComponentListGenerator and Compiler.

**Comment by ZhengCornell** [comment]
I can take a look at this issue. What do you mean by the common module?

**Comment by ewpatton** [comment]
@ZhengCornell I consider each directory under the top level appinventor directory to be a module (appengine, buildserver, etc.). There is one called common. However, after looking at how the sources are organized, I think that it might be better to put the constants into components/src/com/google/appinventor/components/common. This package gets compiled into a CommonConstants.jar file that is used by the appengine, buildserver, and components modules. You should create a new class, e.g. ComponentDescriptorConstants, and move the constants there. Once you've done that, you can update ComponentListGenerator and Compiler to reuse the shared constants rather than their own copies.

**Comment by ZhengCornell** [comment]
So only shared constants should be put into ComponentDescriptorConstants. Or all private static final constants must be put into this file? Besides, except these three files, do I have to modify others?

**Comment by ewpatton** [comment]
Fixed via 516cd43
