### ISSUE TITLE
Buildserver return 503 ERROR

### ISSUE THREAD

**Issue by HanderWei** [mit-cml/appinventor-sources#1524]
I run the app engine development server and the buildserver, but when i visit localhost:8888, it returns 503 ERROR.

![2019-01-15 5 20 38](https://user-images.githubusercontent.com/5194035/51170844-635d8d00-18ea-11e9-9e59-c8c81d502d13.png)

**Comment by ewpatton** [comment]
The build server runs fine on both our development machines and in production. If this is a setup specific issue, or if you modified the sources in some way, I recommend that you instead ask your question in the [App Inventor open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).
