### ISSUE TITLE
Add MakeInstant method using individual components

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1533]
Chris Ward suggests that we have a version of MakeInstant that can compose an instant from the constituent parts rather than from a string (see screenshot).

![makeinstant](https://user-images.githubusercontent.com/1331253/51547489-6f8aa280-1e34-11e9-95b6-6a38e280fd0f.png)

I think this is good idea, but I think the ordering should be major-minor, i.e., year month day hour minute second. We might also want to consider a MakeDate and MakeTime for compatibility with the DatePicker and TimePicker, resp.

**Comment by xueyuanw** [comment]
I can take a look at this issue!

**Comment by josmas** [comment]
hey @xueyuanw this is the [file to look at](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/Clock.java). Have a go at changing or adding methods and see how that changes in the UI. The [docs here](http://appinventor.mit.edu/appinventor-sources/#documentation) will be helpful.

**Comment by ewpatton** [comment]
Resolved by 294905feb31ce8f2bd29b5950ac2b328646da35a
