### ISSUE TITLE
Many property setters should use dropdowns for their inputs

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#155]
There are many examples of properties that can take on specific values.  For example,
screen.AlignVertical can take only the arguments: left, center, or right, and the designer provides a dropdown that has only those options.    In the blocks, however, the setter takes a numeric input.  The user needs to know which number corresponds to the desired value, and the implementation code must check whether the number is legal.

Instead, we could make the setter block use a dropdown for selecting the input.
Implement this system and change the component property code to make use of this.

**Comment by halatmit** [comment]
This is the same as issue #195

**Comment by halatmit** [comment]
Here's another nice use for dropdown blocks in specifying widths and heights:
see
https://groups.google.com/forum/#!topic/mitappinventortest/h6I7RHVW8GU

<img width="391" alt="screen shot 2015-08-14 at 4 16 01 pm" src="https://cloud.githubusercontent.com/assets/789431/9283213/ed335ed0-429f-11e5-842a-7cc343f620d0.png">

**Comment by ewpatton** [comment]
Dropdowns for known sets of property values has been addressed by the helper blocks.
