### ISSUE TITLE
Improve the welcome screen

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1553]
The welcome screen could use some TLC. I'd like to imagine that when you open App Inventor for the first time, the welcome would give you some options for next steps, such as Start a New Project, the Talk To Me tutorial, Hello Purr, or a YR media tutorial, as buttons. An option to configure these (or randomly select from a list) might also be useful. Buttons with screenshots/graphics to indicate what is accomplished in the project, rather than text, might also be preferred for internationalization purposes.

**Comment by ewpatton** [comment]
@ramiAbdou You might want to mock this up first to show what it would look like so that others can comment on it before you implement.

**Comment by ramiAbdou** [comment]
@ewpatton What exactly did you mean by:
"Buttons with screenshots/graphics to indicate what is accomplished in the project, rather than text, might also be preferred for internationalization purposes."

**Comment by ramiAbdou** [comment]
@ewpatton @josmas Just created a mockup of a welcome screen. Let me know what comments you guys might have.

![image](https://user-images.githubusercontent.com/38056800/52989272-a5d62600-33d0-11e9-8f38-c757dda25120.png)

**Comment by ewpatton** [comment]
I think this is a good start. A couple things that jump out at me: We should make sure that the Codi logo is integrated in some way. I also think that the last line should be "Or click here to start a new project"

cc @jsheldonmit @kdclang @stezelMIT for their thoughts

**Comment by ramiAbdou** [comment]
Okay sounds, let me know what other changes need to be made so I can get started creating the HTML.

![image](https://user-images.githubusercontent.com/38056800/53030487-e10c3f80-3438-11e9-9dec-8dc4c6484674.png)

**Comment by PeterMathijssen** [comment]
According to the styleguide for the use of the logo you have top put a white hexagon around codi when using on a colored background.

![selection_999 339](https://user-images.githubusercontent.com/32273650/53149342-b263a580-35ad-11e9-87bc-831922909456.png)

**Comment by jsheldonmit** [comment]
Good call, Peter.

This looks great.

Can we code it so that the “Start a new project” link pops up the name the project alert directly, bypassing the start new project button in the my projects screen?

Similarly, I’ve lost track of which tutorials we have sidebar versions of, but it would be ideal if we could make the tutorial links go to a starter project with assets loaded & the tutorial in the left-side pane

================
Josh Sheldon
Associate Director – MIT App Inventor
pronouns: he/him/his

MIT Computer Science and Artificial Intelligence Lab
32 Vassar St., Room 32-G504
http://whereis.mit.edu/?go=32
Cambridge, MA 02139
mobile phone: 617-671-5491

http://appinventor.mit.edu - @MITAppInventor<http://twitter.com/MITAppInventor>

**Comment by ewpatton** [comment]
That was the plan. I just wanted some input from the other team members on the design before Rami starts implementing the technical changes. It sounds like we are ready to move forward on this.

Rami: I will send you the PNG for the logo with hexagon as well as the HTML color codes for styling.

**Comment by ramiAbdou** [comment]
@ewpatton sounds great, looking forward to receiving that!

**Comment by grufelous** [comment]
Hi, is there still any requirement of updates on the welcome screen?

**Comment by ewpatton** [comment]
@grufelous This is still being worked on by @ramiAbdou.

**Comment by bhogteyash99** [comment]
Make a splash screen that will welcome the user and and then the further activity may arise.
The procedure for making the splash screen is:-
1.Make a full screen image that will be my branding screen
2.Set the Background Image property of Screen1 to this image
3.Add a Clock (from the Sensors section of the Palette) to the app
4.Make sure the Timer Enabled property is checked
5.Set the timer to however long I want the branding screen to show (usually 3000 ms)

**Comment by harshsaver** [comment]
Maybe also ask you what kind of application you want to build, and setup the required conditions for you.
For example, if someone wants to develop a game, and chooses the 'game' option, then the first screen will already have a canvas in it and a pop up will show me useful tips and links to how to make good games.

Another use case will be when the developer needs to have a database in the app, and can be choose as 'offline' and/or 'cloud'. Then the screen1 will have the required database.

For new users, they can also 'tick' functionality they expect from the app they want to develop and then they will be redirected to the tutorials of components necessary for the app.

**Comment by ewpatton** [comment]
Implemented by #1637
