### ISSUE TITLE
WebViewer documentation out of date

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1558]
The WebViewer documentation is missing the addition of the WebViewStringChanged event. We should also update the text that describes how to interact with the web view string to also include the fact that the WebViewStringChanged event will run when setWebViewString is called from JavaScript.

**Comment by ewpatton** [comment]
@mit-cml/cornell-cs-5152-students This is an easy one if one of you wants to take it on.

**Comment by kuan9611** [comment]
@ewpatton I'm looking into #1347 right now, but I can also do this first since it should be pretty straightforward.

**Comment by ewpatton** [comment]
Sure @kuan9611
