### ISSUE TITLE
name of getVersionName translations are not updated

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1562]
Since 3362b27151037ac90b43e5e659b8b9f6cb151774 renamed `PhoneStatus.getVersionName` with `GetVersionName`, the translation of this block cannot be loaded correctly (following cap is from the PlayApp)
![image](https://user-images.githubusercontent.com/22613139/52768286-15ae7e80-3068-11e9-980b-279b4603a29a.png)
To fix, just need to change only a single character in every locales.
e.g. 
https://github.com/mit-cml/appinventor-sources/blob/30f86098463941fd67c203ea3b0ce6be4da648b3/appinventor/appengine/src/com/google/appinventor/client/OdeMessages_zh_CN.properties#L1095
Can be fixed by changing to
```
GetVersionNameMethods = 获取版本名 
```

**Comment by ewpatton** [comment]
Given that the PhoneStatus is an internal component (at least as far as the base App Inventor platform is concerned), it's not a high priority to fix this. It is a relatively small change though if someone wants to take it on.

**Comment by weihuali0509** [comment]
@ColinTree Can you please fix it in the MIT App Inventor version as well? thanks!
