### ISSUE TITLE
Swap the order of copy from and paste to backpack workspace menu items

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1566]
If one right-clicks on the workspace, you will see that there are options to copy to and paste from the backpack. The problem is that these are in the opposite order from every other GUI in existence (typically, Copy then Paste, but we have them the other way around). It should be a straightforward change to swap the order of the two menu items.

**Comment by xueyuanw** [comment]
I can take a look at this issue!

**Comment by ewpatton** [comment]
Closed via 545bd08
