### ISSUE TITLE
Move "Empty Backpack" menu item to backpack menu from workspace menu

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1567]
I went to go empty my backpack by right-clicking on the backpack and selecting the "Empty Backpack" menu item... except that it doesn't live there. The "Empty Backpack" menu item lives in the workspace menu. I think we should move the menu item to the backpack's menu. This may require updating the [backpack documentation](https://docs.google.com/document/d/14-VRxyUNDsYqzFplWHspThbkTQTL8gr0siAqPqYW5do/edit).

**Comment by ZhengCornell** [comment]
I can take a look at this issue.
