### ISSUE TITLE
Implement a join-with-separator block

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1577]
Many languages have a join function that can join elements of an array using a given separator. For example, in Javascript:

```javascript
['a', 'b', 'c'].join(',') === 'a,b,c'
```

will be true. Right now, one needs to implement their own version of this function in App Inventor because the join operator we provide only joins one or more given string values provided via the block mutator. It would be convenient to have a block that provides similar functionality. Given that this block would only be applicable to lists, I think we should put it under the list block category, and I propose the text be `join items using separator %1  list %2`

**Comment by halatmit** [comment]
If you make this block, look at how test split is done with a dropdown that
allows people to have split and splitAtFirst as variants of the same basic
block.
so join and join-with-separator could be similar variants
== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
@halatmit My concern with that approach (although I can’t verify at the moment on mobile) is that the split block variants have the same arity, argument types, and return type. The join and join-with-separator blocks would have different arity and input types, so switching between the two would immediately need to disconnect any connected blocks.

**Comment by halatmit** [comment]
I realze that the arity would change, but maybe there's a way to make it
work - but I haven't tried doing that.   another idea is to alway include
the separator argument and default it to empty.



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by lightingft** [comment]
I would like to help out on this issue!


I believe that choosing the option proposed by @ewpatton would be more suitable for implementing this block, and as mentioned above, setting the separator to the "" could be the default, which would act as joining multiple strings together (except the types would not necessarily be text)


Before working on the issue (if, of course, it's still available to work on), I would like to know if this approach is correct to adding the block:


1.Modifying appinventor\blocklyeditor\src\blocks\lists.js by adding a new element to Blockly.Blocks and setting up all the relevant properties


2.Modifying appinventor\blocklyeditor\src\generators\yail\lists.js by adding the relevant functionality which will handle taking a list & separator arguments and constructing a new String (text object) with the specified parameters


3.Modifying _messages.js in appinventor-sources\appinventor\blocklyeditor\src\msg to include the new block messages. Should a placeholder be used for other languages than English, or simply not modified at all? (Also, these messages should be included in step 1's edit)


4.Writing tests, proper documentation, making sure these are all committed on my own fork & branch, and then making the final pull request with the changes


Is there anything else that would be required to carry out this issue? So far I have played around with steps 1 & 2 and have managed to add a block with it's own functionality, I feel like that should be sufficient?

**Comment by ewpatton** [comment]
For this block, my vision was for it to take two arguments, the separator and the list, making it semantically equivalent to the JavaScript join function as I presented it above. The current join block would then be equivalent to `join-with-string(separator: "", list: make-a-list(...))`

**Comment by lightingft** [comment]
@ewpatton So if I understood this correctly, the block should look something like this:

![image](https://user-images.githubusercontent.com/34982762/53762182-b5249b80-3ec7-11e9-98ca-0bbabaa397a6.png)

And the result of this should be the text object: '1-2-5-9'

Is that correct? In which case, in my eyes, I believe this would be the suitable way to proceed with this idea. I would love to work further with this issue and  look into implementing the actual block functionality if this approach is well-suited for adding this block.

**Comment by ewpatton** [comment]
@lightingft Yes this matches what I have in my head. If you want to implement this one, it's yours.

**Comment by lightingft** [comment]
@ewpatton I would definitely like to implement this block. Feel free to assign me to the issue!

**Comment by halatmit** [comment]
+1

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
@lightingft I invited you to join our external collaborators group. Once you do so I can assign you the issue.

**Comment by ewpatton** [comment]
Resolved by ceb27bf233d93e61ef741e9255149e1bb3e8ff8c
