### ISSUE TITLE
Refine "Sort Blocks by Category" operation

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1583]
The "Sort Blocks by Category" menu item doesn't really do what its name implies. Most blocks are sorted by category, yes, except for procedure and component blocks, which they are sorted by name, and except for any-component blocks, which are all "Component" for the purposes of sorting.

I propose that we refine the sorting algorithm to do the following:

1. Global defs first, lexicographically sorted
2. Procedure defs next, lexicographically sorted
3. Component event handlers, lexicographically sorted by type name, instance name, then event name
4. Other free-floating blocks, sorted by category then block type. For component blocks, they should be sorted internally first by type, whether they are generic (generics precede specifics), then by instance name (for specific blocks), then by method/property name.

If this is implemented after #1548 is merged, I propose that any component event handlers, sorted by type then event name, precede all specific event handlers (step 2.5).

**Comment by halatmit** [comment]
+1

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by xueyuanw** [comment]
I would like to take a look at this issue!

**Comment by ewpatton** [comment]
@xueyuanw It’s all yours.

**Comment by xueyuanw** [comment]
May I know what files I should look into? Thanks!

**Comment by ewpatton** [comment]
@xueyuanw The logic for sorting by category is defined on line 627 of blocklyeditor/src/workspace_svg.js

**Comment by ewpatton** [comment]
Another subtlety here that we should consider is when ordering by component name, if the component names end with numerals, we might want to sort those numerical rather than lexicographically, e.g., Button10 should sort after Buttons 2-9, not before.

**Comment by ewpatton** [comment]
Implemented by #1612
