### ISSUE TITLE
CSS broken on blocks reference pages

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1586]
[For Example](http://ai2.appinventor.mit.edu/reference/blocks/). We should replicate all of the CSS resources on ai2. This worked when we deployed it, but since every static run of the website changes the CSS file names, the URLs no longer match up. Rather than rely on the resources hosted on GitHub, we should just include them in the ai2 sources.

**Comment by ewpatton** [comment]
cc @SusanRatiLane

**Comment by SusanRatiLane** [comment]
We're talking about replicating the same CSS file in multiple places? Or changing the source of truth? Is there a way to place the same file in multiple places in the staticify step to keep from having to make a change in two places?

**Comment by ewpatton** [comment]
Given that the component reference pages are fine, I think we might be able to get away with updating the script/style tags in the block reference pages to point to the same locations as the component reference pages.

**Comment by PeterMathijssen** [comment]
I did a simple copy and paste 
https://github.com/PeterMathijssen/appinventor-sources/commit/3311057f45fe521a94211acdc2f260a4d5d52225#diff-040c74093cc5d378e65af36c94691bce

And my testdocument looks like this now.
![selection_999 369](https://user-images.githubusercontent.com/32273650/54019889-a7536c80-418c-11e9-88d0-00aba0aea46b.png)

**Comment by ewpatton** [comment]
@SusanRatiLane To capture our conversation, we'll move the `<style>` element from the maps documentation page into a new css file, and add all of the necessary `<link>` elements to replace the `<style>` elements in the blocks pages (similar to what @PeterMathijssen has done).

**Comment by ewpatton** [comment]
Fixed by #1601
