### ISSUE TITLE
Project Merge Tool - "Invalid File Name" error is not helpful

### ISSUE THREAD

**Issue by rallen911** [mit-cml/appinventor-sources#1599]
I have two projects that I was trying to merge, and I got to the point where I was prompted for a file name for the merged project, and I got a "Invalid file name" error pop up.  The error should be more descriptive, so that I can try and rectify the problem.

I don't know if it was the file name I was trying to save to, "test.aia", or if one of the file names in the project was causing a problem (AI2 was not having a problem, so not sure why that would be the case).

The behavior should be to output the file name that it is having problems with, so that the user can try to fix the problem.

**Comment by ewpatton** [comment]
@rallen911 Can you email me the two projects in question? It will help us narrow down the problem.

**Comment by abhinavk99** [comment]
Is there any further insight about this? A family member is having the same issue.

**Comment by ewpatton** [comment]
@abhinavk99 What version of the project merge tool are you using? I was not able to replicate this issue in v1.2 ([link](https://appinventor.mit.edu/explore/resources/ai2-project-merger)). If you are having issues with 1.2, please send us the AIA files so we can further debug.

**Comment by ewpatton** [comment]
Thanks. I've used your projects to reproduce the issue.
