### ISSUE TITLE
'Palette' not shows on deleting screen in 'Blocks'

### ISSUE THREAD

**Issue by Ujjwal0501** [mit-cml/appinventor-sources#1603]
When there is more than one screen available, and we close one screen from the 'Blocks' section, then it takes us to the 'Designer' section, but then the palette does not show up until you go back to 'Blocks' and then come back to 'Designer' section.

**Comment by ewpatton** [comment]
@Ujjwal0501 Thanks for the report. I was able to confirm this behavior. Additionally, it seems as though the components/media panels end up below the blocks panel, which is also wrong.

**Comment by Ujjwal0501** [comment]
I want to look into the issue. But since I'm unfamiliar with the codebase, I will need some guidance to proceed to correct the problem.

**Comment by ewpatton** [comment]
@Ujjwal0501 The discrepancy comes from how the loadDesigner and unloadBlocksEditor methods interact in YaFormEditor and YaBlocksEditor, respectively. I believe that the issue reduces down to the fact that the unload method shows the palette panel and assets panel, but if the screen has been deleted then technically it won't be available and onHide (which calls unloadBlocksEditor) won't trigger. At the point when Screen1's designer is shown, selectedFileEditor is already null, so the onHide method is never called.

If I had to take an educated guess, I expect that what we need to do is call selectedFileEditor.onHide() in ProjectEditor.closeFileEditors(String[]) before we set it to null. This seems like it might be the minimal change we need to make.

However, it might make sense to clean up how onShow/onHide work. I think that only the onShow method should be responsible for showing boxes while only onHide should be responsible for hiding them. Right now the semantics are mixed which can lead to these types of unexpected combinations of views.

Try making the first change I suggested and see if that resolves the issue. Then, start thinking about the more general cleanup of these two methods and do some experiments.

**Comment by Ujjwal0501** [comment]
@ewpatton I added the line to call _selectedFileEditor.onHide()_ in ProjectEditor.closeFileEditors(String[]) and the __issue was resolved__.

I'll do the required code cleaning. :)
Thanks

**Comment by ewpatton** [comment]
@Ujjwal0501 Great! Thanks for testing it and I look forward to a PR.

**Comment by ewpatton** [comment]
@Ujjwal0501 You can open a PR with the fix and we can review it incrementally as you make improvements. Once complete, it will get squashed down into a single change.

**Comment by Ujjwal0501** [comment]
@ewpatton 

I looked into the code. The way onshow/onhide are implemented, they call another load/unload functions which do all the clearing and visibility related operations.
What I can think of is remove the load/unload and perform all the operations in onshow/onhide functions itself.

What is your suggestion?

**Comment by ewpatton** [comment]
@Ujjwal0501 I think we can close this for now since your PR fixed the issue. It's probably worth filing a separate issue to track the technical debt.
