### ISSUE TITLE
Error in "ant extensions" after commit 516cd43

### ISSUE THREAD

**Issue by RobertoNegro** [mit-cml/appinventor-sources#1604]
After commit [516cd43](https://github.com/mit-cml/appinventor-sources/commit/516cd43b023f1d57ae2111449aef17d97b4994fe) when I try to launch the command ant extensions it fails and in terminal I get:

BuildServer:
    [javac] Compiling 5 source files to /path/appinventor/buildserver/build/classes/BuildServer
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:12: error: package com.google.appinventor.components.common does not exist
    [javac] import com.google.appinventor.components.common.ComponentDescriptorConstants;
    [javac]                                                ^
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:262: error: cannot find symbol
    [javac]       loadJsonInfo(permissionsNeeded, ComponentDescriptorConstants.PERMISSIONS_TARGET);
    [javac]                                       ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:284: error: cannot find symbol
    [javac]     mergeConditionals(conditionals.get(ComponentDescriptorConstants.PERMISSIONS_TARGET), permissionsNeeded);
    [javac]                                        ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:380: error: cannot find symbol
    [javac]       loadJsonInfo(libsNeeded, ComponentDescriptorConstants.LIBRARIES_TARGET);
    [javac]                                ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:405: error: cannot find symbol
    [javac]       loadJsonInfo(nativeLibsNeeded, ComponentDescriptorConstants.NATIVE_TARGET);
    [javac]                                      ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:430: error: cannot find symbol
    [javac]       loadJsonInfo(assetsNeeded, ComponentDescriptorConstants.ASSETS_TARGET);
    [javac]                                  ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:455: error: cannot find symbol
    [javac]       loadJsonInfo(activitiesNeeded, ComponentDescriptorConstants.ACTIVITIES_TARGET);
    [javac]                                      ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:480: error: cannot find symbol
    [javac]       loadJsonInfo(broadcastReceiversNeeded, ComponentDescriptorConstants.BROADCAST_RECEIVERS_TARGET);
    [javac]                                              ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:492: error: cannot find symbol
    [javac]     mergeConditionals(conditionals.get(ComponentDescriptorConstants.BROADCAST_RECEIVERS_TARGET), broadcastReceiversNeeded);
    [javac]                                        ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:504: error: cannot find symbol
    [javac]       loadJsonInfo(componentBroadcastReceiver, ComponentDescriptorConstants.BROADCAST_RECEIVER_TARGET);
    [javac]                                                ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:519: error: cannot find symbol
    [javac]       loadJsonInfo(minSdksNeeded, ComponentDescriptorConstants.ANDROIDMINSDK_TARGET);
    [javac]                                   ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:1762: error: cannot find symbol
    [javac]           boolean isV7a = lib.endsWith(ComponentDescriptorConstants.ARMEABI_V7A_SUFFIX);
    [javac]                                        ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:1763: error: cannot find symbol
    [javac]           boolean isV8a = lib.endsWith(ComponentDescriptorConstants.ARM64_V8A_SUFFIX);
    [javac]                                        ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:1764: error: cannot find symbol
    [javac]           boolean isx8664 = lib.endsWith(ComponentDescriptorConstants.X86_64_SUFFIX);
    [javac]                                          ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:1771: error: package ComponentDescriptorConstants does not exist
    [javac]             lib = lib.substring(0, lib.length() - ComponentDescriptorConstants.ARMEABI_V7A_SUFFIX.length());
    [javac]                                                                               ^
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:1775: error: package ComponentDescriptorConstants does not exist
    [javac]             lib = lib.substring(0, lib.length() - ComponentDescriptorConstants.ARM64_V8A_SUFFIX.length());
    [javac]                                                                               ^
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:1779: error: package ComponentDescriptorConstants does not exist
    [javac]             lib = lib.substring(0, lib.length() - ComponentDescriptorConstants.X86_64_SUFFIX.length());
    [javac]                                                                               ^
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:2023: error: cannot find symbol
    [javac]           } else if (e.getMessage().contains(ComponentDescriptorConstants.ANDROIDMINSDK_TARGET)) {
    [javac]                                              ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] /path/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java:2067: error: cannot find symbol
    [javac]     JSONObject conditionals = compJson.optJSONObject(ComponentDescriptorConstants.CONDITIONALS_TARGET);
    [javac]                                                      ^
    [javac]   symbol:   variable ComponentDescriptorConstants
    [javac]   location: class Compiler
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 19 errors
    [javac] 1 warning

**Comment by RobertoNegro** [comment]
Reverting the changes of that commit in my local fork resolve the issue.

**Comment by ewpatton** [comment]
So this is a somewhat subtle bug in the build system. If I build the full system and then run ant extensions, it works correctly, but if I ant clean and then run ant extensions, it fails. The problem is that in 516cd43 we take advantage of the fact that building the website comes before building the buildserver, and so CommonConstants.jar is available at that point in the build process. When building extensions, however, that assumption is broken.

**Comment by ewpatton** [comment]
@RobertoNegro You can try PR #1605 to see if it resolves your issue.
