### ISSUE TITLE
Add OpenDyslexic font as alternative user setting

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1606]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/KFkF0ZfUI6g/rhRAIFUJBQAJ): Adding the ability to use a font such as OpenDyslexic to improve the readability of the web interface would benefit app inventors. I don't think we want to make it the default, but having an option to switch it on (and store the state in UserSettings) would make the platform more accessible.

**Comment by ewpatton** [comment]
This would also benefit from #1593, since it moves the loading of UserSettings earlier in the app initialization, which means we can also apply a stylesheet with the font at that time.

**Comment by 27vinayvyas** [comment]
I wanted to give it a try, know how to do in android studio. 
Can u please show me where to make the required changes.
I m new in here.

**Comment by 27vinayvyas** [comment]
If i m not wrong,there must be a folder for fonts , and there the Open Dyslexic font is to be added but i cannot figure out where is that fonts folder

**Comment by ewpatton** [comment]
@27vinayvyas Fonts are located in `appengine/war/fonts/`.

The real challenge here is the design for how this is presented to the app developer. We've tried to keep discovery somewhat easy by putting most things in the designer view. But one might want to turn this feature on before they start a project, or even before they've created an account (in the case of code.appinventor.mit.edu). A simple first pass might be to add an entry to the Help menu that can be enabled/disabled in the current session but doesn't persist. A second pass could add persistence.

To add menu items, please see TopToolbar.java in the appengine module.

**Comment by 27vinayvyas** [comment]
I m having problem understanding how to do this
What does these two arguments in bold mean and what would be there value in this case??

fileItems.add(new DropDownItem(WIDGET_NAME_EXPORTPROJECT, **MESSAGES.exportProjectMenuItem()**,
        new **ExportProjectAction()**));

**Comment by 27vinayvyas** [comment]
@ewpatton 
Sorry for the delay but its finally working(changing font to opendyslexic on a button click)
What i have done is that i have REMOVED  all the font-family attributes  from Ya.css and gwt.css EXCEPT from the body tag which has Roboto as default.
On clicking the Dyslexic font button, the Roboto font attribute is removed and the opendysleic font is added to the body tag.
All the other elements ,being body's child , gets the new font.

I am facing an issue, the font inside the main design screen doesnot seems to be controlled by Ya.css and gwt.css files. It sfont is unaffected when the above changes are made.

Which css files control their font??

I just wanted to clarify if what i am doing is right or not.
If so, i can send the pr

**Comment by bartmathijssen** [comment]
As there was little activity in pull request #1639 I started working on my own version. I used #1639 as a starting point. I now made it that the user's preferred font gets saved to the UserSettings object. I did run into an issue. When changing the font, the blocks' font gets changed, but the padding doesn't. It does render the blocks properly when reloading the page.

| Before reload  | After reload |
| ------------- | ------------- |
| ![Selection_002](https://user-images.githubusercontent.com/54038995/63370485-95543780-c382-11e9-980a-27b9b58c5a13.png) | ![Selection_001](https://user-images.githubusercontent.com/54038995/63370438-79e92c80-c382-11e9-8388-a1262aa6ec26.png) |

I can solve this by reloading the window when a new font is selected. This is also done when selecting a new language, but this doesn't feel like it is the right way to do it.

I was also thinking about the user interface of the font switcher. Pull request #1639 made it that there were always two options in the Settings dropdown. I want to make it that when the regular font is selected the `DropDownItem` has a caption of `Enable OpenDyslexic` and when OpenDyslexic is selected the `DropDownItem` has a caption of `Disable OpenDyslexic`. What do you think?
