### ISSUE TITLE
EROFS Error in SoundRecorder Component

### ISSUE THREAD

**Issue by wangiv2** [mit-cml/appinventor-sources#1619]
Hello,

when i tried to use the SoundRecorder component, can not record sound in android devices, it popup "cannot start recording: *.amr:open failed:erofs(read-only file system)" error message. Anyone can help to advise how to fix it?

**Comment by ewpatton** [comment]
@wangiv2 Try adding a `Screen1.AskForPermission` block in `Screen1.Initialize` with the permission name `android.permission.WRITE_EXTERNAL_STORAGE` and see if you can start a recording afterward (you may be prompted for permission).

**Comment by wangiv2** [comment]
Hi Ewpatton,

Thanks for your help. But after trying, still the same error popup, below is my setting in block, if there is any wrong? i can not find the android permission so just add as text value. Can you help to advise? Many thanks.

![image](https://user-images.githubusercontent.com/7232767/54729816-85141280-4bc0-11e9-9966-ed3d055cadb5.png)

**Comment by ewpatton** [comment]
@wangiv2 That looks right. Did you get prompted for storage permissions when the app started? If not, does everything work if you go to Settings>Applications and then turn the permission on manually?

**Comment by dennishhwu** [comment]
@wangiv2 
Hello, I recently found the same issue, is it solved with any solution ?

**Comment by JanusChoi** [comment]
> @wangiv2 That looks right. Did you get prompted for storage permissions when the app started? If not, does everything work if you go to Settings>Applications and then turn the permission on manually?

Same issue. I already set the permission of AI2 companion Allow to access storage...

**Comment by ewpatton** [comment]
I'm closing this for now as a potential fix is part of companion 2.65. If the issue persists we can revisit it.
