### ISSUE TITLE
Survey on build server callback url issue

### ISSUE THREAD

**Issue by jerry73204** [mit-cml/appinventor-sources#1626]
Current implementation assumes [hard-coded callback url](https://github.com/mit-cml/appinventor-sources/blob/c51e829a3e9b62ab14c8cf0e91a203b211a13640/appinventor/appengine/src/com/google/appinventor/server/project/youngandroid/YoungAndroidProjectService.java#L831) for build server under development env. I haven't seen a _canonical_ way to solve this in GAE. I consider it a bad pattern, and want to deploy AI2 with ease. Hence, here maybe a place to discuss and I list some solutions here.

We could make it configurable in `appengine-web.xml`, the easiest way at least. For example:
```xml
<property name="buildserver.callback.host" value="my.domein:8080" />
```

Another direction is using alternative asynchronous protocol. Opposed to initiating a callback from buildserver, we may consider server-sent events (sse) or websockets. The advantage is that it reuses connections and avoid url issue. IMHO, I prefer websocket over SSE based on these findings:

- Out-of-box SSE implementations require Java 1.8 due to necessary lambdas in JAX-RS 2. There's a long way to upgrade AI2 from 1.7. For websocket, we have [Tyrus](https://tyrus-project.github.io/) and [Java-Websocket](http://tootallnate.github.io/Java-WebSocket/) for 1.7.
- Websocket can transfer binary data, while SSE cannot. With SSE, we can only base64-encode with performance penalty or initiate another connection.

**Comment by ewpatton** [comment]
@jerry73204 The likely bigger issue here is that you are trying to use the dev server as a production server. That's not really the intended use of the dev server and is probably going to cause more problems than it will solve. Also, in the case of GAE, frontend operations are limited to 60 seconds, so SSE or WebSockets won't work if a build takes longer than that.

FYI you can specify a callback URL already to override the appengine-provided default. The property is appengine.host in appengine-web.xml.

**Comment by jerry73204** [comment]
It's good to have the flag that I didn't notice. I'm working on an alternative build of App Inventor 2 Ultimate. That's why these issues become my headache. This thread can be closed. Thanks.
