### ISSUE TITLE
Getting error java returned 1

### ISSUE THREAD

**Issue by mejvi91246** [mit-cml/appinventor-sources#1629]
Others have had similar issues but not identical.  I am getting the below log when attempting to compile - any help would be greatly appreciated...

PlayApp:
     [java] Mar 24, 2019 9:13:33 PM com.google.appinventor.buildserver.ProjectBuilder build
     [java] INFO: temporary project root: C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\android.keystore from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\assets\AI2Companion-Icon.png from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\assets\Instructions.png from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\assets\connectwCode.png from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\assets\connectwQR.png from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\assets\mooning.png from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\assets\splash.html from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\src\edu\mit\appinventor\aicompanion3\Screen1.bky from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\src\edu\mit\appinventor\aicompanion3\Screen1.scm from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\src\edu\mit\appinventor\aicompanion3\Screen1.yail from input zip
     [java] Mar 24, 2019 9:13:34 PM com.google.appinventor.buildserver.ProjectBuilder extractProjectFiles
     [java] INFO: extracting C:\Users\Rob\AppData\Local\Temp\1553480013981_0.9611548065801465-0\youngandroidproject\project.properties from input zip
     [java] java.lang.IllegalArgumentException: Unable to parse file - cannot locate beginning of $JSON section
     [java] 	at com.google.appinventor.buildserver.FormPropertiesAnalyzer.parseSourceFile(FormPropertiesAnalyzer.java:62)
     [java] 	at com.google.appinventor.buildserver.FormPropertiesAnalyzer.getComponentBlocksFromSchemeFile(FormPropertiesAnalyzer.java:123)
     [java] 	at com.google.appinventor.buildserver.ProjectBuilder.getComponentBlocks(ProjectBuilder.java:279)
     [java] 	at com.google.appinventor.buildserver.ProjectBuilder.build(ProjectBuilder.java:155)
     [java] 	at com.google.appinventor.buildserver.Main.main(Main.java:82)

BUILD FAILED
C:\Users\Rob\appinventor-sources\appinventor\build.xml:21: The following error occurred while executing this line:
C:\Users\Rob\appinventor-sources\appinventor\buildserver\build.xml:180: Java returned: 1

**Comment by josmas** [comment]
Please discuss this type of issues in the forum. It seems to be the same issues as other people are reporting on windows _Unable to parse file - cannot locate beginning of $JSON section_.

Closing this now. If you need help, please use the forum.

**Comment by mejvi91246** [comment]
Thank you!  I am new to git hub and appreciate the help.  I did go to the forum and tried to enter the search string below but got no matches – any advice on what I am doing wrong??

Thanks again,
Rob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by josmas** [comment]
https://groups.google.com/forum/#!searchin/app-inventor-open-source-dev/cannot$20locate$20beginning$20of$20$24JSON$20section%7Csort:date

**Comment by mejvi91246** [comment]
Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
