### ISSUE TITLE
MockSwitch does not respond correctly to font size changes

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1630]
Per @PeterMathijssen: If one changes the font size of the text with the switch in the designer, the switch graphic won't vertically align. Instead, after enabling the switch the SVG will be resized to match the height of the font. On the device, the correct behavior occurs and the switch is vertically aligned and its size doesn't change.

Note that I'm putting this in the milestone but it's low risk so if it needs to slip due to other issues that is fine.

**Comment by ewpatton** [comment]
[Animated GIF demonstrating the issue](https://www.google.com/url?q=https://drive.google.com/file/d/1Qben4VdiqFbPMlvpGvRGdruErgP4dZGO/view?usp%3Dsharing&sa=D&ust=1553424546429000&usg=AFQjCNHbtgVaWvFb0VIDFv4k9QL_vhFtrQ)

**Comment by SusanRatiLane** [comment]
Resolved by #1631
