### ISSUE TITLE
API level

### ISSUE THREAD

**Issue by DigitalCoin1** [mit-cml/appinventor-sources#1635]
I'm trying to post my app to the Google Play Store, but I get the following error:

> Upload failed
> Currently your API's desired API level is 7. However, this level must be at least 26 for the app to use the latest APIs, which feature security and performance optimizations. Change the desired API level of your app to at least 26.

I'm using version 4.6 of the AI2U

**Comment by josmas** [comment]
Hi there, you are going to have to ask for help to the AI2U maintainers. That distribution is built from these same sources, but we have nothing to do with it. Closing this now. Best!
