### ISSUE TITLE
Error While Making Component

### ISSUE THREAD

**Issue by aryanrauniking** [mit-cml/appinventor-sources#1653]
Whenever I Add Any Component Then About 75% Complete To Build AI Play App And Get Error java.lang.NullPointer Expectation Why Is It So?
DOES IT HAS ANY SOLUTION TO STOP Null Pointer Expecatation

**Comment by ewpatton** [comment]
It's unclear that this is an issue with the sources but is rather how you're coding your component. The issue would be better discussed on the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).
