### ISSUE TITLE
Texting.SendMessage opens texting app

### ISSUE THREAD

**Issue by ellenspertus** [mit-cml/appinventor-sources#1658]
When the attached app runs Texting.SendMessage, it opens one of my separate texting apps, rather than sending it quietly using internal App Inventor libraries. This happened while using the AI2 Companion 2.51a on a Pixel 2 running Android version 9 (April 5, 2019). Please let me know what other information would be helpful.

[MillsRaffle.aia.zip](https://github.com/mit-cml/appinventor-sources/files/3076586/MillsRaffle.aia.zip)

**Comment by ankritisachan** [comment]
Hi. Just confirming, do you want your app to  send messages without opening default messaging app of your phone? 
There is this method, Texting.SendMessageDirect() which sends message immediately without opening any other messaging app.

**Comment by ellenspertus** [comment]
> Just confirming, do you want your app to send messages without opening default messaging app of your phone?

Yes.

> There is this method, Texting.SendMessageDirect() which sends message immediately without opening any other messaging app.

I had not realized the behavior of the original method had changed. Thank you for letting me know what to use in the future.

**Comment by ankritisachan** [comment]
No worries. Both these methods(Texting.SendMessage() and Texting.SendMessageDirect()) are available for use depending upon developers' requirements.

**Comment by ewpatton** [comment]
Note that the reason for this change is because of Google Play policy changes with respect to texting and phone call permissions. We were not allowed to keep the permissions needed for the old behavior in the companion app distributed through the Play Store. If you want to test the functionality you will need to install the version from AI2 under Help>Companion Information. The version is 2.51au.

**Comment by ankritisachan** [comment]
@ewpatton, Okay. I just checked version history regarding changes done in Texting so far. Thanks for the information.

**Comment by ankritisachan** [comment]
@ewpatton Shouldn't we close this issue or anything needs to be done here?
