### ISSUE TITLE
Investigate warning/error stepper with collapsed blocks

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1678]
From a beta tester of nb176:

> Clicking on the right set of up or down arrows does not show blocks that have errors. Instead it clears the blocks screen. I have 33 errors in my app but I can't find them. Why can't we add a "Show Errors" button?

**Comment by BeksOmega** [comment]
@SusanRatiLane If I could add the ability to open up the collapsed blocks so you could see the warning, would you be interested in a PR? Or is this a low-priority thing?

Note that atm I'm not sure that I could get this working in a way that isn't horribly messy haha. I'd have to investigate further.

**Comment by SusanRatiLane** [comment]
@BeksOmega I think this would be very useful. If you want to investigate, you have my blessing.
