### ISSUE TITLE
Dropdown menu designer screen size doesn't show when set to fixed.

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#1682]
I noticed that the dropdown for switching the designer screen size to allow for more size options only appears when the screensize is set to responsive. When it is set to fixed there is no dropdown menu.

**Comment by conorshipp** [comment]
This is intentional as apps in Fixed mode are created at a fixed resolution which isn't designed to be scaled to larger screen sizes.

You may also remember how the tablet preview checkbox could only be activated when responsive sizing was enabled.

**Comment by PeterMathijssen** [comment]
I shouldn't post issues early in the morning when waking up. ;-)

**Comment by ewpatton** [comment]
@PeterMathijssen Per your post on the dev group, I've updated the release notes to include that this is only available when Screen1's Sizing property is Responsive.

In the future we could consider making this option available in Fixed mode and playing with the CSS zoom property to mimic what happens on the device w.r.t. scaling.
