### ISSUE TITLE
Investigate upgrade issues with new Windows emulator

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1685]
Steve reports that the new emulator package for Windows does not upgrade correctly with the latest release. Need to test the out-of-date upgrade path via App Inventor as well as dragging the latest APK into the emulator to upgrade.

**Comment by ewpatton** [comment]
So the issue in this particular case was that the APK file Steve attempted to load was the version with the WebRTC binaries. We only include armv7, arm64, and x86_64, but the emulator uses an x86 image. The APK was being rejected due to the fact that there wasn't a compatible shared library for the CPU architecture.

We should reenable the option to upgrade the companion for the emulator to allow users to upgrade their companion version if they want the newest features but it isn't old enough to trigger an upgrade.

**Comment by ANUKULJHA1506** [comment]
can i work on this issue

**Comment by ewpatton** [comment]
Closing this for now as it is superseded by the new emulator.
