### ISSUE TITLE
Spanish translation shows German text for some untranslated strings

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1687]

**Comment by SusanRatiLane** [comment]
OK, this is perplexing. The German translation had trouble with some strings being in Spanish, and they fixed it. So now some strings show up in German on the Spanish translation?

Do we have a specific string? I haven't looked yet.

**Comment by ewpatton** [comment]
I'm pretty sure I know what the problem is and I should have a fix shortly.
