### ISSUE TITLE
Update emulator to Gingerbread

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#170]
@afmckinney 
When we push new setup packages, update the emulator, probably to Gingerbread.

**Comment by halatmit** [comment]
@afmckinney Was this issue fixed?   If not, are we still planning to fix it, and can you do it?

**Comment by halatmit** [comment]
@afmckinney Has this been fixed?

**Comment by ewpatton** [comment]
We now have a script to produce an emulator package for a given Android version, which has been used for creating the Windows and macOS emulator packages. The latest release uses Android 11 (SDK 30).
