### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by mengds2016** [mit-cml/appinventor-sources#1710]
I upgraded the latest source code and failed to compile. The results are as follows:
[java] May 22, 2019 6:58:30 上午 com.google.appinventor.buildserver.Compiler writeAndroidManifest
     [java] Info: VName: 2.52
     [java] May 22, 2019 6:58:35 上午 com.google.appinventor.buildserver.Execution execute
     [java] Info: ____Executing /tmp/aapt4685872592385425715 package -v -f -M /tmp/1558479508316_0.17385631690465164-0/youngandroidproject/../build/AndroidManifest.xml -S /tmp/1558479508316_0.17385631690465164-0/youngandroidproject/../build/intermediates/res/merged -A /tmp/1558479508316_0.17385631690465164-0/youngandroidproject/../build/assets -I /tmp/android2687385293882325577.jar -F /tmp/1558479508316_0.17385631690465164-0/youngandroidproject/../build/deploy/MIT AI2 Companion.ap_ -m -J /tmp/1558479508316_0.17385631690465164-0/youngandroidproject/../build/generated/src --custom-package edu.mit.appinventor.aicompanion3 --output-text-symbols /tmp/1558479508316_0.17385631690465164-0/youngandroidproject/../build/generated/symbols --no-version-vectors
     [java] /tmp/aapt4685872592385425715: 3: /tmp/aapt4685872592385425715: Syntax error: Unterminated quoted string
     [java]May 22, 2019 6:58:36 上午 com.google.appinventor.buildserver.Compiler runAaptPackage
     [java] Warn: YAIL compiler - AAPT execution failed.

BUILD FAILED
/home/me/appinventor-sourcesold/appinventor/build.xml:21: The following error occurred while executing this line:
/home/me/appinventor-sourcesold/appinventor/buildserver/build.xml:188: Java returned: 1

See the previous discussion: 32 bit compatibility is required, but the system I use: Ubuntu 14.04 32 bit, has been used very well before the upgrade. After experimentation, the problem appears after upgrading Android API 26, please help!

**Comment by ewpatton** [comment]
This is because we upgraded to a new version of aapt and that version is 64-bit. You should be able to replace it with a 32-bit version from the Android SDK if you are limited to a 32-bit architecture.

**Comment by mengds2016** [comment]
Thank you! libc++.so replace?Does this mean that the basic installation environment is 64bit?

**Comment by ewpatton** [comment]
@mengds2016 If you install the Android SDK for your platform, you can copy the aapt from the build tools in the SDK over the aapt in lib/android/tools/linux/aapt to have the 32-bit support again. However, I wouldn't count on having 32-bit support for an extended period of time so you should consider upgrading to a 64-bit architecture in the future.

**Comment by ewpatton** [comment]
In the future, please ask build system questions on the [App Inventor Open Source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).

**Comment by henry5001** [comment]
Sorry, I can't access [App Inventor Open Source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).
I tried to compile in [Termux](https://github.com/termux/termux-app)(arm architecture), but I got the following question, whether the arm architecture is not supported?
So I can currently only access the local 8888 port service on my Android phone and export aia files, but I can't package the APK
```bash
     [java] [CreateManifest] INFO: Writing screen 'edu.mit.appinventor.aicompanion3.Screen1'
     [java] [CreateManifest] Task succeeded in 0.038 seconds
     [java] [AttachNativeLibs] Starting Task
     [java] [AttachNativeLibs] Task succeeded in 0.27 seconds
     [java] [AttachAarLibs] Starting Task
     [java] [AttachAarLibs] Task succeeded in 3.768 seconds
     [java] [AttachCompAssets] Starting Task
     [java] [AttachCompAssets] Task succeeded in 0.049 seconds
     [java] [MergeResources] Starting Task
     [java] [MergeResources] Task succeeded in 4.669 seconds
     [java] [SetupLibs] Starting Task
     [java] [SetupLibs] Task succeeded in 0.004 seconds
     [java] [RunAapt] Starting Task
     [java] [RunAapt] ERROR: Error running AAPT
     [java] [RunAapt] Task errored in 0.267 seconds
     [java] Oct 08, 2023 1:20:30 PM com.google.appinventor.buildserver.util.Execution execute
     [java] INFO: ____Executing /tmp/aapt5872305410813437323 package -v -f -M /tmp/1696771217913_0.014525809870728934-0/youngandroidproject/../build/AndroidManifest.xml -S /tmp/1696771217913_0.014525809870728934-0/youngandroidproject/../build/intermediates/res/merged -A /tmp/1696771217913_0.014525809870728934-0/youngandroidproject/../build/assets -I /tmp/android2862322336661920433.jar -F /tmp/1696771217913_0.014525809870728934-0/youngandroidproject/../build/deploy/MIT AI2 Companion._ap -m -J /tmp/1696771217913_0.014525809870728934-0/youngandroidproject/../build/generated/src --custom-package edu.mit.appinventor.aicompanion3 --output-text-symbols /tmp/1696771217913_0.014525809870728934-0/youngandroidproject/../build/generated/symbols --no-version-vectors
     [java] Oct 08, 2023 1:20:30 PM com.google.appinventor.buildserver.util.Execution execute
     [java] WARNING: ____Execution failure: 
     [java] java.io.IOException: Cannot run program "/tmp/aapt5872305410813437323": error=2, No such file or directory
     [java]     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
     [java]     at java.lang.Runtime.exec(Runtime.java:593)
     [java]     at com.google.appinventor.buildserver.util.Execution.execute(Execution.java:111)
     [java]     at com.google.appinventor.buildserver.tasks.android.RunAapt.execute(RunAapt.java:75)
     [java]     at com.google.appinventor.buildserver.tasks.android.RunAapt.execute(RunAapt.java:25)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:498)
     [java]     at com.google.appinventor.buildserver.Compiler.call(Compiler.java:169)
     [java]     at com.google.appinventor.buildserver.Compiler.call(Compiler.java:33)
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [java]     at java.lang.Thread.run(Thread.java:750)
     [java] Caused by: java.io.IOException: error=2, No such file or directory
     [java]     at java.lang.UNIXProcess.forkAndExec(Native Method)
     [java]     at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
     [java]     at java.lang.ProcessImpl.start(ProcessImpl.java:134)
     [java]     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
     [java]     ... 14 more
     [java] 

BUILD FAILED
/root/IdeaProjects/appinventor-sources/appinventor/build.xml:23: The following error occurred while executing this line:
/root/IdeaProjects/appinventor-sources/appinventor/buildserver/build.xml:199: Java returned: 1

```

**Comment by josmas** [comment]
The problem is that aapt is not available.

There are a few projects that provide binaries such as
https://github.com/rendiix/termux-aapt but they might not be very up to
date.

I haven't tried any of those, but if they work for you, do let us know.

**Comment by ewpatton** [comment]
@henry5001 We include x86-64 binaries by default for all platforms under `lib/android/tools`. You will need to replace the aapt and other executables with their ARM versions from the Android SDK if you want to build on an ARM powered device.

**Comment by henry5001** [comment]
Thanks to the replies of the above two, I replaced [termux-aapt](https://github.com/rendiix/termux-aapt) does not work, I don't know anything about compilation, it seems that these have to be replaced with the ARM version, and I need some time to learn to compile.
Because I installed Debian in termux.
```
appinventor-sources/appinventor/lib/android/tools/linux/aapt
appinventor-sources/appinventor/lib/android/tools/linux/aapt2
appinventor-sources/appinventor/lib/android/tools/linux/lib64/libc++.so
appinventor-sources/appinventor/lib/android/tools/linux/zipalign
```

**Comment by ewpatton** [comment]
@henry5001 That's about the gist of it. We have previously deployed a full App Inventor stack on a Raspberry Pi this way.
