### ISSUE TITLE
Fix PhoneCallEnded regression

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1719]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/s3eV2jK0eaQ/7rk0lo5cBAAJ): PhoneCallEnded no longer works due to how conditional permissions work. We need to also check for READ_PHONE_STATE.

**Comment by bartmathijssen** [comment]
Closed via 5a74fe2

**Comment by ewpatton** [comment]
Closed via 5a74fe2
