### ISSUE TITLE
How can I get a database dump?

### ISSUE THREAD

**Issue by eugene-haas** [mit-cml/appinventor-sources#1722]
There is an error in the app inventory we manually installed,
I installed a new app-inventor on my docker.

Installation is referenced in README.md.
There is no manual database configuration.

How do I replicate the old system's database (user and project data) to the new system?

**Comment by jisqyv** [comment]
@eugene-haas You will have to say more about what you are doing for us to give you any help. Did you deploy the App Engine development server in a Docker container?

**Comment by eugene-haas** [comment]
Sorry for not giving you much information.

I have deployed the App Engine development server in a docker container.
The app inventor in the docker container works well.
Here is my app engine installation process.

apt-get -y update && \
export CLOUD_SDK_REPO = "cloud-sdk - $ (lsb_release -c -s)" && \
echo "deb http://packages.cloud.google.com/apt $ CLOUD_SDK_REPO main" \
| tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
curl -SL https://packages.cloud.google.com/apt/doc/apt-key.gpg \
| apt-key add - && \
apt-get -y update && apt-get install -y \
google-cloud-sdk \
google-cloud-sdk-app-engine-java

export PATH = $ PATH: / usr / local / ant / bin; / usr / lib / google-cloud-sdk / bin

App Inventor Run command.
nohup ant RunLocalBuildServer> /usr/local/appinventor-sources/appinventor/log/buildserver-log.out &
nohup java_dev_appserver.sh --port = 8888 --adress = 0.0.0.0 / usr / local / appinventor-sources / appinventor / appengine / build / war / usr / local / appinventor-sources / appinventor / log / mainverver-log. out &

I want to know how to dump my member data and put it in.
What other information do you need?

**Comment by eugene-haas** [comment]
I explained the installation process, but I can not get an answer, so I close the issue.
