### ISSUE TITLE
Prevent AIA files from being uploaded to projects as media assets

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#173]
It is possible for beginners who are trying to load a template AIA source file to upload them into an existing project as media assets. Beginners may be susceptible to this mistake if they had recently learned how to upload media assets, which is commonly a 1st or 2nd session event.

This mistake was observed during a teacher training.

I propose a feature that checks media uploads. If the user attempts to upload the AIA, refuse, and guide the user towards a web page describing how to use AIA files.

**Comment by halatmit** [comment]
@jisqyv 
I can put this check in, but I don't know where to put it.   Somewhere in FileUploadWizard??

**Comment by josmas** [comment]
@jisqyv have just removed you from this one; marking as `help needed` for easy fixes to get started with the sources.

**Comment by varunm22** [comment]
Hi, my name is Varun! I'm a new UROP student with the App Inventor team. 
@bxie assigned this to me as a starter project
I'll prevent AIA files from being uploaded as media assets.

**Comment by wadleo** [comment]
I have added a appropriate condition to check if the file being uploaded is an aia file in the FileUploadWizard class. I have also added an appropriate error message in OdeMessages class and will soon sent a pull request, thanks.

**Comment by marksherman** [comment]
I'll check it out this week, @wadleo (though I have no pull power, it seems right that I give it a test!)

**Comment by wadleo** [comment]
thanks @marksherman, waiting for your reply.

**Comment by bxie** [comment]
@wadleo : this may be redundant work. 
@varunm22 has been working on this over the past month and his work is almost ready to be merged (currently working on some UI fixes). 

@varunm22 please confirm

**Comment by wadleo** [comment]
Hello @bxie,
sorry i didn't realise he is still working on these looking at the dates above and please can provide a link to his work, thanks for the info

**Comment by varunm22** [comment]
Hi @wadleo my fixes are on the bytesize branch of my fork at https://github.com/varunm22/appinventor-sources/tree/bytesize. In addition to adding the .aia fix, I've replaced the window.alerts that show up during file upload errors with dialog boxes for greater consistency.

**Comment by wadleo** [comment]
Hi @varunm22, thanks for the feedback.

**Comment by varunm22** [comment]
Hi @wadleo, sorry for the confusion, and please let me know if you have any more questions!

**Comment by ewpatton** [comment]
Closed by #747
