### ISSUE TITLE
Supermarket in Mit app inventor

### ISSUE THREAD

**Issue by rodrigo123-cmyk** [mit-cml/appinventor-sources#1737]
432/5000
I'm trying to make a project that consists of a supermarket that sells food, clothes and appliances, where customers register and buy their products, and ask them to take them home.
But I'm having some difficulties because this is a language I'm still learning, which is the MIT app inventor, so I wanted to ask if anyone could help me or tell me if there is any site that can help me please.
Thank you.

**Comment by NmdOfficial** [comment]
Ask your question at forum.
Here is the wrong place

**Comment by rodrigo123-cmyk** [comment]
Thank you.

**Comment by moliata** [comment]
@rodrigo123-cmyk it would be great, if you could close the issue.
