### ISSUE TITLE
companion on Chromebook

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#1740]
On my Acer Chromebook the companion of App Inventor looks not good. Fonts and buttons are much to big. 

I compared the companions from the four biggest builders and added them here for reference. Two of them work as it should, two of them show the same effect of large fonts and buttons. 

![Screenshot 2019-07-12 at 15 14 35](https://user-images.githubusercontent.com/32273650/61131036-6bbd0c00-a4b8-11e9-87a3-c3dbe20c9a82.png)

Maybe it has to do with the screen being set to fixed instead of responsive.

**Comment by ewpatton** [comment]
This is an issue with the scaling factor computed by Fixed sizing mode. It also happens with any project that uses fixed sizing mode, and the easiest fix is to just put an app into responsive sizing. I believe that the fixed mode computes based on the screen width, not the window width, and so for apps that aren’t full screen on the chromebook the calculation is off. Try making a simple project like Hello Purr with the different systems and see if toggling the Sizing property has any effect. My guess is that Thunkable and Kodular have changed the companion to use responsive sizing so it looks better on tablets but it is only a guess.

**Comment by PeterMathijssen** [comment]
it has definitely to do with the fixed and responsive setting. 

This is responsive
![Screenshot 2019-07-12 at 17 16 50](https://user-images.githubusercontent.com/32273650/61139146-13423a80-a4c9-11e9-873f-5c2e5fc5b956.png)

This is fixed size. But it looks much worse then my fixed size on my phone. So the resolution of the companion app on the Chromebook is lower in fixed size then on my phone. 
![Screenshot 2019-07-12 at 17 16 28](https://user-images.githubusercontent.com/32273650/61139159-1b01df00-a4c9-11e9-84c5-b8f2d4e74fc2.png)

**Comment by PeterMathijssen** [comment]
Tested it with Kodular and it has the same exact problem as the App Inventor companion when run in Fixed size.

**Comment by wxbit** [comment]
@PeterMathijssen Would you mind testing this for me? https://app.wxbit.com/AI2Companion3.apk

**Comment by PeterMathijssen** [comment]
![image](https://user-images.githubusercontent.com/32273650/61152312-5f50a780-a4e8-11e9-8b52-d9e9c388a96b.png)
I got a bunch of chinese, japanese text but was able to get this image.

**Comment by wxbit** [comment]
@PeterMathijssen Thanks, is Chinese.I don't know why the buttons uses background image,I have changed them to text.

**Comment by ewpatton** [comment]
Resolved by #1993
