### ISSUE TITLE
Deleting MockContainer does not delete children components fully

### ISSUE THREAD

**Issue by elatoskinas** [mit-cml/appinventor-sources#1743]
**Issue**
When deleting a MockContainer that has children components attached to it (in the Designer), the children disappear from the hierarchy. However, they are not entirely removed (neither onRemoved() nor delete() is invoked)

**Implications of the issue**
When adding new features, this behavior might not exactly be expected. For instance, a child component might be listening to certain events, however, upon removal of the parent, the child component is still listening to those events (since it is not completely removed), which might cause issues and undefined behavior.

**Possible solution**
Override the MockContainer's onDelete method to iterate all the children components and call delete() on them before deleting the parent component entirely

**Example scenario**
Consider that the user adds a Map component, and then attaches a few Marker components. Upon deleting the Marker components individually, the onRemoved and delete() methods get invoked. However, when deleting the Map with the Marker components attached, neither the onRemoved nor delete methods get invoked on each individual Marker components, causing them to still remain as invisible components and react to events.

**Comment by ewpatton** [comment]
@lightingft What's the easiest way to confirm that the deleted mock components are still listening (e.g., how did you discover this initially)?

**Comment by lightingft** [comment]
@ewpatton I discovered this while working with Property Selectors. A relatively simple way to verify the behavior is through the following example:

1.In the YoungAndroidComponentSelector, add a Log message in the onComponentRenamed method under the if (oldName.equals(currentValue)) block.
2.In Designer, create a Map component, attach a LocationSensor to it, delete the Map and rename the LocationSensor. The log message should not be triggered.
3.Now, create any Layout (e.g. HorizontalArrangement), and place a Map component there.
4.Attach a LocationSensor component to the Map.
5.Remove the Layout object (but not the Map individually)
6.Rename the LocationSensor component
7.See the debug log. The log message should be triggered.

This might be more of an issue with how the component selectors work, but nevertheless, some actions are not performed on the children component (in this case, the properties have not been wiped, and the LocationSensor still remained attached to the map)

**Comment by lightingft** [comment]
@ewpatton Provided that you would agree that this is indeed an issue, I could work on a fix for this.

**Comment by ewpatton** [comment]
@lightingft Yes, I was able to confirm that this is a bug. If you have time to work on it, please do.
