### ISSUE TITLE
checkbox.setChecked is deprecated

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#175]
in file: BooleanPropertyEditor.java

This file defines the boolean checkbox property (such as visibility or enabled) in the designer palette.

It uses checkbox.setChecked() and checkbox.isChecked() which are deprecated.

Full file location: ./appengine/src/com/google/appinventor/client/widgets/properties/BooleanPropertyEditor.java

**Comment by josmas** [comment]
closing issues; merged #177
