### ISSUE TITLE
Component search filter robustness

### ISSUE THREAD

**Issue by conorshipp** [mit-cml/appinventor-sources#1750]
The component search filter isn't as robust as one might expect. For example, when searching for "textbox", you would probably expect to see both the `TextBox` component as well as the `PasswordTextBox` component, but only the former is present. Another example could be searching for the "picker" components. You might expect to see the different picker components (`DatePicker`, `TimePicker`, `ListPicker`, `ContactPicker`, `EmailPicker`, etc.) but you don't. The same can be said about arrangements.

**Comment by ewpatton** [comment]
This is true. We implemented the search using a prefix trie, so while it is very fast it only allows searching components from the beginning of the name. How is the performance if you swap out the trie data structure with iterating over an array list? If it's comparable and you want to submit a patch, please do so.

**Comment by ewpatton** [comment]
@conorshipp Did you or the rest of @mit-cml/kodular do any work on this? I'd be interested in knowing what you've found out.

**Comment by conorshipp** [comment]
No, not yet. I've asked @Vishwas-Adiga if it's possible to port our search function over to you as we have a different implementation.

**Comment by Vishwas-Adiga** [comment]
Kodular's search function iterates through all the component names and checks if the search input is a substring of any component's translated name.

This method ensures all components are listed, even if only a part of their names are entered. However, it can block the UI for a second or so, which is especially noticeable when there are lots of components. To prevent excessive blocking of the UI when short search terms are input (like only one letter that is present in most component names), the search automatically stops when 10 search results are shown.

I've attached the code below.
If you think momentarily blocking the UI for a more extensive search is a compromise that can be made, then I would be more than willing to make a PR with the changes.

`public void searchComponentByName(String componentName) {
    searchPanel.clear();
    int currentComponent = 0;
    if(componentName != "") {
        //Search for the component name in the set of all
        for (String component : COMPONENT_DATABASE.getComponentNames()) {
            if(ComponentsTranslation.
                 getComponentName(component).
                 toLowerCase().
                 contains(componentName.toLowerCase())) {
                this.addComponent(component, true);
                currentComponent++;
                if(currentComponent >= 10) break;
            }
        }
    }
}`

**Comment by ewpatton** [comment]
@Vishwas-Adiga @conorshipp Take a look at 
536a989
