### ISSUE TITLE
Should use SdkLevel.java to check Android version

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#1756]
https://github.com/mit-cml/appinventor-sources/blob/2a7110ba62cf0cbe649dab4d78495b6463e6aae5/appinventor/components/src/com/google/appinventor/components/runtime/ScaledFrameLayout.java#L61

To check Android version, you should use [`SdkLevel.java`](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/util/SdkLevel.java)

**Comment by ewpatton** [comment]
#1780 removed this check entirely, so I'm going to close this for now.
