### ISSUE TITLE
"Unable to load SVG from assets" on map longPressAtPoint

### ISSUE THREAD

**Issue by Piruzzolo** [mit-cml/appinventor-sources#1761]
I created a callback when longPress on the map, to create a marker. There appears a msgBox instead, with the message above.

The only instance in the code is here
https://github.com/mit-cml/appinventor-sources/blob/0d3364ee790ba0c8887b198cfa7b033359ce5869/appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java#L942

Attached, the project file.

The problem shows up in Android P, Huawei 9 Lite, EMUI 9.1

[proj (2).zip](https://github.com/mit-cml/appinventor-sources/files/3464125/proj.2.zip)

**Comment by ewpatton** [comment]
Confirmed this through a separate test when working with one of the power users. Specifically, the issue occurs if an app without a marker is compiled and a runtime marker is created. The buildserver doesn't include the marker asset since it wasn't used at compile time.
