### ISSUE TITLE
Update README to use newer commands based on Google Cloud SDK instead of App Engine SDK

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1762]
We should update the relevant documentation to use the Google Cloud SDK now that Google has officially deprecated the Google App Engine SDK and appcfg.

**Comment by bartmathijssen** [comment]
I setup App Inventor on my local machine using the Google Cloud SDK. The only differences I could find is that you need to install the `app-engine-java` component and the command to run appinventor has changed to:
```
$ your-gcloud-SDK-folder/bin/java_dev_appserver.sh --port=8888 --address=0.0.0.0 appengine/build/war/
```

**Comment by halatmit** [comment]
Going along with this, we need to update
How to build App Inventor from the MIT sources
https://docs.google.com/document/d/1Xc9yt02x3BRoq5m1PJHBr81OOv69rEBy8LVG_84j9jc/edit#

And integrate this with 
Setting up an Appspot Instance to use Google Cloud Store (GCS)
https://docs.google.com/document/d/1JvexwXOQ4wW2Cccfyq3z83fXklP7Ob_1jPmMdxsv8WM/edit#
which also needs to be updated.
