### ISSUE TITLE
Procedure Parameters not shown in Call block

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#1763]
If you create a procedure with parameters, when you then open the blocks drawer the call block will not show parameters, nor will they appear when they are dragged out. To get the parameters to appear you need to click on the mutator wheel in the declaration. Then the parameters will appear.

This breakage is caused by the blocks toolkit change (I reverted that commit and the problem was resolved).

**Comment by ewpatton** [comment]
Closed via #1770
