### ISSUE TITLE
Fix Ball so the x- and y-coordinates are at the center

### ISSUE THREAD

**Issue by espertus** [mit-cml/appinventor-sources#1777]
For bad historical reasons, the X and Y properties of a Ball are not the coordinates of the center but of the upper left corner of the bounding box containing the Ball (a point that isn't even part of the circle). Users would expect the X and Y coordinates of a Ball to be its center.

**Comment by espertus** [comment]
I propose fixing this by adding a backwards compatibility flag. For existing programs, backwards compatibility would be enabled, and the behavior of Ball would stay the same.

If the backwards compatibility flag is false, the X and Y properties will represent the x- and y-coordinates of the center of the Ball.

I welcome suggestions of what to call the user-visible flag.

**Comment by halatmit** [comment]
We might want to fix this for image sprite also, and put the location of the sprite at the center of the sprite rectangle.  Better, we could make the location of the sprite be a settable property.   This change will be a little delicate, since it also affects sprite rotation and collision.

**Comment by espertus** [comment]
Sounds good. I suggest that ImageSprite be a separate issue and PR.

**Comment by halatmit** [comment]
I think it's fine to defer the image sprite upgrades to a later issue and PR.

**Comment by halatmit** [comment]
For the compatibility flag, how about
Ball origin at ball center. 
and
Ball origin at ball corner (deprecated).

**Comment by ewpatton** [comment]
For brevity, maybe `OriginAtCorner`?

**Comment by espertus** [comment]
How about `CoordsAtCorner`?

In any case, could an admin please assign this to me?

**Comment by halatmit** [comment]
OriginAtCorner ,  OriginAtCenter,  perhaps

 For scratch, you can set the this value and it's called origin.   It's
also the center of rotation.

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by espertus** [comment]
Thanks. +1 to consistency with Slack

I was planning to do it as a boolean, so we'd have to choose either `OriginAtCorner` or `OriginAtCenter`. The former might be better for future changes to ImageSprite.

**Comment by espertus** [comment]
Could one of you please assign this to me?

**Comment by ewpatton** [comment]
@espertus Done.

What if the property was a dropdown instead, called `Origin`, and had possible values of `Top Left Corner` and `Center`? Possibly I could imagine we might want to eventually add other options, at least for the other corners (if not arbitrary coordinate as origin as far as rotation is concerned).

**Comment by halatmit** [comment]
OriginAtCorner is OK.
But I think OriginAtCenter (boolean with default true) might be better.
At some point, we should more to a settable origin, like Scratch.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by halatmit** [comment]
It's assigned to you.
== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by halatmit** [comment]
I think having a dropdown is not the right place we want to go eventually.
In Scratch the origin is the costume origin, and the way it's set reflects
the costume design.
Making the origin one of the corners seems unnatural in most cases.
But we should keep top-left for legacy purposes.

How about implementing the ability to set the origin as an offset from the
center of the image rectangle?
== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by espertus** [comment]
> What if the property was a dropdown instead, called `Origin`, and had possible values of `Top Left Corner` and `Center`? Possibly I could imagine we might want to eventually add other options, at least for the other corners (if not arbitrary coordinate as origin as far as rotation is concerned).

Sounds good to me. Hal?

**Comment by halatmit** [comment]
Rather than the dropdown/select corner method for sprite center, I'd prefer
what Scratch does.
For Scratch, you can set the origin ("costume origin") as an offset from
the sprite geometric center.
That's useful because the "right" place for the origin will depend on the
shape and design of the sprite --
all the more so because the origin should also be the center of rotation
for the sprite.

So I'd prefer that we extend sprites to include x-offset and y-offset
properties that default to 0.

We might also include some way to easily put the origin at the upper left
so legacy compatibility.

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by espertus** [comment]
For this PR, I'll only make OriginAtCorner/OriginAtCenter show up for Balls, not ImageSprites, so there really are only two options. I don't want to repeat the same mistake of clumsily exposing to the user that Ball and ImageSprite have the same abstract superclass.

I'm cool with making it a boolean or a dropdown. Which would make it easier to communicate that one of the options is deprecated?

**Comment by halatmit** [comment]
I'd suggest making it a boolean.
== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by halatmit** [comment]
Thanks Ellen.
