### ISSUE TITLE
Add fontsize property to ListView

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#178]
This should be simple.  Look at ListView.ItemsToColoredText and include AbsoluteSizeSpan similar to ForegroundColorSpan.   Set dp flag to true. Or do we really want RelativeSizeSpan?

**Comment by josmas** [comment]
Is this fixed with https://github.com/mit-cml/appinventor-sources/commit/231a2b0d376f4239305872d66f5cdae32ff6cc6e ? Please close if that's the case (ignore the comment if it's not) cc/ @cooper-sloan @halatmit
