### ISSUE TITLE
useFront property of camera no longer works

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#180]
This property relied on an undocumented feature of the android camera system, so there was a well-known risk that it may stop working someday. That day came faster than anticipated.

It appears that the feature has been removed from nearly all androids, including older ones. My guess is a google play services update was pushed out that removed it, even to old 2.3 devices.

Leaving the useFront feature may cause more confusion than anything else. In current testing I, and some others on the forums, can't find a single remaining device where it works. 

What I do not know is the right way to remove it. There exist projects that use it, is there a mechanism to check projects on load to nudge the components to updated versions? I believe there is, I just don't know enough about it to complete this recommendation alone.

**Comment by josmas** [comment]
code to mark bad blocks has been around for quite a while: https://github.com/mit-cml/appinventor-sources/pull/112

**Comment by halatmit** [comment]
see pull request #335

**Comment by halatmit** [comment]
Usefront was undocumented in pr #652 
It's not clear how we can make this work, short of writing our own Camera app, rather than launching Google's.   we'll leave this unimplemented, and people will need to select the front camera manually, once Camera is launched.
