### ISSUE TITLE
Handle special cases of sin, cos, tan

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1816]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/0S9EnMQEzmk/yEK18T6KBAAJ): Passing known good values to sin, cos, and tan (e.g., 0 degrees, 90 degrees, etc) result in very small errors. This is likely due to converting degrees to radians and then passing those values into the corresponding trig functions. We should confirm that this is true and consider adding checks to handle these values known to have integral results.

**Comment by jsuyash1514** [comment]
@ewpatton I would like to work on this issue.

**Comment by ewpatton** [comment]
@jsuyash1514 Please take a look at runtime.scm under the buildserver module, and also look at the YailEvalTest.java file in the same module. The former is where the various block functions are defined and the latter is where the unit tests are located.

**Comment by ewpatton** [comment]
Fixed by #2004
