### ISSUE TITLE
Filter bar in listview is broken

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#182]
See this thread, and the comment from Taifun

https://groups.google.com/forum/#!topic/mitappinventortest/1K3FwCmgGSc

**Comment by josmas** [comment]
@kkashi01 @halatmit Hi guys, what's the state of this issue? Has it been merged?

**Comment by kkashi01** [comment]
@josmas ListView was not returning the correct index. That fix was put in and addressed in [1]. This made it behave the same way as ListPicker. However, there was a request that when FilterBar is used and data is filtered, keep the original indices. Neither ListPicker nor ListView has fix for this. 

[1]
https://github.com/mit-cml/appinventor-sources/pull/199

**Comment by josmas** [comment]
@kkashi01 I see that #199 is still open; has it not been merged/reviewed?
It looks like it might need rebasing if it hasn't been merged yet.

If the PR fixes the first issue, I would suggest reviewing/merging and closing both the PR and this issue, and to open a new issue with the new request. What you guys think? cc/ @halatmit @jisqyv

**Comment by kkashi01** [comment]
@josmas Looking at code base, seems like this has been merged in.
Gerrit: https://gerrit.appinventor.mit.edu/#/c/1350/

**Comment by josmas** [comment]
@kkashi01 is it this commit? https://github.com/mit-cml/appinventor-sources/commit/0db6ce014e3d816a503fc4f0fcbdb562c553af38

I am closing this guy now then. Feel free to reopen if that's not the case.

**Comment by halatmit** [comment]
I agree.  Please merge and close this, and then open a new issue for the
new request


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty
