### ISSUE TITLE
official support for wifi

### ISSUE THREAD

**Issue by aster94** [mit-cml/appinventor-sources#1845]
I know that there is an extension for wifi https://puravidaapps.com/wifi.php but since wifi nowadays is more* important that bluetooth why not officially support this working extension and bundle it in the Connectivity palette?

I am writing this mainly in the need of using a MCU with WiFi and I will control it with AI2. Since the  spread in the last years of these kind of boards (arduino, esp8266, esp32, ecc) I think this would be a good idea for the project

*in same user cases

**Comment by ewpatton** [comment]
Most of the boards in question use HTTP as the means of communicating with them once connected. We have the Web component to do so. If you have specific use cases, I suggest that you first raise them either in the [user forum](https://groups.google.com/forum/#!forum/mitappinventortest) or on the [open source dev list](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).

**Comment by aster94** [comment]
I completely agree that ai2 have the web component to communicate with these boards **after** they are connected, but how do we connect them?

I still think that a new user may be discouraged if he doesn't find the wifi module bundled inside the app at the same level of Bluetooth
