### ISSUE TITLE
add ability to see source from visual blocks

### ISSUE THREAD

**Issue by aster94** [mit-cml/appinventor-sources#1847]
I wasn't able to find a way to see the text generated by the visual blocks. Is it possible to do this? Would it be a good addition for the project?

I know i can use the aia file but I was thinking about an easier way to share block of codes (as text) between different projects.

**Comment by ewpatton** [comment]
We do not have a textual representation of the blocks code. Code generation creates code in a special language called YAIL, which is a Scheme, that doesn't exactly have a 1-1 correspondence with the original blocks language. If you'd like to see what it looks like, you can look in the developer tools in your browser while using the companion app. The YAIL code is logged to the console. However, we don't have a way to take arbitrary Scheme code and represent it as blocks, so the bidirectional nature of what you're asking isn't possible.

Some alternatives to using text are:
* Use the copy/paste feature of Blockly, which hooks into the platform-specific keystroke (Ctrl+C / Ctrl+V on Windows and Linux, Cmd+C / Cmd+V on macOS) to copy and paste code.
* Use the Backpack. The Backpack is a persistent per-user storage mechanism for blocks. You can place blocks into the backpack, switch projects (or reload your browser, etc.) and the blocks will be there to "paste" back into a project.
* Use the Download Blocks as PNG feature. This produces a PNG file with embedded Blockly descriptions. You can then drag and drop this file into another workspace.

**Comment by aster94** [comment]
Thanks a lot for the detailed answer, now is everything clear 😃 also I didn't know that the backpack was shared in all the project nor I knew that the png image could store the blocks.

Really wonderful tools! Thanks again
