### ISSUE TITLE
Add support for hexadecimal numbers without conversion

### ISSUE THREAD

**Issue by aster94** [mit-cml/appinventor-sources#1854]
can someone have a look at these blocks? I can't see any error

![blocks (1)](https://user-images.githubusercontent.com/21184718/65345659-10577a80-dbdb-11e9-8412-804b84c9aafc.png)

i get `0 - 0 - 0`

**Comment by ewpatton** [comment]
App Inventor doesn't include 0x as a prefix for hex. Of the blocks that you have, only the last one including the convert number block will do what you want, and only if you remove the `0x` prefix. Note that you'll need to use a text block instead because 'ff' is not a valid decimal number.

**Comment by ewpatton** [comment]
In the future, these types of inquiries should be directed to the [MIT App Inventor Forum](https://groups.google.com/forum/#!forum/mitappinventortest).

**Comment by aster94** [comment]
Yes, sorry, it would be nice if something like this was in the doc http://ai2.appinventor.mit.edu/reference/blocks/math.html#bitwise_and people who cames from C could have problems to make this block working
