### ISSUE TITLE
FieldFlydown is generating detached nodes

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#1865]
**Describe the bug**

FieldFlydown is calling createDom() multiple times, causing the generation of detached nodes.

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

There should only be one instance of the Flydown dom on the page.

**Steps to reproduce**

1. Grab a block that has field flydowns.
2. Show and hide the flydowns a few times.
3. Show the flydown a final time.
4. Inspect it in console.
5. Observe how there are multiple instances of the same dom.
![Flydown](https://user-images.githubusercontent.com/25440652/65820156-87dc6980-e1da-11e9-8434-047f47fdac49.png)

**Additional Information**
I believe the problem originates [here](https://github.com/mit-cml/appinventor-sources/blob/66b2a13ad0e5676bd9e9c4573484a57fa0525415/appinventor/blocklyeditor/src/field_flydown.js#L154).
Also see jsdoc [here](https://github.com/mit-cml/appinventor-sources/blob/66b2a13ad0e5676bd9e9c4573484a57fa0525415/appinventor/blocklyeditor/src/flydown.js#L46).

But I can't be sure.

**Comment by ewpatton** [comment]
@BeksOmega I believe your diagnosis is correct. The flydown should only call createDom once.
