### ISSUE TITLE
Facing Build Failed Issue ! 

### ISSUE THREAD

**Issue by kunalkool** [mit-cml/appinventor-sources#1870]
Hello Everyone , actually i am facing very strange issue when i did ant , an this the following issue
<code>
[java] WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(…) returned error code 5.
[java] Compiling module com.google.appinventor.YaClient
[java] Ignored 2 units with compilation errors in first pass.
[java] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[java] Exception in thread “main” java.lang.OutOfMemoryError: Java heap space
[java] at java.awt.image.DataBufferInt.(DataBufferInt.java:75)
[java] at java.awt.image.Raster.createPackedRaster(Raster.java:467)
[java] at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
[java] at java.awt.image.BufferedImage.(BufferedImage.java:333)
[java] at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:557)
[java] at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:541)
[java] at sun.java2d.loops.MaskBlit$General.MaskBlit(MaskBlit.java:189)
[java] at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Blit.java:204)
[java] at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
[java] at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
[java] at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
[java] at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
[java] at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
[java] at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
[java] at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3445)
[java] at com.google.gwt.resources.rg.ImageBundleBuilder.toPng(ImageBundleBuilder.java:546)
[java] at com.google.gwt.resources.rg.ImageResourceGenerator.reencodeToTempFile(ImageResourceGenerator.java:674)
[java] at com.google.gwt.resources.rg.ImageResourceGenerator.prepare(ImageResourceGenerator.java:587)
[java] at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.initAndPrepare(AbstractClientBundleGenerator.java:1015)
[java] at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.initAndPrepare(AbstractClientBundleGenerator.java:1041)
[java] at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.generateIncrementally(AbstractClientBundleGenerator.java:421)
[java] at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:739)
[java] at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
[java] at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
[java] at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
[java] at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
[java] at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
[java] at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
[java] at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
[java] at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
[java] at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
[java] at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
</code>
and terminal get stop at last line and it does not move forward .
I don’t why such a error is taking place , so how i can solve this ???
And the changes i have made that adding a Images on Dialogs boxes, i have checked 101 times , but no issue in that .
Regards,
Kunal

**Comment by conorshipp** [comment]
You already asked in the open source forum... Why are you posting here after you've already been given the solution?
Also, this isn't an issue with the App Inventor sources so this isn't the correct place to ask.

**Comment by ewpatton** [comment]
Agreed with @conorshipp. You've made modifications and so this doesn't qualify as an issue with our repo. Please continue the conversation on the open source group.
