### ISSUE TITLE
Add "Force Refresh Companion" menu item to "Connect"

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1920]
**Describe the desired feature**

Add a menu item to the Connect menu called Force Refresh Companion that will resend all of the YAIL for the screen.

**Give an example of how this feature would be used**

On rare occasions we might not detect that the screen needs to be updated. In this case, the developer can use this option to force resending the entire screen (versus editing a designer property or switching projects).

**Why doesn't the current App Inventor system address this use case?**

It can, but doing so uses a workaround rather than a blessed feature. It's possible we might break these workarounds in the future so a dedicated function would be preferred.

**Why is this feature beneficial to App Inventor's educational mission?**

In instances where the companion becomes out of sync with the editor, students and teachers can use this to get things back into sync. It would also be useful to include some sort of analytics when this happens in order to understand why it happened.

**Comment by ewpatton** [comment]
@mit-cml/cornell-cs-5152-students-fall-2019 @bartmathijssen One of you might want to take a look at this.

**Comment by kalsheikh** [comment]
Hey @ewpatton can you assign me to this? Also, can I get an idea of where I should look into for adding the menu item / the function for refreshing the companion app?

**Comment by ewpatton** [comment]
@kalsheikh The menus are constructed in [TopToolbar#createConnectMenu](https://github.com/mit-cml/appinventor-sources/blob/82d04c8a3f0361f5095233bb0067d21514de781e/appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java#L247) and an example of how to send the screen to the device is shown in [YaFormEditor#updatePhone](https://github.com/mit-cml/appinventor-sources/blob/82d04c8a3f0361f5095233bb0067d21514de781e/appinventor/appengine/src/com/google/appinventor/client/editor/youngandroid/YaFormEditor.java#L992). You'll want to add an entry to [OdeMessages.java](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java) for internationalization of the menu text.
