### ISSUE TITLE
Properties description issue

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#1931]
Related: 0e2a9adf42fb2aacf0acd27e08fb9a4657038f16 (#1825)

E.g.
![image](https://user-images.githubusercontent.com/22613139/70225276-ab4b0400-1789-11ea-92dc-f0c085e3d423.png)

**Comment by conorshipp** [comment]
This is already a known issue. It's fixed in #1911.

Also, I believe it was introduced in #1739 not #1825.

**Comment by ColinTree** [comment]
@conorshipp Thanks, I'll have a check

**Comment by ewpatton** [comment]
@ColinTree I think this has been resolved in our latest release. Can you confirm?

**Comment by ewpatton** [comment]
@ColinTree I'm going to close this for now. If you're still seeing the error, please reopen.
