### ISSUE TITLE
Include if-else and if-elseif-else mutations in blocks drawer

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1975]
**Describe the desired feature**

We should add if-else and if-elseif-else block mutations in the blocks drawer as using the mutator on the if block is not obvious. This is particular true of the if-else block because people often (wrongly) identify the if-then-else ternary block as the if-else block and wonder why it has a plug rather than statement notches.

**Give an example of how this feature would be used**

People could drag out if-else and if-elseif-else blocks without needing to use the mutator, making the branching more discoverable than it currently is.

**Why doesn't the current App Inventor system address this use case?**

The current system only includes the if block with mutator. Getting more complicated branch statements requires first understanding the mutator (which is not particularly intuitive).

**Why is this feature beneficial to App Inventor's educational mission?**

This feature makes mutated variations of the if block more readily accessible to new users without forcing a discussion of mutators onto the critical path when they're just getting started programming.

**Comment by shivanik6z** [comment]
Hi , I want to confirm if I got this right or not. Our motive is to replace current if-then block with mutator(which I am guessing is the settings sign on the block which helps in adding more branching statements) with a new block of "if-else" with mutator so people don't get confused when they wanna use if-else block and end up using if-then-else block which is wrong. If I got this right I would like to work on the issue.

**Comment by ewpatton** [comment]
@shivanik6z We are not replacing the existing block. The proposal is to add the additional mutations as options so that they don't have to be created by first discovering how mutators work. An example of how this is done already is the `lists_create_with` block, which has two variants--one without any sockets (create empty list) and one with two sockets. This is done by an entry in [blocklyeditor/src/drawer.js#L510](https://github.com/mit-cml/appinventor-sources/blob/7ee36cdc46976aebd4e3475bc6b4c2fa687baa19/appinventor/blocklyeditor/src/drawer.js#L510). We'd want to add a similar entry for `controls_if` that provides the 3 variations described above (if, if-else, if-elseif-else).

**Comment by conorshipp** [comment]
So I just took a quick look at this and it seems to be quite straightforward. @ewpatton is this what you're expecting it to look like?
![image](https://user-images.githubusercontent.com/25845449/72450683-b21a5d00-37b2-11ea-90a1-6e9a5aeafc52.png)

@shivanik6z let me know if you still want to work on this issue so I know whether or not to commit my changes.

**Comment by shivanik6z** [comment]
Yeah I got it. @conorshipp I guess you did it right, sure commit the changes:)
