### ISSUE TITLE
Multiselect fails when dealing with Cmd+action on macOS

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1987]
**Describe the bug**

On macOS, and possibly others but I haven't observed it, the browser doesn't always trigger the keyup event for the command key. This can cause App Inventor to think it is in multiple component select mode when it is really not. This results in all sorts of havoc with properties changing when they shouldn't because two or more components are selected when the user didn't intend it.

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Selecting a component should only trigger a multiple select if the corresponding key is pressed when the click action occurs.

**Steps to reproduce**

It's hard to reproduce, but I seem to trigger it more often when switching to/from App Inventor because Cmd+Tab switches apps and it may not be the case that the browser is dropping the keyup since it's no longer the active app.

**Comment by bartmathijssen** [comment]
I just tested this and saw that the same behavior is happening using Firefox. I tested this by using the Ctrl+Tab key combination, this switches browser tabs. Also, I am not getting any visual representation of multiple components being selected. Only the counter of components selected in the top right.
