### ISSUE TITLE
Add HelloPurrStarter project to built-in repository

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#1988]
**Describe the desired feature**

Add @stezelMIT's HelloPurrStarter to the built-in repository. Currently it's in the gallery, which means that people wanting to participate in workshops and use code.appinventor cannot do so.

**Give an example of how this feature would be used**

Workshop instructors can ask participants to load the starter file from the repository rather than needing to craft special links.

**Why doesn't the current App Inventor system address this use case?**

The code server (and others) don't have the gallery, so our current technique of launching someone into the gallery for the starter file isn't portable.

**Why is this feature beneficial to App Inventor's educational mission?**

It would make the behavior consistent across all App Inventor versions as currently bringing everyone in sync takes substantial instructor time and can be detrimental to the learning experience.

**Comment by conorshipp** [comment]
> HelloPurrStarter

Where can we find this project?

**Comment by stezelMIT** [comment]
Title is: HelloPurr_Starter
The gallery link is:
ai2.appinventor.mit.edu/?galleryId=5771384324751360

Hope this helps.
Selim
