### ISSUE TITLE
ProjectManager and Project List need refactoring

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#1997]
Currently, the Projects View is built through a complicated relationship among ProjectListBox, ProjectList, and ProjectService. Adding the Trash feature made this even more complicated by adding TrashProjectListBox and TrashProjectList. 

Code was copy-pasted between ProjectList and TrashProjectList.

Project lists and trashed project lists are maintained separately in ProjectManager and (Trash)ProjectList. One updates in a callback while the other updates using an event listener. Meanwhile, the UserProject object has a projectMovedToTrash flag that is underutilized.

All this complexity makes the trash can and upcoming folder enhancements much more complicated than they should be.

**Comment by ewpatton** [comment]
👍 

Since this might take a while, do you want to address this in the February sprint?

**Comment by ewpatton** [comment]
Fixed by #2002
