### ISSUE TITLE
Sound not ready error 710

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#200]
See the issue and blocks at:
https://groups.google.com/forum/#!category-topic/mitappinventortest/specific-programming-issue/lCt2Rh-D93M

Problem is that Sound gives errror 710 if not ready.

**Comment by halatmit** [comment]
I cannot duplicate this.   I've asked Enis to send  a project that elicits it.

**Comment by EnisM** [comment]
Posting one on the forum... Run it in the emulator... First click on a button (only first 4 do anything), get error.  Click again, works...

**Comment by halatmit** [comment]
This is working as intended, as far as I can see.   See my note on the forum.
