### ISSUE TITLE
Request foreach block for dictionary

### ISSUE THREAD

**Issue by wxbit** [mit-cml/appinventor-sources#2019]
Iterate over key-value pair, as foreach for List do.

**Comment by ewpatton** [comment]
Note that you can technically do this as dictionaries will coerce into an associative list when used in a list operation. For example:

![blocks (33)](https://user-images.githubusercontent.com/1331253/73811617-f98b7c00-47a7-11ea-8700-c56721c9e547.png)

However, a version of the foreach that has two variables (key, value) might be more intuitive than unpacking the item into key and value.

**Comment by wxbit** [comment]
Thanks for your advice..There are many ways to iterate over dictionary. As you said, there are two variables that are more intuitive.BTW: It would be better if the foreach had 2 variables, one is item and other is the index of the current iteration.

**Comment by BeksOmega** [comment]
I'd like to give this a shot. My idea is to make a "foreach key,value" block:
![Dictionary](https://user-images.githubusercontent.com/25440652/74091840-62f1e000-4a71-11ea-8922-bd5b020a7437.png)

That generates the same code as this combination of blocks:
![blocks (2)](https://user-images.githubusercontent.com/25440652/74091849-756c1980-4a71-11ea-9efb-40a579b166fb.png)
Does that seem like the correct strategy?

**Comment by ewpatton** [comment]
@BeksOmega that sounds reasonable to me, although we might want to have the text be for each [key] with [value] in dictionary

The block definition should be straightforward for you given your familiarity with Blockly. If you’re not familiar with the Scheme language, defining the behavior will be a bit more complicated. Take a look at the existing definitions in runtime.scm for the other for each blocks to get a sense of how they work. We can help you out if you get stuck.

**Comment by wxbit** [comment]
@BeksOmega Please note that need to support the "break" block.

**Comment by wxbit** [comment]
@ewpatton How about adding the current iteration index to foreach? When using foreach in java, in order to get the serial number, you have to define a count variable or use for.It is more tedious in ai that requires at least 6 code blocks.

**Comment by wxbit** [comment]
@ewpatton How about adding the current iteration index to foreach? When using foreach in java, in order to get the index, you have to define a counter variable or use for.It is more tedious in ai that requires at least 6 code blocks.
