### ISSUE TITLE
Migtool deployment failure

### ISSUE THREAD

**Issue by codeRunner1111** [mit-cml/appinventor-sources#2025]
All in cmd prompt
I was trying to deploy my code to my org using Migtool which works through ANT.
When I select the--    ant deployChangesFromLocalToOrg    --  it checks my credential from my build.properties.xml and goes fine and asks me to select a commit which lists last 10 commits; 
 I select one and copy and hit enter I get the below errors.
Please suggest to avoid these errors.
BUILD FAILED
C:\newClone\migTool\build.xml:176: The following error occurred while executing this line:
C:\newClone\migTool\lib\ant-rba-salesforce.xml:948: The following error occurred while executing this line:
C:\newClone\migTool\lib\ant-rba-salesforce.xml:806: The following error occurred while executing this line:
C:\newClone\migTool\lib\ant-rba-salesforce.xml:866: Deployment was cancelled

**Comment by ewpatton** [comment]
@codeRunner1111  I don't really see how this is related to App Inventor?
