### ISSUE TITLE
Designer startup glitch on ScreeScrollable

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#203]
Create a project with a canvas and make it's vertical fill_parent.

You'll see that it doesn't fill in the designer.

To fix this, go to the screen proprties in the design.  Check Screen "scrollable" and then uncheck it and the canvas should fill.    It looks like the startup for the Form(?) assumes the screen is Scrollable even though the designer says that it's not.

**Comment by josmas** [comment]
This might be related to the change made for screens being non-scrollable by default. It's a good bite-size (needs a bunch of debugging in the designer). Will change labels now.

**Comment by jisqyv** [comment]
The fix for this has been merged into master.
