### ISSUE TITLE
ItemTextColor property for ListPicker

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#204]
Add a property to Listpicker that determines color of the text items, similar to ListView.  Note that this is called TextColor in LisstView, but ListPicker already has a different property called TextColor that controls the text on the listPicker Label.

**Comment by kkashi01** [comment]
How about ItemTextColor or ElementTextColor

**Comment by halatmit** [comment]
ItemTextColor sounds good.  Maybe we should also change ListPicker.TextColor to ListPicker.ItemTextColor.

**Comment by kkashi01** [comment]
@halatmit For 2nd part, are you referring to ListView.TextColor to ListView.ItemTextColor
If so, should the block be marked as bad?

**Comment by halatmit** [comment]
Maybe I'm confused be don't want to mark it as bad -- just change the
property name, which is one of the things the upgrader should do,


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by kkashi01** [comment]
If we just rename ListView.TextColor to ListView.ItemTextColor, doesn't it break existing apps that had used ListView.TextColor?

**Comment by halatmit** [comment]
One of the functions of the upgrader is to rename existing blocks when
projects are read in. We've been doing that since Google days in AI Classic.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
#207 is merged. Closing this issue.
