### ISSUE TITLE
Automatically fix invalid project name input with spaces

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#2045]
Currently Appinventor handle invalid project name with spaces like this:
![image](https://user-images.githubusercontent.com/22613139/75018841-edabf380-54e3-11ea-8547-691888b10de7.png)

Why not use underscore to replace space automatically?
Just like this:
![image](https://user-images.githubusercontent.com/22613139/75019403-e76a4700-54e4-11ea-8c88-20ecad22c349.png)

**Comment by ewpatton** [comment]
This sounds to me like a reasonable enough thing to do.

**Comment by imdhruvgupta** [comment]
@ewpatton I would like to work on this issue.

**Comment by mhk19** [comment]
I want to work on this issue

**Comment by mhk19** [comment]
> I want to work on this issue

@ewpatton

**Comment by imdhruvgupta** [comment]
@mhk19 Please pick another issue, I am working on this one.

**Comment by ewpatton** [comment]
Fixed by #2143
