### ISSUE TITLE
Proguard for Extensions

### ISSUE THREAD

**Issue by Abhijith4124** [mit-cml/appinventor-sources#2047]
**Describe the desired feature**

Proguard Helps to Protect the Source Code from being reused without the permission of the Orginal Creator. 

**Give an example of how this feature would be used**

It can help Developers make Orginal Content without others stealing their hard work. It can also be Helpful for Students to see how a Code Obfuscator works. Some Students might have limited bandwidth so Proguard can help in Reducing the Size of the Extension. Teachers can use it to teach students how to Protect their Work, What changes a code Obfuscator does, etc.

**Why doesn't the current App Inventor system address this use case?**

The Current System Compiles the Extension without any kind of Obfuscation. Adding Proguard to the Current System might obfuscate the libraries used in the extension as well.

**Why is this feature beneficial to App Inventor's educational mission?**

It is more Useful for Developers and Students who like to know a little bit more about programming as a whole.

**Comment by ewpatton** [comment]
@mit-cml/kodular I know we've discussed this in the past and I thought you were already doing this in Kodular. I don't mind having this for extensions if it is activated by a separate flag but off by default.

**Comment by barreeeiroo** [comment]
@ewpatton right. I can make a version of the implementation I did at Kodular, to make it work with extensions, which would be disabled by default.
Can you assign me the issue?

**Comment by barreeeiroo** [comment]
@ewpatton should I implement it in this repository, or in https://github.com/mit-cml/extension-template?

**Comment by ewpatton** [comment]
@barreeeiroo I would Implement it here and then you can backport it to the template.
