### ISSUE TITLE
Hi-res download blocks as PNG

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2069]
**Describe the bug**

The download blocks as PNG function produces images that appear fuzzy on high resolution displays (versus screen capture).

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Images should be of similar quality

**Steps to reproduce**

On a high resolution display, take a screenshot of the blocks. Similarly, export the blocks as PNG. Compare images and note that the screenshot is of higher quality than the export.

**Comment by NirmalManoj** [comment]
I am new to this project, but would love to work on this issue. I might take some couple of days to really understand how this codebase works. But if that is not a problem, can I take up this issue?

**Comment by ewpatton** [comment]
@NirmalManoj If you'd like to try this one, go ahead. All of the logic is in blocklyeditor/src/exportBlocksImage.js. I think it should be as straightforward as:

1. Create the canvas at 2x the current size
2. Draw the image to the canvas at 2x the current size
3. When we construct the PNG, add the pHYs chunk with the following 9 bytes: `00 00 16 25 00 00 16 25 01`

Note that the pHYs chunk needs to come before the IDAT chunk per the PNG specification.

**Comment by NirmalManoj** [comment]
@ewpatton Unfortunately, I got busy with some other work. I would finish this when I get time, probably in the next couple of weeks. If anyone else wants to work on this, please go ahead. Just comment here, so that in case I have made any progress, I could share those so that you won't have to do duplicate work.

**Comment by Ramanathi** [comment]
@ewpatton I didn't get what the bug is, Can u explain it further?

**Comment by Ramanathi** [comment]
> @NirmalManoj If you'd like to try this one, go ahead. All of the logic is in blocklyeditor/src/exportBlocksImage.js. I think it should be as straightforward as:
> 
>     1. Create the canvas at 2x the current size
> 
>     2. Draw the image to the canvas at 2x the current size
> 
>     3. When we construct the PNG, add the pHYs chunk with the following 9 bytes: `00 00 16 25 00 00 16 25 01`
> 
> 
> Note that the pHYs chunk needs to come before the IDAT chunk per the PNG specification.

Hello @ewpatton 
I didn't get why this works and how to implement.
Could you suggest any per-requisite to solve this or any help??

**Comment by Ramanathi** [comment]
Can I get any help to solve this? @ewpatton

**Comment by ewpatton** [comment]
@Ramanathi Rather than decoding the PNG manually, you could use the PNG object code I wrote and then just use array splice to insert the pHYs chunk at the right location. Also, make sure that in addition to doubling the size of the canvas that you actually draw the blocks at double the size.

**Comment by Ramanathi** [comment]
![Screenshot from 2020-04-06 12-14-17](https://user-images.githubusercontent.com/55206019/78529957-60590000-7800-11ea-8e5e-2785e9389051.png)

left is downloaded, right is screenshot! (you can see the percentages of sizes )

**Comment by Ramanathi** [comment]
[pngLog.txt](https://github.com/mit-cml/appinventor-sources/files/4436783/pngLog.txt)

This is it's pngchunk data

**Comment by ewpatton** [comment]
@Ramanathi Do you want to submit a PR for us to review? It's hard to determine whether the behavior is correct simply from the screenshots.

**Comment by Ramanathi** [comment]
> @Ramanathi Do you want to submit a PR for us to review? It's hard to determine whether the behavior is correct simply from the screenshots.

Yes @ewpatton  I will submit a PR.

**Comment by ewpatton** [comment]
Fixed by #2152
