### ISSUE TITLE
Type name to delete project/screen

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2071]
**Describe the desired feature**

Rather than simply having a delete and cancel button to delete a screen or project (which is not undoable), instead prompt the person to type in the exact name of the thing to confirm deletion. Don't activate the button until the string is typed.

**Give an example of how this feature would be used**

This is intended to prevent accidental deletion of screens and projects, which cannot be undone.

**Why doesn't the current App Inventor system address this use case?**

The current system only asks the user to confirm with a single click or press of the enter key. Since we cannot undo this step, we should increase the barrier to deleting a screen or project (project deletion is alleviated somewhat with the addition of the trash project list).

**Why is this feature beneficial to App Inventor's educational mission?**

It will prevent students from accidentally deleting a significant amount of work in some instances. Since we can't recover screens it further increases the barrier to a bad outcome.

**Comment by beinganonymous** [comment]
@ewpatton  Do you mean to implement same feature which GitHub is using to delete repositories, means GitHub ask to type correct repository name to delete and after that it enables ``delete`` button.
Then i would like to work on this issue.

**Comment by ewpatton** [comment]
@beinganonymous Yes, that's the general idea.

**Comment by HimaniKaul** [comment]
@beinganonymous Well I think you have a great idea.. but typing keyword before deleting screens would be too tedious. What if I have to delete 3 screens one after another for which I have to enter the keyword 3 times.

**Comment by beinganonymous** [comment]
@HimaniKaul What you are saying is correct, but it's better to Enter the keyword 3 times rather than dealing with accidental deletion of projects/screens. If you have any ideas, i am open for suggestions.

**Comment by HimaniKaul** [comment]
Well according to me typing keyword 3 times won't be better but I can suggest you that you can add check boxes for deleting more than 1 screen so that we have have to type keyword only once.

**Comment by beinganonymous** [comment]
@ewpatton After we delete the project the App Inventor System moves the project to Trash and we can restore the project from Trash, but once deleted from Trash there is no way to restore it. So do you want me to implement this ``Type name to delete project/screen`` feature on ``Delete from Trash`` button or on the ``Move to Trash`` button?

**Comment by ewpatton** [comment]
Eh. I would just focus on implementing for screens for now since we have the trash as a backup. If people go through the effort of both moving a project to the trash, going to the trash, and then removing it again, I'm okay with saying they really wanted to delete it. Currently, there is no such protection w.r.t. screens.

**Comment by ewpatton** [comment]
@beinganonymous I was thinking about this a bit more this morning. I think it might make sense to have a box (checked by default) in the dialog as well that is used to indicate that a checkpoint of the project should be taken. This way, if they delete a screen they can go back to a version of the project with the screen present. If they're confident they really don't need the screen any more, they can uncheck the box and no checkpoint will be made. See [CheckpointAction](https://github.com/mit-cml/appinventor-sources/blob/47628a856bf9f6a4b55282c91056b37afdcc6d3a/appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java#L428) in TopToolbar.java for an example of how the checkpoint is taken.

**Comment by beinganonymous** [comment]
Okay that sounds good. I will implement this feature then.

**Comment by beinganonymous** [comment]
@ewpatton As you told me to implement ``Checked Box`` in the dialog to store current checkpoint of project. So should i implement both ``Type name to delete screen`` and ``Checked Box`` feature in dialog box or just a ``Checked Box`` feature ?

**Comment by ewpatton** [comment]
@beinganonymous I would do both and have the checkpoint option on-by-default.

**Comment by beinganonymous** [comment]
@ewpatton I have implemented all changes you have mentioned such as ``Type name to delete screen`` and ``CheckBox`` feature, please find attached gif and let me know if you want any changes.


![app](https://user-images.githubusercontent.com/30001594/76617608-a944ce00-654c-11ea-84ba-7c9b74ac1583.gif)

**Comment by SusanRatiLane** [comment]
@beinganonymous OK, since @ewpatton is on vacation, I'm looking at this.

This looks like the right design to me. 

I don't think the checkpoint checkbox (say that three times fast) has a clear enough description. I'm not even familiar with checkpoints and will need to look them up. If I don't know what this refers to without research, I'm sure most users won't either.

Massaging the message text shouldn't keep you from moving forward however.

**Comment by beinganonymous** [comment]
@SusanRatiLane So, good to go with the design and regarding the CheckBox I'll put a user friendly message and make the pull request.

**Comment by SusanRatiLane** [comment]
@beinganonymous That sounds great.
