### ISSUE TITLE
OpenDyslexic not working in the contextmenu in the block editor

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#2081]
**Describe the bug**

Not all parts of the context menu in the block editor are using the OpenDyslexic font if selected. See the results as shown below.

![Screenshot 2020-03-05 at 07 59 29](https://user-images.githubusercontent.com/32273650/75957527-80706900-5eba-11ea-9364-f46acbb75ec8.png)

![Screenshot 2020-03-05 at 08 00 39](https://user-images.githubusercontent.com/32273650/75957538-88c8a400-5eba-11ea-9dcc-9c186422e2a7.png)

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

All items in the context menu should use the OpenDyslexic font. 

**Steps to reproduce**

Select the OpenDyslexic font. Go to the blockseditor and rightclick on the white background or on a block.

**Comment by BeksOmega** [comment]
Two options:
1) Add `.dyslexic .goog-menuitem .goog-menuitem-content,` [here](https://github.com/mit-cml/appinventor-sources/blob/47628a856bf9f6a4b55282c91056b37afdcc6d3a/appinventor/blocklyeditor/media/ai2blockly.css#L40).
2) Add `!important` [here](https://github.com/mit-cml/appinventor-sources/blob/47628a856bf9f6a4b55282c91056b37afdcc6d3a/appinventor/appengine/war/static/css/Ya.css#L49).

Not sure which one would be better in this case.
