### ISSUE TITLE
Contextmenu in blockeditor doesn't disappear or stays in front after selecting an item in the main menu. 

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#2082]
**Describe the bug**

If you select the contextmenu it will not disappear or go to the back if you for instance click on the menu item to start to build an apk. 

![Screenshot 2020-03-05 at 08 38 53](https://user-images.githubusercontent.com/32273650/75958689-08577280-5ebd-11ea-93e5-8e58dbb5f425.png)
![Screenshot 2020-03-05 at 08 38 20](https://user-images.githubusercontent.com/32273650/75958695-0c839000-5ebd-11ea-8826-1aaf6b7c0472.png)

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

When selecting a item in the main menu the context menu should disappear or go to the back. 

**Steps to reproduce**

Go to the blockeditor and right click on the white background. Click on the menu item to build an apk. The apk is being build but the dialogform is behind the context menu.

**Comment by BeksOmega** [comment]
I believe this is the dreaded https://github.com/google/blockly/issues/2066 Both alshmiedt (https://github.com/google/blockly/pull/2359) and I (https://github.com/google/blockly/pull/2286) have tried to fix this before to no avail.

I'd like to take a look and see if there's a way to fix this for App Inventor specifically (and if it is indeed the issue I think it is). But my instinct is that this is probably unfixable with the current state of Blockly's event handling :/

**Comment by ewpatton** [comment]
I wonder if it is possible for us to install a mouse up event handler such that if the event doesn’t occur on an element with a parent of either the Blockly widget div or a Blockly SVG workspace root calls Blockly.hideChaff(). @ellelili2025 also worked on making sure we hide the Blockly chaff more frequently and may have insights to offer.

**Comment by BeksOmega** [comment]
@ewpatton @ellelili2025 Idea: What about adding a listener to the [TopToolbar](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/appengine/src/com/google/appinventor/client/TopToolbar.java)? or to the TopToolbar dropdowns? I think that should pretty much cover any time page navigation happens, or popups (like the apk building) are created. But I'm not familiar enough with App Inventor to be sure.

I couldn't figure out how to attach a listener to the TopToolbar, but I did get one working on the projects dropdown:
![HideChaffListener](https://user-images.githubusercontent.com/25440652/76149920-9e280480-6059-11ea-92a7-df851aee0f33.gif)
