### ISSUE TITLE
"Download blocks as image" does not include comment bubbles

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2089]
**Describe the bug**

Comment bubbles are not included in the image of the workspace when you select "download block as image" from the context menu.

Note that this is different from #624 as in that case bubbles were included, but the text did not show. Here there are no bubbles at all.

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Comments should be included in the downloaded image. As they are helpful for documenting how something is working.

**Steps to reproduce**

1. Drag a block from the toolbox.
2. Add a comment and type text into it.
![BlocksWComment](https://user-images.githubusercontent.com/25440652/76247839-707bc080-61fd-11ea-86bf-e47f96d62782.png)
3. Right click on the workspace background and select "Download blocks as image" from the context menu.
![blocks (9)](https://user-images.githubusercontent.com/25440652/76247853-75407480-61fd-11ea-9755-1dc9b68b08ac.png)
4. Open your image and observe how comments were not included.

**Request for Assignment**

I don't want to fix this issue (I've got quite a few projects atm hehe) I'm just reporting it.

**Comment by conorshipp** [comment]
Duplicate of #892?

**Comment by BeksOmega** [comment]
> Duplicate of #892?

Yessir! I did do a search before I posted this, but I must have missed that one. Thank you for the link :D

Closing as dupe.
