### ISSUE TITLE
Add a filer event to indicate when the file has been written

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#210]
The output side equivalent to File.GotText.

**Comment by kkashi01** [comment]
@halatmit Can you provide more explanation? What is a filer event?

**Comment by halatmit** [comment]
This would be similar to File.GotText, but on the output side.   It's an event that would be signaled at the completion of a File.SaveFile or File.AppendToFile command.   
For implementation, look in File.java at how ReadFrom uses AsyncRead and do the analogous with Write.

**Comment by halatmit** [comment]
handled in pr #438
