### ISSUE TITLE
Move to Trash menu item should change to Delete from Trash

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#2107]
The drop-down menu item My Projects->Move to Trash should change to Delete from Trash when viewing the Trashcan.

- [X] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Comment by beinganonymous** [comment]
can i work on this issue?

**Comment by beinganonymous** [comment]
@SusanRatiLane I have implemented the changes, please find attached ``gif`` and let me know if you want any changes.


![mit2](https://user-images.githubusercontent.com/30001594/77252469-03930c80-6c7a-11ea-9ee9-259e81c8f126.gif)

**Comment by SusanRatiLane** [comment]
That looks correct. I look forward to the pull request.

**Comment by beinganonymous** [comment]
Yes, sure.
