### ISSUE TITLE
Drag and Drop Support to upload files

### ISSUE THREAD

**Issue by beinganonymous** [mit-cml/appinventor-sources#2122]
While uploading media files we have to select file from File chooser,  instead of that we can add Drag and Drop support for file uploading.
It is a common test case for file uploading in browsers.

**Comment by ewpatton** [comment]
I have a draft version of this functionality available here: http://dnd.ai2-ewpatton-temp.appspot.com/. More information [here](https://community.appinventor.mit.edu/t/upcoming-feature-preview/1176?u=ewpatton).
