### ISSUE TITLE
Allow setting Yandex Translate API key

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#2126]
The Yandex Translate component doesn't have a API key property field. This restricts me from setting my own API key in the component when running the AI server offline. Using the component otherwise yields "Error 2201".

I propose to add a new String property to the Yandex Translate component.

**Give an example of how this feature would be used**
Users can choose to set their own API key.

**Why doesn't the current App Inventor system address this use case?**
Currently, the API key is set from the server side (?). There is no way to enter own API key.

**Why is this feature beneficial to App Inventor's educational mission?**
I have no idea.

**Comment by pavi2410** [comment]
@mit-cml/staff Is the Yandex Translate API key set manually by you? I could't find any code that sets the API key in question.

**Comment by ewpatton** [comment]
@pavi2410 We have a branding branch that we apply to master before building, and one of the commits sets the key for YandexTranslation.

**Comment by jisqyv** [comment]
@pavi2410 @ewpatton It is pretty easy to add a property for the key. I'll take this one...
