### ISSUE TITLE
Player bug with Lollipop (and Kitkat?)

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#213]
There's a bug with starting and stopping the player (and mediaplayer in general?) that has appeared with Lollipop and Kitkat.   Please try the example aia file here.  Both Taifun and I have verified this broken behavior.

https://groups.google.com/forum/#!topic/mitappinventortest/eQqqvwSdc1Y

It looks like the bug and the solution are discussed here:

http://stackoverflow.com/questions/21790824/mediaplayer-should-have-subtitle-controller-already-set-kitkat

**Comment by Momoumar** [comment]
What's the status of this bug?
I've tested the example app in the forum, on a One Plus One running android 5.0.2 and it works fine.

**Comment by halatmit** [comment]
All I know is what's in the issue report on the forum.
Is it possible that this was fixed with Android 5.1?

Can someone check?



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
This works in 5.1.1.   Closing the issue.
