### ISSUE TITLE
Trimming Project name

### ISSUE THREAD

**Issue by Ramanathi** [mit-cml/appinventor-sources#2139]
Hello everyone, 
lets say the project name is "hello"
but if the user types " hello  " it gives the white space error. Why can't we just trim the project name before processing?

**Comment by Ramanathi** [comment]
If it is valid issue, help me to contribute

**Comment by Ramanathi** [comment]
![Screenshot from 2020-04-01 13-33-07](https://user-images.githubusercontent.com/55206019/78113611-9facd880-741d-11ea-9e95-a47e95c74394.png)
![Screenshot from 2020-04-01 13-33-17](https://user-images.githubusercontent.com/55206019/78113648-ab989a80-741d-11ea-8081-4e646ab40612.png)

like this!!

**Comment by ewpatton** [comment]
@Ramanathi I think this could be combined with #2045

**Comment by Ramanathi** [comment]
@ewpatton yeah I'm working on #2045 also.

**Comment by Ramanathi** [comment]
Hello @ewpatton 
I've solved #2045.

Approach :
changed geterrorMessage function in Textvalidator.java
changed validator in newYoungAndroidprojectwizard.java
and also LabeledTextbox.java

I want to get checked if I made a mistake
