### ISSUE TITLE
Make Camera component create Pictures directory if not exists

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2140]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/error-201-the-camera-did-not-return-an-image-on-samsung-device-android-8-0/6024?u=ewpatton): Camera fails to return an image if the Pictures directory does not exist.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

App Inventor should create the Pictures directory if it does not exist so that the Camera has someplace to write to.

**Steps to reproduce**

1. Delete the Pictures folder on /sdcard
2. Try to take a picture with the Camera component
3. Observe error

**Comment by singhalsara8** [comment]
@ewpatton I would like to work on this issue.

**Comment by ewpatton** [comment]
@singhalsara8 Please go ahead. I've assigned you the issue.
