### ISSUE TITLE
Disabled blocks in backpack are handled ambiguously

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2147]
**Describe the bug**

Currently adding disabled blocks to the backpack acts unexpectedly:
![Backpack](https://user-images.githubusercontent.com/25440652/78455294-4c6f9b80-7652-11ea-84bc-0a1b20427d74.gif)

The blocks do not appear to be disabled (they are black instead) and you are able to drag them out of the flyout.

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

There are a couple of options I can think of.

1) Don't allow top-level disabled blocks to be added to the backpack.
2) Enable top-level disabled blocks when they are added to the backpack.
3) Keep the blocks as disabled, but allow them to be dragged from the flyout. Also fix the appearance.

For the trashcan, core first went with option 3 (https://github.com/google/blockly/pull/2241), but later switched to option 2 (https://github.com/google/blockly/pull/3255).

**Steps to reproduce**

1. Grab a block.
2. Disable it via the context menu.
3. Add it to the backpack via the context menu.
3. Open the backpack.
4. Observe how the block isn't colored correctly.
5. Drag the block out of the flyout.
6. Observe how it is not disabled.

**Comment by ewpatton** [comment]
I would recommend option 3. It is the case the disabled blocks can be moved in App Inventor, so I don't see why that should prevent people from being able to drag disabled blocks into or out of the backpack.

**Comment by BeksOmega** [comment]
> I don't see why that should prevent people from being able to drag disabled blocks into or out of the backpack.

 @ewpatton That's a special flyout-specific thing. If you have a disabled block in a flyout that means it can't be dragged out -- actually pretty weird behavior now that I think about it lol. It was originally used for implementing that 'maxBlocks' functionality. [Here's](https://github.com/mit-cml/blockly/blob/ddb37e2ebf89deec0a4a43d0327c79c453ebf687/core/flyout.js#L1225) the relevant code.

To fix it for the trashcan I added an [isBlockCreatable_](https://github.com/google/blockly/pull/2241) function to the flyout. But in this case I'd probably have to override [createBlockFunc_](https://github.com/mit-cml/blockly/blob/ddb37e2ebf89deec0a4a43d0327c79c453ebf687/core/flyout.js#L1218).

**Comment by ewpatton** [comment]
@BeksOmega Thanks. I don't like the idea of disabled being a substitute for maxBlocks (especially since the latter is not a feature of Blocky we use in App Inventor). I'm wondering if we can get this changed upstream?

**Comment by BeksOmega** [comment]
> Thanks. I don't like the idea of disabled being a substitute for maxBlocks (especially since the latter is not a feature of Blocky we use in App Inventor). I'm wondering if we can get this changed upstream?

@ewpatton If we wanted to make disabled blocks instantiable by default, I don't think that change would be accepted :/ (even though I think it's a good idea). The problem is that this is [documented as a feature](https://developers.google.com/blockly/guides/configure/web/toolbox#disabled) so I doubt that core would be willing to change it.

But if we can't change the default I think another option would be to add a flag to the flyout. Something to say "yes /this/ flyout can instantiate disabled blocks".

I checked, and [isBlockCreatable_](https://github.com/google/blockly/blob/096d1c46c5066cfa7e59db3b41405b7e854b95d0/core/flyout_base.js#L626) does still exist in core. So overriding that could act as the flag. Or we could try to add an explicit boolean property (e.g. "canCreateDisabled"). I don't think it would be too tricky to implement, and I think it would have a pretty good chance of getting accepted.

**Comment by ewpatton** [comment]
Let's just override `isBlockCreatable_` to always return true in App Inventor. That's sufficient for what we need.

**Comment by BeksOmega** [comment]
@ewpatton I'm not sure if anyone watches the mit-cml/blockly repo, so I wanted to give you a ping.

I put up a [PR](https://github.com/mit-cml/blockly/pull/6) over there because I believe doing it that way will make it easier to upgrade (you should be able to just drop the commit).

**Comment by ewpatton** [comment]
@BeksOmega Thanks, but you should also update the submodule in lib/blockly and make a PR here so that our master will be in sync. Once you submit the PR here I can review both.

**Comment by BeksOmega** [comment]
@ewpatton Done! See https://github.com/mit-cml/appinventor-sources/pull/2164
