### ISSUE TITLE
pizza party tutorial broken? -- check cache control in webviewer

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#215]
The pizza party tutorial is broken in that the webviewer doesn't show new orders.   It seems like a cache issue -- maybe kitkat or lollipop added a cache?   Please check this out and fix it by adding a cache control property to the webviewer, or a load-no-cache or something like that.

**Comment by jisqyv** [comment]
@halatmit I added a ClearCache function to the webviewer and verified that it worked. However it still didn't fix the issue with the Pizza Party tutorial. I believe Google's servers are not updating the web server in real time. In particular I cleared the webviewer cache before each fetch of the URL of the Pizza Party fusion table, and the table still took some time (measured in 10's of seconds) to update.

-Jeff

**Comment by halatmit** [comment]
Thanks.

We should update the tutorial once you add the ClearCache, and also add a
note so people wont expect to see thte update immediately.


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Mon, Jan 12, 2015 at 11:59 PM, Jeffrey Schiller <notifications@github.com

**Comment by jisqyv** [comment]
I have added the Clear Caches operation to the WebViewer. However it doesn't always make Pizza Party work as expected. There appears to be a delay on Google's side from when a change it made via the API and when the Fusion Tables webinterface sees the change.

**Comment by halatmit** [comment]
The Clear Cache operation deals with this, although it's not perfect.  Closing the issue.
