### ISSUE TITLE
The Backpack Bug

### ISSUE THREAD

**Issue by Vaibhav-creator** [mit-cml/appinventor-sources#2153]
**Describe the bug**
It seems that there is a bug related to adding blocks in the backpack. After adding any block to the backpack if we click (a simple left click) on that block, the block gets added/duplicated in the backpack on every simple click.

**Affects**

The blocks are duplicated in the backpack

**Expected behavior**
No block should be added to backpack on simple click

**Steps to reproduce**

1. Drag any block in the block editor

2. Add that block in the backpack by simple drag and drop

3. After the block is added, try to simply click on the block

Attaching video below(.zip file)
[MIT App Inventor - Google Chrome 2020-04-07 17-14-52.zip](https://github.com/mit-cml/appinventor-sources/files/4444066/MIT.App.Inventor.-.Google.Chrome.2020-04-07.17-14-52.zip)

**Comment by ewpatton** [comment]
@Vaibhav-creator Thanks for the report. I am able to replicate the issue. @BeksOmega Do you want to take a look at this?

**Comment by BeksOmega** [comment]
@BeksOmega Do you want to take a look at this?

I would love to!
