### ISSUE TITLE
Add a `onCreateListener`

### ISSUE THREAD

**Issue by amsdamsgram** [mit-cml/appinventor-sources#2165]
Hi,

**Describe the desired feature**
Could it be possible to add a `onCreateListener`? The same way there is already a `onDestroyListener` [here](https://github.com/mit-cml/appinventor-sources/blob/8d2490a2ecce9987faaf37a055821103416722cb/appinventor/components/src/com/google/appinventor/components/runtime/OnDestroyListener.java)

**Give an example of how this feature would be used**
I’m building an extension to log events with Facebook Analytics.
According to the [documentation](https://developers.facebook.com/docs/app-events/getting-started-app-events-android), we need to call some methods when the app is created:

```package com.example.hellofacebook;

import android.app.Application;

import com.facebook.FacebookSdk;
import com.facebook.appevents.AppEventsLogger;

public class HelloFacebookSampleApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        FacebookSdk.sdkInitialize(getApplicationContext());
        AppEventsLogger.activateApp(this);
    }
}
```

**Why doesn't the current App Inventor system address this use case?**
I'm not sure why but I'm probably not the only one who needs this listener. And as there is already a `onDestroyListener`, it makes sense to have the `onCreateListener` too.

I can make a PR to add this listener if this feature request is accepted.

Thanks

**Comment by ewpatton** [comment]
Every component can define a void noargs method called `Initialize` that is invoked once the activity has been created. Unless the app is running on an older device where we have to pause to load multiple dex files, this will be called from within the context of the `onCreate` method. You could technically also call it in the constructor of your extension, which will be called before `Initialize` but still as part of the same block of code (all components are created, Screen Initialize is called, all components are Initialize, if defined, are called).

**Comment by amsdamsgram** [comment]
Thank you for your answer.
I'll try calling these methods in the constructor extension as it doesn't seem to work when I call it in a Initialize function called in the screen Initialize function:

```
@SimpleFunction(description = "Initialize SDK")
    public void Initialize(String facebookAppId) {
        FacebookSdk.setApplicationId(facebookAppId);
        FacebookSdk.sdkInitialize(this.container.$context().getApplicationContext());
        AppEventsLogger.activateApp(this.container.$context().getApplication());
        this.logger = AppEventsLogger.newLogger(this.container.$context());
    }
```

**Comment by ewpatton** [comment]
@amsdamsgram If there is a property involved, then the correct way is to do it with Initialize. Component properties are set after the constructor is called but before Initialize. You may want to take a look at the code for FirebaseDB, which has similar constraints and also needs to do some static initialization of its framework.

**Comment by amsdamsgram** [comment]
Thanks for your answer again!
I'll take a look at the code for FirebaseDB and close this issue as it is not related anymore.
