### ISSUE TITLE
LineString.PointsFromString Tooltip Incorrect

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2176]
**Describe the bug**
It seems that the tooltip for the LineString.PointsFromString function is incorrect. It reads:

> Set the points of the LineString from a specially-coded character string of the form: [[longitude1, latitude1], [longitude2, latitude2], …] Note the reversal of latitude and longitude versus how they are typically represented.

But this doesn't seem to actually be the case. This is confirmed by two users over on [this post](https://community.appinventor.mit.edu/t/error-text-description-linestring-pointsfromstring/7732/2), as well as my own testing.

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [X] Other: Documentation

**Expected behavior**

It should read something like:
Set the points of the LineString from a specially-coded character string of the form: [[latitude1, longitude1], [latitude2, longitude2], …]

**Steps to reproduce**

1. Add a map via the designer.
2. Add a LineString to the map via the designer.
3. Drag the LineString.PointsFromString block into the workspace.
4. Wait for tooltip.
5. Observe the incorrect tooltip info.

**Additional Info**

I was going to go ahead fix this, but then I realized that I don't know how to notify translators that they would need to update their translations. I'm not sure how to handle a situation like this, but I'm happy to contribute in any way.

**Comment by ewpatton** [comment]
@BeksOmega The English documentation is generated from the source code. We use Weblate to manage the translations, so when we update the English documentation it will mark the existing translations as needing review. I'm not sure at the moment that we have any translations for the LineString properties.

**Comment by BeksOmega** [comment]
@ewpatton Oh sweet! That's a really nice system. Does that mean I can give updating the source-code-doc a shot?

**Comment by ewpatton** [comment]
@BeksOmega Sure. You'll want to make the changes to the Javadoc for PointsFromString in components/.../LineString.java and then rebuild the system. When you do, it should update the Markdown and HTML versions of the documentation under docs/. You may need to install ruby and bundler on your machine if you haven't already (not 100% sure of your setup).
