### ISSUE TITLE
Allow x- and y-coordinates are at the center for ImageSprite

### ISSUE THREAD

**Issue by markconnolly** [mit-cml/appinventor-sources#2189]
**Describe the desired feature**

Similar to the fix for Ball, make it possible to position the ImageSprite by using its center.

**Comment by ewpatton** [comment]
@espertus Would you have any time and interest to work on this, or should we offer it up as a student project?

**Comment by conorshipp** [comment]
According to this comment, it seems like the property was purposely not added to the ImageSprite
https://github.com/mit-cml/appinventor-sources/blob/ae1488696407a0e88f8e849fbec47ebc15969b41/appinventor/components/src/com/google/appinventor/components/runtime/Sprite.java#L395

If there is a specific reason why the property wasn't added, it might be useful to know before someone starts working on this.

**Comment by markconnolly** [comment]
A different comment makes me think the reason might be more about just addressing the Ball request.

https://github.com/mit-cml/appinventor-sources/blob/ae1488696407a0e88f8e849fbec47ebc15969b41/appinventor/components/src/com/google/appinventor/components/runtime/Sprite.java#L152

Also, this is by no means an important request.  I can work around this in code blocks with my own offset calculations (using the sprite image's width and height, which might be a little naive but serves my purpose).  

I did see in interchanges about the ball origin at center that someone raised the idea that ImageSprite should provide the same.  Since I tripped across the ImageSprite need, I figured I'd make the suggestion a formal request.

**Comment by espertus** [comment]
See #1777 where @halatmit said:

> We might want to fix this for image sprite also, and put the location of the sprite at the center of the sprite rectangle. Better, we could make the location of the sprite be a settable property. This change will be a little delicate, since it also affects sprite rotation and collision.

**Comment by ewpatton** [comment]
I think it would be good if we do this to make it so that it can be an arbitrary point in the image sprite. Have a special property editor that specifies the origin in coordinates and then have a button that would show an indicator on the image itself that can be dragged to change the location. This would allow for specifying the location numerically (such as in the blocks) or visually in the designer. Consider also having a reset button to return the origin to 0, 0.

**Comment by halatmit** [comment]
This should be a property of the canvas (or possibly of the sprite -- need to think about this).
Along withs, the canvas coordinates should match standard cartesian coordinates with (0,0) at the center and increasing upward and to the right.

As a related issue, there should be a better algorithm for detecting when two sprites are touching.

**Comment by ewpatton** [comment]
@halatmit I think that's really a different issue, which should also be addressed but separately from the ImageSprite's origin.

**Comment by ewpatton** [comment]
PR #2496 made it so that the user can specify an arbitrary point within the bounds of the image sprite as the origin for the purposes of positioning and rotation.
