### ISSUE TITLE
SetFocus for textboxes

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#219]
Here's a suggestion form Enis for a new useful feature. 

Here's the reference from the SDK:

Added in API level 1

Call this to try to give focus to a specific view or to one of its descendants. A view will not actually take focus if it is not focusable (isFocusable() returns false), or if it is focusable and it is not focusable in touch mode (isFocusableInTouchMode()) while the device is in touch mode. See also focusSearch(int), which is what you call to say that you have focus, and you want your parent to look for the next one. This is equivalent to calling requestFocus(int, Rect) with arguments FOCUS_DOWN and null.
Returns

    Whether this view or one of its descendants actually took focus. 

And here's the actual suggestion for App Inventor

        Would love a SetFocus method for textboxes.

        Say for example, you evaluate the contents of textboxes before submitting to something, and you find one incorrect.  So you pop up a message box that says the address is missing... Ideally, after eh message box closes, you put the user back to the offending address textbox for new entry, but in AI, you're left in a bizarre never-never land.

        And there are times when you want to pop users back to the top of an input screen, but there's no way to do it in AI...

**Comment by ReachAayush** [comment]
Hello @halatmit 

I have started working on this and have come up with a setter and a getter for the Focus property of textboxes. 

This is a screenshot of what the options look like from the textbox methods menu:
![screenshot](https://cloud.githubusercontent.com/assets/2350321/5995170/14dcec14-aa5a-11e4-9457-18e1ea40b214.png)

**Comment by halatmit** [comment]
Looks good.  Thanks!



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
Like the looks of this... This will REALLY help....

**Comment by ReachAayush** [comment]
Added pull request #244

**Comment by jisqyv** [comment]
Pull Request #244 merged.
