### ISSUE TITLE
jetifier and D8

### ISSUE THREAD

**Issue by AKBIROCK3** [mit-cml/appinventor-sources#2197]
**Describe the bug**

so i was adding the changes of #2034 and https://github.com/ewpatton/appinventor-sources/pull/13 to my project the i faced a problem jetifier requires to add lines in DexExecTask.java file which was removed in order to add D8 and it has no function 
so where should i add the lines of jetifier ?
**Affects**

- [x] Buildserver

**Comment by pavi2410** [comment]
It doesn't matter much except readability.

#2034 removed DexExecTask.java because D8 could run as a simple function just like other Android build tools used in the Compiler.java

ewpatton#13 added Jetifier into the DexExecTask.java because it doesn't use D8 and I felt it fit better there because that class is also responsible for pre-dexing.

**Comment by AKBIROCK3** [comment]
> It doesn't matter much except readability.
> 
> #2034 removed DexExecTask.java because D8 could run as a simple function just like other Android build tools used in the Compiler.java
> 
> [ewpatton#13](https://github.com/ewpatton/appinventor-sources/pull/13) added Jetifier into the DexExecTask.java because it doesn't use D8 and I felt it fit better there because that class is also responsible for pre-dexing.

THANKS for your reply could you guide me what i did is adding all the lines like you did

then add this line
`DexExecTask dexTask = new DexExecTask();`
to
`			    List<String> jetifierClasspath = new ArrayList<>();
    for (String path : JETIFIER_CP) {
      jetifierClasspath.add(getResource(JETIFIER_DIR + path));
    }
    dexTask.setJetifierClasspath(Joiner.on(File.pathSeparatorChar).join(jetifierClasspath));
`
then i replaced all runDx in DexExecTask to runD8
but it didn"t work it don't want to compile apps

**Comment by AKBIROCK3** [comment]
UPDATE:Since i was trying to migrate to androidX i forget to add some jars for that the compile was fail but i fix it now but still there's a problem with jetifier i add all the lines but it doesn't load while building the app the code doesn't function at all

**Comment by pavi2410** [comment]
I can't say for sure, because I lost track of the Jetifier PR. There are a couple of things left to do.

**Comment by AKBIROCK3** [comment]
> I can't say for sure, because I lost track of the Jetifier PR. There are a couple of things left to do.

i see so you can't fix it anymore btw thnx for starting this great idea i'll try to fix it by myslf

**Comment by ewpatton** [comment]
d8 is now the default in App Inventor's build server if Java 11+ is used.
