### ISSUE TITLE
Deprecation in components works inconsistently

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2216]
**Describe the bug**

Each type of component feature (event, method, or property) reacts differently to deprecation.

Events: Nothing happens.
Methods: Marked as badBlock() and disabled.
Properties: Get a warning saying "Block is not defined. Delete this block!"

![Deprecation](https://user-images.githubusercontent.com/25440652/85619164-be82cb80-b616-11ea-8486-a802163b7ec1.png)

**Affects**
- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

I am assuming that methods are the only feature following the desired behavior. But I could be wrong.

**Steps to reproduce**

1. Open the Form component definition.
2. Deprecate `BackPressed`, `AskForPermission`, and both `AboutScreen` functions.
3. Load the attached (zipped) .aia
[test10.zip](https://github.com/mit-cml/appinventor-sources/files/4827569/test10.zip)

**Additional Info**

Events can be fixed by fixing [this line](https://github.com/mit-cml/appinventor-sources/blob/012a07bdef7ce1590af46c47ff27c83485c2191f/appinventor/blocklyeditor/src/blocks/components.js#L304). 
It should be:
```
    if (eventType && eventType.deprecated && this.workspace == Blockly.mainWorkspace) {
```
Not:
```
    if (eventType && eventType.deprecated === "true" && this.workspace === Blockly.mainWorkspace) {
```

Properties can be fixed by removing [this line](https://github.com/mit-cml/appinventor-sources/blob/012a07bdef7ce1590af46c47ff27c83485c2191f/appinventor/blocklyeditor/src/component_database.js#L337).

Happy to do this real quick if you guys agree methods have the correct behavior!

**Comment by ewpatton** [comment]
@BeksOmega I agree. If you have time please go ahead and make a PR.
