### ISSUE TITLE
.aar Library Support For Extension

### ISSUE THREAD

**Issue by aryanrauniking** [mit-cml/appinventor-sources#2218]
From Many Days AppInventor Team Is Able To Add Support Of Many Features  ....Which Was Supposed To Impossible To For External component :/
But adding .aar support For Extension Will Be More Awesome :) If AppInventor Team Will Help To Add This Feature than It Would Be Great :)

**Comment by pavi2410** [comment]
Duplicate of https://github.com/mit-cml/appinventor-sources/issues/2196
