### ISSUE TITLE
Validate exception after displaying mutatable menu

### ISSUE THREAD

**Issue by wxbit** [mit-cml/appinventor-sources#2225]
**Describe the bug**

https://github.com/mit-cml/appinventor-sources/pull/2184  

Test server: https://ai2-test.appinventor.mit.edu

![ezgif-2-e7300e95c9e5](https://user-images.githubusercontent.com/3827464/86198401-2347a400-bb8a-11ea-9d8e-a8c66f1d8a12.gif)

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Comment by ewpatton** [comment]
@wxbit Thanks for the report. This should be fixed in #2220
