### ISSUE TITLE
 Blocks editor bug: typeblocked user procedures lack parameter sockets 

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#224]
Please see this thread

https://groups.google.com/forum/#!topic/mitappinventortest/5V1JeWv2jYA

**Comment by halatmit** [comment]
This is pull request 121.
@josmas @evanrthomas @jisqyv @afmckinney 
Evan, will you be finishing this up?  Do you need help?

**Comment by josmas** [comment]
Just adding link to #121 so we close this when the other one is closed

**Comment by jisqyv** [comment]
#121 merged, this is fixed.
