### ISSUE TITLE
Empty property descriptions override previous non-empty descriptions

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2257]
**Describe the bug**
Empty (long) property descriptions override previous non-empty (long) property descriptions. This is bad because the long descriptions show up in documentation.

An example of this is the ScaleUnits property of the Map component:
```
  /**
   * Specifies the units used for the scale overlay. 1 (the default) will give metric units
   * (km, m) whereas 2 will give imperial units (mi, ft).
   */
  @SimpleProperty
  public void ScaleUnits(int units) {  }

  @SimpleProperty
  public int ScaleUnits() { }
```
The docs end up looking like [this](http://ai2.appinventor.mit.edu//reference/components/maps.html#Map.ScaleUnits):
> Property for ScaleUnits

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [X] Docs

**Expected behavior**

The description should be the javadoc description.

**Steps to reproduce**

1) Create a property with a getter and a setter.
2) Add a description to whichever comes first in the component.
3) Rebuild the docs.
4) Observe how the docs are incorrect.

**To Fix**

Change this:
```
if (!newProperty.longDescription.isEmpty()) { 
  priorProperty.longDescription = newProperty.longDescription;
}
```
To this:
```
if (!newProperty.longDescription.isEmpty() && !newProperty.isDefaultDescription()) { 
  priorProperty.longDescription = newProperty.longDescription;
}
```

**Comment by sarthakhanda** [comment]
please allow me to work on this issue!

**Comment by ewpatton** [comment]
@sarthakhanda I'm fine with that assuming that @BeksOmega wasn't intending to do this (or already has it done).

**Comment by BeksOmega** [comment]
Yeah absolutely @sarthakhanda go ahead :D It would be great to get this fixed!
