### ISSUE TITLE
Change name of "My Projects" toolbar menu to "File" or something else

### ISSUE THREAD

**Issue by pavi2410** [mit-cml/appinventor-sources#2264]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28837746/89123445-05ed5900-d4ed-11ea-89ee-8e916cc940a8.png)

The buttons highlighted in yellow are same, but the one in blue is different and therefore, should have different name to it to avoid confusion.

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Comment by ewpatton** [comment]
I'd be happy with the main button being "Projects" instead of "My Projects". However, there's also a few items on that menu not really related to projects, such as keystore management, but they're probably fine to stay.

**Comment by pavi2410** [comment]
Fixed by #2279
