### ISSUE TITLE
Need help in creating workspace like appinventor 

### ISSUE THREAD

**Issue by suryadevelope** [mit-cml/appinventor-sources#2277]
hai 

i am working to make a webpage to write program using blockly.

i used the following files to create the workspace:

* Blockly_compressed.js
* Blocks_compressed.js
* javacsript_compressed.js
* en.js

from the google blockly repository https://github.com/google/blockly

so i created workspace using 

`Blockly.inject('divforworkspace',options);`

then i got the following workspace

https://community.appinventor.mit.edu/uploads/default/original/3X/4/7/47b826323409319864fd4fb8492b9ec57792646c.png  

But i need to integrate:
1. Toolbar like  :https://community.appinventor.mit.edu/uploads/default/original/3X/7/2/7267270acf7fbd07033027391cd44b1df242dbc2.png
2. Warnings and errors like :https://community.appinventor.mit.edu/uploads/default/original/3X/a/e/ae9d9ebbf81aa7f889718534c47a0c9cc79dd545.png

3. Backpack :https://community.appinventor.mit.edu/uploads/default/original/3X/7/e/7eba003812f9f278f72afa17e67973857405b95a.png

finally the workspace should be as following

https://community.appinventor.mit.edu/uploads/default/original/3X/4/c/4cdf99583c95d33af33bc53b675c7238329e2ad9.png  

i refered to blockly docs but didn't found anything .i found it in app inventor open source github repository but unable to understand the procedure how to integrate in my code using javascript 

i need only Blocks part not the designer part from appinventor 

Regards,surya

Advanced thanks

**Comment by ewpatton** [comment]
You've already asked about this in the community. It's not an issue with the App Inventor sources so I'm closing this.
