### ISSUE TITLE
Do not load extensions into the palette from simple_components.json

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#2281]
When components appear in simple_components.json with type EXTERNAL should be ignored when loading component palettes. These are extensions that were present in the source code when the designer was compiled. They should only be imported from aix files by the user.

**Comment by BeksOmega** [comment]
I thought it wasn't possible to load extensions when testing on a local instance.

**Comment by ewpatton** [comment]
More specifically, we should check when the SimpleComponentDescriptor's getExternal() returns true, just in case we decide to allow for extensions to appear in other categories in the future.

**Comment by SusanRatiLane** [comment]
> I thought it wasn't possible to load extensions when testing on a local instance.

Importing extensions on a local instance works the same as in the production instances.

**Comment by ewpatton** [comment]
Another thing that fits into this is some work I did to optimize App Inventor memory use wherein the SimpleComponentDatabase populated by simple_components.json is shared across all open projects/screens and each project has a separate SimpleComponentsDatabase specifically for its extensions. Having this split would help us understand when we are loading simple_components.json versus an extension, as in master both paths use the exact same code and there isn't a way to really differentiate the context.
