### ISSUE TITLE
Implement a "contains any" text block

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2284]
**Describe the desired feature**

Add a built-in text block called "contains any" that takes a text and a list of texts (similar to the "contains" block) and returns true if any of the items in the list occur in the text.

**Give an example of how this feature would be used**

In the voice calculator, we need to check if the input text contains any of ["multiply", "product", "times", "*', ...]

**Why doesn't the current App Inventor system address this use case?**

This can be implemented as procedure in the blocks using local variables, loops, the break block, and the contains text block, but this is cumbersome and may require younger learners to learn more advanced topics than needed to accomplish the same goal.

**Why is this feature beneficial to App Inventor's educational mission?**

For younger users, this gives the power of the procedure implementation as a single block.

**Comment by BeksOmega** [comment]
I can take this :D

**Comment by ewpatton** [comment]
@BeksOmega Go for it!

**Comment by BeksOmega** [comment]
If someone passes in an empty list, do you want it to return true or false?
<img width="356" alt="blocks (1)" src="https://user-images.githubusercontent.com/25440652/90450970-ade35480-e09f-11ea-9c87-53f78254d2e8.png">

**Comment by halatmit** [comment]
might be better to have this as an alternate form of contains, with a mutator to select it,
similar to how split is done with split at and split at any

**Comment by ewpatton** [comment]
I think the semantics should be for a given string S and a set of elements Q, ∃x∈Q x⊆S. Therefore, if |Q| == 0, the block is false because there isn't an element to be found.

**Comment by ewpatton** [comment]
@halatmit The challenge with that is that you can't pass a variable since we don't have a block equivalent to `apply`. This allows us to use any number of elements if they are stored in a list, which could be dynamically changed at runtime.

**Comment by halatmit** [comment]
I'm not sure I understand.  Wouldn't split have the same issue?

**Comment by halatmit** [comment]
@BeksOmega I think containsAny with the empty list should be false.   It's like having an OR with no clauses.

**Comment by ewpatton** [comment]
Double checked on the 'split' block. It uses a field rather than a mutator. Changing the field changes the second argument to "at (list)", which I think is acceptable for this block. When you said mutator I was imagining in my head something closer to the "add items to list" block, which uses a mutator to add more arguments to the block.

**Comment by halatmit** [comment]
Right.  That was a little hack I did with the split block.  When I wrote
"mutator" I wasn't remembering correctly.
== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
Was merged and released in nn185.
