### ISSUE TITLE
Need help in creating workspace with backpack and all others

### ISSUE THREAD

**Issue by suryadevelope** [mit-cml/appinventor-sources#2287]
i need to create a workspace as appinventor ,so i have coded as below

1).injected a workspace then 
2).made as below for backpack

`var opts={

	collapse : true,
	disable : true,  
	trashcan : true, 
	comments:true,

	css : true, 	
	rtl : false, 
	scrollbars : true, 
	sounds : true, 
	setMetrics:{
		absoluteLeft:100,
		absoluteTop:10,
		contentHeight:100,
		contentTop:10,
		contentLeft:10,
		contentWidth:10,
		flyoutHeight:undefined,
		flyoutWidth:undefined,
		svgHeight:undefined,
		svgWidth:undefined,
		toolboxHeight:undefined,
		toolboxPosition:undefined,
		toolboxWidth:undefined,
		viewHeight:10,
		viewLeft:100,
		viewTop:10,
		viewWidth:100
	}

}

  Blockly.Backpack(Blockly.getMainWorkspace(),opts);`

i got error as below for everythin i do like in case of backpack,show warnings/error, toolbox

![Screenshot (41)](https://user-images.githubusercontent.com/59243908/90646452-d95b7000-e254-11ea-9b21-a21a0cd867f5.png);

can anyone fix it please 

Regards surya,
Thanks in advance

**Comment by suryadevelope** [comment]
Actually what is this bind error and how to solve it..

**Comment by suryadevelope** [comment]
how to create block workspace as app inventor not the design part need only blocks using javascript need a guide throw it

**Comment by suryadevelope** [comment]
@NeilFraser 

can u help me with that please

**Comment by ewpatton** [comment]
I think we should continue this discussion on the forum as it doesn't actually pertain to the App Inventor sources.
