### ISSUE TITLE
Ev3GyroSensor should reset previousValue in setMode?

### ISSUE THREAD

**Issue by BeksOmega** [mit-cml/appinventor-sources#2291]
**Describe the bug**

It seems that the Ev3GyroSensor should reset its previousValue to -1 inside its [setMode](https://github.com/mit-cml/appinventor-sources/blob/9638c167f559ad4b40fccd310ee5baf3ce6f76ad/appinventor/components/src/com/google/appinventor/components/runtime/Ev3GyroSensor.java#L178) function to match the behavior of the [Ev3ColorSensor](https://github.com/mit-cml/appinventor-sources/blob/9638c167f559ad4b40fccd310ee5baf3ce6f76ad/appinventor/components/src/com/google/appinventor/components/runtime/Ev3ColorSensor.java#L445). As noted by Evan [here](https://github.com/BeksOmega/appinventor-sources/pull/21#discussion_r476446536):

> The checker logic uses -1 to indicate that data has yet to be received. Given that changing the mode changes the value space of the data being received it really ought to reset the previous value to indicate no data has been received in the new value space. Otherwise, the comparisons occurring in that code are really apples to oranges (or angles to rates).

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [X] Components

**Comment by ewpatton** [comment]
Thanks @BeksOmega. I think this is a trivial fix based on our earlier back and forth. However, until we can get access to the Ev3 hardware in the lab we can't really test it. Do you want to prep a PR? If not, please go ahead and mark this as help wanted.
