### ISSUE TITLE
Cancelling asset deletion throws error

### ISSUE THREAD

**Issue by barreeeiroo** [mit-cml/appinventor-sources#2298]
**Describe the bug**

When you mistakenly hit "Delete" asset, and then click on "Cancel" to avoid its deletion, an error appears.
Asset does not get deleted, but the error pops.

`java.lang.IllegalArgumentException: node must be a YoungAndroidProjectNode`

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

**Steps to reproduce**

1. Click on any Media file
2. Hit Delete
3. Hit Cancel

![H0UCFwHQWX](https://user-images.githubusercontent.com/19251112/91640283-b5e6b100-ea1c-11ea-9d7b-9af9c6150451.gif)

---

Actually, the line that causes this is https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java#L79. And for some reason, it has been placed right there on purpose.
It was introduced with this change: https://github.com/mit-cml/appinventor-sources/pull/2101/files/6b763f04495ae8f7d2e2fd28bfea6b643938126c#diff-f1bd2868a1cf5db2f7acd9cacb9a7e6aR79
Is there any reason why you really want to throw an error?

I have already prepared a fix if it's fine to remove that exception: https://github.com/mit-cml/appinventor-sources/compare/master...barreeeiroo:fix/cancel-asset?expand=1#diff-f1bd2868a1cf5db2f7acd9cacb9a7e6a

**Comment by ewpatton** [comment]
Yes, I think it's fine to remove the exception.
