### ISSUE TITLE
Component named quote breaks apps

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2305]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/error-from-companion-attempt-to-invoke-virtual-method-java-lang-class-java-lang-object-getclass-on-a-null-object-reference/15679?u=ewpatton): Companion gives cryptic error about not being able to invoke `getClass()` on null object. The issue was due to a component being named `quote`, which I expect caused issues with the Scheme code.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [ ] Compiled apps
- [x] Buildserver (possibly compilation of screens)
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

We should not allow people to name their components with reserved keywords for Scheme.

**Steps to reproduce**

1. Create a Label component
2. Rename it to `quote`
3. Connect the companion
4. Observe failure

Renaming the label to something different fixed the issue.

**Comment by ewpatton** [comment]
We should think of other syntaxes that might be problematic, e.g., `if`, `def`, `define`, etc.

**Comment by conorshipp** [comment]
This seems straightforward to resolve. Can I self-assign this?

> We should think of other syntaxes that might be problematic, e.g., if, def, define, etc.

`if` has already been added as a reserved word so that can't be used but I also tested with `def` and `define` and they didn't seem to show the error.

I did find that "begin" is problematic but I'm yet to find any others.

**Comment by ewpatton** [comment]
@conorshipp Go for it!
