### ISSUE TITLE
Spelling mistake in README.md File.

### ISSUE THREAD

**Issue by ghost** [mit-cml/appinventor-sources#2311]
**Describe the bug**
Spelling mistake in README.md file

Under Checkout dependencies:
"For developers who will be working on **Blocky** within the context of App Inventor"

![spelling](https://user-images.githubusercontent.com/65233229/92966647-8bbdd600-f495-11ea-882a-8c964820f83c.png)

**Affects**

Creates confusion among new contributors & ruins the aesthetics of Read-Me file.

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [x] Other... (please describe)

**Expected behavior**

"For developers who will be working on **Blockly** within the context of App Inventor"

**Steps to reproduce**

Correct the spelling.
**Blocky** --> **Blockly**

**Comment by sarthakhanda** [comment]
please review & approve it if the issue raised is correct, so i can link the pr.
