### ISSUE TITLE
 yusufcihan Dynamic Components add 

### ISSUE THREAD

**Issue by adnan0350** [mit-cml/appinventor-sources#2343]
pleass new update in yusufcihan Dynamic Components add in mit app appinventor-sources

https://github.com/ysfchn/DynamicComponents-AI2

**Comment by ewpatton** [comment]
If we were to add functionality with similar effect as what the extension is trying to accomplish, we would likely make it built-in blocks rather than a component. If you need the functionality, just use the extension.
