### ISSUE TITLE
UI improvements on MIT app inventor website.

### ISSUE THREAD

**Issue by ABasral** [mit-cml/appinventor-sources#2345]
**Current Landing website of MIT App inventor has many bugs related to UI which can be improved and making it more clean and user friendly**

Current Website have issues like:
1.Buttons not properly aligned like learn more button on the banner, search button, more button on news and events cards, etc.
2. All the text is center aligned, which does not seem uniform, justifying text will create uniformity.
3. Proper padding is not present between elements.
4. Font size is not uniform.
5. It is not properly  
**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [x] Other... (UI of the website)

**Expected behavior**

**Steps to reproduce**

**Comment by Preet-Vadaliya** [comment]
Can you explain bit more about problem because i have confusion between builder ui or landing page of MIT App Inventor.

**Comment by ABasral** [comment]
> Can you explain bit more about problem because i have confusion between builder ui or landing page of MIT App Inventor.

I am talking about the landing page of MIT App Inventor.
![Screenshot (722)](https://user-images.githubusercontent.com/32901089/102609709-fc8a2380-4151-11eb-85e7-0de4ae090a51.png)

**Comment by Preet-Vadaliya** [comment]
Thank you for responding.
@ewpatton sir I want to work on this issue.

**Comment by ewpatton** [comment]
We will take these items under consideration. The website is managed using a separate system, so I'm going to close this issue as it is unrelated to this repository.
