### ISSUE TITLE
Too big cache.js file in use. 

### ISSUE THREAD

**Issue by hypotyposis** [mit-cml/appinventor-sources#2347]
I deployed the app inventor in manual way, it works well but one of the js files is too big(34MB actually). It takes decades for my backend to post it to frontend. the js file seemingly has not been compressed at all. I think compress it will greatly reduce its size thus i tried uglify-js but it doesn't work for me. Can anyone help me or give some advice?  Thanks a lot!

```
root@ac-dev:~/appinventor-sources/appinventor/appengine/build/war/ode# du -sh *
4.0K	0C0130491283766E7C2BD8410CB8A311.gwt.rpc
92K	279FAD9901DB5B0E48C990C3C648E084.cache.txt
96K	40978221ACF8DAF16CC3D034AC729D90.cache.txt
84K	57638CCECA544DE916ADEA6AE2DA2589.cache.txt
96K	87F102C773DCBA5272E8290BEF403897.cache.txt
16K	8BFF2A4E0FB0DA76103F79F8597CCA7B.gwt.rpc
100K	98A5C339D52C4AAB6468A1F79482EA86.cache.txt
92K	9C1250590D0A6AD06DDB6886997A2328.cache.txt
4.0K	B148609FF694DF5EC2B1F1FF1156BCC7.gwt.rpc
96K	B15E2D63BFC78A6717552F2502FF9D11.cache.txt
12K	C388B27375545154EC752193F1B58EF9.gwt.rpc
4.0K	clear.cache.gif
40K	compilation-mappings.txt
92K	D199DF325AD106E533E836A0E1F9CDAF.cache.txt
92K	D56A4ED871A380E578B316ABF7687EC5.cache.txt
4.0K	DC4EA60FE0821583DB5DCE49D2DA7CBA.gwt.rpc
34M	DEF13B3AD59919E6AA6FD70A613C9A55.cache.js #this is the big file
112K	E04C003FB91FBFD10816C467121C4CF6.cache.txt
4.0K	E31298273F9FCF3EAB1C3FC542664B56.gwt.rpc
96K	E4686C9796A0B44FFE8DD43AB192FF33.cache.txt
96K	E4986E548DA6C1AD868F1C6FEAC7B53F.cache.txt
92K	EFBECB5045B351E1EBA98716A28FA75D.cache.txt
4.0K	FFA8F452438BD688B163A593998CB1DB.gwt.rpc
16K	ode.devmode.js
20K	ode.nocache.js
4.0K	scrollTableLoading.gif
```

**Comment by ewpatton** [comment]
The default build creates a development build, not a production build. At a minimum, you should remove `<collapse-all-properties/>` from YaClient.gwt.xml. If you want to do more, you also need to add `-optimize 9` to the options in appengine/build.xml and change the mode from raw to simple in blocklyeditor/ploverConfig.js.

**Comment by hypotyposis** [comment]
> The default build creates a development build, not a production build. At a minimum, you should remove `<collapse-all-properties/>` from YaClient.gwt.xml. If you want to do more, you also need to add `-optimize 9` to the options in appengine/build.xml and change the mode from raw to simple in blocklyeditor/ploverConfig.js.

thank you! It works for me. And, where exactly should i add `- optimize 9` to the appengine/build.xml pls?

**Comment by ewpatton** [comment]
Locate the line that mentions -style pretty and replace that with -optimize 9

**Comment by iwanglian** [comment]
But as these , the output js is 4.3M,  also larger than official  1.3M.  How to reduce next?
