### ISSUE TITLE
Creating an API that takes in a project file (.aia file) and outputs an APK file.

### ISSUE THREAD

**Issue by sajeedmehrab** [mit-cml/appinventor-sources#2356]
I am working on a project that requires me to generate APK files from MIT App Inventor Project files (my_project.aia, for example). 

I am aware that I can do this by uploading the aia file to the App Inventor Server, building the project, and downloading the apk. I have run the app inventor server locally and can hence perform this step offline as well. 

I would like to make an end-to-end API where I can pass an aia as input and get the corresponding APK file, getting rid of the uploading aia and downloading apk steps.

I think this can possibly be done using MIT App Inventor’s codebase (from GitHub) by using the right source code files and calling the appropriate functions. I am very new to App Inventor and might be wrong though. Is there a way to do this?

**Comment by barreeeiroo** [comment]
Yes, you are right, you can programmatically export AI2 projects as APK by providing the AIA file. Actually, that is how the Companion is generated: you generate it from command line using `ant PlayApp`, and not from the "standard web UI". See [this ant build target](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/build.xml#L189) with the code that triggers the AIA to APK method.

To export apps as APK, you can run java with the [Main class in the buildserver](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/src/com/google/appinventor/buildserver/Main.java), and provide the AIA file with the argument `--inputZipFile` (as a ZIP file with the keystore). It will then build the APK and place it in the directory specified with `--outputDir`.

**Comment by sajeedmehrab** [comment]
@barreeeiroo Thank you so much!

I am getting a lot of compilation errors. Here's what I have tried:

I have built the project using ant from the appinventor folder. I have then tried compiling the Main.java file from the terminal using the javac command. The main error is caused by the absence of the package org.kohsuke.args4j. (package org.kohsuke.args4j does not exist)

I have also run the buildserver using ant, and tried compiling the Main.java from another terminal. I get the same errors. I was hoping that when I build the projects, the dependencies (packages) would automatically be taken care of.  

What am I missing here? And thanks again for taking the time!

**Comment by sajeedmehrab** [comment]
@barreeeiroo 
Should this [`ant build target`](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/build.xml#L318) do what you have just mentioned? 

I have tried running this with an input zip file (tried both .aia and .zip file). I get an error - "[java] SEVERE: Problem opening inout zip file: test.zip"

**Comment by ewpatton** [comment]
As mentioned this functionality already exists in the sources, so I'm going to close this issue as it is redundant. If you have further issues getting it to work in your environment please ask clarification questions in the [open source community](https://community.appinventor.mit.edu/c/open-source-development/10).
