### ISSUE TITLE
List of all functionalities and components in the App Inventor Sources

### ISSUE THREAD

**Issue by sajeedmehrab** [mit-cml/appinventor-sources#2357]
Which source code files are responsible for listing/generating all functionalities (blocks) for the components? The attached photo shows the functionalities for a button. Which source code files are responsible for all the components and their functionalities that we have in the appinventor website? 
<img width="457" alt="app_inventor_functionalities" src="https://user-images.githubusercontent.com/65396882/103347870-727f7a80-4ac2-11eb-9f31-bd4e64f3c2c2.png">

**Comment by rupesh-kumar-lpu** [comment]
MIT App Inventor uses a separate block editor based on a javascript library called Blockly. Blockly Editor is responsible for reflecting the respected blocks based on the components added in the designer frame. [Here](https://github.com/mit-cml/appinventor-sources/tree/master/appinventor/blocklyeditor/src) you can find the sources for Blockly Editor.
You may join the official MIT App Inventor Community Page to ask your queries https://community.appinventor.mit.edu/

**Comment by Preet-Vadaliya** [comment]
Basically all components are present in **`components`** folder under **`com.google.appinventor.components.runtime`** package and **`components.js`** `appinventor/blocklyeditor/src/blocks/components.js ` file is responsible for convert java code into blockly blocks.

**Comment by ewpatton** [comment]
I think @Preet-Vadaliya 's answer is the one you are looking for. However, in the future these types of questions are better asked in our [open source community](https://community.appinventor.mit.edu/c/open-source-development/10). This issue tracker is only used for bug/features.
