### ISSUE TITLE
Sound recorder not working on some phones

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#236]
A user claims that evey app that uses the sound recorder component crashes on some phones, including  THL 5000 and  the Elephone p8 Pro.  The phones are running Android 4.4.2.
Check whether this happens with 4.4.2 in general, or whether it's something about those phones.

Look here for the original comment

https://groups.google.com/forum/#!category-topic/mitappinventortest/16Pv_0WT_yc

**Comment by sjais789** [comment]
Sound recorder component is crashing on some devices because of microphone is not released from other process in start() method. We have to use the microphone.release() just after the start() function.

**Comment by jisqyv** [comment]
This *may* have been fixed in commit 8cbe40cfcf911f465d390577bb6ca5311f4a300f. I'm going to close this issue for now.
