### ISSUE TITLE
Block issue: replace all

### ISSUE THREAD

**Issue by tomer2526** [mit-cml/appinventor-sources#2360]
I recently discovered that if I try to replace the character: $ with the block replace all then it is not replaced (the character itself is deleted but not replaced with $), in addition if I attach the character ($) to the join block with a mathematical number I get an error.
My temporary solution is to use the character ＄ (this character is very similar to the $ character, but is less common - it is also not found on the keyboard)

Here is a link to aia: https://drive.google.com/file/d/1uzXb0_aud4aWXudGY27D_Px4yrG_AwDl/view?usp=sharing

**Comment by ewpatton** [comment]
I'm reclassifying this as a documentation issue for now. The replace all block allows for regular expressions, and the `$` is a special character indicating the end of the match. If you want to use `$` you need to escape it with a `\`, i.e., `\$`. This could be better explained in the documentation.

**Comment by tomer2526** [comment]
Got it, thanks for the explanation.  Is it necessary to close the issue?

**Comment by kmryashasvi** [comment]
You can close it if your motive of creating this issue is completed or if you dnt need any further improvement on this issue.
@tomer2526

**Comment by BeksOmega** [comment]
Please don't close this! As far as I know the documentation still needs to be updated.

But in general @kmryashasvi 's advice is correct =)

**Comment by JustinFrost47** [comment]
@ewpatton Can i work on this issue ?
