### ISSUE TITLE
The blocks area did not load properly / Empty block area

### ISSUE THREAD

**Issue by jonas-klein** [mit-cml/appinventor-sources#2364]
**Describe the bug**

When i load my project, there appears an error message: "The block area did not load properly. Changes to the blocks for screen ... will not be saved." (refer to the picture at the bottom. I've censored the code, i don't know if it contains sensitive information). I don't know, what i've did wrong. Yesterday, i saved my project and today, the errormessage appears and the block-view is empty. The backup from yesterday (aia-export to computer) leads to the same issue. How i can get back my code?

Ive remembered: I've added a string-block with some unprintable characters from ASCII, maybe this led to this issue?

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

> ![ai2 bug](https://user-images.githubusercontent.com/56542272/103668218-3000e680-4f77-11eb-9a2a-f7ad75eb20c8.jpg)

--
edit: This Issue occurs, among other, when a backspace appears in a string-block. But, the question remain: 
 - How to get back the code in case of use of an illegal character?

**Comment by importlogic** [comment]
Hello developers, 
I am new to open source and I already know Java and how to use Git and Github but I am not able to understand this project. Can anybody help me and point me in the right direction so I can know about the the technologies used in this project. I have been using MIT App Developer from a long time and now I want to contribute to this project.

**Comment by Preet-Vadaliya** [comment]
@importlogic 

Project is using **`Java, JS`** as a programming languages.

**Comment by patryk84a** [comment]
The error described here occurs when blocks that do not exist in the project have been added to the project. If there are expansion blocks in the backpack that are not in the design and we paste such blocks from the backpack then the design crashes. It is impossible to save the project, so no changes are made. It only helps to edit the AIA file manually and get rid of the bad blocks.
A similar error occurs when we add sample extension applications for Kodular to AppInventor. For example, if the project uses color blocks from Kodular, and we open this project in AppInventor, we get the error as above and the blocks are not visible.

**Comment by bobanss** [comment]
>     * How to get back the code in case of use of an illegal character?

Only doable by to editing the AIA file manually!

**Comment by ewpatton** [comment]
@jonas-klein If you have a sample project that exhibits the problem, it will help us to better understand how we can fix this issue.

**Comment by jonas-klein** [comment]
@patryk84a 
> ...It only helps to edit the AIA file manually and get rid of the bad blocks...

How is this possible? If im not mistaken, the aia-File is a binary one. Is there another programm, 
in which i can open these files?

@ewpatton 
I have already the work reconstructed on the basis of an older backup. You mean, i should upload the aia-File? Here it is. I've tried to send via serial bluetooth a null-char (0x00) to seperate two userinputs. The idea was to create a string-block from each ASCII-char and to extract a single char with the segment-block using a routine.

[Hauptuhr_Control.zip](https://github.com/mit-cml/appinventor-sources/files/5814492/Hauptuhr_Control.zip)

**Comment by bobanss** [comment]
@ewpatton It's the same issue I've reported two months ago https://community.appinventor.mit.edu/t/broken-project/19594?u=boban

![bild](https://user-images.githubusercontent.com/5558402/104613269-5e717680-5687-11eb-88fb-4afd820c947a.png)

@patryk84a here you have a working one [Hauptuhr_Control.zip](https://github.com/mit-cml/appinventor-sources/files/5815393/Hauptuhr_Control.zip)

https://community.kodular.io/t/n-b-note-observe-notice-chrome-might-delete-your-blocks-use-firefox/91567?u=boban

https://photos.app.goo.gl/6Ymw4aHucQTRSfvGA

**Comment by ewpatton** [comment]
@bobanss Yes I recalled seeing your post but wasn't finding it when I searched. I did some initial work on a fix at that time. I'll try to resurrect that work.

**Comment by ewpatton** [comment]
@bobanss @jonas-klein Potential fix #2370 deployed here: http://pr2370.ai2-ewpatton-temp.appspot.com/

**Comment by bobanss** [comment]
@ewpatton Works like a charm on Firefox..

**Comment by jonas-klein** [comment]
Yup, works like expected 🥇 nice, thank you
