### ISSUE TITLE
Let sound recorder specify the file where the sound is saved

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#237]
Add someething like canvas.saveAs, or add a property to soundRecorder to let users specify where the recording should be saved.

**Comment by ReachAayush** [comment]
Hello @halatmit,

Do you want users to be able to specify the path to where the recording is being stored?

If we added a method block to allow user to set fileName would this satisfy your request?

**Comment by halatmit** [comment]
I think it should be a property rather than a method.  I'll add this to the fix I'm currently making to SoundRecorder in PR #238

**Comment by halatmit** [comment]
This is implemented in pull request #238

**Comment by jisqyv** [comment]
MERGED
