### ISSUE TITLE
How to enable AI companion download link in self-deployed app inventor website?

### ISSUE THREAD

**Issue by hypotyposis** [mit-cml/appinventor-sources#2372]
I have deployed App inventor on my own server. I noticed that a download link should appear when the `about AI companion` button clicked. In which way could I enable this link?

**Comment by ewpatton** [comment]
You have to set the appropriate URLs at the bottom of YaVersion.java for those links to appear. In the future, you should ask questions of clarification in the [open source community](https://community.appinventor.mit.edu/c/open-source-development/10).
