### ISSUE TITLE
Question: How to set rendezvous server on AI companion for self-host AI?

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [mit-cml/appinventor-sources#2378]
Related to #2372, somehow, I suppose, but I am not sure.

**Comment by ewpatton** [comment]
In addition to running the rendezvous server code from under the misc directory, you need to specify the default rendezvous server in YaVersion.java and change the default rendezvous server in Screen1.yail of the companion you build. In the production companion, you can change the rendezvous server via the Settings menu item.

In the future, please ask clarifying questions in our [open source community](https://community.appinventor.mit.edu/c/open-source-development/10).
