### ISSUE TITLE
Select all projects checkbox

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2386]
**Describe the desired feature**

[From the forum](https://community.appinventor.mit.edu/t/suggestion-select-all-button-for-managing-projects/24506?u=ewpatton): It is suggested to add a checkbox in the upper left corner of the project list to select all projects, which could be useful for bulk emptying the trash, among other things.

**Give an example of how this feature would be used**

After removing multiple projects from the project list, being able to select all the projects to dump them from the trash would save time when cleaning up projects. For example, if a teacher is clearing out homework assignments.

**Why doesn't the current App Inventor system address this use case?**

One can manually check all the boxes, so this would serve as a convenience.

**Why is this feature beneficial to App Inventor's educational mission?**

This improves the project management process by both students and teachers.

**Comment by AnujSinghal12** [comment]
Hi! I would like to work on this issue. Can you assign it to me?

**Comment by ewpatton** [comment]
@AnujSinghal12 Sure. The necessary changes should mostly be scoped to ProjectList.java under the appengine module.
