### ISSUE TITLE
Only one project restored from trash even when multiple selected

### ISSUE THREAD

**Issue by AnujSinghal12** [mit-cml/appinventor-sources#2394]
**Describe the bug**

The restore button in the Deleted Projects menu only restores one project at a time even when more than one projects have been selected. The restored project is the one which is selected first. I came across this bug while working on the issue number #2386 
**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**
All selected projects should be restored.

**Steps to reproduce**

1. Select more than one project in the Deleted Projects menu.
2. Click on restore button.
3. Only the first project selected will be restored.

**Comment by AnujSinghal12** [comment]
Please assign this issue to me, I found the fix.

**Comment by ewpatton** [comment]
@AnujSinghal12 All set
