### ISSUE TITLE
How to complete translations?

### ISSUE THREAD

**Issue by hypotyposis** [mit-cml/appinventor-sources#2401]
I notice that App Inventor has offered many language translations. The Developers have done a good job. However, a few words are not translated yet. I want to do the localization job by myself. Take simplified chinese for example, it seems these 2 files——`OdeMessages.java` and `OdeMessages_zh_CN.properties`(both under `appinventor/appengine/src/com/google/appinventor/client/`) are related to translation. I cannot tell how it exactly works, can anyone give a brief introduction on how to add translated textfield by modify these files or other way? thx.

**Comment by ewpatton** [comment]
Please create an account at https://weblate.appinventor.mit.edu and then ping @SusanRatiLane with your username so she can grant you access.
