### ISSUE TITLE
Parameter moving under cursor cancels field editing

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2402]
**Describe the bug**

![6760a473e83aedae1db609b18aae8225ce4c483c](https://user-images.githubusercontent.com/1331253/106007597-7b914680-6084-11eb-9d71-446f2bb2ad9f.gif)

(GIF courtesy of @PeterMathijssen)

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The flydown should not open when the edit field is focused.

**Steps to reproduce**

See GIF.

**Comment by Siddharth1010** [comment]
Hi @ewpatton, I would like to work on this. Could you please let me know which file this issue lies in?

**Comment by ewpatton** [comment]
@Siddharth1010 I haven't looked into it yet, but I expect that what needs to be done is in to add another check in field_flydown.js in `showFlydownMaker_` that tests whether `Blockly.WidgetDiv.DIV` is non-null.

**Comment by Siddharth1010** [comment]
@ewpatton There does not seem to be a `Blockly.WidgetDiv.DIV` component in `field_flydown.js ` . I had added `Blockly.WidgetDiv.Div != null` in `showFlydownMaker_` . But on executing `ant tests` the Blockly tests seem to be failing.
![image](https://user-images.githubusercontent.com/59433969/106091735-050f4a00-6153-11eb-846b-58ce685ea5e4.png)

Also, I am unable to reproduce this exact issue using a procedure block. Could you please guide me?
![image](https://user-images.githubusercontent.com/59433969/106091865-40117d80-6153-11eb-9d78-509c40d5eeef.png)

**Comment by patryk84a** [comment]
You need to add an input variable to the procedure. Click on that blue badge in the upper left corner of the block.

**Comment by Siddharth1010** [comment]
@ewpatton @patryk84a , Yes I have added an input variable and I am able to recreate the issue. But isn't this issue related to `Blockly.FieldTextInput` as opposed to `Blockly.WidgetDiv.DIV`?

**Comment by BeksOmega** [comment]
> @ewpatton @patryk84a , Yes I have added an input variable and I am able to recreate the issue. But isn't this issue related to `Blockly.FieldTextInput` as opposed to `Blockly.WidgetDiv.DIV`?

Hi @Siddharth1010 =) The widget div is non-null whenever a text input field is being edited (the place where your text goes when you're typing is the widget div). So If you only want the flydown to open when a text input field is /not/ being edited, you should be able to use the widget div to check for that state. I hope that helps!

**Comment by Siddharth1010** [comment]
Hi @BeksOmega , thank you so much :) . So logically, if we check `Blockly.WidgetDiv.DIV===null` (not being edited) in the `showFlydownMaker_` function, it should work. And it does, sort of. The problem is, now the flydown does not show up at all. Even if I am not editing the text field.

Fix:

![Peek 2021-01-30 20-44](https://user-images.githubusercontent.com/59433969/106360090-9d1c5780-633c-11eb-914b-5b8cc29ed62d.gif)

Problem:

![Peek 2021-01-30 20-45](https://user-images.githubusercontent.com/59433969/106360103-aad1dd00-633c-11eb-893b-0f3cbcd69793.gif)

Please let me know if I am doing something wrong

**Comment by BeksOmega** [comment]
> Hi @BeksOmega , thank you so much :) . So logically, if we check `Blockly.WidgetDiv.DIV===null` (not being edited) in the `showFlydownMaker_` function, it should work. And it does, sort of. The problem is, now the flydown does not show up at all. Even if I am not editing the text field.

Hmmm you're right it looks like DIV never gets set back to null after it's created... maybe try the `Blockly.FieldTextInput.htmlInput_` instead? It looks like it gets [set](https://github.com/mit-cml/blockly/blob/99604ec642a36d202e04533076ddf80f6eb009dc/core/field_textinput.js#L185) and [unset](https://github.com/mit-cml/blockly/blob/99604ec642a36d202e04533076ddf80f6eb009dc/core/field_textinput.js#L343) properly hehe

Thank you for looking into this!

**Comment by Siddharth1010** [comment]
@BeksOmega Yes  `Blockly.FieldTextInput.htmlInput_` seems to be working fine :)

![Peek 2021-01-30 21-49](https://user-images.githubusercontent.com/59433969/106361898-e4f3ac80-6345-11eb-9eac-9f6cb18b3a96.gif)

Shall I create a pull request?

**Comment by BeksOmega** [comment]
> Shall I create a pull request?

@Siddharth1010 I'm not an official maintainer hehe, but I'd say it looks like you're good to go!

**Comment by Siddharth1010** [comment]
@BeksOmega Oh okay. Thank you for your help  :)

**Comment by patryk84a** [comment]
Will the fix work for other blocks as well?

**Comment by BeksOmega** [comment]
> Will the fix work for other blocks as well? The same situation is also with the block of the procedure returning result. The same applies to local variables when we add more than one variable to the same block.

Yeah it should fix all of the relevant blocks because the fix is in the root cause (the field). So you should be good! Be sure to write back if you find anything else that isn't working though :D
