### ISSUE TITLE
Dictionary constructors coerces list-of-lists to dict

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2408]
**Describe the bug**

[Forum post](https://community.appinventor.mit.edu/t/problem-with-dictionary-of-list-of-lists/25850/2?u=ewpatton): Passing a list-of-lists as a value in the dictionary constructor converts it into a dictionary unexpectedly. Using a set block to update an empty dictionary does the correct thing (storing the list in the dict).

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The value should be stored unmodified in the dictionary.

**Steps to reproduce**

1. Create a list of lists
2. Create a dictionary, setting mapping a string key to the list-of-lists value
3. Print the dictionary using Do It or a label, observe that the what should be a list of lists is now a dictionary

**Comment by AnujSinghal12** [comment]
Hi I'd like to work on this issue, could you assign it to me?

**Comment by ewpatton** [comment]
@AnujSinghal12 Go for it!

**Comment by AnujSinghal12** [comment]
There are 3 constructors for `makeDictionary` in YailDictionary.java under components , to test out which one help the bug I replaced then with methods which return an empty dictionary. This did not change anything in the app i was using to test (I'm using the same app as the one used in the forum thread), it they still returned the same Dictionary as it was doing prior to me editing the code to return empty Dictionary. Am I looking in the wrong place?

**Comment by ewpatton** [comment]
runtime.scm invokes `makeDictionary(List<Pair>)`, and looking at that method it branches if the list is an alist. My guess is that we want to eliminate that branch and always take the else condition.
