### ISSUE TITLE
Add Try To Catch The Exception

### ISSUE THREAD

**Issue by RajaHarshVardhanSolanki** [mit-cml/appinventor-sources#2418]
**When the user use GET, POST, DELETE methods when the internet off it show the error.**

**Affects**
User get the internal function of the app, That is How the app works?

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**
Not Get The Notifier from the web component directly, Instead of Error Event

**Steps to reproduce**
Just Off Internet and Try to use GET, POST, DELETE methods from the blockyeditor , Compile app use it in real android device. Get the error message from notifier but not from the Error EventDispatcher.

![Screenshot_20210225_182708](https://user-images.githubusercontent.com/77908087/109159444-a0b7c880-779a-11eb-9763-04a3c6395239.jpg)

Get error like this directly by the Web Component.

**Comment by puravidaapps** [comment]
it seems to be, you forgot to use the Screen.ErrorOccurred event... because there you can catch that error...
btw. next time you first might want to ask in the community before opening an issue at Github...
Taifun

**Comment by RajaHarshVardhanSolanki** [comment]
Thanks I Forgot About That Event Completely.

**Comment by RajaHarshVardhanSolanki** [comment]
Thanks I Forgot About That Event Completely.
