### ISSUE TITLE
How Api calls works?

### ISSUE THREAD

**Issue by znyrpavithra** [mit-cml/appinventor-sources#2424]
How api calls like ode/userinfo and ode/projects works? If all of them are post requests, what data is sent? Can anyone explain them?

**Comment by ewpatton** [comment]
The calls are made via GWT RPC and encode the function and its arguments to be executed on the server. In the future, please ask any clarifying questions in the [open source community](https://community.appinventor.mit.edu/c/open-source-development/10).
