### ISSUE TITLE
In which file api's are written and how the process work ?

### ISSUE THREAD

**Issue by samsu007** [mit-cml/appinventor-sources#2425]
In which file api's are written and how the process work ?
1. user information get api
2. project list api
3. components update api
4. new user add api

**Comment by ewpatton** [comment]
You'll find the implementation of most of these in either CommonProjectService.java or YoungAndroidProjectService.java. I'm not sure what you mean by "components update api". For future clarifying questions, please ask them in the [open source community](https://community.appinventor.mit.edu/c/open-source-development/10).
