### ISSUE TITLE
Implement another event("If Changed"-block) for the input field

### ISSUE THREAD

**Issue by Shipyde** [mit-cml/appinventor-sources#2431]
Hey,
Could you implement another "If" block with the function that whenever a new input is made something should be executed for the input field.

Such a function is somewhat missing for me, since the "focus" does not achieve the desired effect.

- ShipyDe

**Comment by ewpatton** [comment]
Do you mean an event block? "if" is a control block and part of the built-in blocks, but TextBox (the closest thing we have to an input field) is a component. Something like a when TextBox1.Changed event is what you'd need?

**Comment by Shipyde** [comment]
Oh sorry, but yes exactly, that's what I meant. 
It shouldn't be too difficult to implement this event or am I wrong?

Can I actually extend such an event via extension or would that not work?

**Comment by easrng** [comment]
I would also like this to be implemented. I am using a Clock timer to check for changes every 10 ms I think which obviously isn't ideal.

**Comment by ewpatton** [comment]
@Shipyde You could probably implement it as an extension, but it's probably better for the whole community if it were added as a built-in block. This is especially true if you'd like to be able to use it in apps built for iOS.

**Comment by ewpatton** [comment]
This was resolved by #3093
