### ISSUE TITLE
Separate Sign in option without using Google id.

### ISSUE THREAD

**Issue by gourish3** [mit-cml/appinventor-sources#2437]
**Describe the desired feature**
Whenever we try to login it asks for the Google account . We can use a sign up and sign in option which may help students to use it without having a google id.
A new feature of Sign in Option

**Give an example of how this feature would be used**
In the starting it will ask for the method you want to sign in through.

By creating their separate ID of students and teachers so that teacher can see the students progress without any need of gmail id.

**Why doesn't the current App Inventor system address this use case?**

**Why is this feature beneficial to App Inventor's educational mission?**
Cause it will help the students and teachers to see others work without needing an gmail id password of other person.

**Comment by ewpatton** [comment]
If you need to not use a Google account, we recommend using [code.appinventor.mit.edu](http://code.appinventor.mit.edu) instead as it has an option to use App Inventor anonymously.
