### ISSUE TITLE
Spelling error in TextToSpeech documentation

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2438]
The TextToSpeech component's documentation calls it TestToSpeech in the first line. This can be corrected by editing the description in TextToSpeech.java and rebuilding the documentation.

**Comment by AnujSinghal12** [comment]
This is present in multiple default messages spread across the codebase, a quick search gave me around 10 matches in java and json files. Should be a quick fix, may I work on it?

**Comment by ewpatton** [comment]
@AnujSinghal12 Sure.

**Comment by gourish3** [comment]
Can you please assign me any beginner issue?

**Comment by gourish3** [comment]
@ewpatton Can you please assign me any beginner issue?

**Comment by preetvadaliya** [comment]
@gourish3 this issue is already assigned to @AnujSinghal12 so you can tack look into another issue use **Help Wanted** tag for beginner issue.
