### ISSUE TITLE
I would like to contribute to MIT app inventor

### ISSUE THREAD

**Issue by akash-kd** [mit-cml/appinventor-sources#2442]
I am Akash K, I have used this web application since my school days. I am very huge fan of this app. I would very much like to contribute to this, but i don't know where to start could any help with this?

**Comment by Himanshu2107** [comment]
From [this](https://community.appinventor.mit.edu/t/introduction-to-google-summer-of-code-2021/23739) post on the [community website](https://community.appinventor.mit.edu/).

To get started with App Inventor, we recommend that you review the following documents and get your environment set up correctly.

- GitHub Readme: https://github.com/mit-cml/appinventor-sources 
- Contributing to the MIT App Inventor Sources: https://docs.google.com/document/d/1ZJlh5-U-eLAxXTvK2QxIrJklC3EjZgsavbIFe4FhxyA/edit#heading=h.57b2hufh8hwc 
- How to build App Inventor from the MIT sources: https://docs.google.com/document/d/1Xc9yt02x3BRoq5m1PJHBr81OOv69rEBy8LVG_84j9jc/edit 
- How to add a property: https://docs.google.com/document/d/1ukpZXcd0fIn1fV0cNp4J00wrfwwA1daswU1yY6dqqfs/edit 
- How to add a component: https://docs.google.com/document/d/1xk9dMfczvjbbwD-wMsr-ffqkTlE3ga0ocCE1KOb2wvw/edit 

We have a set of issues labeled "Help Wanted": https://github.com/mit-cml/appinventor-sources/issues?q=is%3Aissue+is%3Aopen+label%3A"help+wanted". This is the best place to find ways to contribute.

You should ask these type of questions on the community website. Only report issues with the sources here.

**Comment by halatmit** [comment]
Dear Hyojae,

Thanks for asking about App Inventor.  It's great that you've been  working
on it and would like to improve the platform.
We don't have the staff available at MIT to work personally with
volunteers, but we encourage you to join the App Inventor Community Forum
<https://community.appinventor.mit.edu/> which includes experienced
developers who can give you help and advice.  You are also more than
encouraged to work on our own and in collaboration with others.  For system
development,  the App Inventor code base is available on Github at
https://github.com/mit-cml/appinventor-sources.    Feel free to
experiment.  Good luck, and be sure to post any interesting results to the
forum.

== Hal

Hal Abelson
***@***.***
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.


== Hal

Hal Abelson
***@***.***
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by akash-kd** [comment]
thanks for the response and i will sure check it out..

**Comment by ewpatton** [comment]
Closing this for now. Discussion should continue in the [community](https://community.appinventor.mit.edu/c/open-source-development/10).
