### ISSUE TITLE
Really Need a Processing Dialog Message

### ISSUE THREAD

**Issue by EnisM** [mit-cml/appinventor-sources#245]
This probably isn't that difficult to do and it would be VERY helpful, especially in situations when you know what you're going to do in AI Code will be time consumptive...

![prog1](https://cloud.githubusercontent.com/assets/10585909/6051391/a9480158-ac95-11e4-84b8-50f4c5738612.png)

Could have two blocks... one to turn it on and add a message:
![waitingblock1](https://cloud.githubusercontent.com/assets/10585909/6051140/7bcbb758-ac93-11e4-84e8-39e66b2f1e03.PNG)

And a simple block to hide or turn it off...
![waitingblock2](https://cloud.githubusercontent.com/assets/10585909/6051074/edb3ed32-ac92-11e4-935a-7272d661ece6.PNG)

**Comment by halatmit** [comment]
This should probably be a emthod in the Notifier component, rather than a separate component.

**Comment by EnisM** [comment]
Agreed, if it doesn't screw the Notifier up... It would be MUCH clearer if it could be included in the Notifier component because it is indeed, a notifier of sorts!

**Comment by kkashi01** [comment]
How about:
ProgressShow(String title, String message)   //if empty title, then remove title -- always cancellable
and
ProgressDismiss()  // cancels if already on

**Comment by EnisM** [comment]
No need for title... just message... These things don't usually have titles... just a simple message telling the user what's going on in the background (please stand by, Loading File, Merging Text etc.)

**Comment by jisqyv** [comment]
#268 Merged into master. ProgressDialog added.

**Comment by EnisM** [comment]
Thanks Jeff... Can't tell you how useful this will be.  Very much
appreciated...

**Comment by jisqyv** [comment]
@EnisM Thank Yash, he did the work. I just reviewed it...

**Comment by EnisM** [comment]
Yes, I know, but you merged it and that means it's coming...

Thanks Yash... really appreciated...
