### ISSUE TITLE
Show project name dialog when uploading a project with an invalid name

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2453]
**Describe the desired feature**

Currently, if you attempt to import a project, either through the drag and drop approach or through the Import from my Computer menu item, and another project exists with the same name, the import will be rejected. Similarly, if the AIA file has an invalid name, such as "HelloPurr (4).aia", this will also be rejected. In the case where there is a collision of names or the name is invalid, we should show the project name dialog instead to let the user specify a new, valid name, and then use that when importing the project. Bonus points if the dialog suggests a valid name that isn't colliding with an existing project name. For example, if they have HelloPurr in their project list and the AIA is called HelloPurr.aia, propose HelloPurr2.

**Give an example of how this feature would be used**

Often when working with multiple copies of the same project, one might want to import an older version for comparison. This currently entails juggling the filenames to make them palatable to App Inventor. The proposed change would make it easier for people (especially teachers) who might have many project files with the same name.

**Why doesn't the current App Inventor system address this use case?**

The current behavior is to reject the import outright, placing the burden on the user if they've forgotten to rename the file to something more appropriate.

**Why is this feature beneficial to App Inventor's educational mission?**

See previous note about teachers having to import potentially many projects with the same name, such as assignments submitted by students.

**Comment by AKandAK** [comment]
**What should be the behaviour when the user enters a new name and there exists a project with that name too**
1.Should we show the new project name dialog box repeatedly until the user enters proper name or clicks cancel button
2.Or Show an error and reject the import straight away (similar to the current behaviour)

I would like to work on this issue if you could assign me

**Comment by ewpatton** [comment]
Option 1 is what I am envisioning for this change.

**Comment by AKandAK** [comment]
From the above PR #2475 the new feature does the following :
1.If  projects HelloPurr , HelloPurr3  exists and user uploads another HelloPurr.aia then a dialog box is shown to enter a new valid name which suggests "HelloPurr4".
2.If a project with invalid name or reserved name is uploaded then dialog box is shown to enter a new valid name.

**Comment by Aarshhh** [comment]
@ewpatton I would like to work on this issue.

**Comment by ewpatton** [comment]
@Aarshhh This issue was resolved by #2475, but wasn't closed when the PR was merged. I'll close it now.
