### ISSUE TITLE
Build Failed with the newest version of source code.

### ISSUE THREAD

**Issue by hypotyposis** [mit-cml/appinventor-sources#2459]
I git cloned the newest version of source code and try to deploy it in the manual way. I use the `./buildtools doctor` and it returns
```
[PASS] Java is installed.
[PASS] Required version of Java is installed.
[PASS] Git is installed.
[PASS] Git submodules are properly set up.
[PASS] Google Cloud SDK is installed.

Passed 5 checks and 0 failing
```
and my environment should be ok because an old version(cloned like 6 months ago) of App Inventor still runs well on this server.
The error information is below:
```
BUILD FAILED
/root/CodingBackup/appinventor-sources/appinventor/build.xml:16: The following error occurred while executing this line:
/root/CodingBackup/appinventor-sources/appinventor/appengine/build.xml:581: Java returned: 137
```
and line 581 of `build.xml` is
```
 <java failonerror="true" fork="true" classname="com.google.gwt.dev.Compiler">
```
Maybe I have missed something or there is bugs with the latest version? Thanks for your help.

**Comment by ewpatton** [comment]
`master` is building cleanly for us. Please ask issues around failed local builds in the open source community: https://community.appinventor.mit.edu/c/open-source-development/10. Please include the full output of the `ant` command in your post.

**Comment by hypotyposis** [comment]
> `master` is building cleanly for us. Please ask issues around failed local builds in the open source community: https://community.appinventor.mit.edu/c/open-source-development/10. Please include the full output of the `ant` command in your post.

Thank you for replying. I have solved this problem, the causes of error are:
1. 4GB Memory is not enough for building project.
2. If it is builded under Ubuntu 20.04, should manually prevent JDK token verification by `sudo vim /etc/java-8-openjdk/accessibility.properties` and comment out the following line : `assistive_technologies=org.GNOME.Accessibility.AtkWrapper`
