### ISSUE TITLE
Clean up BluetoothConnectionBase and its descendants

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2471]
Currently, the Bluetooth code uses reflection to perform many operations to account for the fact that Bluetooth support was introduced in Android SDK 5 but App Inventor originally targeted SDK 3/4. Now that our min SDK is 7, we can remove the use of reflection for Bluetooth related operations and get the benefit of the static typing in the Java language. This will also simplify many of the code paths were reflection operations need to be checked for success/failure.

**Comment by gourish3** [comment]
Can I work on this?

**Comment by ewpatton** [comment]
Fixed by #2993
