### ISSUE TITLE
Allow NumbersOnly property on PasswordTextBox

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2477]
**Describe the desired feature**

The TextBox component has a NumbersOnly property for enforcing that the input only contain numbers. Support for this feature on the PasswordTextBox would enable the ability to have numeric PIN entry, for example.

**Give an example of how this feature would be used**

**Why doesn't the current App Inventor system address this use case?**

**Why is this feature beneficial to App Inventor's educational mission?**

**Comment by preetvadaliya** [comment]
@ewpatton can I work on this issue?

**Comment by ewpatton** [comment]
@preetvadaliya Sure.

**Comment by preetvadaliya** [comment]
@ewpatton Sir please close this issue.

**Comment by ewpatton** [comment]
@preetvadaliya Sure. In the future if you use `fixes` or `closes` in the PR along with the number GitHub will automatically close it when we merge.
