### ISSUE TITLE
Image out of boundaries on resize

### ISSUE THREAD

**Issue by Himanshu2107** [mit-cml/appinventor-sources#2502]
**Describe the bug**
Sometimes when an image (ImageSprite or Image component) is resized it does not respect its boundaries. The image may be much smaller than its boudaries or it may spill out of them.

![image](https://user-images.githubusercontent.com/53406453/122939382-30f4cb80-d391-11eb-9d47-a724ead3d7de.png)
![image](https://user-images.githubusercontent.com/53406453/122939559-5a155c00-d391-11eb-906b-a1db2d85d86e.png)
 

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**
The image should remain inside the boundaries.

**Steps to reproduce**

1. Associate an ImageSprite or Image component with an image.
2. Play around with the height and width values to observe than on some changes the image is not scaled appropriately with respect to its boundaries.

**Comment by ewpatton** [comment]
@Himanshu2107 should I assign this to you?

**Comment by Himanshu2107** [comment]
Sure.
