### ISSUE TITLE
Spanish version - Button event

### ISSUE THREAD

**Issue by OmgCopito95** [mit-cml/appinventor-sources#2504]
**Describe the bug**

The spanish version of the Blocks editor has a misspelling. The spanish name of the event "GotFocus" (button component) is "ObtenertFocus".

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The name of the event must be call ObtenerFoco, without a T before F.

**Steps to reproduce**

![button](https://user-images.githubusercontent.com/18623248/123195054-e69d4880-d47d-11eb-8394-8bb2204640b2.png)

**Comment by OmgCopito95** [comment]
I had noticed that all the events "GotFocus" have the same problem with the spanish name.

**Comment by aliaia744046** [comment]
Hello my friends, 
how are you doing and work? 
I would like to translate as you do, but for Arabic, how can I do this? Can you explain the use? I tried a program that translates applications, but it does not translate the emulator, can you help me, knowing that I am a fast learner

**Comment by SusanRatiLane** [comment]
> Hello my friends,
> how are you doing and work?
> I would like to translate as you do, but for Arabic, how can I do this? Can you explain the use? I tried a program that translates applications, but it does not translate the emulator, can you help me, knowing that I am a fast learner

We would be delighted to have help with our Arabic translation. If you wish to do this, please contact me on our community forum https://community.appinventor.mit.edu

I can help you there.

**Comment by aliaia744046** [comment]
I am in the community. Is there a special topic there for translation? I want to start translating everything with it. How do we get started can you help me

**Comment by aliaia744046** [comment]
نعم يمكنكِ مساعدتنا في ذالك

سوف يفرح هذا الفريق الذي اقوم بجمعه بعد اكمال امتحانات طلبتنا

الطريقة جيدة يمكنك التعلم بسرعة لكن توجود شروط بعض الجمل صعبة اود ان تتركها
لان لدي مترجم يقوم بلاعمال الصعبة يمكنك ارسال الجميل الخاص بك لبدأ اعطاء
موافقة ايضا سوف ارسل اليك رابطا لموقع ويب الخاص بلترجمة و بعدها نرسل الى
mit طلب للموافقة
شكرا للمساعدة
و ايضا يوجد برنامج تعليمي سوف اقوم بأرساله
لدي سؤال ما امكانية لغتك الانكليزية من نسبة ١٠٠ %


في الجمعة، ١٦ يوليو ٢٠٢١ ٥:٤٤ م Evan W. Patton ***@***.***>
كتب:

**Comment by aliaia744046** [comment]
https://youtu.be/VFwTn32MrBw

رابط البرنامج التعليمي
Tutorial link

في الاثنين، ٢٨ يونيو ٢٠٢١ ٥:٥٤ م Susan Rati Lane ***@***.***>
كتب:
