### ISSUE TITLE
Fix the activity starter and documentation

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#251]
The documentation in  "How to Use the Activity Starter" is obsolete.  And many of the examples are now wrong,  See

https://developer.android.com/guide/components/intents-common.html

Upgrade the activity starter so that is can handle most (all?) of the examples on the common-intents page, and maybe more.   This should  be.   App Inventor users should be able to provide a lot of keys rather than just the fixed set of keys used now.  Probably this should be done with a list of pairs ((key1 data1) (key2 data2) ....).
One issue to consider is how to deal with data types in the case where the values as no strings.

**Comment by E-Hon** [comment]
@halatmit the tasks are to 
1. upgrade activity starter to support the common-intents listed on the site
2. allow users to use more than one key-value pair for extra data
3. update the obsolete doc
is it correct?

**Comment by halatmit** [comment]
Yes, this is correct.   Note that some activities might use various keys for returning data.  
Thanks.

**Comment by E-Hon** [comment]
@halatmit 
for 2, can we simply allow users to enter comma-separated values into ExtraKey and ExtraValue such that the first key corresponds to the first value, etc?

**Comment by halatmit** [comment]
You can have a mode where users enter in CSV format, but also provide a way to specify the keys,values as  actual list of pairs.  It's similar to how ListPicker has both Elements (a list) and ElementsFromString (a comma-separated string).   You might want to restrict the CSV form to where the values a strings without spaces so you don't get into issues about quoting the input elements, or create an adhoc input notation.  In the long run, we need to provide dicsionaries and JSON input format, but I'd like to not get into that yet. 

On second thought, it might be better to not include the CSV format, so as to avoid these issues.   The people who would be using the activity starter would probably prefer the list-of-pairs form anyway, since most of those inputs would be computed and/or the actual call to activityStarter would be from another procedure.

**Comment by E-Hon** [comment]
see #424

**Comment by halatmit** [comment]
#424 was merged.  Closing this issue
