### ISSUE TITLE
Can the hint color of the textbox be set? Question from a appathon participant.

### ISSUE THREAD

**Issue by PeterMathijssen** [mit-cml/appinventor-sources#2519]
**Describe the desired feature**

You should be able to change the hint color of the textbox. 
![image](https://user-images.githubusercontent.com/32273650/127020344-84e0233a-d74e-43e4-9b71-4946811dcfdf.png)

**Give an example of how this feature would be used**
You could do more customizing in the app. Setting in designer and via blocks. You could change colors for negative or positive numbers. 

**Why doesn't the current App Inventor system address this use case?**

This option is not available in the component.

**Why is this feature beneficial to App Inventor's educational mission?**

Not especially beneficial for the educational mission.

**Comment by ewpatton** [comment]
Resolved by #3093
