### ISSUE TITLE
ListView filter crashes in nb187

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2550]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/listview-filter-keeps-crashing-nb187-bug/40086?u=ewpatton): The filtering capability in the new ListView crashes the companion.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Filtering should not crash the app.

**Steps to reproduce**

**Comment by Trisystema** [comment]
What can we do instead of using listviews until this issue is fixed?
