### ISSUE TITLE
b4557d64c8938e60298e5376157365c0c98a6b72

### ISSUE THREAD

**Issue by tabacojt** [mit-cml/appinventor-sources#2560]
**Describe the bug**

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

**Steps to reproduce**

**Comment by ewpatton** [comment]
Marking this as invalid and closing without more information.
