### ISSUE TITLE
type blocking on join block

### ISSUE THREAD

**Issue by kkashi01** [mit-cml/appinventor-sources#257]
When performing type blocking on join, it returns the block with no sockets. I believe previously, it was returning 2 sockets.
![image](https://cloud.githubusercontent.com/assets/8935543/6193436/2f1958be-b389-11e4-90dd-1136bb53803d.png)

**Comment by josmas** [comment]
This is happening to all blocks with mutators (try + or * in math, or 'add items to list').

**Comment by jisqyv** [comment]
Fixed by #258 which is merged.
