### ISSUE TITLE
Typeblocking fails for some blocks

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2576]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/typeblocking-is-quite-buggy/42530?u=ewpatton): The any component blocks do not appear to work with typeblocking. The for each element in list block also does not appear.

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

All blocks should be instantiable via typeblocking.

**Steps to reproduce**

Attempt to create any component blocks using typeblocking. The string will not include any information about the target event name (see the post for details).

**Comment by preetvadaliya** [comment]
@ewpatton Typeblocking for block `for each number from is also not working properly.

**Comment by preetvadaliya** [comment]
@ewpatton, sure I would like to work on this can you please assign it to me?

**Comment by ewpatton** [comment]
Fixed by #2586
