### ISSUE TITLE
Add menu item to remove all orphaned blocks

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2582]
**Describe the desired feature**

[From the forum](https://community.appinventor.mit.edu/t/no-way-to-mass-delete-orphaned-blocks/43110?u=ewpatton): During experimentation, one may accumulate many disconnected blocks that are not top level blocks. It may be desirable to clean up (i.e., delete) any non-declaration block (i.e., those blocks that aren't global definitions, procedure definitions, event handlers). It would be useful to add a new menu item to the Blockly workspace to delete any orphaned blocks. We should prompt to confirm the user intends to take this action, similar to deleting all of the blocks in the workspace.

Another potential design might be to provide this option behind a key combo. For example, on macOS you can often hold the option key to see additional menu items or alternative interpretations in the same spot. We might have "Delete all blocks (#### blocks)" and then when option is held show "Delete orphan blocks (#### blocks)". This would keep the context menu from becoming too cluttered.

**Give an example of how this feature would be used**

The feature would be used to keep the code clean and workspace uncluttered.

**Why doesn't the current App Inventor system address this use case?**

It does not provide this functionality. People can manually go around deleting unattached blocks (such as through the warning stepper buttons), but this may be cumbersome.

**Why is this feature beneficial to App Inventor's educational mission?**

The functionality can be used to help students maintain clean, understandable code during and after working on a project.

**Comment by devarsh-mavani-19** [comment]
Hi @ewpatton  i would like to work on this feature. can i get some guidance regarding same? I tried exploring blockly folder but couldn't find anything that can help.

**Comment by ewpatton** [comment]
Fixed by #2638
