### ISSUE TITLE
Create simple ways  for people to use the Intel HAX modue and/or Genymotion

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#260]
Both of these approaches can speed up and improve the use of the emulator, but are not simple to install.   We could provide documentation and/or some help from our installer.   How well can we do?

The HAX information is at
https://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager

and setup documentation for my class with Genymotion is at 

https://docs.google.com/document/d/1x1zvXGPQ2HhSRh2wKVsEHmIOGcaIElnGBsHnr1Pn8tA/edit

**Comment by EnisM** [comment]
I can help with this... I think the only difficult part is setting up Oracle's VirtualBox, which at first I struggled with a bit as I didn't understand all of the options...

**Comment by ewpatton** [comment]
The latest Windows emulator package installs and uses HAXM. Updates to the macOS and Linux versions will follow.
