### ISSUE TITLE
http://phantomjs.org/ 

### ISSUE THREAD

**Issue by I-Cat** [mit-cml/appinventor-sources#2604]
@ewpatton

In your readme.md It ponits to http://phantomjs.org/ but the information says phantomjs is suspended.

**Comment by preetvadaliya** [comment]
Because of lack of contribution phantomjs is suspended but that doesn't mean that we can't use phantomjs anymore.

**Comment by ewpatton** [comment]
We continue to use phantomjs for running some of our unit tests. Eventually I'd like to migrate to another option, but we don't have a timeline to do so. In the meantime you can still use phantomjs and our Jenkins CI will continue to use it.
