### ISSUE TITLE
Player bug

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#261]
I think the issue is that the player isn't released when the app exits

See this thread for the issue, and a test case:

https://groups.google.com/forum/#!msg/app-inventor-dev/M7gPjTwx6Q8/HfSuzGNUIIMJ

**Comment by Momoumar** [comment]
I am using the latest version of MIT App Inventor Companion v2.26 and I am also experienced this:
**How to reproduce**
Using the aia file Taifun made: 
https://groups.google.com/group/app-inventor-dev/attach/83205463ccaef41d/soundrecorder.aia?part=0.1&authuser=0&view=1

1. Record a sound 
2. Press Start to play the sound
3.Simulate a call and hangs up immediately, the previous sound will start playing
3. Or receive a notification, the  previous sound will start playing

I am trying to fix this, but I am a bit lost with the player state (0,1,2,3,4)

**Comment by halatmit** [comment]
The meanings of the states are described in Player.java at line 103.

I haven't tried to debug this, but it seems that the error could be at
onResume in relation to state 4.  Try adding some print statements to show
the state at various points for the rpocessing when the phone call starts
and ends.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by Momoumar** [comment]
I haven't paid attention to the description  of the states.
Thanks @halatmit for the hint, I will try that.

**Comment by halatmit** [comment]
pull request #390

**Comment by jisqyv** [comment]
Fix merged into "ucr" branch and will be in the next component release
