### ISSUE TITLE
Mit app inventor with adcolony ads

### ISSUE THREAD

**Issue by MDAmTrailer** [mit-cml/appinventor-sources#2628]
![Screenshot_20220105-141736](https://user-images.githubusercontent.com/77635809/148965250-96c4d625-c30f-4326-a1dd-ae36569cae04.png)
![Screenshot_20220105-141730](https://user-images.githubusercontent.com/77635809/148965284-a254a377-c9a8-4b51-8449-dacef3a5e7d5.png)
![Screenshot_20220105-141723](https://user-images.githubusercontent.com/77635809/148965326-87fa4766-b919-456f-b830-f58fb7ff2ec8.png)

![Screenshot_20220105-141723](https://user-images.githubusercontent.com/77635809/148965217-72b7525d-35d5-4f55-ae50-b9760139361f.png)
 
@MDAmTrailer MDAmTrailer commented 2 minutes ago
hello
i am really need help with my adcolony ads
i use mit app inventor and dont't know how to make blocks ni my apps about :
1- write/read external storage premission
2- vibrates premission
3- keep screen on
this is my issue please help i depend on you .
this is some screenshot about issue in adcolony that i need help with it
Screenshot_20220105-141701
i solve the error and if someone can solve this one
4- GDPR

**Comment by oseamiya** [comment]
I guess you should ask them on AI2 community : https://community.appinventor.mit.edu/

**Comment by MDAmTrailer** [comment]
thank

**Comment by SusanRatiLane** [comment]
@MDAmTrailer I'm afraid we don't support ads. You can get help with requesting permissions on our forum. That is https://community.appinventor.mit.edu/ as @oseamiya  already mentioned.
