### ISSUE TITLE
Circular Progress Bar Component

### ISSUE THREAD

**Issue by devarsh-mavani-19** [mit-cml/appinventor-sources#2637]
**Describe the desired feature**
The Circular Progress Bar Component can be useful to indicate loading. 

The circular progress bar or loading indicator should have the functionality to change its colour and visibility.

**Give an example of how this feature would be used**
This feature can be very much useful as a loading indicator

This feature can be used by students in their app wherever they are doing time-consuming operations they can show a loading indicator 

In the current system in order to indicate loading users have to show text or a static image that is not user friendly and most of the modern apps have such a basic indicator
**Why is this feature beneficial to App Inventor's educational mission?**
Adding this feature will allow users to improve the UX of their apps. in the current system, they need to display it using a Label or Image component which is not appealing.

**Comment by devarsh-mavani-19** [comment]
@ewpatton can i work on this issue?

**Comment by ewpatton** [comment]
@devarsh-mavani-19 Why is the ShowProgressDialog and DismissProgressDialog in the Notifier component not sufficient for this task?

**Comment by devarsh-mavani-19** [comment]
@ewpatton In notifier component it shows extra space in dialog when text is empty. means it is not possible to show only a loading sign. also currently not possible to change color of notifier loading part. Nothing else major difference
![download](https://user-images.githubusercontent.com/55136047/152927633-5e6bb0c2-9c00-4861-b44c-42655631469d.png)

**Comment by preetvadaliya** [comment]
> @devarsh-mavani-19 Why is the ShowProgressDialog and DismissProgressDialog in the Notifier component not sufficient for this task?

Yes, I also agree with @ewpatton, sir.

**Comment by pavi2410** [comment]
> @devarsh-mavani-19 Why is the ShowProgressDialog and DismissProgressDialog in the Notifier component not sufficient for this task?

Google deprecated ProgressDialog class long ago in order to prevent blocking UI. The reason stated by them is:

> This class was deprecated in API level 26.
ProgressDialog is a modal dialog, which prevents the user from interacting with the app. Instead of using this class, you should use a progress indicator like [ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar), which can be embedded in your app's UI. Alternatively, you can use a [notification](https://developer.android.com/guide/topics/ui/notifiers/notifications) to inform the user of the task's progress.
> https://developer.android.com/reference/android/app/ProgressDialog?hl=en

**Comment by ewpatton** [comment]
Circular progress bar has since been implemented for Android and the iOS version will be in the next iOS release.
