### ISSUE TITLE
Improvements for MIT app inventor website responsiveness and UI design

### ISSUE THREAD

**Issue by Yash621** [mit-cml/appinventor-sources#2639]
I have been observing MIT app inventor website, and I found many issues related to responsiveness and UI design of the website.

Can we work on improving it ?

**Comment by preetvadaliya** [comment]
@Yash621 which website are you talking about? Landing page of the MIT App Inventor or Designer part of App Inventor (Builder UI)

**Comment by Yash621** [comment]
@preetvadaliya landing page

**Comment by SusanRatiLane** [comment]
We're currently reviewing the landing page design. If you report your concerns, I can take them into account.

> I have been observing MIT app inventor website, and I found many issues related to responsiveness and UI design of the website.
> 
> Can we work on improving it ?

**Comment by preetvadaliya** [comment]
@SusanRatiLane if I don't forget then there was a small user feedback post created by MIT student in community (I also talked with her on Google meet regarding this and we discussed about App Inventor gallery view) but i didn't find the link.

@Yash621 please try to search in community I hope you will find it.

**Comment by Yash621** [comment]
I found some responsiveness issues on the landing page,like when i resize the browser some the `divs` and `text` are overlapping  .also I personally feel that we can work on improving the UI design more.

**Comment by SusanRatiLane** [comment]
> @SusanRatiLane if I don't forget then there was a small user feedback post created by MIT student in community (I also talked with her on Google meet regarding this and we discussed about App Inventor gallery view) but i didn't find the link.
> 
> @Yash621 please try to search in community I hope you will find it.

We have a student doing user experience analysis right now. The post you're referring to was a survey that is now closed. I'm not sure if the post is still on the forum or not. 

The forum is still a good place to post feedback about the landing page, however.

@Yash621 OK, I think those are concerns we're currently working on. Thanks.

**Comment by Yash621** [comment]
@SusanRatiLane that's great ! thanks :)

**Comment by Yash621** [comment]
@preetvadaliya I think @SusanRatiLane is right ,I also didn't found any such post on the forum.
