### ISSUE TITLE
Need a TExtBox TextAlignment block

### ISSUE THREAD

**Issue by AyProductions** [mit-cml/appinventor-sources#2640]
**Describe the desired feature**

A text alignment block is required for aligning text with blocks in some cases

**Give an example of how this feature would be used**

Suppose if someone is making a word processor, they need to set the text alignment using blocks in some cases, but there is no such block in the 'Blocks Editor'

**Why doesn't the current App Inventor system address this use case?**

This is very important in some cases as I mentioned above :slightly_smiling_face:

**Why is this feature beneficial to App Inventor's educational mission?**

This will help create more advanced apps in the future :slightly_smiling_face:

**Comment by preetvadaliya** [comment]
@AyProductions good idea, and Text Justification can also be helpful.

**Comment by preetvadaliya** [comment]
@ewpatton I would like to work on this.

**Comment by AyProductions** [comment]
Oh and also FontBold and Italic and Underline please :)

**Comment by preetvadaliya** [comment]
@AyProductions I think **TextAlignment** is not that much important while you are taking input from users.

**Comment by AyProductions** [comment]
But as i am making a word processor so I went on with @TIMAI2's solution in the app inventor community :wink:
