### ISSUE TITLE
Reading images out of CloudDB is broken as of nb188

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#2642]
**Describe the bug**

As the title says, reading images is broken. Attempting to do so results in a CloudDB Error.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Images should be able to be read from CloudDB

**Steps to reproduce**

Attempt to read an image out of CloudDB

**Comment by jisqyv** [comment]
Note: A Pull Request is forthcoming to fix this

**Comment by ewpatton** [comment]
Fixed by #2643
