### ISSUE TITLE
ShowZoom Block In Map Documentation Needs Update

### ISSUE THREAD

**Issue by GordonL0049** [mit-cml/appinventor-sources#2645]
https://github.com/mit-cml/appinventor-sources/blob/d98db0be76dd3e86cae2fb9fed7f99a867028b71/appinventor/docs/html/reference/components/maps.html#L513

I find that the ShowZoom block in the documentation is exactly the same as ShowUser, the descriptions are the same. I suggest to change the description for ShowZoom  to be:

`Specifies whether to show zoom controls or not.`

**Comment by devarsh-mavani-19** [comment]
If no one had yet done it I wold like to change it.
