### ISSUE TITLE
Some projects can contain spaces...

### ISSUE THREAD

**Issue by AyProductions** [mit-cml/appinventor-sources#2648]
**Describe the bug**

This bug is always not triggered actually. When you type a project with spaces. App Inventor turns theme into underscore. But in some cases its not

![bug](https://files.catbox.moe/xb68o5.png)

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [x] Other

**Expected behavior**

We expect that no spaces shall be put in project names.

**Steps to reproduce**

Upload a project with spaces on the gallery and load it into App Inventor

**Comment by preetvadaliya** [comment]
In which case or cases it is not working?

**Comment by PeterMathijssen** [comment]
Gordon_Lu explained in this topic when it happens.

https://community.appinventor.mit.edu/t/interesting-app-inventor-project-names/52539?u=peter

**Comment by AyProductions** [comment]
@PeterMathijssen that is why I posted this report so it never happens again

@preetvadaliya follow that topic https://community.appinventor.mit.edu/t/interesting-app-inventor-project-names/52539?u=ayproductions

**Comment by AyProductions** [comment]
Will this be fixed??

**Comment by ewpatton** [comment]
Hmm. I thought I had already filed an issue on this but can't seem to find it. If someone wants to work on this, please go ahead.

**Comment by devarsh-mavani-19** [comment]
I would like to work on this. Thanks : )

**Comment by devarsh-mavani-19** [comment]
> Hmm. I thought I had already filed an issue on this but can't seem to find it. If someone wants to work on this, please go ahead.

@ewpatton  I was going through the code and found that gallery is accessible at localhost:9001. I tried opening it but doesn't work. I think i need to start some server to setup gallery locally. Can you point me at doc where i can find how to setup gallery locally? Thanks
