### ISSUE TITLE
Renaming components that have collapsed events

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#265]
rename a component that has a collapsed  event handler , e.g. Button1.Click

this will not rename the collapsed block...
you first have to expand it to get the new name...

**Comment by josmas** [comment]
Taking this over in befhalf of @shrutirij which will start looking into it when GSoC starts.

**Comment by shrutirij** [comment]
Thanks @jos.

-----Original Message-----

**Comment by shrutirij** [comment]
@halatmit @josmas, pull request #409 has been opened for this.

**Comment by josmas** [comment]
This was merged at #409. Closing now.
