### ISSUE TITLE
Procedure that does things and *then* returns?

### ISSUE THREAD

**Issue by m93a** [mit-cml/appinventor-sources#2653]
Google Blockly has these two kinds of blocks:  
![image](https://user-images.githubusercontent.com/1671665/157436484-cb9a1919-5c36-4b39-a9a4-6c5081b01f3c.png)

They allow me to *first* do some code and *then* return a value. This is great for eg. finding things in lists. However, in AppInventor, there are only:  
![image](https://user-images.githubusercontent.com/1671665/157436670-85fc9fd0-f0f6-4ca8-8455-1a119cdbc955.png)

Which means I can *either* do something, *or* return a value. This severely limits the procedures a user can create and it seems very unergonomic to me. Is there a walkaround for this? Or would you consider adding the Blockly-style procedure?

**Give an example of how this feature would be used**
![image](https://user-images.githubusercontent.com/1671665/157439005-4aac2378-70af-42ad-a181-5ca29c20815d.png)

**Why doesn't the current App Inventor system address this use case?**
I hope it does and I just couldn't find it.

**Why is this feature beneficial to App Inventor's educational mission?**
Because *doing something and then returning* is a very basic feature present in virtually every programming language.

**Comment by m93a** [comment]
Oh, I completely missed the do-result block!
![image](https://user-images.githubusercontent.com/1671665/157441993-4c6f4041-7692-4239-a3aa-a8d6b8a28f57.png)

Disregard my last post, then!

**Comment by preetvadaliya** [comment]
<img width="846" alt="blocks(1)" src="https://user-images.githubusercontent.com/80121827/157442347-99a49dca-5b7f-48e4-97a7-163cd47106ac.png">
