### ISSUE TITLE
Creating extensions using Kotlin would be greatly appreciated

### ISSUE THREAD

**Issue by AyProductions** [mit-cml/appinventor-sources#2657]
**Describe the desired feature**

We would like to create extensions using Kotlin. App Inventor can only handle Java extensions so we want support for Kotlin extensions also

**Give an example of how this feature would be used**

We would like to create extensions using Kotlin...

**Why doesn't the current App Inventor system address this use case?**

Not everyone knows Java, but are good at Kotlin, so we want this feature extension support

**Why is this feature beneficial to App Inventor's educational mission?**

It will help us to make more powerful App Inventor extensions :)

Kotlin is just like Java

**Comment by oseamiya** [comment]
https://github.com/mit-cml/appinventor-sources/pull/2323

**Comment by oseamiya** [comment]
See this PR by Shreyash,
https://github.com/mit-cml/appinventor-sources/pull/2323
