### ISSUE TITLE
Create developer documentation for internationlization and upgrading

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#266]
It's not  documented what  developers need to to do when they add properties and methods and events to components, and change blocks.

We need documentation for this.   Currently the best we have is in the comments in Yaversion.java and versioning.js

**Comment by halatmit** [comment]
This is now a lot simpler because of the change Jeff made.  But we should put in something about not hardcoding strings.

**Comment by halatmit** [comment]
This seems to be done now.

**Comment by josmas** [comment]
@halatmit where is this documented? I still see the old instructions in the docs: https://docs.google.com/document/pub?id=14c1X19s6pXYHdDBOJJELcmOghWbm2FPekRvGzX0ENps#h.2g0jyctaq6go

**Comment by halatmit** [comment]
There are some comments in YaVerison.
But I'd forgotten about this doc.
Do you want to upgdate it?  Or we can file a new issue that makes it clear
which doc needs to be updated anad also, add a comment into the doc making
people aware that there is more to do


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by josmas** [comment]
someone that knows what's going on should update the docs.

**Comment by halatmit** [comment]
add the documentation to 
https://docs.google.com/document/d/1xk9dMfczvjbbwD-wMsr-ffqkTlE3ga0ocCE1KOb2wvw/edit#

**Comment by halatmit** [comment]
I added a section to How to add a component 
and How to add a property to a component.

Closing this issue
