### ISSUE TITLE
Typeblocking "1" should prioritize number 1

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2660]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/typeblocking-doesnt-always-produce-a-block/51475?u=ewpatton): Entering 1 in the typeblocking window includes the number 1 as the last entry rather than the first. The results should probably be sorted most-least specific but it seems to be opposite. It's much more likely for a program to contain the number 1 rather than the various base conversion blocks that appear earlier in the ist.

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

As above.

**Steps to reproduce**

As above.

**Comment by devarsh-mavani-19** [comment]
@ewpatton  I would like to work on this.

**Comment by ewpatton** [comment]
Fixed by #2661
