### ISSUE TITLE
Unable to copy and paste component in TableArrangement

### ISSUE THREAD

**Issue by siyaoL1** [mit-cml/appinventor-sources#2669]
**Describe the bug**

Copying and pasting a component in TableArrangement using the keyboard shortcuts(ctrl+c, ctrl+v) would cause an error in the Blocks editor. 

**Affects**
As it's common for the content in a table to be similar, this bug affects user's ability to duplicate components in TableArrangement. Users would have to manually create copies of each component in the TableArrangement.

- [x] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**
Copy and pasting a component in TableArrangement would first fill all the spaces in the current row and go to the next row.

**Steps to reproduce**

Create a TableArrangement component and add a Button or any layout component to the table. Copy and pasting the added layout component will trigger the error

**Comment by preetvadaliya** [comment]
@siyaoL1 this looks like #2479

**Comment by siyaoL1** [comment]
@preetvadaliya Thanks for pointing it out! They are referring to the same bug. I will close this issue.
