### ISSUE TITLE
File not found at: /appinventor/appinventor-sources-master/appinventor/blocklyeditor/../lib/closure-library/closure/goog

### ISSUE THREAD

**Issue by zeng-shuo** [mit-cml/appinventor-sources#2674]
Such as title

**Comment by zeng-shuo** [comment]
when I run ant

**Comment by preetvadaliya** [comment]
Hi @zeng-shuo,
Have you followed the guide given in README?

**Comment by preetvadaliya** [comment]
`git submodule update --init` run this before compilation.

**Comment by zeng-shuo** [comment]
> `git submodule update --init` run this before compilation.

ok, I'll try.

**Comment by ewpatton** [comment]
Please follow the instructions in the README. As @preetvadaliya has pointed out, this error is due to not having checked out the submodules.
