### ISSUE TITLE
UI of your website also looks very basic ,so as a UI developer i want to update your UI .

### ISSUE THREAD

**Issue by Hrithik0210** [mit-cml/appinventor-sources#2682]
**Describe the bug
-->

**Affects**

- [x] Designer

**Expected behavior**

**Steps to reproduce**

**Comment by preetvadaliya** [comment]
@Hrithik0210 Can you please tell me which UI you are talking about? The landing page of the MIT App Inventor or Builder UI?

**Comment by Hrithik0210** [comment]
Yes sir landing page as well as builder UI

**Comment by preetvadaliya** [comment]
As far as know and if I am not missing then someone from MIT is already working on it because there was small user feedback that happened in past for this.
Builder UI is made up of GWT(Google Web Toolkit) and written in Java programming language, if you want to contribute to UI you can focus on **`appengine`** folder.

**Comment by Hrithik0210** [comment]
I would love to contribute.Thank you sir

**Comment by ewpatton** [comment]
There is already a project underway to work on updating the UI for App Inventor, so I will close this for now.

**Comment by Hrithik0210** [comment]
Sir,Can you please give me time of today for updating ?

**Comment by Hrithik0210** [comment]
Sir,I am ready with my  UI of MIT APP can you please open so ,that i can
upload my UI

**Comment by Hrithik0210** [comment]
Sir,This is your UI for Application of MIT App Inventor,I hope you like
this,if you give me time also do work on your website UI and make it more
attractive and user friendly

**Comment by preetvadaliya** [comment]
You can share screenshot or any figma prototype here also.

**Comment by Hrithik0210** [comment]
![About](https://user-images.githubusercontent.com/79349648/171097067-c5eea667-8cc8-4541-8cba-f7d047ae0670.jpg)
![Blog](https://user-images.githubusercontent.com/79349648/171097072-c340ea29-d425-41a4-a1f2-9fa5cbaf1af6.jpg)
![First Page](https://user-images.githubusercontent.com/79349648/171097074-5dd4a7d3-b12c-4983-94b2-fb0cbe4c1c09.jpg)
![Home](https://user-images.githubusercontent.com/79349648/171097075-70d235d9-08fe-4ea1-b41e-c6ab75e71bef.jpg)
![Login](https://user-images.githubusercontent.com/79349648/171097078-0a188d1d-fbf0-4529-83c8-ac62dbfe06eb.jpg)
![OTP](https://user-images.githubusercontent.com/79349648/171097081-12c96561-6910-41fb-8cf5-4dd9b52a41e8.jpg)
![Sign Up](https://user-images.githubusercontent.com/79349648/171097083-95205164-c2df-46c2-899d-796a37986073.jpg)
![Started](https://user-images.githubusercontent.com/79349648/171097085-eb20f5d6-b0e7-4cc0-93d0-7a38fbcbea42.jpg)
![Tutorial](https://user-images.githubusercontent.com/79349648/171097087-b3c026ae-0312-4be9-9aca-1f5de188e63f.jpg)

**Comment by Hrithik0210** [comment]
This is your UI for Application of MIT App Inventor,I hope you like
this,if you give me time,  I also do work on your website UI and make it more
attractive and user friendly

**Comment by Hrithik0210** [comment]
https://user-images.githubusercontent.com/79349648/171097510-58c0af3b-044d-4471-accc-aee8575b5097.mp4

**Comment by preetvadaliya** [comment]
What do you mean by application? This also required lots of branding, Red is not App Inventor's brand color also logo is not clearly visible on primary color. 
Anyway good effort but as @ewpatton said the project is already on going so as per my suggestion you have to wait until first look of new design will not published.

**Comment by Hrithik0210** [comment]
Thank you for your response ,I agree with you ,I will do that after your
confirmation because i did not got the proper resources of MIT app.
