### ISSUE TITLE
Build finished but still waiting

### ISSUE THREAD

**Issue by rollinggulf** [mit-cml/appinventor-sources#2684]
**Describe the bug**

- background : I'm using my machine(winodows) as the main server and the build server, and I'm building the HelloPurr into an apk
- problem : the log of build server shows "BUILD 1 FINISHED" but the building progress bar is still stuck at  "Compiling part 2(please wait)" stage.(a snapshot is attached below) 
- cause : I guess this is because I set the ip of the main server as a specific ip address (from cmd "ipconfig") instead of 0.0.0.0 and the log of build server shows that the CallbackURL remains as localhost:8888 (snapshot below). The reason I didn't use 0.0.0.0 is that I want to connect my phone and my App Inventor service with AI Companion and when I try 0.0.0.0 I found that the assests(like kitty.png) can't be transmitted to my phone(snapshot below).
- my test : 
  1. If I use my specific ip address as the main server ip, the assets transmission is ok but the build problem mentioned above occurs. 
  2. if I use 0.0.0.0 as the main server ip, the build process is ok but the assets transmission problem occurs, and the apk successfully built can't be downloaded for the same reason.
  3. if I use 0.0.0.0 as the main server ip, after the disconnect alert(snapshot below), transmission will be **fine** in the next connect try , but if I refresh the page or click connect -> Reset Connection , the next time transmission will fail again.
- solution : I wonder if we can set the ip of the CallbackURL somehow but I didn't find an easy way to do so(like through cmd line arguments, I tried looking it up in "How to build App Inventor from the MIT sources" but didn't found what I want, if I missed anything , I'm sorry) . Now that the build request can be received and handled by the build server, the specific ip address of the main server should already be known by the build server.I guess the CallbackURL is just not consistent with that, is this a conscious design?
- relative issues (not working under this case):
  - https://community.appinventor.mit.edu/t/unable-to-load-file-upon-ai-companion-connection/16887
  - https://community.appinventor.mit.edu/t/companion-error-using-an-offline-version-of-app-inventor/31203

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [x] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

When the build process finished in build server , the build process bar turns into the download window.

**Steps to reproduce**

1. .\appinventor\google-cloud-sdk\bin\java_dev_appserver.cmd --port=8888 --address=192.168.xxx.xxx \appinventor\appengine\build\war\
2. ant RunLocalBuildServer (in buildserver\)
4. open 192.168.xxx.xxx:8888 , login as [test@example.com](mailto:test@example.com)
5. create the HelloPurr project and enter it 
6. click build->Andriod App (.apk)

**Snapshots**
![build_kitty_still_waiting](https://user-images.githubusercontent.com/46695737/169685008-524e825b-7fab-428a-bff2-3d06627421ff.png)
![build_kitty](https://user-images.githubusercontent.com/46695737/169684798-e5c25108-be78-4d79-bed7-4b36c7c07718.png)
![error_on_phone_when_transmisstion](https://user-images.githubusercontent.com/46695737/169684818-7e825d32-1a2b-42c1-a15b-46ba148c298c.jpg)
![disconnected_alert](https://user-images.githubusercontent.com/46695737/169691260-e81cd56d-2a47-48bb-96f5-a3c17a143974.png)

thank you.

**Comment by preetvadaliya** [comment]
@rollinggulf see this thread on the App Inventor community...

https://community.appinventor.mit.edu/t/unable-to-load-file-upon-ai-companion-connection/16887

**Comment by rollinggulf** [comment]
@preetvadaliya thank you, but my problem seems to be different. I checked the HttpOnly and they were not set. Further more, I found that the first time I clicked connect -> AI Companion  , the transmission failed , but After the disconnect alert(snapshot below), I clicked connect -> AI Companion again , it worked. If I refresh the page or click connect -> Reset Connection , then in the next connecting, the transmission will fail again.
![http_only](https://user-images.githubusercontent.com/46695737/169690719-d271d256-a2fb-48c5-be5e-216089f70622.png)
![disconnected_alert](https://user-images.githubusercontent.com/46695737/169690743-a05f5a71-e363-48e3-859a-b88a63699c69.png)

**Comment by ewpatton** [comment]
@rollinggulf Use 0.0.0.0 for the address of the server but in your browser access it via your computer's IP address on the LAN rather than localhost. The hostname used in the browser is also used to load the assets, but localhost will resolve to the phone on the phone, not your computer.

**Comment by ewpatton** [comment]
I'm going to close this issue for now. If you continue encountering problems please ask clarifying questions in the open source group on our [community](https://community.appinventor.mit.edu).
