### ISSUE TITLE
SoundRecorder Shows Error 802 - Cannot start recording, impacts CoolThink curriculum

### ISSUE THREAD

**Issue by anqizzz8989** [mit-cml/appinventor-sources#2712]
**Describe the bug**

When SoundRecorder is used, it shows Error 802 - Cannot start recording: ENOENT (No such file or directory).

Guess it's a directory issue for Android 10+

**Affects**

Compiled app shows error and cannot record sounds.
![Error 802](https://user-images.githubusercontent.com/82657958/184902327-e637f800-3839-46b1-bab6-6b8eec3671ce.jpg)

**Expected behavior**

I expect the SoundRecorder to record sound but error comes up.

**Steps to reproduce**

Use the SoundRecorder.

**Comment by ewpatton** [comment]
Fixed by #2713
