### ISSUE TITLE
Clearer error messages when sending to gallery

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2725]
If one creates an app that contains an extension, sending to the gallery simply shows the error "Error sending project to the Gallery". We might want to add some logic to the client to check the project structure for extensions and not even make the API call. Regardless of whether we do that, the error message should indicate that the presence of extensions is likely the issue.

**Comment by arinmodi** [comment]
@ewpatton, I opned the PR, can you please verify it ?

**Comment by YashSalve695** [comment]
can you please assign me this issue?
