### ISSUE TITLE
Need a Hide Keyboard Block for the Screen

### ISSUE THREAD

**Issue by EnisM** [mit-cml/appinventor-sources#273]
There are times when you want to hide the keyboard.  Presently, this can only be done in specific textboxes.  But, you may want to hide the keyboard after a spinner selection is made, for example.

We should have a Screen-Wide Hide Keyboard block:

![hk](https://cloud.githubusercontent.com/assets/10585909/6273779/0b5ad388-b840-11e4-9cb6-c05e3b6c04c7.PNG)

**Comment by jisqyv** [comment]
There should probably be a complimentary OpenKeyboard block as well.

**Comment by EnisM** [comment]
Agreed!  Great... Thanks Jeff...

**Comment by EnisM** [comment]
Actually, what would you need the OpenKeyboard block for?  The only reason to have the keyboard open is for text boxes, and they self open the keyboard when they get touched.  On the screen itself, opening the keyboard makes no sense because it would be an arbitrary keyboard for nothing.

I can see having an OpenKeyboard for the textbox/password textbox components, but not for anything else...

Just my $.02's worth ;)!

**Comment by jisqyv** [comment]
Actually, I agree with you now that I think about it...

**Comment by puravidaapps** [comment]
you always can close the keyboard using the Textbox1.HideKeyboard method
which means, a screen wide hide keyboard block does not make sense imho...
Taifun

Am 19.02.2015 um 16:10 schrieb EnisM:

**Comment by EnisM** [comment]
Taifun... You can't know when the user is done with their input until they move to another textbox.  Sometimes, the keyboard comes up for a text box.  Let's say, for argument's sake, there's two spinners underneath that textbox.  So, the user inputs into the textbox and then clicks on the spinner.  The keyboard stays open.

You can't anticipate that the user has jumped to another component, but if you had the Screen.HideKeyboard, you could close the keyboard manually even in a spinner.  Or, if someone clicks on a button, the keyboard should hide but it doesn't.

You COULD put a textbox.HideKeyboard in the LostFocus event of EVERY textbox, but that seems consumptive, especially if you have a lot of them.  And there are times when you want to keep the keyboard open because there are two or three textboxes in a row, and closing and then opening the keyboard each time would look like a 70's disco ball.

**Comment by puravidaapps** [comment]
so which event would you use in this case?
probably a Spinner.BeforeSelecting event would make more sense, then you
could put a Textbox1.HideKeyboard block in there...
Note: it doesn't matter which textbox opened the keyboard,
Textbox1.HideKeyboard will close it...
Taifun

Am 19.02.2015 um 17:13 schrieb EnisM:

**Comment by EnisM** [comment]
That would be fine if there WERE a Before Selecting/Picking block for
spinners... Unfortunately, there isn't.

**Comment by EnisM** [comment]
Oops... misread your message Taifun.  Yes, BeforeSelecting would be ideal
too.

Isn't it just simpler right now to be able to close the keyboard from
anywhere?

**Comment by puravidaapps** [comment]
I know... therefore I asked you: which event would you use in this case?
to introduce a Spinner.BeforeSelecting event would make more sense
instead of creating a screen wide hide keyboard method...
Taifun

Am 19.02.2015 um 17:41 schrieb EnisM:
> That would be fine if there WERE a Before Selecting/Picking block for
> spinners... Unfortunately, there isn't.
>

**Comment by puravidaapps** [comment]
if you want to close the keyboard before a spinner is clicked, you need
a Spinner.BeforeSelecting event
a method to close a keyboard from "anywhere" is already there, it is
called Textbox1.HideKeyboard
but "anywhere" can only be inside an event...
Taifun


Am 19.02.2015 um 17:44 schrieb EnisM:

**Comment by jcruze057** [comment]
hi, may i request that when the keyboard appears, it will not resize all screen elements, will not appear like it blanks the whole screen for a moment and will appear in fast but in animated way. It really loks unprofessional when it appears and blanks the whole screen and resize all controls

**Comment by halatmit** [comment]
This behavior is controlled by Android's windowSoftInputMode.
Two possible settings are "adjustResize" and "adjustPan". I've trie both of them, and they both have issues.

AdjustResize is the current behavior.

The alternative AdjustPan tries to move input elements out of the way when the keyboard opens, but it often doesn't work and the keyboards end up covering the screen element you want to interact with.

So I chose to use AdjustResize.

Feel free to experiment with variations.  More information about this here:

https://developer.android.com/training/keyboard-input/visibility.html

**Comment by jcruze057** [comment]
how do i do it in spp inventor? snd slso how to control the app's (first screen) behavior when it is loading? a black screen appears first before the first screen appears.

**Comment by halatmit** [comment]
My comment above was for app inventor implementors, not end users.
If you are an app inventor implementor, you can change the java code to experiment with
windowSoftInputMode.

I don't know what to do about the black screen.

**Comment by ImanCol** [comment]
The truth is that I don't see any use for curiosity to hide the keyboard ... wait. Why can't I hide the keyboard when the user has stopped having activity on or on the touch screen? I would appreciate a solution.
