### ISSUE TITLE
Need to ask for Android 12 dangerous Bluetooth permissions

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2740]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/bluetooth-conection-problem-fail-message-in-the-browser/66107?u=ewpatton): When using blocks like Connect on Android 12, we must first ask for user permission for BLUETOOTH_* permissions. As a workaround, people can go into the settings app and grant permission that way.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

When a Bluetooth request is made to scan, connect, or advertise, permission must be asked of the user on Android 12+.

**Steps to reproduce**

1. Create a simple bluetooth app on Android 12. Using any of the connection blocks will fail with a permission error.

**Comment by arjundevasi** [comment]
Hi, I'm new to open sourcing but I have experience in building android apps, I think I can do this,
can you help me get started?

**Comment by ewpatton** [comment]
@arjundevasi Thank you for offering but I was already underway on fixing the issue when you sent your message. There is a PR open now at #2755 that should fix the issue.

**Comment by ewpatton** [comment]
Fixed in release nb191
