### ISSUE TITLE
SendMessageDirect fails on Android 12

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2741]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/runtime-error-targeting-s-version-31-and-above-requires-that-one-flag-of-flag-immutable-be-specified/66394?u=ewpatton): Using the Texting.SendMessageDirect block fails on Android 12 due to the need to specify a mutability flag in the PendingIntent, but we don't do so.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Using the SendMessageDirect block should work correctly without causing a runtime error on Android 12.

**Steps to reproduce**

An example is provided in the post.

**Comment by gr3453m0nk3y** [comment]
@ewpatton Any updates on this?

**Comment by jeff9315** [comment]
@ewpatton Any updates on this? 

I want to use this to send text messages to a small group I'm in,  in the event of another hurricane or a tornado. So, time is of the essence if I'm going to use it this season. Otherwise, if it looks like it might be awhile, I'll go a different route.

Thanks!

**Comment by ewpatton** [comment]
@gr3453m0nk3y @jeff9315 You can try out the PR I submitted on this temporary server and verify whether or not it addresses the issue: http://nb190a-bugfixes.ai2-ewpatton-temp.appspot.com/

**Comment by nan805** [comment]
It works. The issue of the sendMessageDirect a runtime error can be fixed building by the temporary server.

**Comment by hamedhosseini55** [comment]
@ewpatton i cant open this site( http://nb190a-bugfixes.ai2-ewpatton-temp.appspot.com) error message:403. That’s an error.

Your client does not have permission to get URL / from this server. That’s all we know.

How can I access the temporary server ?

**Comment by ewpatton** [comment]
@hamedhosseini55 Try using HTTPS and seeing if the problem persists. Sometimes HTTP proxies can interfere with accessing App Inventor but they tend to not cause as much trouble when switching to HTTPS.

**Comment by hamedhosseini55** [comment]
@ewpatton thank you for your answer.
Unfortunately, after three hours of trying, I could not open the site.

Is it possible to send you the .aia file and you  convert it to apk format for me?thanks

**Comment by hamedhosseini55** [comment]
@ewpatton finally i could open it. and i built .apk and it works without any problems and compatible with android 12 thanks.

**Comment by ewpatton** [comment]
Fixed in release nb191
