### ISSUE TITLE
Charts Causes App to Crash When Reading from Spreadsheet with Scatterplot On 

### ISSUE THREAD

**Issue by bobparks** [mit-cml/appinventor-sources#2774]
The app should read data into the Chart component from [this spreadsheet](https://docs.google.com/spreadsheets/d/1Hrxxa8kroOWKUQOA7x2OYJTtjxKSPweSWPqrKMahVL8/edit#gid=883443412).

When you set the Chart component to "scatter" type chart, the app crashes. It crashes whether live testing or packaged as an app. 

This is problematic because many types of data (such as the lake ice example here) are properly visualized by a scatterplot. In this example, a line graph for the ice data doesn't make sense. 

In contrast, when you set the Chart component to "line" type and press "Get Data" in the app, it works fine.  

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x ] Companion
- [ ] Compiled apps
- [x ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The Chart should fill with data with scatterplot points. To see how it looks as a line graph in the attached AIA, change the properties in the chart component with the attached AIA. 

**Steps to reproduce**

To see this happen, load one of the two enclosed AIA and press the "Get Data" button. There are two ways of retrieving spreadsheet data into chart, so I have included both variations (both will crash with scatterplot data). 
- The first AIA reads a range of data from a spreadsheet using the Spreadsheet component, then in the Sheets callback function puts it in a Chart using ImportfromList method in ChartData2D
- The second AIA reads the spreadsheet using the Spreadsheet component, then it imports the data into Chart using the ChartData2D component. 

[Spreadsheet_to_Chart_starter.zip](https://github.com/mit-cml/appinventor-sources/files/10059730/Spreadsheet_to_Chart_starter.zip)
[Spreadsheet_to_Chart_starter_test.zip](https://github.com/mit-cml/appinventor-sources/files/10059732/Spreadsheet_to_Chart_starter_test.zip)

**Comment by dhruvpatidar359** [comment]
is this issue solved , or i can work on this ?

**Comment by ewpatton** [comment]
@dhruvpatidar359 I believe this is fixed on the test server I set up. @bobparks can you confirm?

**Comment by bobparks** [comment]
@ewpatton Yes, it works well now. @dhruvpatidar359 Thanks for checking.

**Comment by ewpatton** [comment]
Fixed by #2746
