### ISSUE TITLE
Add "RemoveItemAtIndex" block to ListView

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2782]
**Describe the desired feature**

A user raised an issue about the most effective way to remove an item from a list. The current solution takes 7 blocks, but we could certainly add a method to the ListView component to perform this operation atomically (from the point of view of the blocks) and reduce the block count for the operation from 7 to 1.

**Give an example of how this feature would be used**

See above description.

**Why doesn't the current App Inventor system address this use case?**

The capability is there but is fairly verbose. Conceptually, users are likely thinking about removing items from the ListView itself rather than its underlying elements (plus, the property copies the elements so it's not sufficient to do `remove item from list (ListView1.Elements, index)`. Scheme gives us this power but it would require additional engineering to make it work.

**Why is this feature beneficial to App Inventor's educational mission?**

Beginners may not always have a good working mental model of the computation involved in removing an item from a list view. Adding this capability would give the list view some responsibility in the managing of its underlying data (a good OOP design as well where the component manages its state).

**Comment by devarsh-mavani-19** [comment]
@ewpatton can't we do something like this (for the non-legacy list)? I am not sure how we can call scheme methods from java for the legacy part
```
 @SimpleFunction(
      description = "Removes Item from list at a given idnex")
    public void RemoveItemAtIndex(int index) {
      if (!dictItems.iseEmpty()) {
        dictItmes.remove(index);
      } else {
        // not sure how to implement
      }
    }
```

**Comment by SharmaDhruv2511** [comment]
I am interested in this issue and can solve this so can you please assign this to me..

**Comment by ewpatton** [comment]
@SharmaDhruv2511 It looks like this issue might be addressed by #2789

**Comment by kartikay2203** [comment]
assign me this issue

**Comment by devarsh-mavani-19** [comment]
> assign me this issue

Issue is already being addressed by an existing PR.

**Comment by ewpatton** [comment]
This was released in nb195.
