### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

### ISSUE THREAD

**Issue by mayuribbps21** [mit-cml/appinventor-sources#2792]
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

kindly helip me ,i am using realme 8 pro android mobile
![image](https://user-images.githubusercontent.com/106177262/210039274-0e0261eb-0043-4840-b872-54c17166e6cd.png)
![image](https://user-images.githubusercontent.com/106177262/210039282-888ca511-8fd1-4c1a-9ff5-e1c217142d99.png)

**Comment by ewpatton** [comment]
This is already a known issue for the Serial component and should be fixed by #2761. If you'd like more assistance please ask questions at https://community.appinventor.mit.edu.
