### ISSUE TITLE
String replacement accidentally invokes regex logic

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2794]
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/replace-certain-letters-by-symbol/73564?u=ewpatton): the `replace all text` block will throw an error if the replacement string contains `$`. This is because the string replacement logic will try to substitute in regex capture groups provided in the input pattern. However, we call `Pattern.quote` on the input string to make sure that users don't accidentally trip over regex, so the semantics of the `$` in the replacement cannot ever be satisfied. According to [Java's String.replaceAll method](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll(java.lang.String,%20java.lang.String)), we can use Matcher.quoteReplacement to get similar behavior to how we use Pattern.quote to protect against regex semantics.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Users should be able to replace with a `$` without having to escape it with `\`.

**Steps to reproduce**

An example is provided in the linked forum post.

**Comment by ewpatton** [comment]
I will note that this will end up being a breaking change when implemented for anyone who has happened to work around the issue by escaping the `$`. Given the limited number of reports I think it is safe to make the change, at which point folks can "fix" their implementations.

**Comment by akshaykamath45** [comment]
Is this issue already closed?

**Comment by ewpatton** [comment]
@akshaykamath45 Yes, this bug has been fixed. There was a separate PR that didn't mention the issue so this wasn't closed by default.
