### ISSUE TITLE
Need a way to clear error triangles on blocks

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#280]
If you generate a red error triangle on a block, for example by running "do it", there seems to be no way to clear the error.  Can we do this with a dropdown selection?  Or have the error clear automatically in some other way?   For comment balloons we have "remove comment"

**Comment by jisqyv** [comment]
@halatmit If you fix the error and re-run "do it", the red triangle should clear. But I agree, it wouldn't hurt to have a simpler approach.

**Comment by EnisM** [comment]
And along these lines, and Neil responded to a message to app-dev about this, there needs to be a way to show the error/warning triangles on collapsed blocks...  If you have 100 collapsed blocks and an error shows up, the only way to find it is to expand EVERY block, check it, then collapse it again...

**Comment by EnisM** [comment]
BTW, Neil may have already done this thing in his Blockly update...  I'm pretty sure he's already done the warnings on collapsed blocks...

**Comment by ewpatton** [comment]
Closed by #417
