### ISSUE TITLE
Provide warning regarding extensions for iOS companion

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2836]
**Describe the desired feature**

When users have a project containing extensions connects to an iOS device, we should warn them that extensions are not supported and that their project will not load correctly.

**Comment by PThorpe92** [comment]
Interested in checking this out. If you could repost that line you had in the chat as to what file that could be found in that would be cool.

**Comment by ewpatton** [comment]
Hi @PThorpe92. Here's where we first check to see whether the device is Android or iOS after the initial rendezvous step:

https://github.com/mit-cml/appinventor-sources/blob/8af31edea85246f05019d99d530b8d40a245b30f/appinventor/blocklyeditor/src/replmgr.js#L1473

If we detect iOS, we'll want to check if there are extensions, maybe via the AssetManager class. The trick here will be going back and forth across the JSNI boundary that Google provides but we should be able to make it work. Let's plan to add a method to AssetManager that returns a boolean check for whether the project has extensions. If true, then you can put up a dialog using Blockly.Util.Dialog (this is done elsewhere in replmgr.js if you need examples).

**Comment by PThorpe92** [comment]
@ewpatton Do you have a recommendation for what extension I should use to test this? I dont have access to a tablet all the time so I am having to use an emulator (plus I just found a bluetooth extension somewhere), and it's throwing a Java error before my dialog had a chance to show. Are there extentions we know work on emulators?
Obviously I dont have an IOS emulator so I changed the bool value like we mentioned to test it . Thanks for the help too man your time is greatly appreciated

**Comment by ewpatton** [comment]
@PThorpe92 Any of the ones we publish should be a good starting point: https://mit-cml.github.io/extensions/

**Comment by PThorpe92** [comment]
@ewpatton hey sorry this took so long, especially for how simple this was. I screwed up my bootloader and was stuck without the OS w the work and dependencies.
![Capture](https://user-images.githubusercontent.com/121899304/229561839-398ab116-d35d-4ce7-ad2b-f7bf00fdbb9f.PNG)


Before I submit, I want to make sure exactly would you like this to do when this occurs? Or I guess I mean is there a preferred way of stopping REPL without messing with any state/etc? at this time, it's wanting to report a bug with a JS alert. Thanks for the help and patience
