### ISSUE TITLE
Close Application Block Only Closes Screen if Not on Screen1

### ISSUE THREAD

**Issue by EnisM** [mit-cml/appinventor-sources#284]
If you have a Close Application block on any screen other than Screen1, the only thing that gets closed is that screen, and you're returned to Screen1.

**Comment by puravidaapps** [comment]
???
I can't confirm this, if you open and close screens correctly, for
example using the manager screen method, you can use the close
application block on any screen to close the app...
@Enis: you might want to prepare an example proejct and we can take a
look at it...
Taifun

Am 24.02.2015 um 15:09 schrieb EnisM:

**Comment by EnisM** [comment]
OK... In my app, there are ONLY two screens... If I try to close the app
from screen2, it closes screen2 and brings me back to Screen1.  I'll come
up with a sample...

**Comment by halatmit** [comment]
I suspect that Taifun is correct here.   App Inventor's "close application"
closes a screen, and then the screen that started it, and then the screen
that started that , and so on.   See the code in
components/runtime/Form.java

Enis, could you create a test as Taifun suggests, and confirm?







== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by EnisM** [comment]
Yes, I'll create a test tonight.

**Comment by halatmit** [comment]
Thanks



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by EnisM** [comment]
I'll close the issue for the time being... In a basic, nothing in there
app, it works as expected.  I was thinking that maybe the BackPressed block
was interferring, but it's all working as a basic system, so i'll try to
find what's causing it to not work properly on my end...

**Comment by EnisM** [comment]
OK, I found my issue... Terribly sorry to raise that flag...

I did this in a Notifier AfterChoosing, and passed the wrong dialog box (I
handle all of them by using a Global naming which dialog called the
notiofier) name so it's indeed working as expected.
​

**Comment by jcruze057** [comment]
hi, in my case, if the close application block was executed, the entire app closes, but when I tap the app to open it again, a black empty screen appears briefly and closes so I have to tap the app again to open, and this time, it opens normally. here is the video https://www.youtube.com/watch?v=pKfw7pdeuKQ&feature=youtu.be
