### ISSUE TITLE
Request to update GitHub Project Website

### ISSUE THREAD

**Issue by vedantjangid** [mit-cml/appinventor-sources#2845]
Dear GitHub Team,

I am writing to request an update to the project website for [Insert project name here]. As a user and contributor to this project, I have noticed that the current website is outdated and does not accurately represent the current state of the project.

Updating the website would not only improve the user experience but would also help to attract new contributors and users to the project. Specifically, I suggest updating the following:

Updating the project description and mission statement to reflect current goals and progress
Adding recent project updates and news to keep users informed
Adding information on how to contribute to the project, including documentation and guidelines
Updating any outdated information or broken links
I believe that these updates will greatly benefit the project and its users. Thank you for your attention to this matter, and I look forward to seeing the improvements to the project website.

Sincerely,
**vedant**

**Comment by jisqyv** [comment]
?

**Comment by vedantjangid** [comment]
I have noticed that the current website for **appinventor-sources** looks outdated and does not provide a great user experience, So i was thinking that i could help you with that.
