### ISSUE TITLE
change HideKeyboard to be a single block under control

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#285]
.. rather than a method of textboxes.

**Comment by jisqyv** [comment]
@halatmit So we should deprecate the TextBox.HideKeyboard method (and convert the blocks to the new generic block on project upgrade?).

**Comment by halatmit** [comment]
Yes, that's what we should do.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Tue, Feb 24, 2015 at 11:38 PM, Jeffrey Schiller <notifications@github.com

**Comment by EnisM** [comment]
Thanks Hal...

**Comment by halatmit** [comment]
I think that we should do this in two stages:

(1) Add HideKeyboard as a screen method.
(2) Deprecate TextBox.HideKeyboard.

Let's do only (1) for now.   It doesn't hurt to keep the TextBox method around.

**Comment by kkashi01** [comment]
@halatmit If you like, you can assign this to me

**Comment by marksherman** [comment]
@halatmit, you've said it two different ways, and I'd like to clarify. Do you want the new "hide keyboard" block to be under the Screen menu, or under the built-in Control menu?

(question derived from talking with @farxinu)

**Comment by halatmit** [comment]
@marksherman I think we should make it s method of Screen, not a new builtin under Control.

**Comment by halatmit** [comment]
@kkashi01 Thanks for volunteering, but I'd like to assign this to Farzeen, since it's a good starter project.   Anything else you'd be interested in taking.

**Comment by kkashi01** [comment]
@halatmit NP. I'll take a look at list of issues

**Comment by josmas** [comment]
Can this be closed? I can see the block in `Screen` now. Is the deprecation of the TextBox block needed?

**Comment by ewpatton** [comment]
@josmas Agreed. I don't think the deprecation is necessary. There may be many ways to solve the same problem. Some people might be inclined to look at TextBox as a way of hiding the keyboard, whereas others might look to the Screen. I think both ways are valid. (I'd also be willing to throw a block in control, but it's less clear to me that it should be there than something to do with screen management.)
