### ISSUE TITLE
Use -Drelease=true option, also build a big *.cache.js. 

### ISSUE THREAD

**Issue by iwanglian** [mit-cml/appinventor-sources#2876]
**Describe the bug**
As the guide ,I build a development version .I visit in client browser, it is so slow to show in more the 1 minute.
I use chrome devtool to find the *.cache.js is too big , more than 40MB.

Then ,I read the doc again, and use -Drelease=true when build

ant -Drelease=true noplay
The release configuration sets the following additional options:

Blockly Editor is compiled with SIMPLE optimizations (instead of RAW)
App Engine YaClient module is compiled without <collapse-all-properties/> to create per-language/browser builds
App Engine YaClient module is compiled with optimization tuned to 9 and with 8 threads

It works ,generate some *.cache.js ,which is about 4MB, and visit in Chrome. The web page show more quickly.

I compare to official website , its *.cache.js is only 1.3MB,  smaller than mine.

How to reduce  *.cache.js to. 1.3MB?

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

**Steps to reproduce**

**Comment by ewpatton** [comment]
I think you are comparing size on disk versus size over the wire. On disk the production builds are around 4 MB per file, but when they are sent by the server they will be sent with gzip or deflate compression if the browser indicates support. When the file is sent compressed, it is around 1 MB.

**Comment by iwanglian** [comment]
No, I compare size over wire,  using  Chrome devtool.

**Comment by iwanglian** [comment]
Can I 

> 

I deploy in Tomcat ,but it doesn't work, Tomcat could not operate the storage without Google Cloud SDK
