### ISSUE TITLE
Too many classes in --main-dex-list, main dex capacity exceeded

### ISSUE THREAD

**Issue by m-anshuman2166** [mit-cml/appinventor-sources#2879]
**Describe the bug**

I've been trying to integrate Material UI in MIT Appinventor. I've updated a variety of libs to support the material library. Now, I've been facing some errors in compilation.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [x] Compiled apps
- [x] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The compilation should've worked normally and should'nt have caused any issue since MIT Appinventor has Multidex.

**Steps to reproduce**

Implement a bunch of libraries and it will exceed the limit of dx tool.

**Stack Trace**
```
     [java]
     [java] UNEXPECTED TOP-LEVEL EXCEPTION:
     [java] com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
     [java]     at com.android.dx.command.dexer.Main.processAllFiles(Main.java:548)
     [java]     at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
     [java]     at com.android.dx.command.dexer.Main.runDx(Main.java:289)
     [java]     at com.android.dx.command.dexer.Main.main(Main.java:247)
     [java]     at com.android.dx.command.Main.main(Main.java:94)
     [java]
     [java] Apr 16, 2023 5:48:23 PM com.google.appinventor.buildserver.Compiler setProgress
     [java] INFO: The current progress is 75%
     [java] Apr 16, 2023 5:48:23 PM com.google.appinventor.buildserver.Compiler runMultidex
     [java] INFO: DX time: 11.006000 seconds
     [java] Apr 16, 2023 5:48:23 PM com.google.appinventor.buildserver.Compiler runMultidex
     [java] WARNING: YAIL compiler - DX execution failed.

BUILD FAILED
C:\Users\Rudra\Documents\sources-beta\appinventor\build.xml:22: The following error occurred while executing this line:
C:\Users\Rudra\Documents\sources-beta\appinventor\buildserver\build.xml:200: Java returned: 1

Total time: 45 seconds
PS C:\Users\Rudra\Documents\sources-beta\appinventor>
```

**Comment by ewpatton** [comment]
You only need to put the classes into the main dex list required to get the application up and running, at which point multidex will take care of loading the remaining dex files (and on newer versions of Android this is all handled at install time). It sounds like you may have overdone it.

**Comment by m-anshuman2166** [comment]
@ewpatton I've just upgrade the android libraries. Seems like with newer versions of android apis, like sizes and functions have increased. In my local instance, I've fixed this with implementation of D8 somehow.

**Comment by ewpatton** [comment]
It's good that you were able to resolve the issue with your changes.
