### ISSUE TITLE
Create a doc page on posting and emailing images

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#289]
We ought to have something in the "other" part of the documentation.

For posting, we can update Hossein's tutorial 

https://amerkashi.wordpress.com/2014/02/27/how-to-develop-a-photo-boot-android-app/

There's also Eni's digital face painting app.

With either of these, there needs to be a shorter version that gives the gist, without going through the details of tutorial app construction.  Maybe that's a separate page, and the tutorial (or both of them) should be in the tutorial section.

**Comment by halatmit** [comment]
Hal pinged Hossein about this on April 20

**Comment by kkashi01** [comment]
Yes, completely forgot about it. Will take care of this. Thanks for
reminder.

**Comment by halatmit** [comment]
Thanks.    Just point me at the doc when it's ready.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by kkashi01** [comment]
Hi, Please see document here: https://drive.google.com/open?id=0B5b44rWoeEG8fl9nMy14cWM1Z1N5NnM0cTczWjBsSTV2OVJTN2RaYzVieXJIWmUxaEgwd0k&authuser=0

**Comment by halatmit** [comment]
done
