### ISSUE TITLE
Add the stop method for textToSpeech

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#2908]
This will be useful in getting the chatBot to shut up.

**Comment by halatmit** [comment]
Do I just edit the source on github to generate the pull request? I assume it goes into UCR.  How do I specify that?
Also, this needs translations for the popup message on textToSpeech.stop

**Comment by halatmit** [comment]
I thiink Jeff has done this already but it's not released.

**Comment by ewpatton** [comment]
This was implemented in the latest release.
