### ISSUE TITLE
documentation update for screen orientation

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#291]
From Taifun

http://ai2.appinventor.mit.edu/reference/components/userinterface.html#Screen

the current documentation is this

ScreenOrientation
    The requested screen orientation. Commonly used values are unspecified (-1), landscape (0), portrait (1), sensor (4), and user (2). See the Android developer docuemntation for ActivityInfo.Screen_Orientation for the complete list of possible settings.

    correct would be the text and not the numbers, see also this thread in the main forum
    https://groups.google.com/d/msg/mitappinventortest/qr1uTEoL5XA/Up0WMDfAWwkJ

**Comment by halatmit** [comment]
#317

**Comment by jisqyv** [comment]
Change in master branch
