### ISSUE TITLE
Internationalize the About menu in Form

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#295]
"about this application", etc.

requested in 

https://groups.google.com/forum/#!category-topic/mitappinventortest/NhRJDbp793g

**Comment by josmas** [comment]
@halatmit as far as I know, there's no infrastructure in place to internationalize anything on the Android part of the system (error messages, and so forth).

**Comment by halatmit** [comment]
Bummer.   We'll need to fix that.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by josmas** [comment]
Going to close this one as it is the same a #677 and the other issue has more info (it will get cross referenced from this comment too).
