### ISSUE TITLE
iOS Text-To-Speech doesn't stop and plays on top of each other

### ISSUE THREAD

**Issue by anqizzz8989** [mit-cml/appinventor-sources#2952]
There seems to be no way to stop a Text-To-Speech keep playing on when the user switches to another screen with iOS. When several Call TextToSpeech.Speak is triggered, they play on top of each other on iOS.

The bug affects iOS users of Text-To-Speech, especially with multiple screens.

An example is the Tour Guide app. We hope to have a block or a way to stop the TTS.

**Comment by ewpatton** [comment]
@anqizzz8989 The Stop block for the TextToSpeech is available on ai2-test and will go out in the next release. If you have companion 2.64.3 installed you can try it out.
