### ISSUE TITLE
Need to Add SetFocus to the PasswordTextbox as well

### ISSUE THREAD

**Issue by EnisM** [mit-cml/appinventor-sources#296]
SetFocus for text boxes works perfectly.

Also need it for PasswordTextboxes...

**Comment by jisqyv** [comment]
I think the right thing to do is move the RequestFocus handler from TextBox to TextBoxBase which should cause it to be available to all subclasses of TextBoxBase which includes TextBox, PasswordTextBox and EmailPicker.

**Comment by EnisM** [comment]
Thanks Jeff...

**Comment by jisqyv** [comment]
Change merged into master
