### ISSUE TITLE
LineString, Circle, Rectangle, Polygon do not appear on iOS

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2961]
**Describe the bug**

The map features other than Marker appear to be broken on iOS at the moment. These components used to work so we need to identify where the regression occurred.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The map features should appear on the map.

**Steps to reproduce**

Create an app using the above components on a map and connect the iOS companion. Note that none of the features are drawn on the map.

**Comment by varuntecholution** [comment]
are you working on it?

**Comment by ewpatton** [comment]
Fixed by #3026
