### ISSUE TITLE
Line of Best fit should extend to cover the domain and range of the Graph desired

### ISSUE THREAD

**Issue by stezelMIT** [mit-cml/appinventor-sources#2962]
**Describe the desired feature**

Currently the LOBF is chopped to the first and last data point x-values which makes any extrapolation discussion impossible.  This is bad because one of the main uses of LOBF is extrapolation/prediction. 

**Give an example of how this feature would be used**
For example in the Lake data example of Robert, the x-intercept of the LOBF means the year in which  the number of days with lake ice will be zero, which gives a rough sense of when the Global Warming will have catastrophic/apocalyptic effects.  It would be good to be able to show the kids where the line crosses the x-axis and make an estimate of the "end of the world".  Nothing gets kids attention like high stakes drama.

One example is given above.

**Why doesn't the current App Inventor system address this use case?**
Asked this to Hanya many times, not sure why she did not implement this.

We have no way of controlling the domain and range of the LOBF, adding this could help with the task described.

**Why is this feature beneficial to App Inventor's educational mission?**
Example given above should give a sense of this.  Haha!  Education is ultimately benign lying to kids (with oversimplifications of the real world etc.) and creating high stakes drama storylines in teaching is the ultimate form of benign lying to kids.  App Inventor can help with that.

**Comment by ewpatton** [comment]
In the final Trendline implementation we added the Extend property to enable this behavior.
