### ISSUE TITLE
MockSwitch does not respect BigDefaultText property

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#2964]
**Describe the bug**

MockSwitch is not affected by the BigDefaultText property.

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The mock switch component should change its font size similar to other components with text elements, e.g., Checkbox, when the Screen's BigDefaultText property is enabled.

**Steps to reproduce**

1. Create a project
2. Add a Checkbox and a Switch to the Screen
3. Select the screen and check the BigDefaultText property
4. Observe that the Checkbox's text will change size but not the Switch's

**Comment by GordonL0049** [comment]
@ewpatton I would like to work on this issue in the future.

**Comment by gordonlu310** [comment]
@ewpatton I tried changing the setFontSizeProperty method of MockToggleBase to:

```  
  protected void setFontSizeProperty(String text) {
    float convertedText = Float.parseFloat(text);
    MockForm form = ((YaFormEditor) editor).getForm();
    if (convertedText == FONT_DEFAULT_SIZE && form != null
        && form.getPropertyValue("BigDefaultText").equals("True")){
      MockComponentsUtil.setWidgetFontSize(toggleWidget, "24");
    } else {
      MockComponentsUtil.setWidgetFontSize(toggleWidget, text);
    }
    updatePreferredSize();
  }
```

Doesn't work, and then I discovered that no matter how I change the FontSize property of CheckBoxes and Switches, the font size in the Designer will not be affected, even in the main server.

**Comment by gordonlu310** [comment]
@ewpatton Now that the PR is merged, this issue can be closed. :)

**Comment by ewpatton** [comment]
Will be fixed in nb196
