### ISSUE TITLE
FontTypeface of PasswordTextBox is reset after toggling password visibility

### ISSUE THREAD

**Issue by gordonlu310** [mit-cml/appinventor-sources#2966]
**Describe the bug**

After toggling `PasswordTextBox. PasswordVisible` of a PasswordTextBox that has a font typeface different than the default font, the font of the PasswordTextBox is reset to default.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

After changing `PasswordTextBox. PasswordVisible`, the font should be the the font set in the Designer.

**Steps to reproduce**

- Create a new project, add a PasswordTextBox, and set FontTypeface to a font other than Default, such as Serif.
- Connect to the Companion. Observe that even though the password is dots, when typing, the font of the last letter is Serif.
- In the Blocks editor, drag out a `PasswordTextBox. PasswordVisible`, input `true`, and `Do It`. Observe that the font is reset to default (or monospace).
- Change `true` to `false`. Observe that even though the password is dots, when typing, the font of the last letter is reset to default (or monospace).

**Comment by ewpatton** [comment]
Fixed by #3093
