### ISSUE TITLE
Deprecated blocks are still available via typeblocking

### ISSUE THREAD

**Issue by gordonlu310** [mit-cml/appinventor-sources#2967]
**Describe the bug**

Deprecated blocks with `@Deprecated` are not visible in normal block drawers, but are still available through typeblocking.

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Deprecated blocks shouldn't be visible anywhere, neither in block drawers nor typeblocking.

**Steps to reproduce**

The `Pedometer. Pause` is an example of a deprecated function.

- Create a new project on a PC or laptop.
- Add a Pedometer component.
- Open the Blocks editor.
- Type "Pause".

![image](https://github.com/mit-cml/appinventor-sources/assets/88015331/90a8ef2c-5f35-4e3c-9f35-1d8384b7a4d9)

**Comment by AyushABD-17** [comment]
can u please explain little bit more ?

**Comment by AyushABD-17** [comment]
can you please specify where to Type "Pause"

**Comment by josmas** [comment]
hi @AyushABD-17 this is a typeblocking issue. You can see how that works here https://appinventor.mit.edu/explore/tips/typeblocking.html

Also note that for this particular example to work, you will need to have a pedometer component in your app, otherwise you will not see the deprecated blocks.

**Comment by ewpatton** [comment]
Fixed by #3011
