### ISSUE TITLE
Dates in My Projects Are Out of Sequence

### ISSUE THREAD

**Issue by bobparks** [mit-cml/appinventor-sources#2979]
**Describe the bug**

Many of the files listed in My Projects have a "Date Created" that is after "Date Modified." 

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

**Steps to reproduce**

**Comment by ewpatton** [comment]
Looking at the code, it appears in the UI binder version the created/modified dates are swapped. I will submit a PR momentarily to address this.
