### ISSUE TITLE
Procedure names reset to "procedure" when stored in the backpack

### ISSUE THREAD

**Issue by SusanRatiLane** [mit-cml/appinventor-sources#2994]
**Describe the bug**

Community thread: https://community.appinventor.mit.edu/t/copy-block-to-backpack-renamed-to-procedure/93214

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Comment by ewpatton** [comment]
This one is my fault. I should have a fix shortly.
