### ISSUE TITLE
Minor layout issue in UI binder

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#3023]
**Describe the bug**

If the project name and screen name are long, the publish to gallery button gets wrapped to a new line:

<img width="650" alt="image" src="https://github.com/mit-cml/appinventor-sources/assets/1331253/866abab0-5c3d-49cb-bcdd-c3e5b3ff3eb7">

**Affects**

- [x] Designer
- [x] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

I'm not sure what we want to do here. My guess is that we'd probably want to allow the center buttons to shift right to make room.

**Steps to reproduce**

As given above.

**Comment by mahipal2912** [comment]
@ewpatton i would love to work on this issue could you assign me this

**Comment by chiragmalik2612** [comment]
i want to work on it , please assign it to me

**Comment by patryk84a** [comment]
Maybe just leave 2 lines permanently.  The project name is in the first line, and all the buttons are in the second line.  Then the length of the project name would have no effect on anything.

**Comment by SusanRatiLane** [comment]
> Maybe just leave 2 lines permanently. The project name is in the first line, and all the buttons are in the second line. Then the length of the project name would have no effect on anything.

That wasn't the correct location for the Publish to Gallery button. It should now appear after Project Properties. I think this issue is closed.
