### ISSUE TITLE
Vertical scroll arrangement not working? 

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#3033]
I created a small test app
[
](https://drive.google.com/file/d/1ylmDXOKo5YnEQznohtht_BL74GVaIwf8/view?usp=share_link)

This has a single vertical scroll.  It does not seem to scroll.
It fails both on my Android phone with companion 2.67
and on the emulator with 2.68u.

Just start the app and see if it scrolls.

**Comment by halatmit** [comment]
Here is the small test app to try.  Just start is an try to scroll.

**Comment by josmas** [comment]
Hey @halatmit, I think your file is being filtered out by github.

Vertical scroll arrangement is working for me though, at least when I build the app. This is an aia shared from drive. The buttons do nothing, they are there just for padding, but there are two large images that should need scrolling.
 [vertical_scroll.aia](https://drive.google.com/file/d/1paGEliR2Dq99JE9b9Mi03oCsshGVLn-a/view?usp=sharing)

**Comment by halatmit** [comment]
Thanks Jos,

this was my mistake.
