### ISSUE TITLE
Improve language selection for text to speech in the designer

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#305]
We could make this a dropdown showing the available languages.
Maybe something similar for countries, but we migth need a 2-D dropdown since there are so many countries.

**Comment by E-Hon** [comment]
Instead of a 2-D dropdown, how about a scrollable dropdown? Does it serve the same purpose?

**Comment by halatmit** [comment]
Good idea to use a scrollable drowdown!

**Comment by E-Hon** [comment]
any default value for the two fields?

**Comment by halatmit** [comment]
I don't know.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by E-Hon** [comment]
AvailableCountries and AvailableLanguages do not exist in master branch...
But I can see them on the web

**Comment by halatmit** [comment]
???  I see them in the master branch:

https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/TextToSpeech.java

line 336ff




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by E-Hon** [comment]
Oh, I forgot to pull the latest updates. my bad :p

**Comment by halatmit** [comment]
:)



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by E-Hon** [comment]
The 2 fields are device-dependent; only when AI is connected to a device/emulator can it retrieve the possible values. While it works in Blocks view, does the current Designer view support this sort of dynamic update?

**Comment by halatmit** [comment]
The designer doesn't support dynamic update.  

But I dont' understand the issue.  There are lots of fields (e.g., location sensor info) whose value is not know unless a devce is connected.   Is this any different?

**Comment by E-Hon** [comment]
It's that those dynamic values can't be input to the fields in Designer.
The values of a field in Designer have to be known before hand. For
example, emulator supports 5 countries while Galaxy Nexus supports more. It
doesn't know how many and which countries should be put to the fields in
Designer for users to select.

Or did I misunderstand this?

**Comment by halatmit** [comment]
Ah, you are right.  For now, just leave them both blank in the designer, so
you can move ahead. Then create an issue to fix this, and we'll get to that.





== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by E-Hon** [comment]
see #380

**Comment by halatmit** [comment]
#380 was closed
