### ISSUE TITLE
Listview in iOS does not wrap a long text around but chops it.

### ISSUE THREAD

**Issue by stezelMIT** [mit-cml/appinventor-sources#3051]
**Describe the bug**

Listview in iOS does not wrap a long text around but chops it.  Making the ChatBot project near useless in iOS.

**Affects**
ListView in iOS.

- [ ] Designer
- [ ] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

In Android ChatBot project returns a long response from OpenAI and displays it in a readable fashion in Listview.  Same thing does not happen in iOS.
**Steps to reproduce**
[ChatGPTBot_TEST.aia.zip](https://github.com/mit-cml/appinventor-sources/files/13300643/ChatGPTBot_TEST.aia.zip)
You can try the attached AIA in both platforms and see how in iOS the issue occurs.

Try

**Comment by ewpatton** [comment]
@stezelMIT A potential fix is available on TestFlight.

**Comment by ewpatton** [comment]
This should be fixed as of iOS companion 2.64.4 (13).
