### ISSUE TITLE
CloudDB Chat App constantly crashes in iOS

### ISSUE THREAD

**Issue by stezelMIT** [mit-cml/appinventor-sources#3071]
**Describe the bug**

CloudDB Chat App constantly crashes in iOS.

[CloudDBChatApp_FINAL.aia.zip](https://github.com/mit-cml/appinventor-sources/files/13650753/CloudDBChatApp_FINAL.aia.zip)

**Affects**
iOS

- [ ] Designer
- [ ] Blocks editor
- [ ] Projects Explorer
- [x] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [x] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Should not crash.

**Steps to reproduce**

Try to run AI2 Companion

**Comment by ewpatton** [comment]
This is now fixed in iOS companion version 2.64.5 (1).
