### ISSUE TITLE
Support for android 34

### ISSUE THREAD

**Issue by prabhat-sc** [mit-cml/appinventor-sources#3088]
**Describe the desired feature**

**Give an example of how this feature would be used**

**Why doesn't the current App Inventor system address this use case?**

**Why is this feature beneficial to App Inventor's educational mission?**

**Comment by ewpatton** [comment]
Updating to the latest Android SDK is an effort that occurs during the summer, typically in the July time frame.

**Comment by ewpatton** [comment]
Fixed by #3191
