### ISSUE TITLE
Unable to import jar in android studio

### ISSUE THREAD

**Issue by prabhat-sc** [mit-cml/appinventor-sources#3089]
Getting this error while building

<img width="1496" alt="Screenshot 2024-01-05 at 12 22 53 AM" src="https://github.com/mit-cml/appinventor-sources/assets/149680730/e7a0897a-ccae-4a38-b11b-58156b4424ea">

**Comment by ewpatton** [comment]
We do not use gradle as a build system for App Inventor, so I'm not sure what you're trying to accomplish here. If you have questions about building App Inventor sources, please redirect them to https://community.appinventor.mit.edu/c/open-source-development/10
