### ISSUE TITLE
Rewrite the Python "BOM" code in Java

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#314]
We use python to add the BOM (byte order marker) to the beginning of the blockly-all.js file (needed so Chinese characters are not corrupted).

Rewrite this in Java to remove the dependency on Python.

**Comment by Momoumar** [comment]
@halatmit, @jisqyv,
I think this can be closed regarding this commit 
https://github.com/mit-cml/appinventor-sources/commit/154a9ae0dc3e57068e42e796f6888ec65bf705dc
