### ISSUE TITLE
Problem with upload in ai2-test?

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#3177]
Start a new project in ai2-test.   Add an  image
In the designer, click on the picture property for the image.
Now click on upload file in the resulting input box.
Nothing happens:  the uploading dialog does not appear.

This works in ai2 but not in ai2-test.

**Comment by SusanRatiLane** [comment]
There's a good chance this is related to my UI refactor. I'll look at it.

**Comment by jisqyv** [comment]
@SusanRatiLane @ewpatton I'm investigating this. I believe it may be an error when I merged the various PR's together for ai2-test.
