### ISSUE TITLE
Clicking Mark Origin on an Image Sprite without an Image generates an Internal Error

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#3194]
**Describe the bug**

If you click "Mark Origin" in the designer for an ImageSprite, which doesn't yet have an image set, you get the "Internal Error" message.

**Affects**

- [ x] Designer
- [ ] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

An appropriate error message should be generated.

**Steps to reproduce**

Create  a new project, drag in a Canvas and place an Image Sprite in it (but don't set an image). Then click "Mark Origin" on the Image Sprite.

**Comment by ewpatton** [comment]
Fixed by #3195
