### ISSUE TITLE
List from CSV row is missing in the documentation

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#321]
see

see missing documentation here http://appinventor.mit.edu/explore/ai2/support/blocks/lists.html#listfromcsvrow
and this thread https://groups.google.com/d/msg/mitappinventortest/sMQ5t7LnQf8/HLQTGlFJFcgJ

**Comment by halatmit** [comment]
@jsheldonmit 
The text has been added, but the image is currently of the block List from CSV table.  It needs to be replaced.

**Comment by jsheldonmit** [comment]
Fixed on Drupal server - not staticfied yet, and then may need to be propagated to CSAIL local server

**Comment by halatmit** [comment]
Thanks


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
@jsheldonmit
