### ISSUE TITLE
"One Potato" example not quite right for text split

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#322]
The following text could be confusing in a subtle way. The example for the split text block says splitting the string 
"one-potato,two-potato,three-potato,four" at "-potato" 
renders the list "(one two three four)".

This is wrong, as the split token needs to include the comma. 

The problem is in the english, and appears to have propagated to spanish and italian translations. I'm not really competent in the non-romance languages, but zh_cn and zh_tw appear to have the comma correctly inserted.

If someone can check the following, just to make sure, that would be great:

zh_cn:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT = '以指定文本作为分隔符，将字符串分解为不同片段，并生成一个列表作为返回结果。\n'
    + ' 如以","(逗号)分解"一,二,三,四"，将返回列表"(一 二 三 四)"，\n'
    + ' 而以"-土豆"作为分隔符分解字符串"一-土豆,二-土豆,三-土豆,四"，则返回列表"(一 二 三 四)"。'
```

zh_tw:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT = '以指定文字作為分隔符號，將字元串分解為不同片段，並產生一個清單作為傳回結果。\n'
    + ' 如以","(逗號)分解"一,二,三,四"，將傳回清單"(一 二 三 四)"，\n'
    + ' 而以"-土豆"作為分隔符號分解字元串"一-土豆,二-土豆,三-土豆,四"，則傳回清單"(一 二 三 四)"。'
```

Also...
---------
I also found issues with the "split at first of any" tooltip. I've corrected the English, Spanish, and Italian and the pull request, but need someone to check the Chinese (just as above).

This problem was the list (ba ap) was represented with a comma, which was incorrect. I also found the examples in spanish and italian were broken (didn't split the string correctly). Here's the corrected English:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = 'Divides the given text into a two-item list, using the first location of any item \n'
        + 'in the list \'at\' as the dividing point. \n\n'
        + 'Splitting "I love apples bananas apples grapes" by the list "(ba ap)" returns \n'
        + 'a list of two items, the first being "I love" and the second being \n'
        + '"ples bananas apples grapes."';
```
zh_cn:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = '以列表中的任意项作为分隔符，\n'
    + '在首次出现分隔符的位置将给定文本分解为一个两项列表。\n\n'
    + '如以"(稥,苹)"作为分隔符分解"我喜欢苹果香蕉苹果葡萄"，\n'
    + '将返回一个两项列表，其第一项为"我喜欢"，第二项为\n'
    + '"果香蕉苹果葡萄"';
```
zh_tw:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = '以清單中的任意項作為分隔符號，\n'
    + '在首次出現分隔符號的位置將給定文字分解為一個兩項清單。\n\n'
    + '如以"(稥,蘋)"作為分隔符號分解"我喜歡蘋果香蕉蘋果葡萄"，\n'
    + '將傳回一個兩項清單，其第一項為"我喜歡"，第二項為\n'
    + '"果香蕉蘋果葡萄"';
```

Thank you!

**Comment by marksherman** [comment]
@weihuali0509 could you check these, please? (This is what Hal is linking.) I think they're ok. If it needs correction, just comment with the updated text and I'll submit it. Thank you!

**Comment by Eagles2F** [comment]
@marksherman  For the first part, things in the zh_cn and zh_tw are broken.  Comma is also missing. It should be:  "则返回列表“（一      ，二     ，三     ，四）”"

For the second part, I haven't got where you have corrected.  Are you saying to represent the list you should use (ba  ap) instead of (ba,ap) ?

**Comment by marksherman** [comment]
Thank you! And yes, the list representation is space-delineated, not comma. That's what I fixed in the English. I also found that second example was very broken in italian (in a new way), which is why I ask it be looked over again.

**Comment by Eagles2F** [comment]
Ok, then for the second part,  the Chinese list (稥,苹) is also comma-delineated which should be against your modified version.  The space-delineated one should be (稥 苹)

**Comment by marksherman** [comment]
Would you mind applying the edits to the whole chunk, so I can paste in the whole thing? I am really uncertain about making small edits to a language I don't know. I don't confidently know what I need to replace with your edits.

Thank you, @Eagles2F.

**Comment by Eagles2F** [comment]
For the first one:
zh_cn:
'''
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT = '以指定文本作为分隔符，将字符串分解为不同片段，并生成一个列表作为返回结果。\n'
    + ' 如以","(逗号)分解"一,二,三,四"，将返回列表"(一 二 三 四)"，\n'
    + ' 而以"-土豆"作为分隔符分解字符串"一-土豆,二-土豆,三-土豆,四"，则返回列表"(一 ,二 ,三 ,四)"。'
'''

zh_tw:
'''
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT = '以指定文字作為分隔符號，將字元串分解為不同片段，並產生一個清單作為傳回結果。\n'
    + ' 如以","(逗號)分解"一,二,三,四"，將傳回清單"(一 二 三 四)"，\n'
    + ' 而以"-土豆"作為分隔符號分解字元串"一-土豆,二-土豆,三-土豆,四"，則傳回清單"(一 ,二 ,三 ,四)"。'
'''
@marksherman

**Comment by Eagles2F** [comment]
The second one:
zh_cn:
```
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = '以列表中的任意项作为分隔符，\n'
    + '在首次出现分隔符的位置将给定文本分解为一个两项列表。\n\n'
    + '如以"(稥 苹)"作为分隔符分解"我喜欢苹果香蕉苹果葡萄"，\n'
    + '将返回一个两项列表，其第一项为"我喜欢"，第二项为\n'
    + '"果香蕉苹果葡萄"';
```

zh_tw:
```
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = '以清單中的任意項作為分隔符號，\n'
    + '在首次出現分隔符號的位置將給定文字分解為一個兩項清單。\n\n'
    + '如以"(稥 蘋)"作為分隔符號分解"我喜歡蘋果香蕉蘋果葡萄"，\n'
    + '將傳回一個兩項清單，其第一項為"我喜歡"，第二項為\n'
    + '"果香蕉蘋果葡萄"';
```

**Comment by marksherman** [comment]
Thank you so much, @Eagles2F . Once I entered the whole block, I was able to see the diff, and now I understand the changes you made. It looks to me like like all the patterns match up now. The pull request #323 has been updated, so everyone can see for themselves. I think everything is fixed.

**Comment by weihuali0509** [comment]
@Eagles2F @halatmit @marksherman The Chinese translation looks good to me. Moving to the pootle server.

**Comment by weihuali0509** [comment]
@tiffanyle couldn't figure out how to do these in the pootle server. Please go ahead or teach me how to do that :)

**Comment by halatmit** [comment]
#323 done
