### ISSUE TITLE
rename Canvas.WhenTouched parameter

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#324]
rename touchedAnySprite to TouchedSprite

**Comment by hasitpbhatt** [comment]
@halatmit 
You want to revert this change?
https://sites.google.com/site/mitfall2013/canvasnamechange

**Comment by halatmit** [comment]
@hasitpbhatt 

Hmm...   That's a good point.    Probably what we should really do is change that callback so it produces the sprite that was touched rather than just a boolean.   The requires a little thought.  I''l abandon this issue and close it for now.
Thanks for catching this.
