### ISSUE TITLE
Warning Error - Methods with invalid locals information

### ISSUE THREAD

**Issue by pitekkate** [mit-cml/appinventor-sources#3250]
**Describe the bug**

I have build using cmd "ant all" see this?

    ' [java] com.google.appinventor.buildserver.util.Execution execute
     [java] INFO: ____Executing java @C:\Users\Admin\AppData\Local\Temp\1729521789533_1547858475231097856-0\youngandroidproject\..\build\tmp\d8arguments.txt
     [java] Info: Stripped invalid locals information from 5 methods.
     [java] Info in C:\Users\Admin\AppData\Local\Temp\1729521789533_1547858475231097856-0\youngandroidproject\..\build\classes\com\google\youngandroid\runtime.class:
     [java] Methods with invalid locals information:
     [java]   java.lang.Object com.google.youngandroid.runtime.isYailEqual(java.lang.Object, java.lang.Object)
     [java]   Attempt to define local of type int as x:java.lang.Object
     [java]   java.lang.Object com.google.youngandroid.runtime.isYailAtomicEqual(java.lang.Object, java.lang.Object)
     [java]   Attempt to define local of type reference as x:boolean
     [java]   java.lang.Object com.google.youngandroid.runtime.mode(java.lang.Object)
     [java]   Attempt to define local of type int as element:java.lang.Object
     [java]   java.lang.Object com.google.youngandroid.runtime.yailForRangeWithNumericCheckedArgs(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)
     [java]   Type information in locals-table is inconsistent. Cannot constrain type: INT for value: v44 by constraint OBJECT.   
     [java]   java.lang.Object com.google.youngandroid.runtime.textDeobfuscate(java.lang.Object, java.lang.Object)
     [java]   Attempt to define local of type reference as c:int
     [java] Info: Some warnings are typically a sign of using an outdated Java toolchain. To fix, recompile the source with an updated toolchain.
     [java] [RunD8] Task succeeded in 41.647 seconds'

**Build machine**
- Windows OS
- JDK 11
- Cmd via Powershell

**Comment by ewpatton** [comment]
This is fine as it's just due to the version of Kawa we use. It arranges the class file content differently than what D8 expects but things work just fine.
