### ISSUE TITLE
Request to add support for x86 devices for AI2 Companion app

### ISSUE THREAD

**Issue by PANCHO7532** [mit-cml/appinventor-sources#3251]
Currently the companion app supports armeabi-v7a, arm64-v8a and x86_64, by supporting x86 devices the app should work on a broader amount of old devices and emulator images

**Comment by ewpatton** [comment]
Unfortunately, there are not enough Android x86 devices out there to justify the increased payload size for every other App Inventor user. Emulator users can use the Emulator.apk file, which doesn't include the WebRTC binaries, on any architecture.

**Comment by pitekkate** [comment]
> Currently the companion app supports armeabi-v7a, arm64-v8a and x86_64, by supporting x86 devices the app should work on a broader amount of old devices and emulator images

Ihave trybuild for you,rename zipname to apk..
try it
[MIT AI2 Companion.zip](https://github.com/user-attachments/files/17594736/MIT.AI2.Companion.zip)
