### ISSUE TITLE
Unable to deploy to Gcloud, getting error. Max file size is 33554432 bytes.

### ISSUE THREAD

**Issue by itsgaurav** [mit-cml/appinventor-sources#3268]
**Unable to deploy to Gcloud**

**Affects**

Beginning deployment of service [default]...
Created .gcloudignore file. See gcloud topic gcloudignore for details.
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 689 files to Google Cloud Storage              ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
Updating service [default]...failed.                                                                                                                                                                       
ERROR: (gcloud.app.deploy) Error Response: [3] The following errors occurred while copying files to App Engine:
File https://storage.googleapis.com/staging.myapp-mit-inventor.appspot.com/25336b515db4b84aa7ba1507e4eb20b4a71eee8d failed with: File https://storage.googleapis.com/staging.myapp-mit-inventor.appspot.com/25336b515db4b84aa7ba1507e4eb20b4a71eee8d is too big (99175062 bytes). Max file size is 33554432 bytes.

Details: [
  [
    {
      "@type": "type.googleapis.com/google.rpc.ResourceInfo",
      "description": "File https://storage.googleapis.com/staging.myapp-mit-inventor.appspot.com/25336b515db4b84aa7ba1507e4eb20b4a71eee8d is too big (99175062 bytes). Max file size is 33554432 bytes.",
      "resourceName": "https://storage.googleapis.com/staging.myapp-mit-inventor.appspot.com/25336b515db4b84aa7ba1507e4eb20b4a71eee8d",
      "resourceType": "file"
    }
  ]
]

**Comment by ewpatton** [comment]
It looks like you didn't compile a release build. First you will need to run `ant clean` to remove the old build files and then run `ant -Drelease=true noplay` to build a release build.

For further discussion, please see the [Open Source Development category](https://community.appinventor.mit.edu/c/open-source-development/10) in our community site.
