### ISSUE TITLE
formatting numbers for pickers

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#327]
When we print numbers in App Inventor, the conversion a numbers to it's string representation is handle by our formatting code.  We don't have a similar control for items displayed by ListPicker, ListView and others.   So, for example, dividing 2 by 7 and putting the result in a listPicker shows a number with many more decimal places than putting that same result into a label.

**Comment by halatmit** [comment]
#318

**Comment by jisqyv** [comment]
#318 MERGED
