### ISSUE TITLE
Companion Update Causes Bytecode Errors with Multiple Extensions (Works in Compiled APKs)

### ISSUE THREAD

**Issue by crowlingsppider** [mit-cml/appinventor-sources#3294]
**Title:**  
Companion Update Causes Bytecode Errors and Connection Issues with Multiple Extensions  

**Describe the Bug:**  
The latest update to the MIT AI2 Companion has broken compatibility with many extensions. Some common issues include:  
1. Bytecode errors when connecting through USB, especially with extensions such as:  
   - House of Hashing (hashing extension)  
   - Flubbie (animation of components)  
   - Horizon QR Code Generator  
   - Many other custom extensions.  

2. When connecting through Wi-Fi, the app often shows a blank screen. However, removing the affected extensions allows the screen to load.  

3. The compiled APK works perfectly without any issues, so this appears to be a problem specifically with the Companion.  

**Affects:**  
  
- [ ] Designer  
- [ ] Blocks Editor  
- [ ] Projects Explorer  
- [x] Companion  
- [ ] Compiled Apps  
- [ ] Buildserver  
- [x] Debugging  
- [ ] Other...  

**Expected Behavior:**  
Extensions should function smoothly with the Companion, just as they do when the app is compiled. USB and Wi-Fi connections should allow proper testing without errors or blank screens.  

**Steps to Reproduce:**  
1. Connect the app using USB with extensions like House of Hashing, Flubbie, or Horizon QR Code Generator added to the project.  
2. Observe bytecode errors during connection.  
3. Try connecting via Wi-Fi, and observe the blank screen when extensions are added.

**Comment by patryk84a** [comment]
This was fixed a while ago. Here is a test Companion:

https://community.appinventor.mit.edu/t/string-indexoutofbounds-exception-while-using-extensions-in-companion-app/132351/285

**Comment by Nishantware** [comment]
can you share the screenshots of that issue for more clarity ?

**Comment by crowlingsppider** [comment]
No need. Now the issue have been solved. Thanks 🔥
