### ISSUE TITLE
fix error message in fusion table API call to match service account behviors

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#339]
From Taifun

I just tested the fusiontable update and we get a nice error message again, great!

However there is a difference between the service account method and the api key method:
in case of an error, the service account method triggers additionally an error 2601 in the Screen.ErrorOccurred event, the api key method not...
what do you think: shouldn't that be consistent?

Taifun

**Comment by ewpatton** [comment]
Closing because FusiontablesControl is no longer supported.
