### ISSUE TITLE
Spinner AfterSelecting is now invoked only on every 2nd pick after elements are set using the Elements property setter.

### ISSUE THREAD

**Issue by colinwirt** [mit-cml/appinventor-sources#361]
A change was made to suppress the call to AfterSelecting when an item is initialized, however now the call is also suppressed for the first user initiated selection after Elements is set.

This is not a problem for ElementsFromString which does not set isInitialized = false;

Only a problem for Elements as isInitialized is set to false again.

See this note:
https://github.com/mit-cml/appinventor-sources/commit/094c19e4d256a3d74e1d089650305b1c2795edb8#commitcomment-10750680

**Comment by E-Hon** [comment]
Hi @colinwirt 
Would you have a look at #354 ?
Does it solve this issue?

**Comment by colinwirt** [comment]
Hi @E-Hon,
Unfortunately I haven't set up my own build environment to test changes like this, so I can't provide feedback myself.
Is there an AI server I can test this change on?

**Comment by E-Hon** [comment]
@colinwirt I can set up a server for this change but the companion will not support this so you can't really test it there. 

Here is an apk you may try though
https://www.dropbox.com/s/3yobkuw5y0d510i/SpinnerTest.apk?dl=0

I mentioned this issue in that pull request. Let's wait for the reviews' update

**Comment by colinwirt** [comment]
Thanks @E-Hon -- I normally test by installing an apk anyway, but am happy to leave my project on the backburner until I can redeploy via the MIT install.

**Comment by colinwirt** [comment]
#354 will fix this problem -- any help needed to get that released, or to rollback the poorly tested commit that broke the spinner?

**Comment by E-Hon** [comment]
@colinwirt oh really? that's nice that it solved this issue. could you add a comment in #354 to let them know this too? thx

**Comment by halatmit** [comment]
Also see #442
