### ISSUE TITLE
background issue when scrolling a list picker

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#368]
Please see the following bug report:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mitappinventortest/6068fs9UQlM/1rKmNIPZIpoJ

I verified this and saw the following behavior:
I created a project whose only element is a listpicker.   I set the background color of the listpicker to orange.  I set the elements of the listpicker to the 12 numbers 1,2,3,4,5,6,67,8,9,10,11,12, so that it is too long to fit on the screen and needs to be scrolled.
When I scroll the listpicker, the background turns black while my finger is touching.   When I lift my finger, the background generally  turns back to orange but sometimes remains black.

Note the comment from the user about getting different behavior when compiling under App to Market.

**Comment by josmas** [comment]
@halatmit did you mean to close this issue?

**Comment by halatmit** [comment]
Sorry, my mistake.  I'll fix it.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
#369 fixes this issue and it has been merged into the "ucr" branch pending the next component release.
