### ISSUE TITLE
BackgroundImage vs. BackgroundColor

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#371]
There appears to be an interaction between setting a BackgroundImage vs. setting a BackgroundColor. At the moment we always set the Color first followed by the Image which results in code that works. However if we set the BackgroundImage first, things do not work correctly. However the order here shouldn't matter. Clearly we need to get a better understanding of the relationship of setting a Background Image vs. a Background Color and implement the code accordinly.

**Comment by reza89** [comment]
tanks

**Comment by E-Hon** [comment]
it seems to me that BackgroundImage should be placed on top of BackgroundColor but i can't find any problem with Canvas and Screen; they put BackgroundImage on BackgroundColor so BackgroundColor is not shown.

**Comment by halatmit** [comment]
@jisqyv 
Jeff, any comments on this?   Can we close the issue?

**Comment by jisqyv** [comment]
@halatmit Yep, this one is fixed (and will be deployed in the pending release).
