### ISSUE TITLE
Add 24-hour time option to TimePicker

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#374]
It is a little annoying for us users outside the US that the TimePicker is using 12 hour format on an device that is configured for 24 hour format. Maybe the java-code 'behind' this functionality need a change to something like: "new TimePickerDialog(this, mOnTimeSetListener, time.hour, time.minute, DateFormat.is24HourFormat(this));"?

**Comment by halatmit** [comment]
#379

**Comment by jisqyv** [comment]
#379 Merged into UCR
