### ISSUE TITLE
French Translation for MIT App Inventor

### ISSUE THREAD

**Issue by Momoumar** [mit-cml/appinventor-sources#386]
Hi team,
MIT App inventor is translated into 3 languages (Spanish, Chinese, Italian). Which is great for internationalisation. I was thinking about making a french translation.
Some statistics can make it relevant:
"
•Along with English, French is one of the only two languages spoken on all five continents.
• Alone, or along with other languages, French has the status of an official language in 32 different countries and governments.
• In the European Union, the French language is in second place in terms of the number of its native speakers (16%), after German (23.3%).
• About 83 million people study French worldwide. Besides English, it is the most taught language in the world.
• More than one million Americans speak French at home. It is the fourth most spoken language in the United-States after English, Spanish and Chinese. " 

What do you guys think about it?

**Comment by halatmit** [comment]
Please look here for information:

https://docs.google.com/document/d/1v_Sy9u1Da4pmVo1KGR0691kq_AweZjguTJMI0nJA0eQ/edit




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by Momoumar** [comment]
Thanks @halatmit , I've never come across this document.

**Comment by halatmit** [comment]
We've just put it up.  There's now a note pointing to it on the main
appinventor page :

appinventor.mit.edu



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
@monmoumar
Have you done anything about contacting the people doing the French translation.
Can we close this issue?

**Comment by Momoumar** [comment]
@halatmit 
 I joined the App Inventor Translation Server and I saw that the French translation was almost over 
(99%).  Yes we can close it .

**Comment by halatmit** [comment]
closing

**Comment by halatmit** [comment]
Thanks.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty
