### ISSUE TITLE
Build failed! Sorry, can't package projects larger than 5MB.

### ISSUE THREAD

**Issue by Zhenit-606** [mit-cml/appinventor-sources#392]
Do not you think you should remove this limitation?
There is no point in running a local server with this limitation.

**Comment by halatmit** [comment]
We should review this to see if it can be increased.   Also think about relation to stand-alone systems.
Also, can we issue a warning to people who are exceeding that limit, e.g.,when they add assets (with a pointer to documentation about how to build projects that setup their assets so as to not run into the limtation).

**Comment by ewpatton** [comment]
The 5MB restriction was removed. However, there is a hard limit in GAE of [10MB for HTTP requests](https://cloud.google.com/appengine/docs/standard/java/outbound-requests#quotas_and_limits), which means that we cannot build larger apps without an infrastructure redesign.
