### ISSUE TITLE
Don't build if there are warnings.  [Was: Faulty check for empty slot?]

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#394]
I just looked at a project that contains the following block:

![screen shot 2015-05-27 at 8 17 10 pm](https://cloud.githubusercontent.com/assets/789431/7850343/efba5566-04ae-11e5-98ec-db126b8bac1d.png)

In the blocks editor, there was no red triangle, and I was able to select build, which then generated an error about the Yail procedure being called with the wrong number of arguments.

Why was the empty slot not detected?   By the way, the project is in the gallery as
CarRacing 2.   To duplicate the error, download the aia and try to build it.

**Comment by halatmit** [comment]
Jeff and I looked at this, and it seems that the real problem is that you can build or run do-it when there are warnings.  In this case, and empty slot produces a warning (not an error).
So the fix would be to not allow those builds or do-its.

**Comment by halatmit** [comment]
Fixing this should also take care of #395 .  Check that when this is fixed.

**Comment by halatmit** [comment]
Shruti will work on this.

**Comment by ewpatton** [comment]
Fixed by #1895
