### ISSUE TITLE
Image sprite rotation leaves does not fill enclosing rectangle on Android 5.1.1

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#400]
See thread with attached aia file

https://groups.google.com/forum/#!category-topic/mitappinventortest/specific-programming-issue/EDMn85XAlg0

**Comment by Momoumar** [comment]
Thanks @halatmit, I will look on it.

**Comment by Momoumar** [comment]
Adding  ``` java rotatedDrawable.setAlpha(254) ``` just before ``` java rotatedDrawable.draw(canvas) ``` around **line 140** of the **ImageSprite.java** component seems to "fix the bug". 
I don't really understand why. 

There must be a nicer solution.

**Comment by halatmit** [comment]
@jisqyv 
Momoumar, 
That sounds like the right fix, but I don't see the pull request in our public appinventor/sources repo.
I don't understand  why it's not there, since it's apparently in your fork.

**Comment by halatmit** [comment]
pull request #403

**Comment by halatmit** [comment]
handled in pull reuest #408
