### ISSUE TITLE
Improve the drawing code for image sprites (and rotating them)

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#407]
This in an exchange between Hal and Dan Sandler of the Android team regarding how we rotate sprites.     You'll see that Dan suggest changing how we do the drawing.    Try this, and see if it's an improvement.  Make sure it does not have the "black border" bug that was fixed in pr #403

Here's how we create the spriteL

We initially create a BitMapDrawable from an image:

InputStream is2 = openMedia(form, mediaPath, mediaSource);

return new BitmapDrawable(decodeStream(is2, null, options));

I see that the BitmapDrawable constructor is deprecated.  I wonder if that's the issue.

We then build a bitmap
  unrotatedBitmap = drawable.getBitmap();

Then we scale the bitmap and rotate  it using a matrix, mat
scaledBitmap = Bitmap.createScaledBitmap(unrotatedBitmap, w, h, true);

 rotatedBitmap = Bitmap.createBitmap(scaledBitmap,0, 0,scaledBitmap.getWidth(), scaledBitmap.getHeight(),mat, true);

Then we build a drawable from the rotated bitmap

  rotatedDrawable = new BitmapDrawable(rotatedBitmap);

and we draw that on the canvas

  rotatedDrawable.draw(canvas);

As I wrote, this all worked before Lollipop, but starting with system 5, the drawn rotated bitmap is surrounded by black, that fills out the bounding square.
We can fix this by doing rotatedBitmap.setAlpha before calling Bitmapdrawable.

But I'm wondering what changed and/or if we should be doing this another way.

Thanks

Dan Sandler
12:29 PM (8 hours ago)

to me 
A few things:

(1) You're unnecessarily creating a BitmapDrawable when what you really want is the Bitmap; you want to use BitmapFactory.decodeStream() to go right to a Bitmap. 

(2) You probably don't want to bake a new rotated bitmap; you rather want to draw it with rotation (i.e. with a rotation matrix on the Canvas) so that you can keep the original bitmap around for a different rotation, but more importantly this should allow you to take advantage of hardware acceleration in the drawing.

(3) Another way to do this is to create a BitmapDrawable as before (but use the non-deprecated constructor, BitmapDrawable (Resources res, InputStream is)) but then wrap it in a RotateDrawable and let it do all the work for you.

**Comment by Momoumar** [comment]
@halatmit,
The implementation of the second method seems to fix the black background bug in passing.
Ref : pull request #408

**Comment by jisqyv** [comment]
#408  Merged into ucr branch.
