### ISSUE TITLE
Alignment in arrangements is may have unnecessary restrictions

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#410]
See this thread in the forum:

https://groups.google.com/forum/#!category-topic/mitappinventortest/JthYE6ZdxWU

Note that the problem is fixed by changing the HorizontalArrangement  to give is a fixed height and making the VerticalAlignment centered.  But should that be necessary?

Also, in general, if you have a horizontal arrangement whose height is Automatic, then you cannot change the vertical alignment.  (similarly for width/Horizontal).   Hal put this restriction in, but he doesn't remember why, or whether it is necessary.

**Comment by liyucun** [comment]
The possible explanation i can find is that this feature might be used for guiding user to set layout alignment. That can avoid a user wondering why there is no changes after setting AlignVertical to centre when layout height is Automatic.

**Comment by halatmit** [comment]
Adding ghica's comment:

Try the attached .aia
The height of the 2 buttons will become not equal, if they have different amount of text lines in them, also in the test version given here.
The workaround now is: Go to the design view, set the height of the Horizontal Arrangement to something fixed, then set AlignVertical to center. Then you can set the height back to automatic if you wish. After this, the buttons will look OK.
But the real fix should be something more logical I think. 
Cheers, Ghica.

**Comment by halatmit** [comment]
Yucun,
Here is a picture.
![mail google com](https://cloud.githubusercontent.com/assets/789431/8686917/ba2aca64-2a58-11e5-9e46-5508fbebaee9.png)


It shows the screen after the top "try" button is pressed, and it shows that the buttons are not properly aligned.

​I also uploaded a new, modified .aia, to make it (I hope) easier to see what is wrong.
Try the "try" buttons from top to bottom. The first one will show the problem.
The last one will set Align Vertical to center. And that fixes the problem.
You cannot do this from the design view, because "center" is greyed out.

One other remark, I do not know whether you can fix that too: The documentation does not tell how to set the AlignVertical attribute. It does not accept "center", therefore I tried 2 and it works.
Cheers, Ghica.

Met vriendelijke groeten,
Ghica van Emde Boas
email: emdeboas@bronstee.com

**Comment by halatmit** [comment]
adding Mark's comment:

So, it seems that there are some inconsistencies between App Inventor behavior and the documentation, as well as the UI inconsistency I pointed out earlier.

The AI documentation for the HorizontalArrangement (see here) states that the AlignVertical property has no effect if the arrangement's height is automatic.  Ghica's app shows that this is not the case.  Changing the AlignVertical property of a HorizontalArrangement does have an effect!  I suggest either trying to understand the effect, documenting it properly and allowing the designer to change the property or, if the desire really is to have property change have no effect then there's a bug that needs to be fixed.  There may be a similar bug with respect to the AlignHorizontal property when the arrangement's width is automatic but I haven't tested that.

A similar situation to the above probably exists for the VerticalArrangement component, which has similar documentation and UI designer behavior.

I'll also point out that there is another pretty bad inconsistency in the different ways that the UI designer and the device/emulator display buttons with long text.  It would be nice to fix the designer's rendering to at least come a little closer to the device (i.e. be able to do multi-line).

Ghica, please note that the AI documentation for the HorizontalArrangement does, in fact, specify that vertical alignment has the value 2.

**Comment by halatmit** [comment]
See also #468 and check whether fixing that helps this issue.

**Comment by liyucun** [comment]
Hi @halatmit 

As Mark said, this unnecessary restrictions is different from issue #468. I have made a App Inventor instance for fixing this issue, in which the align editor is remove if height or width is automatic. If this looks fine, I can make a pull request for solving this issue.

The link for this issue: http://spinner-issue.appspot.com/

**Comment by halatmit** [comment]
I'm not sure this is correct.   Here's an example with the system you just
put out.
It's a horizontal arrangement whose height is automatic.   Inside that is a
button with height 150 and a button with height 75.   It looks good.


[image: Inline image 1]

Now suppose I want to change this so that the two buttons are aligned at
the top (while the button texts are vertically centered withing each
button, as they are now).     To make that change I would expect to do that
by setting the alignVertical property of the Horizontal arrangement to
Top.  But that's not what happens in the current system (where that
property already is Top).   And I can't set that property at all in your
new system.

I agree that yours is better than the current system (which seems just
wrong).   But can it be fixed so that alignVertical does what I'm
expecting, both on the phone and in the designer?



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by liyucun** [comment]
Hi @halatmit 

This scenario is related to issue #468. The button with 75 height is in centre of horizontal arrangement, it is because arrangement's baselineAligned attr is True by default so that two button have to be aligned based on their text.
![image](https://cloud.githubusercontent.com/assets/4750970/8767504/ffe0c9fa-2e2c-11e5-85ae-8d35c5881b5b.png)
As this pic shows, two buttons are aligned based on that red line (baseline).
If we set baselineAligned attr to False, it will looks like this:
![image](https://cloud.githubusercontent.com/assets/4750970/8767510/379808ea-2e2d-11e5-96bb-3ea173ae6386.png)
This is what buttons should look like if we set Horizontal Arrangement alignVertical property to Top. And yes, Horizontal Arrangement alignVertical property is Top by default. 

At this point, I have to change my mind to say: we should not restrict alignVertical property, it will make sense for user to set Top, Centre or Bottom.

Here is my new App Inventor instance: http://spinner-issue.appspot.com/
AI companion can be obtained by this link:
https://drive.google.com/open?id=0B82XjlreSEX_TzNPdFc0cGN5ZW8

There are still have some inconsistency between Designer view and phone view, but if you set AlignVertical to Top, Center, Bottom, it will show the right view on phone.

**Comment by halatmit** [comment]
What I want is what's in the bottom of your two pictures in the case where
the Horizontal Arrangement alignVertical property is set to Top.


What I also want is that the two buttons should be center aligned when the
Horizontal Arrangement alignVertical property is set to Center.

And similarly, the bottomw of the buttons should line up when the
Horizontal Arrangement alignVertical property is set to bottom.

I understand that it would be only in the Center case that the text of the
two buttons would line up


Is that what you have?




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by liyucun** [comment]
Hi @halatmit 

Yes, this instance covers all these three cases you described.

**Comment by halatmit** [comment]
@liyucun 
Please submit a pull request for this, so we can experiment with it and do a review.  Thanks.

**Comment by halatmit** [comment]
#474 was closed
