### ISSUE TITLE
Set screen bakcground color to none when there is a backgorund image

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#420]
Background images do not show up unless the background color is none.   People always get confused by this -- they think the image is missing, or something.  So let's just set the background color to NONE when there is a background image.  This seems like a simple fix, although it might require some fancy footwork in the designer to keep the background color selection consistent with whether or not there is a background image.

**Comment by William-Byrne** [comment]
Just an FYI, Justus figured out how to fix this issue in another way by making sure a BackgroundImage overlays a BackgoundColor and not the other way around.

**Comment by halatmit** [comment]
Closing this, given Justus's better approach.
