### ISSUE TITLE
arrangement causes blocks to become misaligned

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#429]
from Emery (gerndto@wellesley.edu)

I discovered that when you rearrange the blocks, either vertically, horizontally, or by category, the blocks become misaligned and not quite fit together,

At first glance, this bug would go unnoticed because each rearrangement only moves the blocks apart a very small amount. But the more you rearrange them, the more noticeable the misalignment becomes. It should be noted that this doesn't cause any runtime errors. The blocks are still seen as "connected", although physically they don't appear to be. Once you click the blocks back together, the problem is alleviated. 

I have included a screencast to better show the bug.

https://doc-0c-18-docs.googleusercontent.com/docs/securesc/rd6kbsgd7e16nd3ft488pf0ajqrglngu/vvfceldj1p7t553ccrrnshn85ufr5jk2/1435176000000/06364812470543295210/12122553465742055220/0B6vhv-nWNii5bkM1dmllX0dSb0U?e=download

I'm hoping to pass this along to someone who is bit more savvy in the realm of SVGs.

**Comment by ewpatton** [comment]
I believe this was a bug in Blockly. It does not appear to be happening as of the Blockly merge in May. Closing for now.
