### ISSUE TITLE
Splash Screen should be dismiss-able

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#431]
Add a "Do Not Show Again" checkbox to the splash screen. When checked, we will store the version of the splash screen shown. We will keep track of the version of the current splash screen and only show it when it is greater then the version dismissed.

**Comment by afmckinney** [comment]
Jeff is this done now. ?

**Comment by jisqyv** [comment]
@afmckinney Done. Thanks for pointing this out. I'm closing this issue.
