### ISSUE TITLE
Malformed Component Help Widgets

### ISSUE THREAD

**Issue by William-Byrne** [mit-cml/appinventor-sources#446]
In the Designer Palette, certain component help widgets produce malformed popups. The Sharing, BluetoothClient, and BluetoothServer components are affected to name a few, but I have noticed unreleased components with similar problems.
![ComponentHelpWidgetBug](https://cloud.githubusercontent.com/assets/4909086/8462424/d07811d4-2001-11e5-98d7-2e1bfdf1cfde.png)

**Comment by ewpatton** [comment]
This looks like it was fixed in 84003f0.
