### ISSUE TITLE
streamline localization process

### ISSUE THREAD

**Issue by jsheldonmit** [mit-cml/appinventor-sources#457]
1) easier for admins to create new language
2) better user documentation?
3) #388 - ability to contact language admins
4) are translations going into source control?
5) how to deploy translations
6) how to update/refine translations as they are improved after deployment
@jisqyv

**Comment by jisqyv** [comment]
@jsheldonmit This isn't really an issue for the sources. We need to redesign how we are handling translations. We should have a meeting to just deal with this issue. I should be in on Monday, and I can do a hangout on Friday (and maybe Thursday afternoon depending on how things go that morning).

**Comment by jsheldonmit** [comment]
Gotcha.

On the topic of meetings, maybe Thursday or Friday, and if not, then later next week, as I’m traveling to CSTA on Monday/Tuesday 7/13&7/14.

If this doesn’t go in sources issues, do you have a suggestion for where we track this kind of issue? Start another github project that exists mostly for issue tracking?

Thanks
josh
================
Josh Sheldon
Director of Strategic Programs – MIT App Inventor
Project Manager - MIT Scheller Teacher Education Program
MIT Center for Mobile Learning
20 Ames St., Bldg E15-309
Cambridge, MA 02139
cell: 617-671-5491
work: 617-715-4051

http://appinventor.mit.edu - @MITAppInventor<http://twitter.com/MITAppInventor>
http://education.mit.edu - @mitSTEPlab<http://twitter.com/mitSTEPlab>
