### ISSUE TITLE
Export/share blocks of code (preferably to HTML)

### ISSUE THREAD

**Issue by arve0** [mit-cml/appinventor-sources#461]
Hi!
I'm a volunteer in a Norwegian code club which wants to start an App Inventor course. We base a lot of our activity around [tutorials](http://arve0.github.io/oppgaver/). For Scratch we use [a generator](http://scratchblocks.codeclub.org.uk/generator/) for exporting projects and [scratchblocks2](https://github.com/tjvr/scratchblocks) for rendering the code blocks. In example, [this code](https://github.com/arve0/oppgaver/blob/master/src/scratch/felix_og_herbert/felix_og_herbert.md#sjekkliste-check-2) renders to [this](http://arve0.github.io/oppgaver/scratch/felix_og_herbert/felix_og_herbert.html#sjekkliste-2).

 It would be nice if one could export blocks of code for use in tutorials (kind of *"external #458"*). Does a feature like this exists? I've tried googling and searching issues for *export*, *share* and *blockly*, but have not found anything.

cc @tjesi

**Comment by halatmit** [comment]
We're working on several approaches to copying blocks.  they won't be exactly like what Scratch has, but better than what we have now.   I'm going to close this issue, since we won't be taking it up other than in what we're already working on.  thanks for the suggestion.

**Comment by arve0** [comment]
Thanks for the heads up! Do you have any issues/PRs that I can subscribe to and be kept updated?

**Comment by halatmit** [comment]
All the issues and PR on Github are public.   What we need is people to
work on them.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by arve0** [comment]
Sorry for not being clear.

> other than in what we're already working on.

Found #179 and #458, guess that's all copy features that's in the works now?

**Comment by halatmit** [comment]
You can track it on Github.


You're also welcome to participate in the App Inventor Open source forum
and the App Inventor support forum.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty
