### ISSUE TITLE
Align button in arrangement problem

### ISSUE THREAD

**Issue by liyucun** [mit-cml/appinventor-sources#468]
This problem is originally reported from issue#410, and there are some related discussion in developer group: https://groups.google.com/forum/#!topic/app-inventor-dev/wcw6iKvAJrQ

*if I have a horizontal arrangement, with only 2 buttons in it, who have fixed and equal height, they should be aligned so that their bottom and top are equal. But that is not the case, if they contain text with multiple lines, and not the same number of lines, as my picture shows. And I should not need to set a vertical alignment!*  -- from Ghica's description for the problem

Other than the problem in our app inventor, I tried to make the same view setting in Android, it turns out that Android also have this "problem". If I have a linearlayout that is horizontal orientation, with 2 buttons in it, who have fixed and equal height, it will turns out to be the same view like Ghica's description. Shows as below:

![image](https://cloud.githubusercontent.com/assets/4750970/8763498/05dcb154-2d6d-11e5-931b-098598852208.png)

**Comment by halatmit** [comment]
Yucun,

Thank you for verifying that!  That sounds like a bug in linear layout.  I
wonder if it's been reported on the web. In any case, if that's a bug
there, we won't try to patch around it in App Inventor.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by liyucun** [comment]
Hi @halatmit ,

It turns out that this problem is related to baselineAligned attribute of LinearLayout (http://developer.android.com/reference/android/widget/LinearLayout.html#attr_android:baselineAligned).
 
As below shows:
![image](https://cloud.githubusercontent.com/assets/4750970/8763820/a6f12222-2d7d-11e5-9f80-355af59172b3.png)
These two button above are aligned according to their text instead of button layout. By default, linearlayout's baselineAligned attr is TRUE, and hence we have this kind of alignment problem.

One possible and simple solution would be adding baselineAligned property in our App Inventor for LinearLayout.

I put a reference link here in case of my explanation not clear enough:
https://possiblemobile.com/2013/10/shifty-baseline-alignment/

**Comment by halatmit** [comment]
Would it work to just set BaseLineAligned to false?   It would be good if
App Inentor users didn't have to deal with this.  Or is there a reason why
App Inventor users might  sometimes was it set to true?   If so then you
should go ahead and add the property -- but be sure to document it in a way
that App Inventor users can understand it.






== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
See if this helps with issue #410

**Comment by liyucun** [comment]
Hi @halatmit 

By setting BaseLineAligned to false, it can solve that problem. But for sure, it will definitely have influence for most app which using Vertical/Horizontal Arrangement. I have been working on finding side effects by setting that. For button or textview(baseline is mainly used to the view showing text), there won't be any problem problem for them. Just like Android documents said: it's particularly useful when the children use different values for gravity (http://developer.android.com/reference/android/widget/LinearLayout.html#attr_android:baselineAligned). 
Basically, that particular case is to make different gravity button align their text on the same line, just as below shows:

*button1: gravity = bottom; button2: gravity = top; button3: gravity = bottom
All three buttons have same height and width.*

baseLineAligned = true
![image](https://cloud.githubusercontent.com/assets/4750970/8767064/65e97a68-2e1d-11e5-93e7-95223fbb4e28.png)

baseLineAligned = false
![image](https://cloud.githubusercontent.com/assets/4750970/8767070/afe20d92-2e1d-11e5-945b-de885404447b.png)

I don't think adding baselineAligned property will help us a lot, instead it will increase the complexity of App Inventor to our user because they have to spend time on getting to know what is baseline and how it gets aligned etc...

Therefore, I suggest to set this baselineAligned attribute to false by default in App Inventor so that it will not confusing our user for button or textview alignment problem.

**Comment by halatmit** [comment]
Setting baselineAligned to false sounds like the right thing to do.

Why don't you put up a test ins\stance that we can invite people to
experiment with


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by liyucun** [comment]
The instance is running on: http://spinner-issue.appspot.com/
The Ai Companion can be found at: https://drive.google.com/open?id=0B82XjlreSEX_TzNPdFc0cGN5ZW8
More detail about this instance can be found in issue #410 discussion.

**Comment by halatmit** [comment]
Yucun,

This look good on the phone.  Can you fix it in the designer?

The code is in

appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockHVLayoutBase.java

== Hal



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by liyucun** [comment]
Hi @halatmit ,

Yes, I am going to fix that as well.

**Comment by halatmit** [comment]
#474 was closed
