### ISSUE TITLE
Image sprite rotation losing resolution

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#469]
See this bug report by Taifun:

https://groups.google.com/forum/#!msg/mitappinventortest/1m-qIrXIkSQ/aMkG2ahmx14J

I think this used to work, and the degeneration is due to the new rotation code that was installed here:

https://github.com/mit-cml/appinventor-sources/pull/408/files

**Comment by Momoumar** [comment]
I'm looking into this.

**Comment by halatmit** [comment]
Thank you!  I was hoping you would take this on.   I think I created the
problem when I changed the rotation method.   Please explore that.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
@Momoumar
There are a couple more complaints about image resolution on the forum today.   Let me know if you make progress on this issue, so we can see if it addresses those complaints.   thanks.  file a pull request when you have something. Thanks.

**Comment by Momoumar** [comment]
@halatmit,
I'm looking into it. Actually this seems not to be caused by our latest drawing algorithm. I've reversed to the commit before we changed the drawing and the bug remains the same. I'm exploring other solutions.

**Comment by halatmit** [comment]
@Momoumar I'm surprised that this was not caused by the change in algorithm.
Let me know what you discover.
Thanks

**Comment by halatmit** [comment]
I'm working on this.  Wait for me.

**Comment by halatmit** [comment]
@Momoumar 
I'm going to take this over and finish it and file a pull request.  I had to change the rotation algorithm.  Thanks for looking at it.

**Comment by halatmit** [comment]
PR #472

**Comment by halatmit** [comment]
#472 was closed
