### ISSUE TITLE
"Export all projects" disabled in My projects view

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#481]
I am exporting my students' work from earlier this month.

I've noticed that if I go to the projects listing from the top-level "My Projects" button, then the menu option to "Export all projects" is not available.

OTOH, if I go there by choosing Projects > My projects, then it's available.

I think this is a bug.

**Comment by be1be1** [comment]
Dear Prof. Hal, has this issue be fixed already? I am trying to do it and I have one question. As a normal user, should I be allowed to export all projects when I am in the designer/block view?

**Comment by halatmit** [comment]
@bxie 
Yes, I think you should be able to do it from the designer view.
I'll assign the issue to you.
