### ISSUE TITLE
update developer documentation on how to add a property to a component

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#499]
Update this document:
https://docs.google.com/document/d/14c1X19s6pXYHdDBOJJELcmOghWbm2FPekRvGzX0ENps/edit
The upgrade section needs to be rewritten for App Inventor 2.

**Comment by halatmit** [comment]
Old version marked obsolete:

Use the new version here:

https://docs.google.com/document/d/1ukpZXcd0fIn1fV0cNp4J00wrfwwA1daswU1yY6dqqfs/edit

**Comment by josmas** [comment]
Have modified the website to link to the new document (and made minor corrections). Closing this now.
