### ISSUE TITLE
CheckBox MockComponent Resizing

### ISSUE THREAD

**Issue by thequixotic** [mit-cml/appinventor-sources#500]
As of now, the CheckBox in Designer does not change its size based upon the text content inside it.
Its not really a problem just after dragging it to the Designer (because the size is big enough).
But if you change the Text of the CheckBox to small text length or blank. And then reload the website. Then the bounding box becomes really small and It will get kinda annoying. 

It would be nice if CheckBox(in the designer) resizes itself according to content just like a Button! 

It starts looking like this..
![checkboxerror](https://cloud.githubusercontent.com/assets/4526473/9202947/dd31d3c0-4071-11e5-9f4c-e5c0032743b3.png)

**Comment by thequixotic** [comment]
@William-Byrne ... interested ?
Here is a brief. 
![checkbox2err](https://cloud.githubusercontent.com/assets/4526473/9203003/38f1d4c6-4072-11e5-914f-86ddacd5cde2.png)

The green bounding box, size is determined by the first text content of the CheckBox. Change it so that it kinda behaves like a button.

**Comment by halatmit** [comment]
It's fine to look at this, although there are other probably more critical
issues.   But if you do work on this, try do to make an ad-hoc solution for
the check box.  Won't labels and buttons have similar issues?



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by thequixotic** [comment]
No a label and button does not have similar issues.
Tested them both. CheckBox does have this error.

**Comment by halatmit** [comment]
Try to make checkbox use whatever methods label and button use if that's
possible, rather than implement something unique to checkbox.






== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by William-Byrne** [comment]
@thequixotic 
I will look into this a little bit later today.

**Comment by ylu21** [comment]
Hi, my name is Yichen and I found out about GsoC from our school's email. I try to fix this bug but I'm not sure if this is the result that the app is looking for. Here is the preview. 
![screenshot from 2016-03-09 13 19 50](https://cloud.githubusercontent.com/assets/6993868/13645602/ba0c4352-e5f9-11e5-93d1-a601059054d9.png)

**Comment by metlaivan** [comment]
Hi. I fixed this issue at https://github.com/mit-cml/appinventor-sources/pull/737 pr.

**Comment by ewpatton** [comment]
Closed via #737
