### ISSUE TITLE
Responsive mode seems to apply to screen 1 only

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#509]
See this message from Ghica:

Hi, I am trying the pending release of the responsive system.
(http://ai2-test.appinventor.mit.edu)
I have a very simple testcase (aia attached) with two screens, both with a canvas of 100px square. If I use responsive mode, the width of my screen is 600 on my first screen, but whatever I do, it stays 320 on the second screen.
Here a link to the test case.

https://drive.google.com/open?id=0B3jsksMcCW5bZlNrMGNxeVhWNTA

**Comment by jisqyv** [comment]
I believe I can fix this without a component release!

**Comment by halatmit** [comment]
#513 was closed
