### ISSUE TITLE
Videoplayer crashes if set sizes to percentage

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#538]
Create an app that has only a video player in it.   Nothing else, and you don't need to set the source to anything.
Use fixed sizing.
Set the width and height to some number of pixels, say 100 x 200 and connect the companion.
Now set the width to 40%, and the companion will crash.    Logcat excerpt below.

You also get a crash if this is done with responsive sizing.

E/SurfaceFlinger(  172): dimensions too large 16776176 x 200
E/SurfaceFlinger(  172): createNormalLayer() failed (Invalid argument)
E/SurfaceComposerClient(  549): SurfaceComposerClient::createSurface error Invalid argument
W/WindowStateAnimator(  549): OutOfResourcesException creating surface
I/WindowManager(  549): Out of memory for surface!  Looking for leaks...
W/WindowManager(  549): No leaked surfaces; killing applicatons!
W/ActivityManager(  549): Killing processes Free memory at adjustment 1

**Comment by halatmit** [comment]
close when #537 is merged

**Comment by halatmit** [comment]
also see issue #527

**Comment by jisqyv** [comment]
@halatmit Fixed in #539
