### ISSUE TITLE
Add backgrounds to screen arrangements

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#545]
See

https://groups.google.com/forum/#!msg/mitappinventortest/5DIcuVl0Jck/0cMmcnSRDAAJ

**Comment by kkashi01** [comment]
Having git push issues. Will upload in a day. Sample .apk here: http://www.3NPortal.com/temp/LayoutTest.apk

**Comment by halatmit** [comment]
Please test this for the interaction between background color and image,
that was part of Mouamar's PR.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by josmas** [comment]
did this ever happen or is it still open (link to PR)? @kkashi01

**Comment by ewpatton** [comment]
The provenance appears to be lost here, but I am assuming that PR #547 was the fix for this and that this issue has been resolved. Please reopen it if I am mistaken.

**Comment by kkashi01** [comment]
Wow. That's from 2 years ago :o)

I'll have to check on it.
