### ISSUE TITLE
Troubles with Python scripts shebangs

### ISSUE THREAD

**Issue by jerry73204** [mit-cml/appinventor-sources#556]
I have troubles with Python script shebangs "#!/usr/bin/python" in most of Python scripts since the path 
"/usr/bin/python" on my system (ArchLinux) is symlinked to Python 3.x binary by default.
These Python sources seems to be Python 2.x scripts and thus this causes these scripts failed.
I would recommend changing the shebangs to this one "#!/usr/bin/env python2".
It explicitly calls Python 2.x interpreter and avoids the assumption of the binary path "/usr/bin/python2". (the path maybe /usr/local/bin/python2 on some systems)

**Comment by josmas** [comment]
Hi there, which scripts are you trying to use? The only script used for building is not a dependency anymore, so not sure why you are having issues. What are you trying to do?

**Comment by jerry73204** [comment]
Oops, I found I was building the server on an old repo not following newer commits. It solved after git pull. Sorry for that and thanks for your reminder.
