### ISSUE TITLE
Check out App Inventor with Marshmallow

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#565]
Are there issues with Marshmallow?  We need to run some tests

**Comment by machinaESC** [comment]
I had to downgrade in order to make 2 of my projects work - even after building the .apk
gonna get a second device in a few days and try to test properly and report.

**Comment by halatmit** [comment]
@machinaESC 
thanks. Please send more info when you can get.

**Comment by machinaESC** [comment]
every Query to FusionTable returns a "401 Unauthorized Invalid Credentials".
tested with FusiontablesControl.Query , .GetRows and .GetRowsWithCondition

logging into google again didnt help. all permissions inside of the table are given.  on the same phone downgraded to lollipop with no changes works fine.

tested with 
official marshmallow 6.0 on Nexus 6 
and
12.1-20151024-NIGHTLY-hammerhead on Nexus 6  (which I am not sure if its already using marshmallow as basis)

12.1-20151017-NIGHTLY-hammerhead on Nexus 6 is the last version I tested that worked fine.
5.1 or 5.0 Lollipop on Nexus 6 worked as well

will try test a little bit more focused.

**Comment by halatmit** [comment]
@machinaESC Thanks.  Let' keep collecting information.  I'ts hard to see why moving to Marshmallow would causes this.  Might be worth doing a web search to see if other system than App Inventor are seeing this sort of thing.

**Comment by machinaESC** [comment]
more here: https://groups.google.com/forum/#!topic/mitappinventortest/W45ue3N85CM
and here: https://groups.google.com/forum/#!topic/mitappinventortest/BKANSdkRB9s

**Comment by puravidaapps** [comment]
it seems to be, that this is NOT an Android M issue... It also has been reported on Android L 
and as you can see, the service account method still is working fine
Taifun

**Comment by rinterdonato** [comment]
I am seeing the same thing. Fusion table apps that run on the emulator and on kit kat devices do not run on lollipop or marshmallow phones -either as complied apk files or within app inventor. I have set up new api keys and verified that it is not permissions on the table itself.
I can also confirm that the service account method still works too.

**Comment by sergito91** [comment]
I am having the same problem. Do you know how to solve it?

**Comment by rinterdonato** [comment]
As has been mentioned by others, the service account method works - and in
many ways, it is a better solution all round.

r

**Comment by halatmit** [comment]
Marshmallow works, although we'll need to make changes to how we handle permissions if we move the target SDK to OS 6.
