### ISSUE TITLE
Twitter component not working

### ISSUE THREAD

**Issue by fmntf** [mit-cml/appinventor-sources#572]
Hello. I've tried to use the Twitter component: Twitter1.TweetWithImage(status, imagePath).
Unfortunately it does not work.

Error 306 is triggered with message "set status failed. need to login?"

It looks to be [broken since 2012](https://code.google.com/p/app-inventor-for-android/issues/detail?id=2303) and never fixed. Am I wrong?

**Comment by josmas** [comment]
Are you using the authentication block before trying to send a message?
The component has been changed a number of times when Twitter changed their APIs, so even though the issue linked was never closed, the component was fixed at that time.

**Comment by fmntf** [comment]
Hi, can't test it now. I didn't see the `Authorize` block, so I think that's the problem. Thank you!

**Comment by fmntf** [comment]
Hello, I tested it and it is not working out of the box. ConsumerKey and ConsumerSecret properties are set on the Twitter1 component.

![tw](https://cloud.githubusercontent.com/assets/287717/11508372/bc25b73e-9858-11e5-8ad7-8d3e0d8c774f.png)

![screenshot_20151201-182145](https://cloud.githubusercontent.com/assets/287717/11508379/c7fb39d0-9858-11e5-81ab-9294be789694.png)

**Comment by puravidaapps** [comment]
the twitter component is working fine, see an example here https://puravidaapps.com/twitter.php
Taifun
PS: a better place to ask questions would have been the App Inventor forum https://groups.google.com/forum/#!forum/mitappinventortest ...

**Comment by bennytheshap** [comment]
@puravidaapps are you sure this component still works? Your sample code puravida.../twitter.php raises the same error as the screenshot in @fmntf's screenshot.
