### ISSUE TITLE
Canvas Draw functions only draw on the line y = -x

### ISSUE THREAD

**Issue by ajcolter** [mit-cml/appinventor-sources#575]
The Canvas component drawing functions (DrawCircle, DrawPoint, DrawLine) seem to be broken. They will only draw along the line y = -x (so the X value is always correct, the Y is always the negated value of X). 

Here's a link to a sample AIA: https://www.dropbox.com/s/yf343b8mjtz7dgy/PaintPot.aia?dl=0

**Comment by halatmit** [comment]
I'm seeing weirdness with DrawLine on my Nexus 4.   I haven't had a chance
to to careful obsevation, but it's like what Aubrey is seeing.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
Fixed
