### ISSUE TITLE
update the documentation on testing and debugging

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#583]
https://docs.google.com/document/d/1BeLh_HKtVwmphKZZJyemtr8x5j1whLD8V4v6-QHj8TE/edit#heading=h.tav27sktyepa

Convert to AI2 and add better advice/information on debugging

**Comment by kdclang** [comment]
File has been updated to AI2. Added a bit more about using Notifier and Labels to display values during debugging.

**Comment by halatmit** [comment]
@kdclang Thanks.

closing the issue
