### ISSUE TITLE
Wrong URL in QR code for helloPurr

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#621]
I went to page
http://appinventor.mit.edu/explore/ai2/hellopurr.html
and tried to download the apk for HelloPurr using the QR code.
The code there seems  to be for the wrong URL:  It is 
appinventor.mit.edu/sites/all/files/ai2tutorials/.....

The link just underneath there is correct:
appinventor.mit.edu/explore/sites/all/files/ai2tutorials/....

I didn't check any of the other tutorials, so I don't know how prevalent this is.

I'd hope we can easily solve this with a symbolic link on the server, but I don't know how that interacts with statification.

**Comment by jsheldonmit** [comment]
fixed with new QR code for this tutorial - did not investigate whether other QR codes were broken

**Comment by halatmit** [comment]
fixed
