### ISSUE TITLE
Comment text is not generated in "Download blocks as image"

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#624]
The function "Download Blocks as Image" does show the comment blocks, but they are empty.

**Comment by shrutirij** [comment]
I think it's because the text isn't part of the workspace svg.

I'll look at how to fix this.

**Comment by halatmit** [comment]
Thanks



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by josmas** [comment]
heya @shrutirij let me know if you've no time to work on this and can be assigned to someone else.

**Comment by shrutirij** [comment]
@josmas I've been swamped, so I'll work on this over this weekend. Is that ok?

**Comment by josmas** [comment]
Heya @shrutirij sure, not a problem. Just let me know if you can't get to it in the next week or so and I'll open it up for grabs. Thanks for looking into it anyway; hope you are keeping well! :)

**Comment by thejdeep** [comment]
Would love to work on this. Please help me proceed. Thanks.

**Comment by wadleo** [comment]
Hi @josmas, @halatmit please can more information be provided for this task, thanks.

**Comment by abhijit5893** [comment]
I have been playing around with this for a while and I think I have found out the issue.  In /GSOC/appinventor-sources/appinventor/blocklyeditor/src/exportBlocksImage.js (line 73) there is a function call "cloneNode". cloneNode is an inbuilt function and  a bug regarding textarea content not being cloned has been [reported](https://bugs.chromium.org/p/chromium/issues/detail?id=487352). So if we update the code with the latest version, the bug should be fixed. No change in code necessary.

**Comment by chenglonkhin** [comment]
Has anyone made any progress on this yet? It seems like there was a fix, but hasn't been implemented.

**Comment by halatmit** [comment]
I don't think anyone else worked on this.  See what you can do.

**Comment by jisqyv** [comment]
This issue was fixed by #810 which is now in the master branch
