### ISSUE TITLE
SpeechRecognizer needs another event handler

### ISSUE THREAD

**Issue by jsheldonmit** [mit-cml/appinventor-sources#632]
A user pointed out that when no speech is detected, or when a user of an app inventor app taps the center of the speechrecognizer gui (on my 5.1 device) to end speech recognition without saying anything, App Inventor does not have an event to deal with the situation.

example aia for playing with it is at:
https://drive.google.com/file/d/0B56Z0pvSZgwqY3NwdnAzR0JGVFk/view?usp=sharing

**Comment by halatmit** [comment]
@jsheldonmit 
I tried fixing this, but I can't make it work.  There's supposed to be a timeout error, but I don't see it happening, at least not on my Marshmallow phone.  and I don't see any good suggestions on the Web.

**Comment by josmas** [comment]
Is this the [forum thread](https://groups.google.com/d/msg/mitappinventortest/5TpBqBVC8hE/OWQsXxEgEgAJ)?

The way of reproducing is by making the recognition fail (say, cough to the phone or similar). It will try to recognise it and when it fails, it shows that screen to try again (in 5.1 the widget is much nicer).

There is no point in having a simple function for that (it would not be a handler, but a *call* block to dismiss the widget). The user can either try again, use the cancel button, or click anywhere else in the window to make it go away.

I am closing this for now, feel free to reopen cc/ @jsheldonmit @halatmit
