### ISSUE TITLE
How to change the generated apk package names?

### ISSUE THREAD

**Issue by skylarmt** [mit-cml/appinventor-sources#651]
I'd like to modify the code so packaged apps have my domain for the package name ("com.example.etc"), instead of "appinventor_ai.partofemail.etc".  I'm a Java developer, but can't for the life of me find what I need to change in the sources.

**Comment by josmas** [comment]
You may be able to change it with an external tool like https://groups.google.com/forum/#!msg/mitappinventortest/hrVg1dDzELk/TYdcoT9DEAAJ

If you want to look into the sources, have a look at:
https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java#L315

Haven't checked what that code does exactly, but would be a good first thing to look at.

It's best to discuss this kind of request in the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev) though, so closing this issue for now.
