### ISSUE TITLE
help text for several components breaks the pop-up UI

### ISSUE THREAD

**Issue by jsheldonmit** [mit-cml/appinventor-sources#655]
For the Sharing, BlueToothClient, and BlueToothServer, clicking on the help question mark displays help text that breaks the UI, as per the attached images.

Problem was noticed on a test server for Brazilian Portuguese, but exists on public service, across languages.

Mac, Yosemite, Chrome latest release version (Version 47.0.2526.106 (64-bit))
![screen shot 2016-01-04 at 9 18 18 am](https://cloud.githubusercontent.com/assets/1889964/12091581/f1c03a54-b2c5-11e5-8ad2-d9ffcba2ee82.png)
![screen shot 2016-01-04 at 9 17 19 am](https://cloud.githubusercontent.com/assets/1889964/12091580/f1be8696-b2c5-11e5-9165-007300332461.png)

**Comment by ltphan** [comment]
Hi, 
I'd like to work on this issue. I am fairly new to open source, would anyone be able to guide me in the right direction for this? 
Thank you :)

**Comment by josmas** [comment]
Hi there @ltphan thanks for your interest. The way to get started is to review the [documentation](http://appinventor.mit.edu/appinventor-sources/#documentation). For this particular project, the document [the browser client](https://docs.google.com/document/d/1rOsvtd6ZjmRYqBdL9OWRhtwf735lJydDQjvkjCYVJ6E/pub) would be the most important one, after you get around to [run your own local server from sources](https://docs.google.com/document/pub?id=1Xc9yt02x3BRoq5m1PJHBr81OOv69rEBy8LVG_84j9jc).

**Comment by E-Hon** [comment]
the problem from the first image is reproducible in Chrome, Safari and Firefox but that from the second image is only reproducible in Chrome and Safari but not Firefox

**Comment by halatmit** [comment]
My recollection is a Chrome is more strict about HTML errors than FF, so maybe it's something there.

**Comment by avinasha39** [comment]
I think the width of the table should be inherited from ```<div class="ode-ComponentHelpPopup-TitleBar">BluetoothServer</div>``` .
Presently width is determined by the content of body content.
Can anyone guide me if I am going in right direction or is there any other point to be considered.

**Comment by E-Hon** [comment]
Hi @avinasha39, 
maybe you can try editing the css live in chrome to prove your claim? and then afterwards, you can edit appinventor-sources/appinventor/appengine/war/Ya.css

**Comment by wadleo** [comment]
I tested this on the browser as @E-Hon suggested to @avinasha39 proposal and it worked by just setting the width of the table to 100%. I will send a pull request later today to correct this issue.

**Comment by wadleo** [comment]
Here is the link to the pull request https://github.com/mit-cml/appinventor-sources/pull/723

**Comment by jisqyv** [comment]
Fixed by #727
