### ISSUE TITLE
What are the size limits on Download Blocks as Image?

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#657]
See
https://groups.google.com/forum/#!topic/mitappinventortest/JdpynrSaXRA

**Comment by josmas** [comment]
I have tried exporting all screens (the ones with most blocks) in the aia provided and it worked fast and without an issue. Have replied to the thread; this may be a RAM or other resources kind of issue for that particular user.

**Comment by josmas** [comment]
No reply (forum) in 24 days, so I am going to close this one for now. Feel free to reopen.
