### ISSUE TITLE
Problem with Welcome popup and Start New Project button

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#661]
When a new user sees the Welcome window upon login, the UI buttons don't work unless the window is first dismissed by clicking off of it.

Clicking the buttons themselves (such as the Start New Project button) visually dismiss the Welcome window, but do not enable the buttons, creating a state inconsistent with what is seen.

The buttons only work when the user first clicks somewhere that's not on them. 

Here is a video exercising the bug: https://youtu.be/CilJbxq2Nss

**Comment by ajcolter** [comment]
PR here: https://github.com/mit-cml/appinventor-sources/pull/673

**Comment by marksherman** [comment]
I tested and can confirm bug is fixed.

**Comment by jisqyv** [comment]
Fixed in the master branch
