### ISSUE TITLE
Change NotificationComponent to NotificationControl

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#662]
In the services branch, change the name of the NotificationComponent component to NotificationControl

**Comment by josmas** [comment]
@halatmit is 'services' the same as the Tasks work Vedha started? Is that branch in this repo (don't see it). In any case, it would be good to set a label for work on that branch.

**Comment by halatmit** [comment]
Yes, this is the same.   Andrew is working on it and I'm just today doing a
first doc for use in my class.

See

https://docs.google.com/document/d/1B9sglxkEoV-Cxsp-aQWjHfI4QJ8fryxlcrl2fNcqbHI/edit#


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
Closing as we no longer support background tasks.
