### ISSUE TITLE
Fusion Tables DoQuery does not work, but SendQuery does.

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#670]
Also, the default query that comes with the component, `show tables` doesn't appear to work, so users need something like `GetRowsWithConditions` which does.

@halatmit @afmckinney @jisqyv

**Comment by josmas** [comment]
Isn't doquery deprecated? Should have been for a while; the api changed quite a while ago.

**Comment by marksherman** [comment]
You're right! doQuery is already gone. Guess that was an easy issue.

Mark Sherman
UMass Lowell Computer Science
Engaging Computing Group
msherman@cs.uml.edu
http://www.cs.uml.edu/~msherman/

**Comment by afmckinney** [comment]
Yup it's been deprecated. Thanks Jose.
