### ISSUE TITLE
FusionTables expects a PKCS12 keystore - google no longer provides them

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#675]
The client secret, needed to use a fusion tables service account, is now downloadable as a JSON file. There is no longer an option to download a .p12 file, which is what the FusionTablesControl component requires. 

If the JSON file is attached, queries return the error **"stream does not represent a PKCS12 key store"**

That means App Inventor **can't be set up to use a new service account.**

Here is the new JSON format (whitespace and client_id redaction by me)
```json
{
  "installed":
  {
    "client_id":"000000000000000000000",
    "project_id":"grounded-style-118918",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs"
    }
  }
```

@halatmit @jsheldonmit @jisqyv @afmckinney

**Comment by halatmit** [comment]
@afmckinney @jisqyv @jsheldonmit @marksherman 
Can someone volunteer to fix this?  We need to get fusion tables working.
Thanks.

**Comment by jisqyv** [comment]
@halatmit @jsheldonmit @marksherman @afmckinney I'll take a look over the weekend.

-Jeff

**Comment by jisqyv** [comment]
@marksherman I just created a service account and a p12 file was still an option...

That said, the p12 option is called "legacy" and the JSON path is preferred. So I will look into using a JSON key. NOTE: We will have to support both for a period of time, otherwise we will break existing projects that have and use p12 keys.

**Comment by halatmit** [comment]
thanks


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by marksherman** [comment]
Tell me how to get the p12 and I'll put it in the instructions.

The json is pretty easy. That's how google seems to EOL things, making it
hard to find.

I think it should be possible to have the component take both files. It
wouldn't even be a property or block change, so no breakage. The field just
says "key".

**Comment by jisqyv** [comment]
@marksherman Did you go to the page to create a service credential? When I did, it gave me two radio buttons to choose from:

![createcrentials](https://cloud.githubusercontent.com/assets/1596728/12367521/a135a4b8-bbb0-11e5-9cdc-87bdf72165fb.png)

**Comment by jisqyv** [comment]
@marksherman Btw. I believe I can do the change and still be backward compatible, but it will be ugly. The hard part is I likely will have to upgrade the version of the oauth2 library we are using AND all of its dependencies which may break other parts of App Inventor which will require fixing.

**Comment by marksherman** [comment]
Wow, that's hidden. If you click on the service account itself, you get this:
<img width="924" alt="screen shot 2016-01-15 at 6 10 38 pm" src="https://cloud.githubusercontent.com/assets/2035149/12367828/814f976e-bbb3-11e5-98d7-4e708a4f29e9.png">
With no indication that there's another way to get it. 

The secret is to not click on the service account, or click any of the TWO downloadJSON buttons on that page, but to go back up to "New Credentials" and select "service account key". 

So no need for an immediate change, I'll highlight that path in the instructions.

And still, I doubt most fourth grade teachers will be able to get it on the first, unaided try.

**Comment by halatmit** [comment]
While you're editi the Docs, should we simply tell people to use Service
Authorization and not worry about the other Authorization -- or at least
describe things so that Service is the nornal way and describe the other a
an option (after we get it to work)?


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by marksherman** [comment]
That's actually my plan- not even mention the half-good solution

**Comment by halatmit** [comment]
+1



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by marksherman** [comment]
The P12 is still available. Instructions have been updated to reflect how to get it.
