### ISSUE TITLE
update the Android library

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#678]
Update to API 23 (Marshmallow)

from JIS
It's just work. You put the new library in place (correctly) and deal with the breakage... Its about as much work to assess the amount of work needed as it is to just do the work. In general each thing that breaks doesn't take much effort to fix. You just have to grind through it. Same as with the GCS update I need to do.

**Comment by josmas** [comment]
This is now in the ucr branch. Closing.
