### ISSUE TITLE
Support access to the manifest file for AI Extensions

### ISSUE THREAD

**Issue by josmas** [mit-cml/appinventor-sources#679]
Extensions can already define UserLibraries and Permissions, but there's no way to create extensions that need other type of access to the manifest through Compiler.java

A first iteration of this could be to move the BroadcastReceiver code used in Texting.java to the component (with an annotation) instead of adding it directly in Compiler.java. After that, more support for things like Services, minSDK or finer grain permissions should be added.

**Comment by josmas** [comment]
https://github.com/mit-cml/appinventor-sources/pull/703 is the first pass at this.

I'll add Services next (whenever I can find the time!).

**Comment by ShreyashSaitwal** [comment]
Hi @josmas,
Do you have any plans regarding adding an annotation for using Service? Thanks.

**Comment by josmas** [comment]
Hi @ShreyashSaitwal no plans at the moment.

@ewpatton is this worth adding, in your opinion? I don't currently have a use case for it, but can look into it at some stage.

**Comment by ShreyashSaitwal** [comment]
@josmas 
There's definitely no use case for this in the core system, but it could be very useful for extensions. I was working on an extension which needs to add some service tags in manifest, but since it's not currently possible, I'm unable to proceed further.
I'd greatly appreciate it if you could work on it.
Thanks.

**Comment by josmas** [comment]
@ShreyashSaitwal this could be used in core too, what I mean is that I personally do not have an use case for it at the moment, unlike when I worked on broadcast receivers.

I don't see how you can be unable to proceed though, you have the sources, you can follow https://github.com/mit-cml/appinventor-sources/pull/703 and I'm sure people here can provide feedback and suggestions, so why don't give it a go? Contributions are always welcome.

**Comment by ShreyashSaitwal** [comment]
At first, I was going to try it myself, but saw this issue and hence, pinged you. 
Anyways, I'll give it a try now and reach out to you here if I faced any issues.
Thanks.

**Comment by ShreyashSaitwal** [comment]
Hi @josmas,
I just recently created #2217 which adds annotations for Services as well as Content Providers. Will you please review it?
Thanks.

**Comment by josmas** [comment]
Hey @ShreyashSaitwal thanks a million for working on this; I see it's just merged. Congrats and thanks for the contribution!

**Comment by ewpatton** [comment]
@josmas I'm going to close this for now as @ShreyashSaitwal's work has filled out most of the missing links. I think now we're just down to application-level metadata as a missing feature, which I don't think is that common.
