### ISSUE TITLE
"Welcome" popup should not trigger viewing a gallery link

### ISSUE THREAD

**Issue by marksherman** [mit-cml/appinventor-sources#682]
If you open a gallery link to a project, and you don't have any projects, the Welcome popup still pops up, blocking the gallery app.

It is easy to dismiss but visually confusing. It's also a complication in path-to-setup for a research experiment, which I need to make as uncomplicated as possible.

Thanks to the Gallery, the assumption that the first page is always "My Projects" is no longer true. The semantics of the Welcome should check if the page is a gallery project, OR ensure that it is actually looking at the "My Projects" page. Something like that.

<img width="1089" alt="screen shot 2016-01-23 at 8 52 13 am" src="https://cloud.githubusercontent.com/assets/2035149/12530523/7dd80c5e-c1af-11e5-83ea-1358b2e24576.png">

@ajcolter @afmckinney @jisqyv

**Comment by ajcolter** [comment]
Hi Mark,
I'm trying to recreate this. I deleted all of my projects. I saw the Welcome pop up. I then went to the gallery, and clicked a random app. Clicked Open the App, it asked me to give it a name, and it pulled it up. Where am I going wrong?

**Comment by marksherman** [comment]
Find an app in the gallery, copy its "share" link, which should have
gallery in the URL.

Delete all your projects, log out, then hit the project's share link.

I think that will do it.

**Comment by ajcolter** [comment]
Yep, that did it. Will investigate.

**Comment by ajcolter** [comment]
https://github.com/mit-cml/appinventor-sources/pull/686

Haven't tested it yet, though. :-o
