### ISSUE TITLE
Update design of generated apps

### ISSUE THREAD

**Issue by ThatDuk** [mit-cml/appinventor-sources#696]
We're on Android 6.0.1 now, but generated apps still use design from 2.x era. Apps made with AppInventor therefore look ugly by today's standards. Apps should follow Material or at least Holo design standards by now.

**Comment by halatmit** [comment]
@ThatDuk 
Do you want to work on this, or at least have a proposal for how this should be presented to App Inventor users?    If not, you might want to raise this in the open source forum.

**Comment by josmas** [comment]
@ThatDuk If you are running your own server, you can change [the manifest](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java#L324) to whatever minSDK you want, and also make changes for the theme you want.

**Comment by ThatDuk** [comment]
@halatmit I don't have the skill to work on something like this. I'll submit it to the open source forum. Thanks!

@josmas I'll look in to it.

**Comment by ewpatton** [comment]
This was addressed in 6e23c47. It is currently on ai2-test and will be part of the next components release.
