### ISSUE TITLE
Increase the 5MB limit to 10MB for building apps

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#700]

**Comment by E-Hon** [comment]
Hi @jisqyv, I found the place to change the limit. Can I take this issue? Is there any hidden concern that I might have missed?

**Comment by halatmit** [comment]
It's more complex that just changing the limit in the code.

We put in the limit explicitly.   There is a time limit on connections from
the AppEngine data store.  When that is exceeded, the connection is
closed.    Before we put in that limit there were many more mysterious (to
the users) failures.

It's possible we could expand that to 10 MB, but we should not do this
without a lot of testing.  Part of the timing depends on the speed of the
school's network connection, so testing will be tricky.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by E-Hon** [comment]
Thanks for pointing it out. Anyway, I will be ready to help

**Comment by ewpatton** [comment]
As far as I am aware, we are no longer enforcing a 5 MB limit on projects. There is still a hard 10 MB limit imposed by Google App Engine. Closing this issue.
