### ISSUE TITLE
Backpack state (empty or full of blocks) does not track properly across screen switches

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#712]
... But if you go to another screen, it does not show that items are in the backpack (saved in the previous screen)

**Comment by josmas** [comment]
@jisqyv this is a duplicate of https://github.com/mit-cml/appinventor-sources/issues/630 which one you want to close?

**Comment by jisqyv** [comment]
@josmas Sorry I missed #630. I'm closing this one.
