### ISSUE TITLE
font is listview too small with responsive sizing

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#713]
this might apply to compoents other than ListVew:   The list of elements is too small with responsive sizing -- check for both phones and tablets.

Here's an issue of someone reporting it, but also finding a clever way to patch around it using Javascript.   The real fix (in Java) presimably would not do this, but you can see how he's setting the scaling.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mitappinventortest/_b6jmQGNugI/zBOZzuA_BAAJ

**Comment by InsectiousApp** [comment]
@halatmit Hello , I'am Mahima and I want to contribute in Component Projects( Improvements in Listview) . Can you please suggest how I start working on it ? from where I get the source code ?

**Comment by ewpatton** [comment]
Closed by cac9f88ce
