### ISSUE TITLE
Add "/" To the End of a Firebase URL

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#718]
If a provided Firebase URL is lacking a trailing slash, add one.

**Comment by E-Hon** [comment]
hi @jisqyv 
i created a pr for this and this bitesize issue is bitten :D

**Comment by E-Hon** [comment]
one thing to ask though. why is a trailing slash necessary?

**Comment by jisqyv** [comment]
@E-Hon I don't know why it is needed. It is a requirement of the firebase provided client library.

**Comment by jisqyv** [comment]
Fix merged.
