### ISSUE TITLE
check and fix the installation instructions for using Genymotion 

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#728]
See this comment on the user forum:

https://groups.google.com/forum/#!topic/mitappinventortest/YNBT4C8FjlM

**Comment by SpEcHiDe** [comment]
To fix the issue, need to edit this file https://docs.google.com/document/d/1Hg5z5uAesOftdu3vbk69yTtzJrZVxCYi6DQIs1AnCTs/pub
@halatmit

**Comment by halatmit** [comment]
fixed
