### ISSUE TITLE
Link in the sources page redirects to nothing

### ISSUE THREAD

**Issue by C-O-P** [mit-cml/appinventor-sources#732]
http://appinventor.mit.edu/appinventor-sources/appinventoris 
This link in https://github.com/mit-cml/appinventor-sources redirects to nothing.

**Comment by josmas** [comment]
The first link is incorrect. Where did you see that?

--------------------------------------------
mobile. brevity.typos.cheers

**Comment by C-O-P** [comment]
https://github.com/mit-cml/appinventor-sources
This the place where it is mentioned.

**Comment by halatmit** [comment]
Please provide that actual line on the page that contains the bad link.  thanks

**Comment by C-O-P** [comment]
Please open the link provided.You will see the bad link in the github page description.

**Comment by halatmit** [comment]
I'm sorry ,  I don't see it.  I know that the link itself is bad.  What  don't know is where that link appears on the page.   What is the line of test on the page that contains the bad link?

**Comment by C-O-P** [comment]
http://ctrlv.in/726627 ---> It is a screenshot.Hope this helps.
Regards

**Comment by halatmit** [comment]
I appreciate you helping, but that screenshot does not show a bad link.  could you circle the  specific thing l are clicking on that gives the bad behavior?

**Comment by josmas** [comment]
It was the link to the Docs site at the top. It is fixed now. Thanks for
reporting it.


cheers,
José

**Comment by C-O-P** [comment]
My pleasure.
Regards,
krishna
