### ISSUE TITLE
Unable to find the webapp directory appengine/build/war

### ISSUE THREAD

**Issue by bmanu199** [mit-cml/appinventor-sources#739]
your-appengine-SDK-folder/bin/dev_appserver.sh
        --port=8888 --address=0.0.0.0 appengine/build/war/

but there is no appengine/build/war/ directory inside bin or in the appengine-java-sdk-1.9 folder

**Comment by josmas** [comment]
The war folder is inside the app inventor sources folder after you compile.

--------------------------------------------
mobile. brevity.typos.cheers

**Comment by bmanu199** [comment]
I've just copied the my-app engine-SDK-folder to home and then tried running the server.


so, before I go running the main server, I need to compile the my-app engine-SDK-folder only then war folder will be created? 


So now my question is, how to compile the app-engine-SDK folder.

**Comment by bmanu199** [comment]
should I need to follow these instructions and install app_engine_for java before proceeding to run the server?
Becuase it was said on the main page that you and need the copy of app engine-SDK-folder for JAVA.
[https://cloud.google.com/appengine/downloads](url) 

PS: I am using a macintosh.

**Comment by halatmit** [comment]
This is a reminder that the instructions for building App Inventor are here:

How to build App Inventor from the MIT sources
<https://docs.google.com/document/d/1Xc9yt02x3BRoq5m1PJHBr81OOv69rEBy8LVG_84j9jc/edit>


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by abhijit5893** [comment]
@bmanu199  appengine/build/war/ is a relative url. So from your command line, If you go inside appinventor-sources /appinventor and execute the command. it works perfectly that way. Please try and let me know if that works fine.

**Comment by E-Hon** [comment]
Hi @bmanu199, do you need further help? If you have resolved the problem, would you kindly close this issue? Thanks

If you have other questions, you may raise them in [App Inventor Open Source Development](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev) group which is a more general place for asking questions.

**Comment by josmas** [comment]
closing this issue for now. If any help is further needed, please follow advice from @E-Hon in previous comment. Thanks!
