### ISSUE TITLE
Simplify FusionTable GetRowsWithCondition

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#749]
From Taifun:

Beginners frequently get confused using the fusiontable controls component and its blocks, see also this thread. People for example use the GetRowsWithCondition block and additionally add the SendQuery block. It is confusing... My suggestion therefore is to remove the Query property (or set it to deprecated) and add an input parameter "query" to the SendQuery method. 

See also this thread:

https://groups.google.com/forum/#!topic/mitappinventortest/fe1Gh5cO1OI

**Comment by puravidaapps** [comment]
To avoid misunderstandings: this is about the **SendQuery** method and the **Query** property.

As you can see here https://groups.google.com/forum/#!topic/mitappinventortest/fe1Gh5cO1OI or here  https://groups.google.com/d/msg/mitappinventortest/vomRQaWegpQ/5L4fgS30DQAJ sometimes people think, after using the GetRowsWithConditions or GetRows method **they have to additionally use the SendQuery method**, which results in errors.

![fu](https://cloud.githubusercontent.com/assets/2848474/16098871/791e01a8-3312-11e6-9bac-9f41d1a688df.JPG)

Therefore the suggestion is to modify the **SendQuery** method to add additionally the **query**  as parameter and remove the Query property completely (or set it to deprecated). My assumption is, after the modification of the SendQuery block, users will easier understand _to not use that method additionally_ after using GetRowsWithConditions or GetRows...

**Comment by ewpatton** [comment]
Closing because FusiontablesControl is no longer supported.
