### ISSUE TITLE
Fonts can be set to a floating point size, but then cannot be read

### ISSUE THREAD

**Issue by jisqyv** [mit-cml/appinventor-sources#753]
We should either prohibit people from setting a font size to a floating point number, or we should parse floating point numbers when we read in a project!

**Comment by jisqyv** [comment]
This issue may be limited to checkboxes. Also: If you attempt to set the font size to a floating point number, you will immediately see an error. Unfortunately when you see the error, the project has been written out and will now generate an error each time it is loaded (which is fatal). I do not believe the recent change to checkbox resizing caused this bug, but may have caused it to manifest itself.

Note that the default font size is 14.0, a floating point number. However this doesn't cause a problem because default values are not written to the .scm file and therefore are not parsed later (where the project load error happens).

**Comment by jisqyv** [comment]
OK. So this *was* broken by the checkbox font size change. The problem is that when you set the font of a checkbox to a floating point number, it now also sets the height of the checkbox to match. However font sizes are floats, but heights are integers... and *that* is the problem. Of course the code looks fine because in the Mock everything is passed as a String. But it isn't...

**Comment by E-Hon** [comment]
Hi @jisqyv, 

I was trying to reproduce what you had written above but failed. Then I looked up the history and found your [commit](https://github.com/mit-cml/appinventor-sources/commit/ee9d31420afe0e9b41729e576196e305bde05704). I suppose you fixed it already, right?

**Comment by jisqyv** [comment]
@E-Hon Actually this issue is fixed, so I'm going to close it. Btw. The commit you referenced was the wrong fix. I fixed it in: https://github.com/mit-cml/appinventor-sources/commit/2bad2c59b2c4dd397daabda8d5be3bf9813e0e9e

-Jeff
