### ISSUE TITLE
Wrong URL doc string for media components (and others?)

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#761]
When you click "more information" in a component description in the designer palette, the link shown for media components is /reference/components/index.html rather than to /reference/compoents/media.html#<the component name>

This is resulting from componentHelpWidget.java at line 68 where getReferenceComponentsUrl is returning the wrong thing.

**Comment by E-Hon** [comment]
Hi @halatmit, I just created a pr for this issue. 

The hint above is a very helpful starting point. I fixed this soon after I read it.

**Comment by E-Hon** [comment]
Hi @jisqyv , shall we close this issue? or is there any follow-up action needed to be done?

**Comment by jisqyv** [comment]
Yep, I forgot to close it....
