### ISSUE TITLE
fusion tables API v1 is deprecated. We need to support  v2

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#765]
"Sreeram Balakrishnan" sreevb@google.com

When we previously tried to enforce request safety in v1, the App inventor folks were affected and we decided to roll back and put request safety in v2. Since we are now deprecating
v1 they will have 6 months to make the change if they want to continue to use Fusion Tables.

Sree

On Tue, May 3, 2016 at 6:56 AM, Karen Jacqmin-Adams kadams@google.com wrote:

```
Did you get a chance to send them the API v1 deprecation announcement?

goo.gl/FK0aF5

-- Karen
```

**Comment by jisqyv** [comment]
@halatmit This was fixed (don't have the commit reference handy, but it is fixed).
