### ISSUE TITLE
Add working example of file app.yaml

### ISSUE THREAD

**Issue by luckcolors** [mit-cml/appinventor-sources#786]
This file is required in order to run the app.
Should be here. appinventor/appengine/war

**Comment by josmas** [comment]
hi @luckcolors can you provide a bit of context for this? never seen that file before.

**Comment by luckcolors** [comment]
Ah sorry. It's the one required for Google appengine in order to deploy the app either locally or remotely. It says it's missing when i try to run the app using the command on the readme.md .
Google has probably changed the tool a bit because --address has been removed(probably changed to --host), anyway here's the doku link: https://cloud.google.com/appengine/docs/python/config/appref#example

**Comment by josmas** [comment]
Please note that App Inventor runs on the Java version of appengine, not on the Python version. There's no need for _yaml_ config files in App Inventor.

I am closing this now.

**Comment by luckcolors** [comment]
@Josmas Ah thanks i probably overlocked the download page for the sdk. Sorry for wasting you time.
