### ISSUE TITLE
Fill_parent in vertical arrangement gives wrong result

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#789]
Create an app that has a vertical arrangement whose hight it 50% of the screen.   Place a label inside the vertical arrangement and set its height to fill_parent.   In the designer, the label will correctly fill the arrangment.  But on the phone the label height will not change.   The two images show the correct behavior in the emulator and the incorrect behavior on the phone.
![screen shot 2016-05-29 at 8 50 39 pm](https://cloud.githubusercontent.com/assets/789431/15637163/86bc560a-25e0-11e6-883b-55b835aa6e08.png)
![screenshot_2016-05-29-20-50-05](https://cloud.githubusercontent.com/assets/789431/15637176/c9cb7a98-25e0-11e6-84fa-5dee687d9418.png)

**Comment by chenglonkhin** [comment]
I think this issue might have already been fixed. I tried it on my phone (Nexus 6P) on both the AI companion and the standalone APK. 


![image](https://cloud.githubusercontent.com/assets/18460893/16742186/90f0e194-4774-11e6-9215-2a8b736f74a9.png)

![image](https://cloud.githubusercontent.com/assets/18460893/16742160/79be7040-4774-11e6-8551-d90e1dcd88c3.png)

**Comment by halatmit** [comment]
seems to have been fixed

**Comment by halatmit** [comment]
thanks Lokhin.   I closed the issue.



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
