### ISSUE TITLE
setting slider ThumbPosition in its own PositionChanged handler crashes the Companion

### ISSUE THREAD

**Issue by fgmart** [mit-cml/appinventor-sources#796]
I am trying to make a slider that reports only integer values. I did this:

![screenshot 2016-06-02 at 6 20 55 pm](https://cloud.githubusercontent.com/assets/1038856/15763150/cebb322a-28ef-11e6-9573-4b916ece6cfd.png)

It crashes the Companion when you try to move the thumb. (Error message: MIT AI2 Companion isn't responding. Do you want to close it?)

I tried setting the ThumbPosition to a fixed, in-range value inside the handler and it also locked the Companion.

Setting the ThumbPosition from another handler does work properly; e.g. this:

![screenshot 2016-06-02 at 6 31 23 pm](https://cloud.githubusercontent.com/assets/1038856/15763199/46931de4-28f0-11e6-8ee5-77bfa61951bc.png)

Tested with AI nb148b, Companion 2.36.

**Comment by puravidaapps** [comment]
you created an endless loop: setting the thumb position - position changed event fires - setting the thumb position - position changed event fires etc.

**Comment by halatmit** [comment]
Taifun .. Thanks :)

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by kkashi01** [comment]
@fgmart  Use a global variable for rounding. This way, you won't manipulate the ThumbPosition

**Comment by fgmart** [comment]
OK I feel pretty dumb now 👍
