### ISSUE TITLE
Add multiple inputs to AND and OR

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#797]
Add mutators to these blocks, to permit multiple inputs.  Use the +  block as a model for how to add the mutator.  There are some things in the code that might be hard to understand.  Make sure to ask.

**Comment by candicefan** [comment]
Hi Hal, I finished this, but I made AND and OR separate blocks, without having the dropdown. Is this ok, or it's better to keep the dropdown select for AND and OR.

**Comment by halatmit** [comment]
It would be OK to make them separate blocks without the dropdowns.

Test this more when you are ready and then submit a pull request.





== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
Fixed by #2184
