### ISSUE TITLE
Calling activity starter with no info gives a permissions error

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#800]
If you call the activity starter and do not provide and information it looks like the intent resolution mechanism picks an activity to launch that leads to a permissions error.

See
https://groups.google.com/forum/#!topic/mitappinventortest/-e4mNygdEoQ

José suggests:

When using Implicit intents[1], the system figures out what you are trying to do from the information provided. 'No information' seems to point to that particular one, as Hal mentioned, no idea why, but the 'FIX' here may be validating the data before running the intent, instead of catching an error. In the method 'buildActivityIntent', redirect to a Form.dispatchErrorOccurred if there's no info about the action.

**Comment by halatmit** [comment]
See also the original forum thread

https://groups.google.com/forum/#!topic/mitappinventortest/tq0IysLiIs4

**Comment by jisqyv** [comment]
#816 is merged
