### ISSUE TITLE
Fix minor type error in FusionTablesControl.java

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#820]
Eclipse complains about a type error for "scope" on line 863.

The project compiles nevertheless, but it would be good to fix this.

**Comment by halatmit** [comment]
This turns out to be complicated.   From Evan and Jef:

>
> Actually I don't believe it is trivial. I suspect you are getting the error from Eclipse because Eclipse is finding a newer version of the Google Client APIs then we are actually using. The newer versions expect the argument to setServiceAccountScopes to accept a Collection<String>. However the version we are using is defined to accept "String...", which means a variable number of arguments, each a String scope.

Yes. I’ve been looking at this and agree with Jeff’s hypothesis. The google-api-client jar in libs/oauth provides a version of the method that accepts an arbitrary number of strings but the version used for Google Cloud Services and AppEngine uses Collection<String>. The code compiles because the Ant build task uses the correct library whereas Eclipse is preferring the GCS version to the one packaged into components. You can change the ordering of the jars in Eclipse, but likely you’ll just end up with an error in the AppEngine code for the same reason.

>
> Perhaps we should upgrade the version of the api jar we are using, though this may not be trivial because of the dependencies on other jars that may tickle. I would expect we would wind up having to upgrade a bunch of jars and then we would have to extensively test the resulting system, particularly on older devices which may not be compatible with the newer versions of the Google api jars.

The only two components that directly reference the OAuth Google Client lib in @UsesLibrary appear to be the FusionTableControls and Texting. Only FusionTableControls directly instantiates anything in the com.google.api.client package. Since the dependencies between jars within a @UsesLibrary are not obvious, I guess it is possible that one of the other API jars is relying on it in some way. I need to generate a dependency graph to confirm. If there isn’t really a dependency path for the Texting component, making the change FusionTableControls should be straightforward and only require a few line changes + the update to the newer library version. If there is some hairy dependency that Texting requires, then it becomes more complicated to update because of potential binary incompatibilities within the associated Google libraries

**Comment by jisqyv** [comment]
@halatmit I'm closing this issue as it isn't an issue. The real issue is should we upgrade the jars we are using.
