### ISSUE TITLE
ActivityStarter gives error "java.lang.String.isEmpty"

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#827]
Seen by users on the forums, e.g. [here](https://groups.google.com/forum/#!msg/mitappinventortest/DLzN8cFkuX0/OuWPqsS3AQAJ) and [here](https://groups.google.com/forum/#!category-topic/mitappinventortest/lRpJCkxkR5w).

Create an app with a button, an activity starter, and a notifier. Have the button trigger a StartActivity event, and then have ActivityError show the message. In the emulator it will show java.lang.String.isEmpty. This will also occur on older Android deployments because isEmpty was introduced in JDK 1.6 whereas older versions of Android are compatible with JDK 1.5 only.

Proposed fix: Locate any calls to the `.isEmpty()` method in `components/` and replace them with `.length() == 0` check instead for backwards compatibility.

**Comment by jisqyv** [comment]
Fixed (in ucr pending release)
