### ISSUE TITLE
Deal with text boxes that have a lot on content

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#841]
Idea fromAbrham:   Maybe not his solution, but we should do something.

An idea regarding my Declaration of Independence in a Text Box Blocks Editor Freeze ...

Users with big text will probably continue to abuse copy and paste into text boxes, until they are comfortable with file imports.  But the Blocks Editor should not have to suffer at the hands of these oversized text boxes, bloating the pixel address spaces with their long lengths and raising the compute load on block movement.

AI2 has other ways of limiting the display impact of long texts, for example the Designer Screen1 About box, with its stretchy corner handle, and the Blocks Editor Comment bubble, and the individual file name slots in the Media Drawer (embedded ... if too long) .

An investment in limiting the max displayable length of text boxes (but not their content length) should be considere

**Comment by ewpatton** [comment]
Blockly now truncates the text with an ellipsis if it reaches a certain number of characters so this is no longer an issue as of the Blockly update.
