### ISSUE TITLE
the type java.io.objectinputstream cannot be resolved. it is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by iTouhid** [mit-cml/appinventor-sources#851]
## **Two condition is there where this kind of error will show**

1> If there is multiple version of Jdk is loaded in your System.
Solution : Go to control panel>programs & Features: Delete the old version of java and jdk both. keep only latest version of java and jdk. check both java and jdk version is same. Restart your System.

2> The JRE system library is not set properly.
Solution : Go to project>Properties>java build path>libraries : Remove the "JRE System Library". then click on add library select JRE system library the hit next and select work-space default JRE and click on finish.

Then go to project option and click on clean. clean the selected project. it will re build the project.
May be your red alert of error will be eliminated. otherwise follow step 1.

**Comment by josmas** [comment]
Hi there @iTouhid 
thanks for the tip.
This kind of documentation would be easier to find in the [forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).

I will close the issue now, as there's nothing to fix _code-wise_. Thanks again for sharing the info with all!
