### ISSUE TITLE
Use GWT to alert about deletion

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#852]
When deleting a component or more than 3 blocks, we use the JavaScript prompt to confirm deletion. Chrome will also give an option to prevent further dialogs. If users select this option, then they will be prevented from deleting components/blocks until they reset their dialog settings [1,2]. We should replace this prompt with a GWT dialog that we control so that they can't inadvertently lock out certain UI behaviors.

[1] https://groups.google.com/d/msg/mitappinventortest/UwPcl7HnENA/h0rejrmyCQAJ
[2] https://groups.google.com/d/msg/mitappinventortest/ziDg657qxnI/SlMIQKKlCQAJ

**Comment by josmas** [comment]
Would it be possible/easier to create a little svg widget to show the warning? It would save trips back and forth gwt and js. Something similar to the tutorial bubbles that blockly uses.

**Comment by ewpatton** [comment]
It is possible, but then we would have a different look and feel in the blocks editor versus the rest of the App Inventor UI.

**Comment by josmas** [comment]
Yes, and no :)
If you think of the warning/error widget and the backpack, they are already in that category, right?

**Comment by ewpatton** [comment]
Yes, but there is no equivalent in the designer for those widgets so I don't take issue because there is no look-and-feel to compare them against. The designer does have dialogs, though, so there is an existing look-and-feel to work with. Since this dialog is modal, we also probably want to light box it, in which case we need to do it at the top level window outside of the Blockly frame. I would be more concerned about crossing the iframe boundaries than crossing the GWT/JS boundary.

**Comment by josmas** [comment]
fair enough! :)

**Comment by shivakrishna9** [comment]
@josmas  I will try to fix this. Any suggestions welcome. Also is it on priority?

**Comment by josmas** [comment]
@shivakrishna9 i am not the best person to provide info on this issue... as I have none myself! :)
