### ISSUE TITLE
Update extensions documentation

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#854]
Update

https://docs.google.com/document/d/1orlYWGlHOY0hmAC0zjadQ4DET2K8U34C8hv5zmuxZLU/edit#heading=h.q0qxs8avzosb

The version currently there is from the pre-release

**Comment by ewpatton** [comment]
@halatmit  I made an update to this document on June 9th to address changes to the extension mechanisms made as part of the IoT release. I also removed some of the references to earlier methods, such as checking out the CDK branch. Please make a pass and note any places where you think updates still need to be made.
