### ISSUE TITLE
Conditional Component Visibility

### ISSUE THREAD

**Issue by kkashi01** [mit-cml/appinventor-sources#855]
It appears that current infrastructure doesn't allow for having conditional component visibility. This could be useful when certain components would only be valid for main screen (Screen1). This could help in designing a component like ManifestEditor where it applies only to Screen1.

**Comment by mahikawason** [comment]
Could you please elaborate a bit more. I am not very clear on what you are trying to point out.

**Comment by kkashi01** [comment]
@mahikawason Let's say there is a component called ManifestEditor allowing user to specify application level properties. This component should only be visible for main screen (Screen1), but not for other screens.

**Comment by ewpatton** [comment]
I think for the proposed use case we'd really want to introduce a new UI feature for editing the manifest rather than making it a component.
