### ISSUE TITLE
Build Failed build.xml:21

### ISSUE THREAD

**Issue by emilrowland** [mit-cml/appinventor-sources#864]
System: Ubuntu 16.04 oracle-java7

BUILD FAILED
/home/emil/appinventor-sources/appinventor/build.xml:21: The following error occurred while executing this line:
/home/emil/appinventor-sources/appinventor/buildserver/build.xml:183: Java returned: 1

Some output before
     [java] INFO: ____Executing /tmp/aapt6819156134255930277 package -v -f -M /tmp/1484419595435_0.9910765923036917-0/youngandroidproject/../build/AndroidManifest.xml -S /tmp/1484419595435_0.9910765923036917-0/youngandroidproject/../build/res -A /tmp/1484419595435_0.9910765923036917-0/youngandroidproject/../assets -I /tmp/android5920224570100505622.jar -F /tmp/1484419595435_0.9910765923036917-0/youngandroidproject/../build/deploy/MIT AI2 Companion.ap_ /tmp/1484419595435_0.9910765923036917-0/youngandroidproject/../build/libs
     [java] Jan 14, 2017 7:47:18 PM com.google.appinventor.buildserver.Execution execute
     [java] WARNING: ____Execution failure: 
     [java] java.io.IOException: Cannot run program "/tmp/aapt6819156134255930277": error=2, No such file or directory
     [java] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
     [java] 	at java.lang.Runtime.exec(Runtime.java:617)
     [java] 	at com.google.appinventor.buildserver.Execution.execute(Execution.java:111)
     [java] 	at com.google.appinventor.buildserver.Compiler.runAaptPackage(Compiler.java:1220)
     [java] 	at com.google.appinventor.buildserver.Compiler.compile(Compiler.java:673)
     [java] 	at com.google.appinventor.buildserver.ProjectBuilder.build(ProjectBuilder.java:170)
     [java] 	at com.google.appinventor.buildserver.Main.main(Main.java:82)
     [java] Caused by: java.io.IOException: error=2, No such file or directory
     [java] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
     [java] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
     [java] 	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
     [java] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
     [java] 	... 6 more
     [java] 
     [java] Jan 14, 2017 7:47:18 PM com.google.appinventor.buildserver.Compiler runAaptPackage
     [java] WARNING: YAIL compiler - AAPT execution failed.

**Comment by ewpatton** [comment]
See [this section](https://docs.google.com/document/pub?id=1Xc9yt02x3BRoq5m1PJHBr81OOv69rEBy8LVG_84j9jc#h.qy8kbrxuoxen) of the detailed instructions on configuring your build system. You are likely missing the 32-bit dynamic libraries needed to run the aapt tool.

**Comment by josmas** [comment]
Closing this for now. If you are still having issues, please ask for help in the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev).
