### ISSUE TITLE
Consider using BluetoothSocket.isConnected on phone with API >= 14

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#868]
There is some confusion on the forum regarding the BluetoothClient.IsConnected method since it will only return false when the connection status is reset, which will only occur if one attempts to read/write the broken socket. For devices with an API level of 14 (ice cream sandwich) or higher, we can use the `isConnected()` method of BluetoothSocket to report a more accurate connection status without requiring developers to perform an operation on the socket.

**Comment by ewpatton** [comment]
@farxinu @cavedunissin Would one of you be interested in taking a look at this?

**Comment by farxinu** [comment]
Would this be a change to BluetoothConnectionBase then?
