### ISSUE TITLE
Handling notifier cancel in multiple languages

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#877]
PR #685 made the buttons for the notifier internationalized. Because the text of the button is returned in the AfterChoosing or AfterTextInput events, one gets the localized string. Using an app on phones in different languages will return different results, making it difficult for programmers to test for the cancel condition, e.g. [[1]](https://groups.google.com/forum/#!category-topic/mitappinventortest/DFftXIzEeqY). It might be worth having events such as "TextInputCanceled" or "ChoosingCanceled" that are more descriptive of the action taken by the user and won't run into the internationalization issue.

**Comment by ColinTree** [comment]
I'm working on this: 

- [ ] TextInputCanceled
- [ ] ChoosingCanceled

P.S. In order to backward compatible with the old apps, I think we should still keep dispatching the old events.

**Comment by jisqyv** [comment]
Fixed in https://github.com/mit-cml/appinventor-sources/commit/eda075ad90cd5da2cc0bf89c83a5e09845434e82
