### ISSUE TITLE
Looking for guide on how to install AppInventor 2 over AppScale environment

### ISSUE THREAD

**Issue by xuwenbin** [mit-cml/appinventor-sources#879]
Background - AI2 is based on GAE which is completely blocked in China. We want to use AppScale as an alternative to run AI2 server within China. There's a public AI2 instance in Guangzhou area, however, our network environment stops us from using external public AI2 server(s). As a result, we have to set up our own server in our network environment.

What we are looking for - A detailed guide on how to set up AI2 over AppScale instance(s). Or, any advice on that matter would also be highly appreciated. We're a bunch of poor guys who is almost desperate when facing great china firewall barrier. So, please help us!

**Comment by kirliavc** [comment]
I followed the instructions and successfully set up AI2 server in my own server in China. 
Actually, my server is within a local network and is completely blocked from outside network, and my AI2 server still worked. It attempted to connect Google, but as it failed, it started without other problems. Of course, signing in with Google account doesn't work properly.

**Comment by xuwenbin** [comment]
@kirliavc Can you share with me the instruction details? For sign-in issue with Google, I believe code-level changes must be made. I can put my hands on it only after my local AI2 server is up and running.

**Comment by kirliavc** [comment]
@xuwenbin I made no change on the code, and I just started the server with the official instructions. So where is your problem? I didn't do anything with AppScale. Probably I didn't get your point.

**Comment by xuwenbin** [comment]
@kirliavc so, you didn't use AppScale, but just installed AI2 and got it up and running?

**Comment by kirliavc** [comment]
@xuwenbin of course I downloaded a copy of App Engine SDK from google, but connection with Google isn't a essential step to start the server.

**Comment by xuwenbin** [comment]
@kirliavc we can switch to wechat for more instant chat. mine wechat no. is 2295450513

**Comment by josmas** [comment]
that's a great idea (to move this conversation somewhere else). Closing this issue now. Thanks!
