### ISSUE TITLE
LoginServlet.java -> sendmail() -> HttpUrlConnection doesn't send out http POST request on GAE dev server environment

### ISSUE THREAD

**Issue by xuwenbin** [mit-cml/appinventor-sources#880]
Environment
--------------
1. Ubuntu 14.04
2. GAE SDK 1.9.51
3. OpenJDK 7

Symptoms
-----------
1. In appengine-web.xml file

Disabled Google Auth
Altered localauth.mailserver to point to my own passmail implementation (_note: http only_)
Rebuilt AI2 successfully

2. Ran AI2 locally on GAE SDK dev server (Java)

3. Click set or recovery password link

4. Type in a valid email address

5. Click Send Link button

6. Web page doesn't refresh for a long time

7. After timeout, it says the link was sent, but actually my passmail server side never received POST request, and no email was sent out to designated email address

After debugging the code in LoginServlet.java, it hangs at connection.getResponseCode() inside sendmail function. However, I doubt the previous PrintStream object never sent out the POST request somehow.

**Comment by ewpatton** [comment]
I think this is a discussion better left for the [open source forum](https://groups.google.com/forum/#!forum/app-inventor-open-source-dev). We don't officially support running App Inventor in the dev server other than for testing purposes, so I'm going to close this issue.
