### ISSUE TITLE
MESSAGES.extensionComponentPallette() : ComponentsTranslation.java:3287: error: cannot find symbol

### ISSUE THREAD

**Issue by meera** [mit-cml/appinventor-sources#888]
I am trying out AltCamera example as documented in http://ai2.appinventor.mit.edu/reference/other/extensions.html

My active branch is cdk (as suggested elsewhere). 

When I run 
ant
I get following error message.

appinventor-sources/appinventor/build/components/ComponentTranslation/src/com/google/appinventor/client/ComponentsTranslation.java:3287: error: cannot find symbol
    [javac]     map.put("CATEGORY-Extension", MESSAGES.extensionComponentPallette());
    [javac]                                           ^
    [javac]   symbol:   method extensionComponentPallette()
    [javac]   location: variable MESSAGES of type OdeMessages
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error

**Comment by bennytheshap** [comment]
@meera I wrote to @ewpatton  about this earlier. What I learned is that you can now just use the master branch as your base. However, you still can't compile with a bare ``ant``, but can if you use ``ant extensions``.

**Comment by meera** [comment]
Thank you - 
I was able to compile it using 

ant extensions 
on main branch worked. 

Can some one please update the google document 

https://docs.google.com/document/d/1orlYWGlHOY0hmAC0zjadQ4DET2K8U34C8hv5zmuxZLU/edit

This will make it easier for newer coders trying to create extension for first time..

**Comment by ewpatton** [comment]
I'm going to add this to the messages file. While it doesn't need to be there for the production system, enough people are aware to do `ant` that it will continue to cause headaches.
