### ISSUE TITLE
Errors in generic component method blocks

### ISSUE THREAD

**Issue by kvmathison** [mit-cml/appinventor-sources#890]
Generic Clock.addDays (and similar) blocks turn into Clock.addnull when dragged into the workspace, and throw an error that says "This block is not defined. Delete this block!".

Additionally, several other generic blocks, including Canvas.DrawCircle and Clock.FormatDate, have a default-empty dropdown where the component type should be. These throw an error that says "Component does not exist" regardless of whether a component is selected from the dropdown.

**Comment by ewpatton** [comment]
Closed by #895
