### ISSUE TITLE
Game Client, Voting & Media Store components sources.

### ISSUE THREAD

**Issue by moliata** [mit-cml/appinventor-sources#906]
Hello MIT Team, where can I find Game Client, Voting & Media Store sources for App Engine? Like I can get TinyWebDB sources, I want to get those...
Thanks.

**Comment by moliata** [comment]
@ewpatton

**Comment by ewpatton** [comment]
I'm not sure which, if any, of these sources made their way from Google to MIT. @halatmit @jisqyv @afmckinney do you know whether we have these sources?

**Comment by halatmit** [comment]
The sources are all in the standard github repo with the sources of the
other components.

But the have not been built in years, and I'm sure there would be problems
trying to use them.



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by moliata** [comment]
Could you please tell where they are? Because I am asking for sources (that should be used in AppEngine), not components. For example, I cannot find TinyWebDb sources in github repo, I need to download them from http://appinventor.mit.edu/explore/content/custom-tinywebdb-service.html

**Comment by halatmit** [comment]
The appinventor sources are in the github repo:

https://github.com/mit-cml/appinventor-sources

The Java code sources for all the components are in

appinventor-sources/appinventor/components/src/com/google/appinventor/components/runtime/

But I think you might be looking instead for the code that implements the
TinyWebDB and GameClient Web services.

The code for TinyWebDB is in python, and you can download it as a zip file
from:

http://appinventor.mit.edu/explore/content/custom-tinywebdb-service.html

where is says


   - Download this sample code
   <http://appinventor.mit.edu/explore/sites/all/files/tinywebdb/customtinywebdb.zip>.
   It is a zip file containing the source code for your custom tinywebdb web
   service


I don't know where the code file for the GameClient Web service is.
There's a listing in Bill Magnuson's thesis


<goog_469169277>
http://dspace.mit.edu/handle/1721.1/61253

<http://dspace.mit.edu/handle/1721.1/61253>

<http://dspace.mit.edu/handle/1721.1/61253>











== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by moliata** [comment]
Hello @halatmit! Thank you for the answer & yes, I am talking about code that implements web services. By the way, are the sources for Voting & MediaStore component? Or gone just like GameClient?
Thank you.

**Comment by halatmit** [comment]
I don't think we ever had the code for the voting and mediastore services
at MIT.

The voting service was done by Ei Mustafaraj at Wellesley.  You could write
and ask her if she has the server code.

I think the mediastore work was done by Andrew McKinney here at MIT.   You
can ask him, but I don't know that this ever really worked.

Also, I found the GameServer code.  It's attached here.   Good luck -- this
must be very obsolete.
Note that the GameServer code has a module called Voting, but this is
different from what Eni created for the voting component.

Keep in mind that none of these services (except for TinyWeDB) were ever
distributed or supported.   So don't expect the server code to work:
 AppEngine has changed since these were built.

Good luck.



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by moliata** [comment]
Hello @halatmit, thank you for the info.
1) Could you give me contacts to both of those people?
2) Where could I find attachments? Cannot seem to find them.
3) Yes, I do know that they are obsolete, I'll try to rewrite code (because I think all these web services, are written in Python.)
Thank you.

**Comment by halatmit** [comment]
It looks like th email you got did not include the GameClient code
attachment.

Send me a real email address and I can try to send it again.

Eni Mustafaraj is at Wellesley, and Andrew McKinney is at MIT.   You an use
the Wellesley and MIT directories to search for them


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by moliata** [comment]
@afmckinney do you have sources for MediaStore web service?

**Comment by moliata** [comment]
I'll close this issue as it is no longer important.
