### ISSUE TITLE
Adding a namespace for TinyDB in the companion 

### ISSUE THREAD

**Issue by farxinu** [mit-cml/appinventor-sources#907]
It's possible to stomp on your own TinyDB data within the companion because all the TinyDB data is stored in the same place for the single companion app. While this isn't an issue with actual generated apks, for those testing with the companion, they may run into issues (that don't ultimately truly exist, but the users don't necessarily know that).

**Comment by ewpatton** [comment]
Another suggestion today about allowing a prefix on TinyDB so that one can use multiple TinyDBs to organize data: https://groups.google.com/d/msg/mitappinventortest/lx7if7CL0FM/4WwVqzzrBwAJ

**Comment by ColinTree** [comment]
i got a extensions for myself as a solution, it is here:
https://github.com/OpenSourceAIX/TinyDBEditable

**Comment by ColinTree** [comment]
This can be closed via #1111
