### ISSUE TITLE
Add remove block from backpack menu option

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#911]
To improve backpack management, we should add a "Remove from Backpack" menu item if one right-clicks on a block in the Backpack. Right now one can only clear the whole backpack.

**Comment by luvhalvorson** [comment]
Hi, may I help with this one? I'm sorta beginner tho, could I ask for hints if I can't figure it out? 😊

**Comment by Sivagss97** [comment]
oh sure...!!!

**Comment by ewpatton** [comment]
@luvhalvorson If you want to make an attempt, please do so and put in a pull request. You'll probably want to take a look at backpack.js, backpackFlyout.js, and block_svg.js in blocklyeditor/src/

**Comment by ewpatton** [comment]
@luvhalvorson Were you able to make any progress on this issue?
