### ISSUE TITLE
investigate accelerometer behavior under rotation

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#915]
Different device behave differently in reporting Xaccel and Yaccel when the device is rotated.  Make it easier to write programs that work across all devices and rotations, probably by using the Window Service RotationIndex.

**Comment by halatmit** [comment]
Look here for how to get started.

https://stackoverflow.com/questions/5877780/orientation-from-android-accelerometer

**Comment by halatmit** [comment]
This will be handled by PR #956 .

**Comment by jisqyv** [comment]
Fixed by https://github.com/mit-cml/appinventor-sources/commit/0f01fbe50f55a613f8cdf2425eefb47dbf100f5b
