### ISSUE TITLE
Proposal to change Android MinSDK version

### ISSUE THREAD

**Issue by ozodrukh** [mit-cml/appinventor-sources#917]
Hi guys,

Any thoughts on upgrading Android SDK from 1.5 -> 2.3 or 4.0, by looking on [Android distribution table](https://developer.android.com/about/dashboards/index.html), we can notice that there is only 0.7% devices running Android 2.3.3. 

Why do I come up with idea of upgrading minSdk is obviously for Material Design(esthetic) 😅

**Comment by ewpatton** [comment]
Please [see my blog post](http://appinventor.mit.edu/explore/blogs/evan/2017/08.html) earlier this month about this very issue.
