### ISSUE TITLE
Width/height update on orientation change

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#923]
To repeat:
1. Set the width or height of a component to a percent value
2. Set the width or height of the component to a fixed value
3. Rotate the screen

After the screen rotates, the form will apply the percent layout even though the width/height was changed to a fixed value. We need to unregister the component for a percent layout change if the width/height is set to a non-percent value.

Implement a method `unregisterPercentLength` to mirror `registerPercentLength` on `Form` so that we can remove the previously registered request for sizing.

**Comment by ZhengCornell** [comment]
I can take a look at this issue

**Comment by ewpatton** [comment]
@ZhengCornell I have assigned it to you. Do you have enough information to get started?

**Comment by ZhengCornell** [comment]
Not much, do you have more detailed information or documentation that I can read?

**Comment by ewpatton** [comment]
Not much in the way of documentation, but here's a general flow of what happens and where the bug occurs:

1. In AndroidViewComponent.java (components module), the `Width` and `Height` setters will make a call to `registerPercentLength` on `Form` if the width/height indicates a percent. This is used so that if the screen changes orientation, the width/height can be recomputed in response to the dimensions changing. You can make a simple app to see how this works.
2. If you programmatically change the width/height of a component that has been previously registered to a fixed value (e.g., 200 px) using blocks, the registration doesn't get cleared. This works fine until the screen is rotated, at which point the form will reapply the percent-based width/height constraint (see `Form.ReplayFormOrientation()`).

So there are a couple of things that may need to happen:

1. Replace `dimChanges` in `Form` with a `LinkedHashMap` mapping `Integer` to `PercentStorageRecord`. Keys will be the component hashCode() * 2 plus 0 for width and 1 for height.
2. Update registerPercentLength to add values to the hash map.
3. Update ReplayFormOrientation to iterate over the hash map's values() set.

At this point, you should be able to replicate the behavior above, but with the hash map instead of the array list implementation. Now the new part:

4. Add unregisterPercentLength that takes the component and the dimension, and have it remove the entry for the hash code using the same mapping above.
5. Update Width and Height to call unregisterPercentLength as an else branch to complement the if statement that registers for percent length. Bonus points if you optimize this by checking whether it actually needs to be called.

**Comment by ewpatton** [comment]
Fixed in 3abb556f0308ce241e3a4c2ba1bdc69ba4ab32b9
