### ISSUE TITLE
the hint of methods, events or properties are not translated

### ISSUE THREAD

**Issue by ColinTree** [mit-cml/appinventor-sources#925]
as shown here, Screen1.initialize event in chinese but get a  English hint.
actually not only this event, every method & event & property get the same issue
![_20170909132204](https://user-images.githubusercontent.com/22613139/30237458-f3917018-9564-11e7-8302-2d1cda6b9259.png)

i did not find the translation in source code that included the translated hint, did i miss something or it just doesn't exist yet...

**Comment by moliata** [comment]
Yes, this is happening because hints (aka block descriptions are set together with annotation like this: @SimpleEvent(descripition = "Example"), descriptions are not set within OdeMessages.java, that's why this is happening. If you would have to set description for every single block, it will take so much useless time. For adding a description in OdeMessages for every single block.

**Comment by ColinTree** [comment]
BTW,  what is the solution of translation for extensions?

**Comment by moliata** [comment]
@ColinTree, that is not possible. For components, You just have to modify OdeMessages.java, that is not possible with extensions. Still, that would be a lot of pain to do.

**Comment by ColinTree** [comment]
emm, ok. 
i m trying to do some improvement for some components now. after that i will try to do this. 
what the solution should be like ..? add translation in json file? but i think developers can not do the translate for such a lot language at the same time.

**Comment by moliata** [comment]
Hello, there is OdeMessages.country.LANGUAGE.properties files in appengine/src/.../client directory

**Comment by ColinTree** [comment]
i mean, for the extensions..

**Comment by moliata** [comment]
@ColinTree you said components.. Actually that is not possible at all for now.

**Comment by ColinTree** [comment]
yep, i see. thank you
