### ISSUE TITLE
Update reference materials with new logo

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#932]
The reference documentation uses the old MIT App Inventor logo. It should be updated with the new logo to match the rest of the App Inventor website materials.

**Comment by ewpatton** [comment]
For example: http://ai2.appinventor.mit.edu/reference/components/userinterface.html

**Comment by conorshipp** [comment]
Also, the release notes use the old logo:
http://appinventor.mit.edu/ai2/ReleaseNotes.html
