### ISSUE TITLE
WebViewer not rendering on 5.0+ with latest Android System Webview

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#942]
[From the forum](https://groups.google.com/forum/#!category-topic/mitappinventortest/Iwo-UQGuGSM): On newer versions of Android there is a package "Android System Webview" that can be updated by Google Play. After the most recent update, the WebView component in App Inventor no longer appears to work.

**Comment by josmas** [comment]
I just upgraded to latest Android System WebView on my 5.1.1 (Nexus 4) and the WebViewer still works fine (through the companion).

[unrelated] Something I did not notice before is that any address such as `www.google.com` will not load without a `http://` at the front.

**Comment by moliata** [comment]
Hey Josmas, indeed needs to be like that. Even befpre anything websites always had to have http:// in front of, as WebView component requires that

**Comment by ewpatton** [comment]
Since we've never been able to replicate it and there's been significant work advancing Chrome as the Android System Webview on newer versions of Android, I'm declaring this as won't fix unless we see new reports.
