### ISSUE TITLE
Property dropdown positioning in Chrome 61

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#944]
Reported by @kkashi01 on the [dev forum](https://groups.google.com/d/msg/app-inventor-dev/QRRsFH2NjEs/-8yPQ75IBwAJ):

In the latest version of Chrome (Chrome 61) the dropdowns for properties in the designer do not adjust for the scroll position of the page. They seem to appear always at the location they should appear if scrollTop = 0. This is likely an issue with GWT and we may need to update/patch GWT to address this.

**Comment by kkashi01** [comment]
Initially reported by @gabryk91

**Comment by moliata** [comment]
This needs to have high priority level.

**Comment by ewpatton** [comment]
This is also affected by the scrollX property as well.

**Comment by ewpatton** [comment]
Looks like this was fixed in the [GWT master](https://github.com/gwtproject/gwt/issues/9542).
