### ISSUE TITLE
Twitter OAuth possibly broken

### ISSUE THREAD

**Issue by d0ggo** [mit-cml/appinventor-sources#957]
Hello. I've been trying to make an app using the Twitter plugin, but it's been throwing me an error "message -Could not authenticate you" with error code -32. These are the right keys, they have the right permissions, I'm not sure what else could be going on. I'm using "initialize global" blocks to set my keys as "ConsumerKey" and "ConsumerSecret" as well. Thanks!

**Comment by josmas** [comment]
@d0ggo if you still have this issue, can you ask for help in the forum? I have just created a Twitter app and it works as expected. Closing this for now (can be reopen if needed).
