### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by pdurbin** [mit-cml/appinventor-sources#96]
Support for parsing JSON would be great!

I'd like to do a GET of a RESTful API that returns JSON , parse the response, and display some values in my app.

Perhaps it could have semantics like jq: http://stedolan.github.io/jq/

Something like this, perhaps:

curl -s 'http://localhost:8983/solr/collection1/select?rows=100&wt=json&indent=true&q=*' | jq '.responseHeader.params | {rows,q}'

**Comment by TravisH84** [comment]
I know this is an old thread, but I am wondering if any progress was made around JSON encoding. In my scenario I want to send parameters from the phone to an arduino device over bluetooth to tell it to move to a specific x,y position, pass GPS info and timestamp information across amongst other things. Having the ability to format JSON through the App Inventor would make my life 100 times easier!

**Comment by ewpatton** [comment]
Resolved by #1982
