### ISSUE TITLE
Export / Import AIA files jumbles code together

### ISSUE THREAD

**Issue by deliotca** [mit-cml/appinventor-sources#961]
Platform:  Windows 7
Browser:  Chrome, latest

Issue:  If an AIA of a project is exported using **Projects --> Export selected project (.aia) to my computer**, and then that project is later imported into App Inventor using **Projects --> Import project (.aia) from my computer**, many of the code blocks are jumbled into a pile in the center of the screen.  So it appears that the EXPORT / IMPORT process does not properly track the block position metadata for all blocks.  This happened to most, if not all of the 21 students in class today why Exported, then Imported an AIA to computer.

See attached:
![app_inventor_bug](https://user-images.githubusercontent.com/32963649/31831284-bef55e5e-b577-11e7-833d-04d3031b1ce5.jpg)

**Comment by ewpatton** [comment]
@deliotca Can you attach an example exported project where this occurred? It's unclear to me right now whether this is occurring due to the export process or the import process, but we can look into the file to determine what the state of the project is prior to importing it.

**Comment by deliotca** [comment]
Here's the one that I used that had the problem.  It was a demo for a highly modified version of the class Paint Pot app.  When I re-import this app, many of the blocks are in a "pile".


[AS04Part01Demo.zip](https://github.com/mit-cml/appinventor-sources/files/1403043/AS04Part01Demo.zip)

**Comment by ewpatton** [comment]
This bug may be related to #920, which is fixed but not yet deployed.

**Comment by deliotca** [comment]
OK, odd... 

That file I just provided is fine (I downloaded tested it) but this AIA file shows the behavior on my computer just now:

[AS04Part02Demo_Day01.zip](https://github.com/mit-cml/appinventor-sources/files/1403061/AS04Part02Demo_Day01.zip)

**Comment by deliotca** [comment]
My Version info if that matters:

Built: September 18 2017 Version: nb162a
Use Companion: 2.44

**Comment by deliotca** [comment]
PS:  Thanks for the excellent speedy response.

**Comment by ewpatton** [comment]
@deliotca Which browser (Firefox, Chrome, Safari) are you using? I have imported this project into both [ai2.appinventor.mit.edu](http://ai2.appinventor.mit.edu) and [ai2-test.appinventor.mit.edu](http://ai2-test.appinventor.mit.edu), and neither exhibit the problem using Chrome, so I wonder if this is a browser specific bug.

**Comment by deliotca** [comment]
Mentioned in the first post, Windows 7 Latest Chrome.

Dan

**Comment by deliotca** [comment]
The SECOND Zip file I uploaded (**AS04Part02Demo_Day01.zip**) is causing the problem.  I just downloaded it again from this thread, and opened it in App Inventor.

**Comment by ewpatton** [comment]
@deliotca The second project was definitely affected by bug #920. This is due to an interaction that between the code that updates a project when it is opened and the latest version of the blocks editor. Internally, all of the x, y coordinates get reset to 0, 0 when the bug is triggered. This happens even before the project is exported. In the meantime, you can use the Arrange Horizontally or Arrange Vertically menu items in the blocks workspace context menu to rearrange to blocks in the affected projects.

**Comment by ewpatton** [comment]
I think we have this bug fixed between #1115 and 853908e. However, projects that were affected remain affected because they lost their positioning. Projects created after the next release should not exhibit the problem.
