### ISSUE TITLE
Changing property in blocks does not update tooltip

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#964]
Given a property setter/getter block for a component, changing the property to be get/set using the drop down does not change the block's tooltip.

Reported by @halatmit

**Comment by ewpatton** [comment]
Note that reloading the project will reflect the change, so this is likely a failure to update the tooltip when the mutation changes.

**Comment by halatmit** [comment]
Evan, 
You are correct.  This is an issue with *all* component property get/set.   Amazing that no one noticed it until now!
