### ISSUE TITLE
But wait there's more

### ISSUE THREAD

**Issue by farxinu** [mit-cml/appinventor-sources#973]
![image](https://user-images.githubusercontent.com/3612714/32014148-40de7470-b98b-11e7-8cd3-ccedf579b5b2.png)

**Comment by farxinu** [comment]
Update: Seems to be a graphical issue. Reloading the project makes it "normal". It was possible to snap blocks into the false friend else. Something went wrong when playing with the mutator. 
This may not be a real issue, as I have no idea how I managed to produce this error. If anyone else sees it, let's keep everyone posted.

**Comment by farxinu** [comment]
Update to the update: If you mess with the mutator then "undo", a brand new beautiful false friend "else" appears.

**Comment by halatmit** [comment]
eek.   This looks like my bug.  I'm guessing I simply didn't worry about
this when I coded the mutator for if.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
