### ISSUE TITLE
Upgrade to Java 7 minimum

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#978]
Starting with Java 9, it appears the ai.javac5 ant task breaks because 1.5 is no longer supported by the javac compiler. We need to update the build system to use Java 7, which is the earliest supported Java language in the Java 9 compiler. This will also require testing the buildserver and components to make sure we don't break functionality after upgrading.

**Comment by halatmit** [comment]
Thank you.   How unpleasant!



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
We are now at Java 11 for compiling by default.
