### ISSUE TITLE
Add method to create Fusiontable

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#980]
The Fusiontables v1 API allowed one to create a new table using the SQL syntax. Version 2 provides a separate, HTTP API, for creating tables. We should add a method to the Fusiontables control to allow App Inventors to create tables to make up for the loss in functionality.

[Forum reference](https://groups.google.com/d/msg/mitappinventortest/nd3eD5iA6ps/f8S_zLGbCQAJ)

**Comment by arsha14** [comment]
Could you give me the file where the fusion table api can be added

**Comment by ewpatton** [comment]
@arsha14 Take a look at [FusiontablesControl.java](https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/src/com/google/appinventor/components/runtime/FusiontablesControl.java) in the components module. Note that if you submit a PR for this, it should be made against the branch ucr, not master.

**Comment by arsha14** [comment]
Sure thing. Will do

**Comment by ewpatton** [comment]
Fusion tables is being shut off in just over a week, so this issue is no longer valid.

**Comment by halatmit** [comment]
Should we post something to alert people?

==Hal
