### ISSUE TITLE
App inventor companion is not work on Android 8.1 Oreo

### ISSUE THREAD

**Issue by OnyxClover** [mit-cml/appinventor-sources#981]
I installed my Nexus 5X with Android 8.1 Oreo Developer Preview 1.

And I try to development application with App Inventor 2, App companion is not work.

(Application Live Debug Mode)

I think Google killed old APIs and It makes these problems.

Can you check about your APIs?

I think some APIs will be deprecated.

Thanks.

**Comment by ewpatton** [comment]
Thank you for reporting this issue. If possible, please use adb logcat to obtain a stack trace of the crash and include it here as that will help target our efforts to address the problem.

**Comment by ewpatton** [comment]
I've tested this with the API 27 image in the emulator and was able to build the TalkToMe tutorial without issue. @OnyxClover Can you open the companion? Is there a specific component you are using that crashes the companion app on the phone?

**Comment by OnyxClover** [comment]
Yes, I opened application, and take a QR code.

And It is not work to debug mode.

**Comment by ewpatton** [comment]
@OnyxClover Can you provide a project that fails when you connect with the companion? Does an empty project fail?

**Comment by OnyxClover** [comment]
@ewpatton

First, I development my application with AI2.

And I try to connect my phone with AI2 Companion application, and try to connect QR code, It is work, but It can't go to debug mode.

But I need to check about that again.

**Comment by OnyxClover** [comment]
Oh, It just network error.

Sorry about that. It is work :(
...
