### ISSUE TITLE
Add menu option to hide Blockly workspace chrome

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/appinventor-sources#997]
[From the forum](https://groups.google.com/d/msg/mitappinventortest/if8-jacz9bw/Mi1MlWhnBgAJ): It would be nice to not have the backpack, trash, and zoom controls in the way when working on larger projects. Add a context menu option to hide these features. These features can also be accessed using keystokes (platform-specific copy/paste, mouse wheel, delete key, etc.).

**Comment by hsun1316** [comment]
@ewpatton @josmas I was thinking about exploring this feature, is this something we want to have implemented still?

**Comment by josmas** [comment]
@hsun1316 It would be a nice addition to the editor.

**Comment by ewpatton** [comment]
@hsun1316 Sorry that I missed your comment earlier. I've assigned you the issue.

**Comment by ewpatton** [comment]
Resolved by #1600
